### ISSUE TITLE
Error Windows 10 Git Bash

### ISSUE THREAD

**Issue by zzj0402** [microsoft/unilm#1]
# Environment
## Windows
![image](https://user-images.githubusercontent.com/15345547/66246927-d6f34300-e774-11e9-9902-4b685940b1ef.png)

## Git Bash
git version 2.23.0.windows.1

## Docker Version:
![image](https://user-images.githubusercontent.com/15345547/66246903-9bf10f80-e774-11e9-854f-8bb623aab359.png)

# Error Reproduction
## After run: 
```
alias=`whoami | cut -d'.' -f2`; docker run -it --rm --runtime=nvidia --ipc=host --privileged -v /home/${alias}:/home/${alias} pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel bash
```
##Returns: 
```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Program Files/Git/home/zzj04;C"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

**Comment by donglixp** [comment]
Hi @zzj0402 ,

The recommended platform to run the code is Linux.

Best,
Li

**Comment by zzj0402** [comment]
> Hi @zzj0402 ,
> 
> The recommended platform to run the code is Linux.
> 
> Best,
> Li

State that in README

**Comment by donglixp** [comment]
Thanks for the suggestion. I've updated the md file as in https://github.com/microsoft/unilm/commit/10478e8fcc20d4897fe0dfd4d5b9cf8626811b99 .

-li
