### ISSUE TITLE
do not manage to run with --fp16 & --amp

### ISSUE THREAD

**Issue by Neuronys** [microsoft/unilm#10]
Hi
Thanks for sharing this.
I've tried to run the question generation part.
I can manage to make it work, but with a batch_size of 8, because of my 16GB limit on my GPU.
So I wanted to switch to FP16 to increase the batch_size and speed up the training.

I'm getting this error:

> 10/16/2019 09:32:57 - INFO - __main__ -   device: cuda n_gpu: 1, distributed training: False, 16-bits training: True
> 10/16/2019 09:32:57 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-cased-vocab.txt from cache at /tmp/bert-cased-pretrained-cache/cee054f6aafe5e2cf816d2228704e326446785f940f5451a5b26033516a4ac3d.e13dbb970cb325137104fb2e5f36fe865f27746c6b526f6352861b1980eb80b1
> Loading Train Dataset /root/unilm/data/train
> Load 75722 documents
> 10/16/2019 09:33:02 - INFO - __main__ -   enable fp16 with amp
> 10/16/2019 09:33:02 - INFO - __main__ -   ***** Recover model: /root/unilm/models/unilmv1-large-cased.bin *****
> 10/16/2019 09:33:03 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-cased.tar.gz from cache at /tmp/bert-cased-pretrained-cache/7fb0534b83c42daee7d3ddb0ebaa81387925b71665d6ea195c5447f1077454cd.eea60d9ebb03c75bb36302aa9d241d3b7a04bba39c360cf035e8bf8140816233
> 10/16/2019 09:33:03 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /tmp/bert-cased-pretrained-cache/7fb0534b83c42daee7d3ddb0ebaa81387925b71665d6ea195c5447f1077454cd.eea60d9ebb03c75bb36302aa9d241d3b7a04bba39c360cf035e8bf8140816233 to temp dir /tmp/tmppli0_vk5
> 10/16/2019 09:33:14 - INFO - pytorch_pretrained_bert.modeling -   Model config {
>   "attention_probs_dropout_prob": 0.1,
>   "directionality": "bidi",
>   "ffn_type": 0,
>   "fp32_embedding": false,
>   "hidden_act": "gelu",
>   "hidden_dropout_prob": 0.1,
>   "hidden_size": 1024,
>   "initializer_range": 0.02,
>   "intermediate_size": 4096,
>   "label_smoothing": 0.1,
>   "max_position_embeddings": 512,
>   "new_pos_ids": false,
>   "num_attention_heads": 16,
>   "num_hidden_layers": 24,
>   "num_qkv": 0,
>   "pooler_fc_size": 768,
>   "pooler_num_attention_heads": 12,
>   "pooler_num_fc_layers": 3,
>   "pooler_size_per_head": 128,
>   "pooler_type": "first_token_transform",
>   "relax_projection": 0,
>   "seg_emb": false,
>   "task_idx": 3,
>   "type_vocab_size": 6,
>   "vocab_size": 28996
> }
> 
> ^[[A10/16/2019 09:33:49 - INFO - pytorch_pretrained_bert.modeling -   Weights of BertForPreTrainingLossMask not initialized from pretrained model: ['crit_mask_lm_smoothed.one_hot']
> 10/16/2019 09:33:50 - INFO - __main__ -   ***** CUDA.empty_cache() *****
> 10/16/2019 09:33:50 - INFO - __main__ -   ***** Running training *****
> 10/16/2019 09:33:50 - INFO - __main__ -     Batch size = 4
> 10/16/2019 09:33:50 - INFO - __main__ -     Num steps = 9465
> Epoch:   0%|                                                                        | 0/1 [00:01<?, ?it/s]
> Traceback (most recent call last):                                                                        
>   File "biunilm/run_seq2seq.py", line 483, in <module>
>     main()
>   File "biunilm/run_seq2seq.py", line 461, in main
>     optimizer.step()
>   File "/root/.local/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.egg/apex/optimizers/fp16_optimizer.py", line 157, in step
>     grads_groups_flat.append(_flatten_dense_tensors([p.grad for p in group]))
>   File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 192, in _flatten_dense_tensors
>     flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
>   File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 192, in <listcomp>
>     flat = torch.cat([t.contiguous().view(-1) for t in tensors], dim=0)
> AttributeError: 'NoneType' object has no attribute 'contiguous'
> Iter (loss=5.700):   0%|

when running this command line:

> python3 biunilm/run_seq2seq.py --do_train --num_workers 0 \
>   --bert_model bert-large-cased --new_segment_ids --tokenized_input \
>   --data_dir ${DATA_DIR} --src_file train.pa.tok.txt --tgt_file train.q.tok.txt \
>   --output_dir ${OUTPUT_DIR}/bert_save \
>   --log_dir ${OUTPUT_DIR}/bert_log \
>   --model_recover_path ${MODEL_RECOVER_PATH} \
>   --max_seq_length 512 --max_position_embeddings 512 \
>   --mask_prob 0.7 --max_pred 48 \
>   --train_batch_size 8 --gradient_accumulation_steps 2 \
>   --learning_rate 0.00002 --warmup_proportion 0.1 --label_smoothing 0.1 \
>   --num_train_epochs 1 \
>   --amp \
>   --fp16

Any clue of what it could come from ?
Thanks in advance
Philippe

**Comment by donglixp** [comment]
Hi @Neuronys ,

The error is caused by Nvidia/apex's optimizer. Link: https://github.com/NVIDIA/apex/issues/131

A quick fix would be running the code on multiple gpus.

**Comment by donglixp** [comment]
Another fix method is modifying https://github.com/microsoft/unilm/blob/master/src/pytorch_pretrained_bert/modeling.py#L325 to `mixed_key_layer = self.key(hidden_states)`, and https://github.com/microsoft/unilm/blob/master/src/pytorch_pretrained_bert/modeling.py#L331 to `mixed_key_layer =self.key(x_states)`.

**Comment by Neuronys** [comment]
Thanks that works fine
