### ISSUE TITLE
Script for SROIE dataset

### ISSUE THREAD

**Issue by MarouaneMaachou** [microsoft/unilm#100]
Hey there,

Will you release the preprocessing script that you used for the SROIE dataset ?

Thank you in advance

**Comment by wolfshow** [comment]
Hi @MarouaneMaachou, we did not use the official OCR provided by SROIE dataset, so we cannot provide the pre-processing script for SROIE dataset. If you would like to use the official SROIR dataset, you need to break down the textline OCR into token-level OCR, and mapping the sequence labels to the input tokens.

**Comment by SibtainRazaJamali** [comment]
@wolfshow which ocr did you use and how did you label the data?

**Comment by persistforever** [comment]
> @wolfshow which ocr did you use and how did you label the data?

I have the same question!

Do you label the data by human? or other OCR tools?

Thanks
