### ISSUE TITLE
wavlm speaker verification

### ISSUE THREAD

**Issue by haiderasad** [microsoft/unilm#1001]
hi i am using wavlm (base+large) for speaker verification, i wanted to know if the models are language dependent as in the paper it says it only trained on the English dataset , reason is I am getting poor results in the Urdu language as compared to results mentioned in the paper, also can you confirm that the longer the audio length better will be the embedding generated?

**Comment by MarkWuNLP** [comment]
Hi, yes the model is language dependent. Longer audio length cannot solve the problem foundamentally.
