### ISSUE TITLE
WavLM training

### ISSUE THREAD

**Issue by francqz31** [microsoft/unilm#1007]
Hello, I wanted to train WavLM on a custom dataset of mine that has 44.1khz sample rate to use it as an encoder in an audio project, because the WavLM-Large and the rest of the pretrained models are trained on 16khz data hence the output is 16khz if I'm understanding correctly. is there any chance the training code comes out or should I move on ? because I don't really want to use audio super resolution or upsampling , I rather things stay native.  (also if you don't mind, tell me for how many steps wavLM-large and the rest of the models were trained for)

Thanks in advance.

**Comment by EmreOzkose** [comment]
Hi @francqz31 , did you find any unoffical training code ?

**Comment by EmreOzkose** [comment]
I cannot find training code, can you give a link ?

**Comment by EmreOzkose** [comment]
thank you :)
