### ISSUE TITLE
[BEATs] pretrained models are unavailable for download

### ISSUE THREAD

**Issue by notegeek** [microsoft/unilm#1009]
Hi @Sanyuan-Chen, thank you for releasing the implementation and checkpoints of BEATs.

But now I find it unavailable to download the checkpoints:

![image](https://user-images.githubusercontent.com/126641276/222069641-57ee1ed3-0ddd-4df7-a437-9f11deac0eae.png)

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/126641276/222069506-4074f944-a132-4930-951d-45686e24d97e.png">

Hope you can help. Thank you again:)

**Comment by Sanyuan-Chen** [comment]
Hi @notegeek , we have fixed the links. Please try it again.

**Comment by notegeek** [comment]
Thank you @Sanyuan-Chen !
