### ISSUE TITLE
 how to use layoulm in form understanding?

### ISSUE THREAD

**Issue by hee0624** [microsoft/unilm#101]
Hi there,

Thanks for the repo and help! I was wondering how to use layoulm in form understanding? I don't find python script about it.Other,hot to use layoutlm in extracting table data.

**Comment by ranpox** [comment]
Hi @hee0624 ,
Actually the FUNSD dataset is a form understanding dataset. For other datasets, please modify the sequence labeling example.
Currently, the project doesn't support the table extraction task.
