### ISSUE TITLE
BEIT-3 Code and Pre-trained model

### ISSUE THREAD

**Issue by xinghua-qu** [microsoft/unilm#1011]
Hi,

May I ask when will the code and pretrainde model of BEIT-3 be released? 
Thanks

**Comment by donglixp** [comment]
Our colleague Wenhui is working on this. Will push it soon.

**Comment by donglixp** [comment]
The code and pre-trained models of BEiT-3 can be found at [aka.ms/beit3](https://aka.ms/beit3).

**Comment by xinghua-qu** [comment]
> The code and pre-trained models of BEiT-3 can be found at [aka.ms/beit3](https://aka.ms/beit3).

Thanks for informing me here. It is great for referring your shared code. Besides the fine-tuning, may I ask will the pretraining code be added thereafter?
