### ISSUE TITLE
MiniLMv2 license

### ISSUE THREAD

**Issue by yotam-happy** [microsoft/unilm#1017]
Hi, the miniLMv2 checkpoint does not specify any license. 
I am specifically interested in "L6xH384 mMiniLMv2". 
What is the license for it? is it allowed for commercial usage?

**Comment by wenhui0924** [comment]
Hi @yotam-happy,

I suggest you can refer to the license of the teacher model (such as BERT, RoBERTa).

**Comment by maiiabocharova** [comment]
@yotam-happy @wenhui0924 can you please help me -` L12xH384 MiniLMv2` - which tokenizer should be used with it? in the folder with model weights there is no tokenizer - is it just "roberta-base"?
