### ISSUE TITLE
Pre-train datasets for VLMo checkpoints

### ISSUE THREAD

**Issue by sp-ananth** [microsoft/unilm#1018]
**Describe**

Model I am using (UniLM, MiniLM, LayoutLM ...): VLMo

Question: Hello, I would like to confirm the list of datasets used for the checkpoints published here: (The init and fine-tuned checkpoints posted in VQA Eg: `vlmo_base_plus_patch16_224`). Is this just Conceptual Captions (CC), SBU Captions, COCO and Visual Genome (VG) as mentioned in the paper? The paper also mentions a larger dataset of 1B noisy image-text pairs. Is this still from GCC?

**Comment by wenhui0924** [comment]
Hi @sp-ananth,

For the checkpoints released in the repo, the pertaining datasets are GCC, SBU, COCO, and VG. 
For the 1B image-text data, we crawled them from the internet and they are not from GCC.

Thanks

**Comment by sp-ananth** [comment]
Okay, thanks. So the released checkpoints are not trained on this internet data right? Thanks for clarifying!
