### ISSUE TITLE
Beit-2: why use different interpolation for backbone and tokenizer

### ISSUE THREAD

**Issue by zhangyuygss** [microsoft/unilm#1022]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): Beit-2
Hi, I wonder why do you use different interpolation for backbone(bicubic) and tokenizer(lanczos) [here](https://github.com/microsoft/unilm/blob/master/beit2/datasets.py#L38)?
Will there be difference if I use bicubic for both?

**Comment by pengzhiliang** [comment]
Thanks for the attention!

We use bicubic for both. Refer to [TOKENIZER.md](https://github.com/microsoft/unilm/blob/master/beit2/TOKENIZER.md) for more details.
