### ISSUE TITLE
whether the qkv_bias is used for image classification model?

### ISSUE THREAD

**Issue by peiliu0408** [microsoft/unilm#1023]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...):

The problem arises when using:
* [*] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. down load the checkpoint beitv2_base_patch16_224_pt2k_ft21k.pth
2. follow the instruction of run image task fintuning as mentioned in get_started_for_image_classification.md to finetuning an image model
3. load pre-trained checkpoint: blocks.[0-11].attn.qkv.bias missing in the provided pth file.

**Expected behavior**

- Platform:
- Python version:
- PyTorch version (GPU?): Yes

**Comment by pengzhiliang** [comment]
Thanks for the attention!

We use the qkv_bias. In [here](https://github.com/microsoft/unilm/blob/fca17377f9811b469782d1be2d4829705d5f4112/beit2/run_class_finetuning.py#L56), the qkv_bias is set to True.
