### ISSUE TITLE
Welcome update to OpenMMLab 2.0

### ISSUE THREAD

**Issue by vansin** [microsoft/unilm#1029]
# Welcome update to OpenMMLab 2.0

I am Vansin, the technical operator of OpenMMLab. In September of last year, we announced the release of OpenMMLab 2.0 at the World Artificial Intelligence Conference in Shanghai. We invite you to upgrade your algorithm library to OpenMMLab 2.0 using [MMEngine](https://github.com/open-mmlab/mmengine), which can be used for both research and commercial purposes. If you have any questions, please feel free to join us on the OpenMMLab Discord at https://discord.gg/amFNsyUBvm or add me on WeChat (van-sin) and I will invite you to the OpenMMLab WeChat group.

Here are the OpenMMLab 2.0 repos branches:

|                      | OpenMMLab 1.0 branch  | OpenMMLab 2.0 branch                                               | 
| -------------------- | -------------- | ------------------------------------------------------------ | 
| **MMEngine**         |                | [0.x](https://github.com/open-mmlab/mmengine)                |        
| **MMCV**             | 1.x            | [2.x](https://github.com/open-mmlab/mmcv/tree/2.x)           |  
| **MMDetection**      | 0.x 、1.x、2.x | [3.x](https://github.com/open-mmlab/mmdetection/tree/3.x)    | 
| **MMAction2**        | 0.x            | [1.x](https://github.com/open-mmlab/MMAction2/tree/1.x)      |  
| **MMClassification** | 0.x            | [1.x](https://github.com/open-mmlab/MMClassification/tree/1.x) |  
| **MMSegmentation**   | 0.x            | [1.x](https://github.com/open-mmlab/MMSegmentation/tree/1.x) | 
| **MMDetection3D**    | 0.x            | [1.x](https://github.com/open-mmlab/MMDetection3D/tree/1.x)  |  
| **MMEditing**        | 0.x            | [1.x](https://github.com/open-mmlab/MMEditing/tree/1.x)      | 
| **MMPose**           | 0.x            | [1.x](https://github.com/open-mmlab/MMPose/tree/1.x)         |  
| **MMDeploy**         | 0.x            | [1.x](https://github.com/open-mmlab/mmdeploy/tree/1.x) | 
| **MMTracking**       | 0.x            | [1.x](https://github.com/open-mmlab/MMTracking/tree/1.x)     |  
| **MMOCR**            | 0.x            | [1.x](https://github.com/open-mmlab/MMOCR/tree/1.x)          |  
| **MMRazor**          | 0.x            | [1.x](https://github.com/open-mmlab/MMRazor/tree/1.x)        |  
| **MMSelfSup**        | 0.x            | [1.x](https://github.com/open-mmlab/MMSelfSup/tree/1.x)      |  
| **MMRotate**        | 1.x            | [1.x](https://github.com/open-mmlab/mmrotate/tree/1.x)      |  
| **MMYOLO**        |            | [0.x](https://github.com/open-mmlab/mmyolo)      |  

Attention: please create a new virtual environment for OpenMMLab 2.0.

**Comment by donglixp** [comment]
@vansin Thanks for letting us know.
