### ISSUE TITLE
Question Generation example for S2S-FT

### ISSUE THREAD

**Issue by Neuronys** [microsoft/unilm#103]
Hi Li Dong
Thanks a lot for your code and the S2S-FT example.
You gave us in the README abstractive summarization usage, could you please also give Question Generation usage example ?
Thanks in advance
Philippe
PS: I have another question, but better on a separate issue for tracking

**Comment by donglixp** [comment]
Hi @Neuronys ! Thanks for the suggestion. @WenhuiWang0824 can help to add the QG example.

**Comment by Neuronys** [comment]
Great !
Thanks in advance @WenhuiWang0824 to provide the QG and AS examples, as done for the monolingual version.
Cheers
Philippe

**Comment by WenhuiWang0824** [comment]
Hi Philippe,

I am preparing the English question generation data in JSON format. We will upload the data and add usage in the next two days.

Thanks,
Wenhui

**Comment by Neuronys** [comment]
That's perfect
Thanks a lot

**Comment by WenhuiWang0824** [comment]
Hi Philippe,

Sorry for delay. Here are the English [QG data](https://1drv.ms/u/s!AjHn0yEmKG8qixmA7qh_r1GZNTTy?e=CeYIOR) (SQuAD 1.1, JSON format) and the example code:

Fine-tuning
```bash
TRAIN_FILE=/your/path/to/train.qg.uc.json
OUTPUT_DIR=/your/path/to/save_checkpoints
CACHE_DIR=/your/path/to/transformer_package_cache

export CUDA_VISIBLE_DEVICES=0,1,2,3
python -m torch.distributed.launch --nproc_per_node=4 run_seq2seq.py \
  --train_file ${TRAIN_FILE} --output_dir ${OUTPUT_DIR} \
  --model_type minilm --model_name_or_path minilm-l12-h384-uncased \
  --do_lower_case --fp16 --fp16_opt_level O2 --max_source_seq_length 464 --max_target_seq_length 48 \
  --per_gpu_train_batch_size 8 --gradient_accumulation_steps 1 \
  --learning_rate 5e-5 --num_warmup_steps 500 --num_training_steps 36000 --cache_dir ${CACHE_DIR}
```

Decoding
```bash
# path of the fine-tuned checkpoint
MODEL_PATH=/your/path/to/model_checkpoint
SPLIT=dev
INPUT_JSON=/your/path/to/${SPLIT}.qg.uc.json
export CUDA_VISIBLE_DEVICES=0
export OMP_NUM_THREADS=4
export MKL_NUM_THREADS=4

python decode_seq2seq.py \
  --fp16 --model_type minilm --tokenizer_name minilm-l12-h384-uncased --input_file ${INPUT_JSON} --split $SPLIT --do_lower_case \
  --model_path ${MODEL_PATH} --max_seq_length 512 --max_tgt_length 48 --batch_size 32 --beam_size 5 \
  --length_penalty 1.2 --forbid_duplicate_ngrams --mode s2s --forbid_ignore_word "." --min_len 6
```

**Comment by Neuronys** [comment]
Thanks a lot @WenhuiWang0824 
Cheers

**Comment by othman-zennaki** [comment]
@WenhuiWang0824 could you please also give Question Generation usage example for multilingual MiniLM?
I'd like to fine tune multilingual MiniLM on FQuAD: French Question Answering Dataset.
Thanks in advance
Othman

**Comment by Neuronys** [comment]
@WenhuiWang0824 
I have the same interest in Question Generation with Multi-lingual MiniLM than @othman-zennaki 
Thanks in advance for sharing the details.
Cheers

**Comment by WenhuiWang0824** [comment]
Hi Othman and Philippe, 

Thanks for your suggestion!

We are conducting experiments on cross-lingual generation tasks. We will update our s2s-ft package and provide the Question Generation usage example for multilingual MiniLM.

**Comment by Neuronys** [comment]
Thanks @WenhuiWang0824 
I'm looking forward testing it
Cheers 
Philippe

**Comment by pdcoded** [comment]
Any updates on providing an example ? Also, is there any chance that you provide a saved checkpoint with minilm so that we can compare the decoding latency wrt unilm-v1. Unilm-v1 is very slow even on an Nvidia p4 machine when I run it as a microservice. It takes close to 30sec at a min. since the base model is similar to bert-large.

**Comment by WenhuiWang0824** [comment]
Hi @pdcoded 

Thanks for your suggestion. We will add the fine-tuned checkpoint in README later.

Thanks

**Comment by ArijRB** [comment]
@WenhuiWang0824  I followed the same instructions for finetuning , the for the decoding part , i had to change "config.file"  to "train_opt.json" saved after the finetuning in the output_dir but i still get an error , can you help? 

Traceback (most recent call last):
  File "unilm/s2s-ft/decode_seq2seq.py", line 296, in <module>
    main()
  File "QG/miniLM/unilm/s2s-ft/decode_seq2seq.py", line 195, in main
    max_position_embeddings=args.max_seq_length, pos_shift=args.pos_shift, 
  File "unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 784, in from_pretrained
    model = cls(config, *inputs, **kwargs)
  File "unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 1359, in __init__
    self.bert = BertModelIncr(config)
  File "unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 924, in __init__
    super(BertModelIncr, self).__init__(config)
  File "unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 865, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 261, in __init__
    config.vocab_size, config.hidden_size)
  File "/media/md0/home/arij/miniconda3/envs/hf_transfo/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 97, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 768]

**Comment by ArijRB** [comment]
@WenhuiWang0824 Thank you for your answer. I was checking some issues but i couldn't understand how you evaluate your output after the decoding step. Could you share the code for evaluation? Thank you

**Comment by WenhuiWang0824** [comment]
Hi @ArijRB,

Please refer to the question generation script of unilm-v1 (https://github.com/microsoft/unilm/tree/master/unilm-v1#question-generation---squad).

Thanks

**Comment by ArijRB** [comment]
@WenhuiWang0824 Thank you. I used s2s-ft scripts for fine-tuning and decoding and the data you shared here for squad qg. is it the same split as the one you are using in the example because it's not in the same format
