### ISSUE TITLE
Pre-training code of BEiT-3

### ISSUE THREAD

**Issue by MonsterZhZh** [microsoft/unilm#1032]
Great work! However, the code of [BEiT-3](https://github.com/microsoft/unilm/tree/master/beit3) only includes code for various downstream tasks. Is there any way I can reproduce the pre-training task?

**Comment by courao** [comment]
Looking forward the pre-training code too..

**Comment by MonsterZhZh** [comment]
Thanks!!! Looking forward to it!!!
