### ISSUE TITLE
E5 CCPairs data

### ISSUE THREAD

**Issue by Gouzi3618** [microsoft/unilm#1038]
Hi @intfloat,

Thanks for your great efforts in releasing E5 checkpoints! 

I was wondering if it is possible to release your curated CCPairs data? Thanks!

**Comment by intfloat** [comment]
Thanks for your interest in our work!

Currently we have no plan to release the CCPairs data, but I'll let you know if things change.

The paper includes most dataset curation details, it should not take much effort to reproduce.

Liang

**Comment by dtr3** [comment]
Hi @intfloat,

Awesome work you and the team are doing!

Has there been any update on releasing the CCPairs dataset?
