### ISSUE TITLE
XLM-Roberta text generation in S2S-FT

### ISSUE THREAD

**Issue by Neuronys** [microsoft/unilm#104]
Hi Li Dong,

It's me again ;-)
My second question is related to XLM-Roberta.
I've seen in the source code that you include XLM-Roberta model.
Have you tried / managed to generate text using this model ?
Any suggestions, advices, cluse are welcome, as I want to have question generation & abstractive summarization in french.
Thanks in advance
Philippe

**Comment by donglixp** [comment]
We are going to support multilingual s2s-ft in the next release. The multilingual MiniLM (https://github.com/microsoft/unilm/tree/master/minilm#multilingual-pretrained-model ) will also be added. @addf400

**Comment by Neuronys** [comment]
That's great !😊
I've seen the XNLI example. Do you plan to also add Question Generation and Abstractive Summarization examples, to compare with the XNLG approach ?
https://github.com/CZWin32768/XNLG
Looking forward to test it. 
Cheers 
Philippe
