### ISSUE TITLE
BEIT3  "RuntimeWarning: overflow encountered in scalar negative "

### ISSUE THREAD

**Issue by lwgkzl** [microsoft/unilm#1040]
When i run code from beit3/randaug.py, it output a warn : '"RuntimeWarning: overflow encountered in scalar negative "'. So i print some variable to see,  The print content is：
![image](https://user-images.githubusercontent.com/30727306/226597970-cffcd432-78fc-428a-8a25-6888cd0386de.png)

![image](https://user-images.githubusercontent.com/30727306/226598853-79fc422f-838a-4d49-a128-16485fbab4f6.png)

As we can see,  The type of variable 'low' is 'numpy.uint8'. When we use '- low' in 'offset = -low * scale',  if 'low' is not 0 at this time, it will become a positive number close to 255 (that's why it output  'RuntimeWarning: overflow encountered in scalar negative '.)

Therefore, the content in the variable 'offset' and 'table'  is will greater than 256. 

If the 'low' values of the three RGB channels of an image are all non zero, then the image obtained after this function is all white.

I would like to ask if this situation is normal. In my experiment, the output from randaug.py-autocontrast_func  is not consistent with that of PIL.ImageOps.autocontrol.

**Comment by wenhui0924** [comment]
Hi @lwgkzl,

We do not encountered this warn. Could you check the version of packages in the [setup](https://github.com/microsoft/unilm/tree/master/beit3#setup)?

**Comment by lwgkzl** [comment]
> Hi @lwgkzl,
> 
> We have not encountered this warn. Could you check the version of packages in the [setup](https://github.com/microsoft/unilm/tree/master/beit3#setup)?

Thank you for your prompt reply ! This function may involve two packages. The versions of my 「numpy」 and 「opencv-python」 are shown in the screenshot, but there are no corresponding versions in requirements.txt.

In fact, I am using the environment configured with 「pip - r install requirements.tx」.
![image](https://user-images.githubusercontent.com/30727306/226783974-1121249f-f999-4a66-bfc6-da2906fdb814.png)

**Comment by donglixp** [comment]
@lwgkzl Thanks for reporting the issue. Did you also use the same docker to repro the env?

**Comment by lwgkzl** [comment]
> @lwgkzl Thanks for reporting the issue. Did you also use the same docker to repro the env?

Perhaps it is because of docker, which is not convenient for me to use. So I built the torch environment myself, resulting in a mismatch between the versions of the packages installed by pip. Could you please provide the versions of each package?

**Comment by lwgkzl** [comment]
Hi, @wenhui0924, Thank you for providing the version of numpy. But it seems that I cannot only change the version of numpy because there are other packages associated with it.

I understand that the most direct way is to use the docker to configure the default environment, but for some reasons, I cannot use the docker : (

There may be other researchers who may also encounter this issue. I would be grateful if you could indicate the version of package in the requirements.txt.  Many thanks !

**Comment by wenhui0924** [comment]
Sure, will do it.

**Comment by lrdhaha** [comment]
> Sure, will do it.

I have also encountered the situation in the issue. May I ask when you can provide the requirements.txt mentioned above?

**Comment by wenhui0924** [comment]
I am testing the new requirements.txt now, Will update it ASAP.

**Comment by wenhui0924** [comment]
Hi All, here are the versions of each package. You can refer to this first.

timm==0.4.12
Pillow==8.1.2
blobfile==2.0.1
mypy==1.1.1
numpy==1.20.0
pytest==7.2.2
requests==2.24.0
einops==0.6.0
tensorboardX==2.6
scipy==1.10.1
ftfy==6.1.1
opencv-python==4.7.0.72
sentencepiece==0.1.97
pyarrow==9.0.0
torchmetrics==0.7.3
transformers==4.27.4
deepspeed==0.4.0
pycocotools==2.0.6
pycocoevalcap==1.2
torchscale==0.2.0
