### ISSUE TITLE
Beit-3 on object detection

### ISSUE THREAD

**Issue by zhangxgu** [microsoft/unilm#1047]
Thanks for your nice work of Beit-3. 
I want to know whether the Beit-3 finetune code of object detection on COCO will be released?

**Comment by wenhui0924** [comment]
Thanks for your interest. We will try to merge the code of object detection in the future. You can also refer to the code of [ViTDet](https://github.com/facebookresearch/detectron2/tree/main/projects/ViTDet)

**Comment by wenhui0924** [comment]
Yes, you can try to it.
