### ISSUE TITLE
RuntimeError: Unknown model (beit3_large_patch16_224)

### ISSUE THREAD

**Issue by lc222** [microsoft/unilm#1049]
**Describe**
Model I am using BEITV3:
I meet this issue：
RuntimeError: Unknown model (beit3_large_patch16_224)

timm has no this model,  and i didnt find it.

<img width="949" alt="截屏2023-03-31 下午4 17 33" src="https://user-images.githubusercontent.com/13979105/229065534-1cdf35cc-e560-49f9-94d4-07a9fcf39b96.png">
<img width="771" alt="截屏2023-03-31 下午4 19 57" src="https://user-images.githubusercontent.com/13979105/229065924-f76e9bad-4c9c-47e7-a980-eb6b6785a723.png">

how should i solve it

**Comment by nathanodle** [comment]
Same, looked thru branches and couldn't find anything

**Comment by 464hee** [comment]
I, too, have installed the specified version timm==0.4.12 as required

**Comment by 464hee** [comment]
> I, too, have installed the specified version timm==0.4.12 as required

The situation is the same as yours, the model cannot be found

**Comment by lc222** [comment]
The latest version of timm also doesn't have beit3 model..

**Comment by 464hee** [comment]
> The latest version of timm also doesn't have beit3 model..

Do you have any good methods

**Comment by lc222** [comment]
#1048 run finetune successfully, but i didnt know how

**Comment by wenhui0924** [comment]
Hi @464hee and @lc222, you can first download the pretrained or fine-tuned model to your local folder and then perform fine-tuning. Will share more updated about timm later.

**Comment by lc222** [comment]
> about

I have download the fine-tuned model "beit3_large_indomain_patch16_224.pth", and run this command:
`python3.8  -m torch.distributed.launch --nproc_per_node=4 run_beit3_finetuning.py --model beit3_large_patch16_224 --input_size 224 --task vqav2 --batch_size 4 --layer_decay 1.0 --lr 3e-5 --update_freq 1 --epochs 10 --warmup_epochs 1 --drop_path 0.1 --sentencepiece_model ./beit3.spm --finetune ./beit3_large_indomain_patch16_224.pth --data_path ./data --output_dir ./model --log_dir ./log --weight_decay 0.01 --seed 42 --save_ckpt_freq 5 --task_head_lr_weight 20 --opt_betas 0.9 0.98 --randaug` 

but i meet this issue:
![截屏2023-04-03 下午12 53 24](https://user-images.githubusercontent.com/13979105/229415209-59f7ca60-20e5-4298-b3e0-c7b96fa7afba.png)
![截屏2023-04-03 下午12 52 14](https://user-images.githubusercontent.com/13979105/229415221-9eed4d71-a012-4d1b-aa8f-8e115d4e35a3.png)

timm has no beitv3 model so that create_model error.

**Comment by wenhui0924** [comment]
Hi @lc222, we do not add the 224x224 resolution model in [modeling_finetune.py](https://github.com/microsoft/unilm/blob/master/beit3/modeling_finetune.py) for vqav2 task, you can add the 224x224 model in the code or use the 384x384 resolution model.

**Comment by lc222** [comment]
I find register_model in [modeling_finetune.py](https://github.com/microsoft/unilm/blob/master/beit3/modeling_finetune.py) just now, I will try to use this. thanks~

**Comment by OrangeNo42** [comment]
> > about
> 
> I have download the fine-tuned model "beit3_large_indomain_patch16_224.pth", and run this command: `python3.8 -m torch.distributed.launch --nproc_per_node=4 run_beit3_finetuning.py --model beit3_large_patch16_224 --input_size 224 --task vqav2 --batch_size 4 --layer_decay 1.0 --lr 3e-5 --update_freq 1 --epochs 10 --warmup_epochs 1 --drop_path 0.1 --sentencepiece_model ./beit3.spm --finetune ./beit3_large_indomain_patch16_224.pth --data_path ./data --output_dir ./model --log_dir ./log --weight_decay 0.01 --seed 42 --save_ckpt_freq 5 --task_head_lr_weight 20 --opt_betas 0.9 0.98 --randaug`
> 
> but i meet this issue: ![截屏2023-04-03 下午12 53 24](https://user-images.githubusercontent.com/13979105/229415209-59f7ca60-20e5-4298-b3e0-c7b96fa7afba.png) ![截屏2023-04-03 下午12 52 14](https://user-images.githubusercontent.com/13979105/229415221-9eed4d71-a012-4d1b-aa8f-8e115d4e35a3.png)
> 
> timm has no beitv3 model so that create_model error.

How did you download the pretrained model? I got PublicAccessNotPermitted error when trying to download from https://conversationhub.blob.core.windows.net/beit-share-public/beit3/vqa/beit3_base_patch16_480_vqa.pth

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:95c4ba00-c01e-0054-2ad1-99b75a000000 Time:2023-06-08T06:22:14.6694035Z</Message>
</Error>

**Comment by OrangeNo42** [comment]
> Hi @464hee and @lc222, you can first download the pretrained or fine-tuned model to your local folder and then perform fine-tuning. Will share more updates about timm later.

How to download the pretrained model? I got PublicAccessNotPermitted error when trying to download from https://conversationhub.blob.core.windows.net/beit-share-public/beit3/vqa/beit3_base_patch16_480_vqa.pth
