### ISSUE TITLE
Where to find beit3.spm

### ISSUE THREAD

**Issue by nathanodle** [microsoft/unilm#1050]
Looking for the sentencepiece model for BEIT3, and can't find it anywhere in the docs or repo.  Thanks!

**Comment by nathanodle** [comment]
Nevermind, found on https://github.com/microsoft/unilm/blob/master/beit3/get_started/get_started_for_vqav2.md

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/beit3/README.md#text-tokenizer
