### ISSUE TITLE
Would you share BEiT3 pretraining code?

### ISSUE THREAD

**Issue by deepmo24** [microsoft/unilm#1053]
Hi, thanks for your great job on BEiT3. I wonder if you can share the pretraining code of BEiT3? Thanks.

**Comment by wenhui0924** [comment]
Thanks for your interest. We are preparing the pertaining code and will release it later.

**Comment by Tzx11** [comment]
> 感谢您的关注。我们正在准备相关代码，稍后将发布。

the same question.Has the Pre-trained code release work been completed now?
