### ISSUE TITLE
Cannot fine tune beats model

### ISSUE THREAD

**Issue by haidog-yaqub** [microsoft/unilm#1059]
I want to finetune pre-trained beats model, but there is an error caused by RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation.

I think this problem is caused by transformer.pos_conv, i dont why there is a problem with this 1D conv, a simple way to fix it is  to replace x_conv = self.pos_conv(x.transpose(1, 2)) with x_conv = self.pos_conv(x.transpose(1, 2)).detach() in the backbone.py

Could anyone give other solutions to deal with this problem?

**Comment by Sanyuan-Chen** [comment]
Hi @haidog-yaqub ,

The similar issue can be found in https://github.com/microsoft/unilm/issues/806

I have updated the codes here: https://github.com/microsoft/unilm/blob/9102ed91f8e56baa31d7ae7e09e0ec98e77d779c/beats/backbone.py#L116

Please pull the latest codes and try again~

**Comment by haidog-yaqub** [comment]
> Hi @haidog-yaqub ,
> 
> The similar issue can be found in #806
> 
> I have updated the codes here:
> 
> https://github.com/microsoft/unilm/blob/9102ed91f8e56baa31d7ae7e09e0ec98e77d779c/beats/backbone.py#L116
> 
> Please pull the latest codes and try again~

Thank you!

**Comment by dcleres** [comment]
@haidog-yaqub did you manage to fine-tune the model in the end?

**Comment by haidog-yaqub** [comment]
> 

yeah, they fixed the bug, and I am able to fine-tune it without error.

**Comment by haidog-yaqub** [comment]
> @haidog-yaqub did you manage to fine-tune the model in the end?

yeah, they fixed the bug, and I am able to fine-tune it without error.

**Comment by dcleres** [comment]
Hi @haidog-yaqub,awesome that is good to know. Did you fine-tune the last layer(s) or did you just train another model on top of the output of the model's last layer? If you managed to unfreeze the last layer(s) do you mind sharing a bit more information on how you did it? Thank you would much appreciated!

**Comment by cvillela** [comment]
I have the same question here @dcleres and @haidog-yaqub . What was the process on finetuning?
