### ISSUE TITLE
LLMA code of https://arxiv.org/pdf/2304.04487.pdf ?

### ISSUE THREAD

**Issue by trianxy** [microsoft/unilm#1065]
I was reading [this arxiv article](https://arxiv.org/pdf/2304.04487.pdf) which points to the current repo (https://github.com/microsoft/unilm).

The article describes a method to speed-up inference for large language models by ~2x. This is extremely very exciting!

Are you planning on open-sourcing the respective source code inside this repo? Or can you give any other details which can help us in implementing/reproducing the results?

**Comment by nyanyanya** [comment]
@trianxy Thanks for the interest in our work.
We plan to release the code in another repo: https://github.com/microsoft/LMOps soon.
As for now, can you specify what details are you missing for reproducing the result? Maybe I can help to clarify.
