### ISSUE TITLE
Question about BeiT3 and VLMO.

### ISSUE THREAD

**Issue by MiJordan23** [microsoft/unilm#1068]
Hey,
Thank you for releasing code of beit3 and vlmo!!!

However, while reviewing the beit3 code, I discovered that there is no definition of VL-FFN within the higher-level multiway layers.
Then I downloaded the pretrained checkpoint file, and the state_dict in it also lacks the VL-FFN parameters. This appears to differ from the implementation described in the paper.

However, the VLMO code includes a section for creating VL-FFN modules.

I would like to ask if the experiment found that it works better without VL-FFN?

Any help to this is much appreciated.
Thank you.

**Comment by wenhui0924** [comment]
Hi @MiJordan23, 
Yes, we have done some explorations on the model architecture and found that the current architecture used in the released BEiT-3 model achieves better performance than the architecture using VL-FFN.

**Comment by MiJordan23** [comment]
Thank you for the reply! 
Your response clarified my confusion about the performance of different model architectures.
