### ISSUE TITLE
Pretraining code for beit3

### ISSUE THREAD

**Issue by liuxuannan** [microsoft/unilm#1083]
I have read your paper and code and was deeply impressed. But I had some difficulty trying to reproduce your code, how do you pretrain it? I tried to use mlm and mim and felt that it was difficult to integrate into this project.

**Comment by wenhui0924** [comment]
Hi @liuxuannan, we will release the pretraining code later.

**Comment by Kizna1ver** [comment]
Hi, will the pretrained code and largest model be released? We are looking forward to it.

**Comment by yanshangongzi** [comment]
please release the pretraining code，thanks a lot

**Comment by yanshangongzi** [comment]
I have been recovering the pretraining code by reading beit2！

**Comment by IKnowWhoo** [comment]
@yanshangongzi Could you please share your code or introduce your method? I'm trying to implement pre-training but wonder if beit3_base_patch16_480 could be used for pre-training. Thanks a lot!
