### ISSUE TITLE
Missing run_squad.py file

### ISSUE THREAD

**Issue by sebastienharinck** [microsoft/unilm#109]
Hello ! 

Thank you for your great work. I'm excited to test your new April 5th release 👍 

I saw in your [README](https://github.com/microsoft/unilm/tree/master/minilm) from minilm that you use the file `./examples/run_squad.py`. However in `examples` directory, I only have the file `run_xnli.py`.

Can you push `run_squad.py` please ?

Thanks

**Comment by WenhuiWang0824** [comment]
Hi, please find the `./examples/run_squad.py` in [huggingface/transformers/examples](https://github.com/huggingface/transformers/tree/master/examples). Our English MiniLM can be directly loaded using the BERT code in transformers.
