### ISSUE TITLE
error when fine-tuning VLMO

### ISSUE THREAD

**Issue by det-tu** [microsoft/unilm#1096]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): VLMO

![image](https://github.com/microsoft/unilm/assets/26542172/d2ed19f4-9b92-4ac9-8a59-0f5794204491)

error happens when I fine-tuned pre-trained VLMO model on COCO retrieval task...

**Comment by wenhui0924** [comment]
Are you using the 24-layer base-plus model? That model does not use relative position.

**Comment by det-tu** [comment]
No, I used VLMO-base.

**Comment by wenhui0924** [comment]
Could you share with me your fine-tuning command?

**Comment by det-tu** [comment]
Just follow readme. python run.py with num_gpus=8 num_nodes=1 task_finetune_vqa_base_image480 per_gpu_batchsize=8 load_path=/root/paddlejob/workspace/env_run/tianqi_ROOT_tucan/ckpt/vlmo/torch/1000k_lr2e-4_mlm15_bs16_COCOVGSBUCC3M_base/last.ckpt log_dir=../../output/
