### ISSUE TITLE
Question about the pretrain data of indomain image-text pairs (COCO and VG) 

### ISSUE THREAD

**Issue by XRsalt** [microsoft/unilm#1097]
I would like to know when you train the checkpoints for the BEiT3-large-indomain version, do you use COCO only with the COCO train or is the COCO val data also fed in for pre-training? And are some of the images in the VG that contain COCO val data also used for pre-training?

**Comment by wenhui0924** [comment]
Hi @XRsalt, we only use COCO training data and do not use the COCO val data in VG.
