### ISSUE TITLE
How to write the "test.txt" & "test_box.txt"?

### ISSUE THREAD

**Issue by lelandhuang** [microsoft/unilm#111]
When I use the "--do_predict" parameter to run the run_seq_labeling.py, it show me a error "No such file or directory: 'data\\test.txt". I cannot find the sample of the test.txt and test_box.txt. Can someone tell me how to find the sample?

**Comment by ranpox** [comment]
Hi @lelandhuang ,
Sorry for my late reply. You can use the following command to get the test.txt and test_box.txt:
~~~
python scripts/funsd_preprocess.py --data_dir data/testing_data/annotations --data_split test
~~~
