### ISSUE TITLE
Training, fine-tuning code for TextDiffuser

### ISSUE THREAD

**Issue by unography** [microsoft/unilm#1111]
Hi, are you planning to release the training and fine-tuning scripts for TextDiffuser any time soon?

**Comment by JingyeChen** [comment]
We will release it. Please stay tuned!

**Comment by samsara-ku** [comment]
@JingyeChen Sorry for interrupting this thread, but I have a question for you.

I saw some unused variable in the `layout_transoformer.py`. (e.g. match_embedding, state_embedding...)

Is there any special meaning for this variable? Or is there any consideration about those in your training codes?

**Comment by JingyeChen** [comment]
They are not used. Please ignore it.
