### ISSUE TITLE
textdiffuser KeyError: 'word_embedding.weight'

### ISSUE THREAD

**Issue by Cathy0908** [microsoft/unilm#1116]
**Describe the bug**
Model I am using textdiffuser:

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

refer to the textdiffuser README doc

`python inference.py   --mode="text-to-image"   --resume_from_checkpoint="textdiffuser-ckpt/diffusion_backbone"   --prompt="A sign that says 'Hello'"   --output_dir="./output"   --vis_num=4`

```
Traceback (most recent call last):
  File "inference.py", line 609, in <module>
    main()
  File "inference.py", line 360, in main
    unet = UNet2DConditionModel.from_pretrained(
  File "~/anaconda3/envs/textdiffuser/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 620, in from_pretrained
    if empty_state_dict[param_name].shape != param.shape:
KeyError: 'word_embedding.weight'
```

**Expected behavior**

- Platform: linux
- Python version: 3.8
- PyTorch version (GPU?): gpu torch12.1
- diffuser: pip install from the latest source

**Comment by JingyeChen** [comment]
Did you use the **cp** command to replace some files as stated in the readme? 
```
git clone https://github.com/huggingface/diffusers
cp ./assets/files/scheduling_ddpm.py ./diffusers/src/diffusers/schedulers/scheduling_ddpm.py
cp ./assets/files/unet_2d_condition.py ./diffusers/src/diffusers/models/unet_2d_condition.py
cp ./assets/files/modeling_utils.py ./diffusers/src/diffusers/models/modeling_utils.py
cd diffusers && pip install -e .
```

**Comment by Cathy0908** [comment]
I really forgot it, thanks

**Comment by JingyeChen** [comment]
With pleasure!
