### ISSUE TITLE
Issue with TROCR pre-trained model download 

### ISSUE THREAD

**Issue by abhiagwl4262** [microsoft/unilm#1117]
I was trying to download trocr models but I am getting **no public access** error. 

```
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:2641ba01-d01e-0066-7b2c-99a772000000 Time:2023-06-07T10:40:27.2722011Z</Message>
</Error>
```

**Comment by vitouphy** [comment]
I got the same problem.

**Comment by vitouphy** [comment]
@Dod-o Do you know what may have caused this?

**Comment by ram2366** [comment]
I am also facing the same issue while downloading pre-trained weights in DiT model

**Comment by ShiyuZhangUST** [comment]
I got the same problem when trying to download beit-v3 pre-trained weights from https://conversationhub.blob.core.windows.net/beit-share-public/beit3/vqa/beit3_base_patch16_480_vqa.pth

**Comment by donglixp** [comment]
We are working on the blob issue now. Thanks for your reminder.

**Comment by wolfshow** [comment]
If any file on this page fails to download, please add the following string as a suffix to the URL.

Suffix String: ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2023-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=IWdBT4g5TaS3Mkqib5g6IIAN2u8VSEl90SvRPfzpYNU%3D

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/commit/99a26f37f4442afe0170fb0fec70319339572a0f

**Comment by ram2366** [comment]
Still I am getting "AuthenticationFailed" error after adding the suffix to the url for the weights of "https://github.com/microsoft/unilm/tree/master/dit"

**Comment by joefavergel** [comment]
Same problem here with [https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_cascade.pth](https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_cascade.pth)
