### ISSUE TITLE
LAION-OCR download links are invalid

### ISSUE THREAD

**Issue by FlyHighest** [microsoft/unilm#1118]
**Describe the bug**

The provided links of meta data and url are invalid. 

https://layoutlm.blob.core.windows.net/textdiffuser/laion-ocr.zip
https://layoutlm.blob.core.windows.net/textdiffuser/laion_ocr_image_url.zip

Error message:
```xml
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account.RequestId:xxx Time:2023-06-08T05:36:34.2795483Z</Message>
```

**Comment by ShiyuZhangUST** [comment]
Got same problem when trying to download beit-v3 pre-trained weights from https://conversationhub.blob.core.windows.net/beit-share-public/beit3/vqa/beit3_base_patch16_480_vqa.pth

**Comment by donglixp** [comment]
We are working on the blob issue now. Thanks for your reminder.

**Comment by wolfshow** [comment]
If any file on this page fails to download, please add the following string as a suffix to the URL.

Suffix String: ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2023-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=IWdBT4g5TaS3Mkqib5g6IIAN2u8VSEl90SvRPfzpYNU%3D

**Comment by wolfshow** [comment]
> Got same problem when trying to download beit-v3 pre-trained weights from https://conversationhub.blob.core.windows.net/beit-share-public/beit3/vqa/beit3_base_patch16_480_vqa.pth

Beit3 model links will be updated soon.

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/commit/99a26f37f4442afe0170fb0fec70319339572a0f

**Comment by FlyHighest** [comment]
The links still dont work. They give error messages as follows:
```
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:8093992f-901e-0093-3c76-9a3358000000 Time:2023-06-09T02:03:33.2057389Z</Message>
<AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Thu, 08 Jun 2023 08:48:15 GMT] - Expiry [Thu, 08 Jun 2023 16:48:15 GMT] - Current [Fri, 09 Jun 2023 02:03:33 GMT]</AuthenticationErrorDetail>
</Error>
```

And the onedrive link:
```
That didn't work
We're sorry, but zhangtianyu@buaa.edu.cn can't be found in the mail2sysueducn-my.sharepoint.com directory. Please try again later, while we try to automatically fix this for you.

```

**Comment by JingyeChen** [comment]
> The links still dont work. They give error messages as follows:
> 
> ```
> <Error>
> <Code>AuthenticationFailed</Code>
> <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:8093992f-901e-0093-3c76-9a3358000000 Time:2023-06-09T02:03:33.2057389Z</Message>
> <AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Thu, 08 Jun 2023 08:48:15 GMT] - Expiry [Thu, 08 Jun 2023 16:48:15 GMT] - Current [Fri, 09 Jun 2023 02:03:33 GMT]</AuthenticationErrorDetail>
> </Error>
> ```
> 
> And the onedrive link:
> 
> ```
> That didn't work
> We're sorry, but zhangtianyu@buaa.edu.cn can't be found in the mail2sysueducn-my.sharepoint.com directory. Please try again later, while we try to automatically fix this for you.
> ```

Links are updated.

**Comment by HireTheHero** [comment]
@JingyeChen @wolfshow 
I can click the link to download the checkpoint, but cannot `wget <ckpt-link>` resulting in "access blocked".
Reported wget stuff earlier for [another model from Microsoft](https://github.com/microsoft/Oscar/issues/205).
Is this expected?

**Comment by skytodmoon** [comment]
mark met the sam problem
