### ISSUE TITLE
is  S2S-ft suitable for Semantic parsing？

### ISSUE THREAD

**Issue by slliao445** [microsoft/unilm#112]

**Comment by slliao445** [comment]
Hello, Dong:
Thank you very much for the open source UNILM model. I know that you have done work related to semantic parsing before. Do you think it's possible to fine-tune unilm with semantic parsing data？ 
Thank you very much!

**Comment by donglixp** [comment]
Hi @slliao445 , 

The model was pre-trained for text-to-text generation tasks. We haven't tried the model on the semantic parsing problem. At least the model should help to improve the encoding of NL. If you would like to use https://github.com/microsoft/unilm/tree/master/s2s-ft , the vocabulary can be extended to include new tokens.
