### ISSUE TITLE
Reopening issue #1117

### ISSUE THREAD

**Issue by abhiagwl4262** [microsoft/unilm#1123]
Opening the Issue #1117 as the solution is not working for trocr checkpoints.

**Comment by ram2366** [comment]
Same issue with https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_cascade.pth not able to download the weights 

getting 'AuthenticationFailed' after adding '?sv=2022-11-02&ss=b&srt=o&sp=r&se=2023-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=IWdBT4g5TaS3Mkqib5g6IIAN2u8VSEl90SvRPfzpYNU%3D' suffix

**Comment by wolfshow** [comment]
> Same issue with https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_cascade.pth not able to download the weights
> 
> getting 'AuthenticationFailed' after adding '?sv=2022-11-02&ss=b&srt=o&sp=r&se=2023-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=IWdBT4g5TaS3Mkqib5g6IIAN2u8VSEl90SvRPfzpYNU%3D' suffix

I am able to download using https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_cascade.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2023-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=IWdBT4g5TaS3Mkqib5g6IIAN2u8VSEl90SvRPfzpYNU%3D.

**Comment by wolfshow** [comment]
I am able to download using the string '?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D'
