### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ofettaya** [microsoft/unilm#1124]
**Describe**
I want to test Beit3 and do some image text retrieval on some images and texts, here how I began the code

tokenizer = XLMRobertaTokenizer(tokenizer_path)

args = _get_base_config(
    img_size=384,
    patch_size=16,
    checkpoint_activations=checkpoint_base_path
)

model_base = BEiT3ForRetrieval(args)
state_dict = torch.load("/Users/ornellafettaya/Desktop/models pretrained/beit-3/poids du model/beit3_base_patch16_384_coco_retrieval.pth")
model_base.load_state_dict(state_dict['model'])
list_img_path = sorted(glob.glob("/Users/ornellafettaya/Desktop/projet_git/transformers-multimodaux/datasets/imagenette2-320/val/*/*.*"))
len(list_img_path), list_img_path[:10]

how can I get the text embeddings and image embeddingsor preprocess function?

**Comment by donglixp** [comment]
The document is at https://github.com/microsoft/unilm/blob/master/beit3/get_started/get_started_for_retrieval.md#example-evaluate-beit-3-fine-tuned-model-on-coco-retrieval-and-flickr30k-retrieval
