### ISSUE TITLE
Downloading weights for DiT with Mask R-CNN fine tuned on PubLayNet but get unexpected files

### ISSUE THREAD

**Issue by a3huang** [microsoft/unilm#1125]
**Describe the bug**
I am trying to download the weights here: https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_mrcnn.pth.

If I just try to download from that link alone, I get:
```
HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
```

When I add the suffix string as mentioned in the README and download from `https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_mrcnn.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D`, the download seems to work, but I end up with a zip file which, when unzipped gives me a folder with the following structure:
```
archive/
  data/
  data.pkl
  version
```

Is this expected?

**Expected behavior**
I was expecting to get a `.pth` file containing the weights of the above model.

**Comment by wolfshow** [comment]
adding the string "?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D" to the end of the current URL will be ok.

**Comment by donglixp** [comment]
You can use the `mv` command to change the file name to `publaynet_dit-b_mrcnn.pth`.

**Comment by jonahkaye** [comment]
@donglixp @a3huang which file are you renaming? The data folder has a lot of small files in it. Are these the weights but broken up into subfiles. How does one transform this file structure into .pth. 
Thanks!
