### ISSUE TITLE
Any plans to release a sample code for layoutLM on SROIE dataset?

### ISSUE THREAD

**Issue by zhongzhuoyao** [microsoft/unilm#114]

**Comment by wolfshow** [comment]
Please follow the FUNSD samples for other sequence labeling tasks.

**Comment by zhongzhuoyao** [comment]
Of course, I can follow the FUNSD samples for other sequence labeling tasks. I just want to know how did you envaluate layoutLM on SROIE testing dataset because it only provides images?

**Comment by wolfshow** [comment]
Duplicate of #115
