### ISSUE TITLE
LayoutReader pretrained model and data links are broken

### ISSUE THREAD

**Issue by stepelu** [microsoft/unilm#1143]
Trying to download the pre-trained model weights at https://layoutlm.blob.core.windows.net/readingbank/model/layoutreader-base-readingbank.zip results in:

```
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:a057d9bf-f01e-0003-75f9-9f0936000000 Time:2023-06-16T02:21:24.6931396Z</Message>
</Error>
```

Same error for the pre-processed data: https://layoutlm.blob.core.windows.net/readingbank/dataset/ReadingBank.zip.

**Comment by wolfshow** [comment]
If any file on this page fails to download, please add the following string as a suffix to the URL.

Suffix String: ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D
