### ISSUE TITLE
BEiT3.pth 与 pkl模型转换的问题

### ISSUE THREAD

**Issue by 1605707467qq** [microsoft/unilm#1146]
**Describe**
Model I am using (BEiT3...):
The zip archive downloaded when downloading the Retrieval checkpoint is not a .pth file after decompression. I want to know how to load this model weight to fine-tune or verify the model, because it is the first time I have encountered such a situation and I have not found a solution on the Internet. So I come to ask you for advice.
zip:
├── archive
│   ├── data
│   │   ├── 94233140743056
│   │   ├── 94233140743152
│   │   ├── 94233140743376
│   │   ├── 94233180092720
│   │   ├── 94233180117264
│   │   ├── 94233180214192
│   │   ├── 94233180217920
│   │   ├── 94233180235520
│   │   ├── 94233181357168
│   │   ├── 94233181428592
│   │   ├── 94233181439216
│   │   ├── 94233181439856
│   │   ├── 94233181456416
│   │   ├── 94233181457056
│   │   ├── 94233181539664
│   │   ├── 94233181540304
│   │   ├── 94233181645552
│   │   ├── 94233181716976
│   │   ├── 94233181721056
│   │   ├── 94233181721696
│   │   ├── 94233181849520
│   │   ├── 94233181849920
│   │   ├── 94233181940704
│   │   ├── 94233181941344
│   │   ├── 94233182129760
│   │   ├── 94233182201184
│   │   ├── 94233182223296
│   │   └── 94233182294720
│   ├── data.pkl
│   └── version
├── beit3_base_patch16_384_f30k_retrieval.zip

**Comment by donglixp** [comment]
You could manually modify the file to a `.pth` file without unzip.

**Comment by 1605707467qq** [comment]
Many thanks！！！
