### ISSUE TITLE
How did you envaluate layoutLM on SROIE testing dataset because it only provides images

### ISSUE THREAD

**Issue by zhongzhuoyao** [microsoft/unilm#115]

**Comment by wolfshow** [comment]
We submit our results to their evaluation website and get the results from there.

**Comment by zhongzhuoyao** [comment]
I try to express my question more detailedly. The SROIE testing dataset only provides images, while LayoutLM takes images, text contents and their bounding boxes as input. I just want to know how did you get the text contents and their bounding boxes and which OCR engine has been used ? I can get the corresponding descriptions from your paper.

**Comment by wolfshow** [comment]
@zhongzhuoyao, the SROIE also provided the OCR results in the dataset.

**Comment by zhongzhuoyao** [comment]
@wolfshow The testing set only provides images.

**Comment by wolfshow** [comment]
> @wolfshow The testing set only provides images.

They also provided OCR results. Please look into the dataset carefully.

**Comment by wolfshow** [comment]
> @wolfshow The testing set only provides images.

They also provided OCR results. Please look into the dataset carefully.
