### ISSUE TITLE
Failed to download https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_mrcnn.pth

### ISSUE THREAD

**Issue by joel1895** [microsoft/unilm#1150]
![Screenshot 2023-06-22 204612](https://github.com/microsoft/unilm/assets/57807710/5b281525-30e8-4a56-8d99-5bf1bb90e7a7)
 I am not able to download publayent_dit-b_mrcnn.pth or any other model for inferencing. The permissions are denied to download any model. 
What should I do to rectify this?

**Comment by gaspar-avit** [comment]
> https://github.com/microsoft/unilm/tree/master/dit#pretrained-models
> 
> If any file on this page fails to download, please add the following string as a suffix to the URL.
> 
> Suffix String: ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

This doesn't work for me. I'm trying to download DiT model, more concretely the "publaynet_dit-b_cascade" model. Any clue how to solve it?

**Comment by sebastianfernandezgarcia** [comment]
now it´s not working

**Comment by seabass011** [comment]
+1, not working
