### ISSUE TITLE
BEIT-2: why use ViT-B instead of ViT-L

### ISSUE THREAD

**Issue by yzy-thu** [microsoft/unilm#1157]
**Describe**
Model I am using BEIT-2:
I read in the paper that all versions of tokenizer using ViT-B. I'm curious if you have tried training with ViT-L？ Is it possible to get a better tokenizer?

**Comment by pengzhiliang** [comment]
Thanks for the attention!
Yeah, the ViT-L version is used in BEiT-3. In our experiments, a better tokenizer can bring a consistent improvement [1].

[1] [A Unified View of Masked Image Modeling](https://arxiv.org/abs/2210.10615)

**Comment by yzy-thu** [comment]
Thanks for your reply!
