### ISSUE TITLE
Kosmos-2: using segmetation keypoints rather than bbox

### ISSUE THREAD

**Issue by zhangj1an** [microsoft/unilm#1158]
**Describe**
Hi, thanks for the amazing model! I am amazed by the data construction pipeline, I am learning a lot from that. The essay writing is also very clear.

Is there anyway to finetune model such that, given an image and text query, it outputs a list of segmentation keypoints (e.g. contour of animals/roads), rather than 2 bounding box points? 

Thank you!

**Comment by pengzhiliang** [comment]
Thanks for the attention!

You only need to adjust the input format to complete your needs, such as <loc_1> <loc_2> ... <loc_n>, but you may need to train or instruction-tune the model on the dataset that contains segmentation points.
