### ISSUE TITLE
How can i do the Receipt Understanding with layoutlm?

### ISSUE THREAD

**Issue by lelandhuang** [microsoft/unilm#116]
Form Understanding: run_seq_labeling.py
Document Image Classification: run_classification.py
Could you tell me how to do the Receipt Understanding with SROIE data?
Thanks a lot.

**Comment by wolfshow** [comment]
@lelandhuang, generally, receipt understanding is similar to form understanding so you may use the sequence labeling code for that. Basically, all you need to do is to leverage some OCR tools to get the text and 2d position informaiton. After that, you can fine-tune the pre-trained models using your own labeled receipts and get the output from the fine-tuned models.
