### ISSUE TITLE
Where do I get weights for kosmos-2

### ISSUE THREAD

**Issue by Michael89** [microsoft/unilm#1161]
I'm looking for try kosmos-2 locally on my machine is there place where I can find weights for this model
run_gradio contains this line
model_path=/path/to/kosmos2.pt
but I couldn't manage to find this file

**Comment by pengzhiliang** [comment]
Hi, please check it in [here](https://github.com/microsoft/unilm/tree/master/kosmos-2#checkpoints) now.
