### ISSUE TITLE
More demo for KOSMOS-2

### ISSUE THREAD

**Issue by hhaAndroid** [microsoft/unilm#1165]
Hello, the KOSMOS-2 algorithm provides many exciting features such as parse grounding and VQA. However, currently the gradio demo only provides the Image Captioning + Parse Grounding function. I would like to inquire if you have plans to provide a demo for the VQA function or other functionalities mentioned in the paper? Thank you!

**Comment by donglixp** [comment]
We will add the evaluation scripts of other tasks to our repo.

**Comment by Tourbillon** [comment]
@donglixp I used the 'kosmos2.pt' downloaded from the url for offiline demo,but I get wrong result. Is the model correct?
