### ISSUE TITLE
cant download pretrained model

### ISSUE THREAD

**Issue by DSJingguo** [microsoft/unilm#1166]
(UniLM, Mi<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:aa6ce4d6-c01e-00a1-5e2f-ab332f000000 Time:2023-06-30T08:47:29.0872362Z</Message>
</Error>niLM, LayoutLM ...):

**Comment by ATidiane** [comment]
I have the same error as well, if someone can help please.

**Comment by ATidiane** [comment]
> (UniLM, Mi `PublicAccessNotPermitted` Public access is not permitted on this storage account. RequestId:aa6ce4d6-c01e-00a1-5e2f-ab332f000000 Time:2023-06-30T08:47:29.0872362Z niLM, LayoutLM ...):

Hey, I just figured, it's acutally mentionned in the documentation. 

Just add this to the page url of the error you are seeing above and hit enter : 

?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

**Comment by gaspar-avit** [comment]
> > (UniLM, Mi `PublicAccessNotPermitted` Public access is not permitted on this storage account. RequestId:aa6ce4d6-c01e-00a1-5e2f-ab332f000000 Time:2023-06-30T08:47:29.0872362Z niLM, LayoutLM ...):
> 
> Hey, I just figured, it's acutally mentionned in the documentation.
> 
> Just add this to the page url of the error you are seeing above and hit enter :
> 
> ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

This doesn't work for me. I'm trying to download DiT model, more concretely the "publaynet_dit-b_cascade" model. Any clue how to solve it?
