### ISSUE TITLE
get wrong results using the downloaded checkpoint

### ISSUE THREAD

**Issue by Tourbillon** [microsoft/unilm#1167]
**Describe**
I used the 'kosmos2.pt' downloaded from the url for offiline demo,but I get wrong result. Is the model correct?

**Comment by donglixp** [comment]
What error message did you get?

**Comment by Tourbillon** [comment]
The caption results is wrong and without any logic. The code is correctly running.

**Comment by Tourbillon** [comment]
@donglixp The caption results is wrong and without any logic. The code is correctly running.

**Comment by donglixp** [comment]
Did you launch the model using the Gradio demo setup script?

**Comment by Tourbillon** [comment]
yes, I used the Gradio to launch the model. I email the result to your Gmail.

**Comment by jiang-hai-qi** [comment]
Hello, could you please tell me the versions of torch and torchvison? My code seems to have reported an error due to version issues

**Comment by donglixp** [comment]
> yes, I used the Gradio to launch the model. I email the result to your Gmail.

@Tourbillon Thank you for providing the feedback. We are working on reproducing the results.

**Comment by donglixp** [comment]
> Hello, could you please tell me the versions of torch and torchvison? My code seems to have reported an error due to version issues
@jiang-hai-qi We used torch 1.13.

alias=`whoami | cut -d'.' -f2`; docker run -it --rm --runtime=nvidia --ipc=host --privileged -v /home/${alias}:/home/${alias} nvcr.io/nvidia/pytorch:22.10-py3 bash

**Comment by hai-qi** [comment]
thank you.

**Comment by Tourbillon** [comment]
@donglixp @qihai-j Because of some limits, we can not use cuda11.8, so i did not use the docker. 
fairseq I used 0.12.0
the apex i used the brach 'f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0'
the torch version is 1.13.1
the cuda version is 11.6

**Comment by hai-qi** [comment]
thank you very much

**Comment by pengzhiliang** [comment]
@Tourbillon Hi, I check it but can not reproduce the results you mentiond:
> The caption results is wrong and without any logic

The commands are:
```bash
alias=`whoami | cut -d'.' -f2`; docker run -it --rm --runtime=nvidia --ipc=host --privileged -v /home/${alias}:/home/${alias} nvcr.io/nvidia/pytorch:22.10-py3 bash

wget -O /tmp/kosmos-2.pt "https://conversationhub.blob.core.windows.net/beit-share-public/kosmos-2/kosmos-2.pt?sv=2021-10-04&st=2023-06-08T11%3A16%3A02Z&se=2033-06-09T11%3A16%3A00Z&sr=c&sp=r&sig=N4pfCVmSeq4L4tS8QbrFVsX6f6q844eft8xSuXdxU48%3D"

git clone https://github.com/microsoft/unilm.git
cd unilm/kosmos-2

bash vl_setup_xl.sh
pip install gradio

# replace the model path in run_gradio.sh with /tmp/kosmos-2.pt
bash run_gradio.sh
```
After launching the local demo, I can obtain the same results (not enabling the sampling) as the [online demo](https://aka.ms/kosmos-2-demo), for the examples in the demo.

**Comment by pengzhiliang** [comment]
More details about default packages or env settings can be found in [here](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-10.html)

**Comment by Tourbillon** [comment]
@pengzhiliang @donglixp I sovled the problem by using the fairseq in this project. I used fairseq==0.12.0 fro source code and got the wrong results

**Comment by Tourbillon** [comment]
@donglixp @pengzhiliang @pengzhiliang @donglixp Thanks for your reply! I sovled the problem by using the fairseq in this project. I used fairseq==0.12.0 fro source code and got the wrong results.

**Comment by Tourbillon** [comment]
The paper mentioned that you use the spaCy to get noun chunks and referring expression. Will the processing code be released？

**Comment by Tourbillon** [comment]
@donglixp @pengzhiliang The paper mentioned that you use the spaCy to get noun chunks and referring expression. Will the processing code be released？
