### ISSUE TITLE
[kosmos-2] Is there a plan to release code for more tasks of kosmos-2?

### ISSUE THREAD

**Issue by BIGBALLON** [microsoft/unilm#1172]
Thanks for the amazing work [kosmos-2].
From the paper, kosmos-2 can do lots of tasks: (1) visual grounding, (2)-(3) grounded question answering, (4)-(6) multimodal referring via bounding boxes, and (7) grounded image captioning. 

Is there any plan to release a demo for these tasks?

**Comment by pengzhiliang** [comment]
Thanks! Those all are in our release schedule. 
If you can't wait to experience it, please refer to [here](https://github.com/microsoft/unilm/issues/1170#issuecomment-1617952420).

**Comment by BIGBALLON** [comment]
Hi, @pengzhiliang .
according to https://github.com/microsoft/unilm/issues/1170#issuecomment-1617952420

I modify the code and test the performance using demo pictures.
but I got some abnormal phenomenon, is something wrong

**correct cases:**

- ![image](https://github.com/microsoft/unilm/assets/7837172/d9b62fc2-0d26-42e9-b314-03e52a14eb47)
- ![image](https://github.com/microsoft/unilm/assets/7837172/e5be9652-089c-4857-b650-85c0ab4fbc7a)
- ![image](https://github.com/microsoft/unilm/assets/7837172/abe90950-d166-4008-a2dc-aa0e40531fce)


**badcase:**

- ![image](https://github.com/microsoft/unilm/assets/7837172/4aa5e587-7c0c-4da9-92e4-bdfb54d31173)
- ![image](https://github.com/microsoft/unilm/assets/7837172/3e152f78-67ee-4665-b96e-2d72b1120e89)
- ![image](https://github.com/microsoft/unilm/assets/7837172/8ad36e1c-d51e-432c-8c8b-57016abd1dd3)
- ![image](https://github.com/microsoft/unilm/assets/7837172/f5b9c2f9-ecaa-4352-ba78-03e967e6c24f)

It seems that no matter what question I ask, it hits yes and matches a bbox. Is there something I'm not doing the right way?

**Comment by pengzhiliang** [comment]
We have released evaluation code of some tasks in [here](https://github.com/microsoft/unilm/pull/1193#issue-1800428980).

**Comment by JierunChen** [comment]
> We have released evaluation code of some tasks in [here](https://github.com/microsoft/unilm/pull/1193#issue-1800428980).

Thanks for your hard work. Could you continue to release the remaining evaluation code? It would be a valuable contribution to the field.

**Comment by donglixp** [comment]
> > We have released evaluation code of some tasks in [here](https://github.com/microsoft/unilm/pull/1193#issue-1800428980).
> 
> Thanks for your hard work. Could you continue to release the remaining evaluation code? It would be a valuable contribution to the field.

@JierunChen  Which tasks you would like to evaluate first? So we could prioritize the release pipeline.

@pengzhiliang FYI.

**Comment by JierunChen** [comment]
@donglixp @pengzhiliang I do not have a strict preference and you may prioritize at your best convenience.  The evaluation code is requested for the following tasks: 
1. Referring expression generation
2. Image captioning
3. Visual question answering

Grateful for your contributions.
