### ISSUE TITLE
Can you provide the conda environment for kosmos-2?

### ISSUE THREAD

**Issue by liguang0115** [microsoft/unilm#1177]
Thank you for your fantastic work!

Could you provide the conda environment for kosmos-2?

It will be really helpful so that we don't have to figure out the confusing dependencies between deepspeed, xformer, apex, and various cuda libraries.
Thank you so much!

**Comment by pengzhiliang** [comment]
Thank you. I will try to fix it and get back to you.

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/kosmos-2#setup

It's recommended to use docker to set up the environment.

**Comment by pengzhiliang** [comment]
Hello, @runjiali-rl. Sorry for the late response.
Check it in this [comment](https://github.com/microsoft/unilm/issues/1208#issuecomment-1645228614).
