### ISSUE TITLE
kosmos-2 :Can i  get grounded images 

### ISSUE THREAD

**Issue by hai-qi** [microsoft/unilm#1178]
hello,I'm interested in the grounded image captioning feature of Kosmos-2. Can I get grounded images? For example, the grounded image captioning function you gave an example, which identifies 6 boxes, and I want to get these 6 images. Can I get this by modifying the code?

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/kosmos-2/demo/gradio_app.py#L436

**Comment by hai-qi** [comment]
Thank you so much. I have solved this problem.
