### ISSUE TITLE
Question about the inpainting process of Text Diffuser

### ISSUE THREAD

**Issue by wjj1106** [microsoft/unilm#1181]
I noticed that the layout generation process did not take into account the area to be filled in the original image. How do I ensure that the character layout matches the mask area when doing inpainting?

**Comment by JingyeChen** [comment]
The layout generation stage is only used in Text-to-Image function. For the text inpainting function, it is recommended to use some tools like powerpoint to draw mask and inpainted text (the color of mask should be gray and the color of text should be black).

**Comment by wjj1106** [comment]
> 

Thanks for your response.
