### ISSUE TITLE
[Kosmos-2] The right way to use "Grounded question answering"

### ISSUE THREAD

**Issue by BIGBALLON** [microsoft/unilm#1186]
Thanks for your great work [kosmos-2].

According to https://github.com/microsoft/unilm/issues/1170#issuecomment-1617952420

I modify the code and test the performance using demo pictures.
But I got some abnormal phenomenon.

**correct cases:**

- ![image](https://github.com/microsoft/unilm/assets/7837172/d9b62fc2-0d26-42e9-b314-03e52a14eb47)
- ![image](https://github.com/microsoft/unilm/assets/7837172/e5be9652-089c-4857-b650-85c0ab4fbc7a)
- ![image](https://github.com/microsoft/unilm/assets/7837172/abe90950-d166-4008-a2dc-aa0e40531fce)

**badcase:**

- ![image](https://github.com/microsoft/unilm/assets/7837172/4aa5e587-7c0c-4da9-92e4-bdfb54d31173)
- ![image](https://github.com/microsoft/unilm/assets/7837172/3e152f78-67ee-4665-b96e-2d72b1120e89)
- ![image](https://github.com/microsoft/unilm/assets/7837172/8ad36e1c-d51e-432c-8c8b-57016abd1dd3)
- ![image](https://github.com/microsoft/unilm/assets/7837172/f5b9c2f9-ecaa-4352-ba78-03e967e6c24f)

It seems that no matter what question I ask, it hits yes and matches a bbox. 
Is there something I'm not doing the right way?

**Comment by pengzhiliang** [comment]
Hi, @BIGBALLON. Happy to see your success!
You can try:
```
<grounding> Question: Are there any people in the image? Answer: 
```
`<grounding>` token encourages model to answer with boxes.

Prompt `<phrase> {text span} </phrase>` let model generate boxes, even if `{text span}` does not exist in the image. 
In our observation, if a `{text span}` does not exist in the picture, then the model tends to predict a box covered the whole image.

**Comment by BIGBALLON** [comment]
Thanks @pengzhiliang, I try the prompt 
``` 
<grounding> Question: Are there any dogs in the image?  Answer:
```

**The observation is still not normal, can you give some more suggestions and opinions?** 

**A. without sampling, without <phrase>**

![image](https://github.com/microsoft/unilm/assets/7837172/8cc4c3aa-00f2-4fd0-b428-2e1589d43905)
![image](https://github.com/microsoft/unilm/assets/7837172/f79f07c0-fb54-4ce5-9637-0d60b1a038bd)


**B. without sampling, with <phrase>**

![image](https://github.com/microsoft/unilm/assets/7837172/88bbb0fc-c070-4d2b-8161-c92f5f78bf8d)
![image](https://github.com/microsoft/unilm/assets/7837172/5c7664b0-04fa-475e-8590-09a97ed98553)
![image](https://github.com/microsoft/unilm/assets/7837172/303e391a-3d99-4343-b82b-d0fc29631e54)


**C. with sampling, without <phrase>**

![image](https://github.com/microsoft/unilm/assets/7837172/6724f60c-aa7b-4c22-b7b3-aa7fd9847f68)
![image](https://github.com/microsoft/unilm/assets/7837172/21ccef7a-e416-4150-af88-468cf8e06060)

**D. with sampling, with <phrase>**

![image](https://github.com/microsoft/unilm/assets/7837172/3faf5e10-04cf-4fda-9c88-0e2c3e23fea0)
![image](https://github.com/microsoft/unilm/assets/7837172/3035ca56-7477-4d82-b12e-3e7aa11c3459)
![image](https://github.com/microsoft/unilm/assets/7837172/26db07b2-4b76-4764-be77-1285ce65c766)

**Comment by pengzhiliang** [comment]
Hi, @BIGBALLON . Sorry for the late.
Your prompt seems little wrong, take your last image as example:
```text
<grounding> Question: Are there any <phrase>cats</phrase> in the image?  Answer:
```
In our training process, `<phrase>...</phrase><object>...</object>` is a continuous sequence.
Therefore, using `<phrase>...</phrase>` separately might cause a high confusion.

**Comment by pengzhiliang** [comment]
Additionally, Kosmos-2 has not used the end task dataset during the pretraining and instruction tuning process, which may result in suboptimal performance for some Q&A tasks. 

By the way, we did not introduce negative examples during the training/inst-tuning process, so the model may often provide incorrect answers when asked about the location of objects that do not exist in the image. 

Addressing these issues is one of our goals for the next phase.  Thanks!
