### ISSUE TITLE
[Kosmos-2] local demo keeps running without output

### ISSUE THREAD

**Issue by JierunChen** [microsoft/unilm#1189]
**Describe**
I follow the README steps to run the KOSMOS-2 demo locally. However, when I choose an image and click the "run" button.  The code keeps running without returning any output. Any advice is well-appreciated.

**Comment by donglixp** [comment]
Is there any error message (from the bash console, or the browser console)?

**Comment by JierunChen** [comment]
It was due to dependency issues. It has been resolved after recreating a container and following the README setup and the [post](https://github.com/microsoft/unilm/issues/1185#issuecomment-1629305294).
