### ISSUE TITLE
kosmos-2 High CPU RAM usage

### ISSUE THREAD

**Issue by sheldonchiu** [microsoft/unilm#1194]
**Describe**
I tried to load kosmos-2 with 29GM of RAM and result in OOM. Is there any way to minimize the RAM usage while loading the model?

**Comment by pengzhiliang** [comment]
Hi, @sheldonchiu . I will check it for you.

**Comment by sheldonchiu** [comment]
I have successfully run kosmos-2 with a vm having 44GB RAM. I notice that the peak RAM usage is around 33GB and drop back to 18GB. 

The RAM usage after torch.load is around 20GB and OOM happened during build_model, is it taking up double the space during this stage?

**Comment by pengzhiliang** [comment]
> I notice that the peak RAM usage is around 33GB and drop back to 18GB.

I run `htop` on the machine where we host demo. But the mem is about 10G.
![image](https://github.com/microsoft/unilm/assets/26346329/51363c42-9d6e-4fcf-a95a-643a56acce4f)

**Comment by pengzhiliang** [comment]
When I hosted a new Demo, I observed that the peak RAM usage was about 31GB.

**Comment by pengzhiliang** [comment]
We will try to fix it.
@sheldonchiu Thanks for the feedback!

**Comment by pengzhiliang** [comment]
It looks like the checkpoint is too large, which causes a lot of RAM uage to load it into CPU. Therefore, the possible solution is to delete the unnecessary parameters of the checkpoint, such as Optimizer.

**Comment by sheldonchiu** [comment]
Thanks for the advice, the peak RAM usage decrease to 21GB after I deleted last_optimizer_state from the state.
