### ISSUE TITLE
Downloadl links for BEiT-3 are no longer working

### ISSUE THREAD

**Issue by Fr0zenCrane** [microsoft/unilm#1199]
Thank you for contributing this great work, i'm afraid the links you provided are no longer working . I got EMPTY_RESPONSE_ERROR as it suggest that your links are not valid and need a fix. I tried every link mentioned in unilm/beit3/README.md and every one return with the same error.

**Comment by wenhui0924** [comment]
May I know how you download the files? I have tried the links in beit3 README and it works.

**Comment by Fr0zenCrane** [comment]
hello, after your reply, I let my colleague to try these links, and they wrok fine in his computer. Considering that , I will use the weght files downloaded by him. Just let you know that your links work fine, and it was because something went wrong in my computer. I will clsoe this issue
