### ISSUE TITLE
No Module Named Bleu

### ISSUE THREAD

**Issue by nullphantom** [microsoft/unilm#12]
Hi, where is the Bleu come from?

I encounter this when run eval

```python
File "src/qg/eval_on_unilm_tokenized_ref.py", line 4, in <module>
    from bleu.bleu import Bleu
ImportError: No module named bleu.bleu
```

**Comment by WenhuiWang0824** [comment]
Hi, The file `qg/eval_on_unilm_tokenized_ref.py` is dependent on the [evaluation scripts](https://github.com/xinyadu/nqg/tree/master/qgevalcap) of Du et al., (2017). You could find the BLEU package at this [folder](https://github.com/xinyadu/nqg/tree/master/qgevalcap).
