### ISSUE TITLE
Is LayoutLM SROIE score obtained by using ground truth OCR?

### ISSUE THREAD

**Issue by renjithsasidharan** [microsoft/unilm#120]
Is LayoutLM SROIE score obtained by using ground truth OCR? Or did you guys run OCR on test images ?

**Comment by wolfshow** [comment]
It is based on the OCR released by SROIE, but we manullay go through the dataset to fix OCR errors.

**Comment by mikezhang95** [comment]
> It is based on the OCR released by SROIE, but we manullay go through the dataset to fix OCR errors.

Can you share your fixed OCR for fair comparison?
