### ISSUE TITLE
BEIT3 models not available in TIMM and cannot create a model objecft

### ISSUE THREAD

**Issue by rahcode7** [microsoft/unilm#1203]
**Describe**
Model I am using BEIT3:

I am trying to finetune the model, but I am not able to create a model object as BEIT3 is not available in TIMM model library

```
model = create_model(
        model_config,
        pretrained=False,
        drop_path_rate=args.drop_path,
        vocab_size=args.vocab_size,
        checkpoint_activations=args.checkpoint_activations,
    )
```

**Comment by donglixp** [comment]
@rahcode7 You could post a feature request at https://github.com/huggingface/pytorch-image-models/issues

**Comment by rahcode7** [comment]
Is it possible to run it currently without timm. I have downloaded pretrained weights from this repo and changed the above code to the model
model = torch.load("/mypath/beit3_base_patch16_224.zip")
But, I am now getting 'dict' object has no attribute 'state_dict' error.
Can you please help on how to run it without the timm dependecies ?
