### ISSUE TITLE
pip list via kosmos2 docker image?

### ISSUE THREAD

**Issue by caacoe** [microsoft/unilm#1204]
Hey, I totally understand that the recommended usage is via docker. (saying this after finding a prior closed issue with this being the answer)

However, as we all know, this isn't an absolute requirement.

Would any kind person be able to provide a pip list for the docker image please?

Thank you 🙏

**Comment by pengzhiliang** [comment]
@caacoe Hi, sorry for the late response.

After setuping the env, I run `pip list` and the [requirements.txt](https://github.com/microsoft/unilm/files/12078398/docker_requirements2.txt).

After running `pip freeze`, I get [requirements.txt](https://github.com/microsoft/unilm/files/12078405/docker_requirements.txt).

**Comment by pengzhiliang** [comment]
Some packages have changed, and I will be updated in Readme later.

**Comment by caacoe** [comment]
thank you, very much appreciated 🙏
