### ISSUE TITLE
Cannot run KOSMOS2 without DOCKER

### ISSUE THREAD

**Issue by yolandalalala** [microsoft/unilm#1208]
Hi,

First of all, I would like to express my greatest gratitude for developing this excellent work! I'm so impressed with how much it can achieve.

However, I so regret that I am not able to evaluate the KOSMOS2 without the docker. I'm not allowed to run a docker image in my development environment. I have spent a tremendous amount of time trying different workarounds, but they are all failed. To make this impactful work accessible to more people, could you please kindly provide more instructions on how to run the KOSMOS2 without the docker? Thank you so much for your time and for answering my questions!

**Comment by pineking** [comment]
https://github.com/microsoft/unilm/issues/1204#issuecomment-1639812388

**Comment by pengzhiliang** [comment]
Hi, @yolandalalala. Sorry for the late response.
Thanks for [pineking](https://github.com/pineking)'s efforts in making it possible to set up a conda environment for kosmos-2.
You can check it in the mentioned PR, and then have a try.

**Comment by yolandalalala** [comment]
> Hi, @yolandalalala. Sorry for the late response. Thanks for [pineking](https://github.com/pineking)'s efforts in making it possible to set up a conda environment for kosmos-2. You can check it in the mentioned PR, and then have a try.

Thank you so much for your big efforts! @pineking @pengzhiliang
