### ISSUE TITLE
KOSMOS-2: Top-k predictions

### ISSUE THREAD

**Issue by JierunChen** [microsoft/unilm#1209]
When evaluating the KOSMOS-2 on flickr30k entities dataset, R@1, R@5, and R@10 are all reported. However, the predictions are limited to top1 as the `--nbest` is set to be 1 in the file `grd-zeroshot-flickr.sh`. Anything went wrong here?

**Comment by pengzhiliang** [comment]
Hi, @JierunChen . 
`--nbest` is not used to control the top-k box generation.
R@1, R@5, and R@10 means that we use the top 1/5/10 box (depending on the generation order of boxes, if there is no 5/10 box, we will use all predicted box) to calculate recall. 
In fact, we can't control how many boxes produced by kosmos-2, which is different from previous detectors.

**Comment by JierunChen** [comment]
@pengzhiliang Got it. Thanks a lot : )
