### ISSUE TITLE
retnet: pseudocode in the paper is inconsistent with Equation(7)

### ISSUE THREAD

**Issue by fanfanfan-hff** [microsoft/unilm#1213]
![image](https://github.com/microsoft/unilm/assets/70521515/45853cbb-d2eb-4f0c-b541-900e93408680)
![image](https://github.com/microsoft/unilm/assets/70521515/f8db8f08-e776-4b70-aabd-e30beede72bd)

is the cross_retention different with Cross-Chunk?

**Comment by sunyt32** [comment]
Thanks for carefully checking the consistency of Equation(7) and pseudo code. There is an index mistake in Equation(7), where Cross-Chunk should be $Q_{[i]}R_{i-1}\odot \xi$. We will fix this in the next version of our paper.

**Comment by okpatil4u** [comment]
When are you planning to release the code ? The repo says in two days. Are you adhering to that timeline ?

**Comment by donglixp** [comment]
> When are you planning to release the code ? The repo says in two days. Are you adhering to that timeline ?

@okpatil4u https://github.com/microsoft/torchscale/commit/bf65397b26469ac9c24d83a9b779b285c1ec640b
