### ISSUE TITLE
 a multi-line problem about layoutlm

### ISSUE THREAD

**Issue by hyybuaa** [microsoft/unilm#122]
Can layoutlm solve the problem of an entity scattered in multiple lines, such as in a table

**Comment by wolfshow** [comment]
It depends on how your labeled data looks like. For example, multi-line entities also exist in the form understanding task.

**Comment by hyybuaa** [comment]
Do you mean concatenate multi-line of entities through tags？It seems that I need to modify the BIEO labeling method. There may be other tags in the middle of an entity, in the order of reading from top to bottom and from left to right.

**Comment by wolfshow** [comment]
Yes, depending on your applications, you might need to modify the labeling method.

**Comment by nunenuh** [comment]
whoaa, this is my problem too, thanks for the idea to modify the labelling method. But do you have any idea how to do that, I mean the best practice maybe?

**Comment by shihanmax** [comment]
also interest in the discontinuous entitiy tagging scheme
