### ISSUE TITLE
KOSMOS-2 on MMBench

### ISSUE THREAD

**Issue by JierunChen** [microsoft/unilm#1221]
Hi, I noticed that the results of KOSMOS-2 on MMBench were obtained with the help of perplexity, instead of using the GPT-based marking scheme. Is there any reason behind this? How about the performance when using the GPT-based marking scheme? Thanks : )

**Comment by donglixp** [comment]
@JierunChen We directly follow the evaluation protocol of GPT-3, which produces more consistent results across model sizes for the scaling law.

**Comment by JierunChen** [comment]
@donglixp Hi, I try the perplexity-based evaluation on MMBench using the prompt: 
''<image> [image] <\image> [context if any] Question: [question] Answer: [a choice]''. 
But only got 54.9% accuracy on MMBench. Could you kindly suggest what are the prompts used in your evaluation?  Thanks.

**Comment by wenhui0924** [comment]
Hi @JierunChen, we use the same prompt. May I know how you obtain the final answer?

**Comment by JierunChen** [comment]
@wenhui0924 Hi, I modified the ```gradio_app.py```, fed the prompt for inference, extracted the positional scores corresponding to the prompt, and then calculated the PPL. Could you release your script for evaluation? If it's not ready for public release, could you send a copy to me by email [jrchan@zju.edu.cn](mailto:jrchan@zju.edu.cn)? Grateful for the help.

**Comment by wenhui0924** [comment]
We use the average score of tokens of the choice to obtain the final answer. We will release the code for MMBench to the repo.
