### ISSUE TITLE
Can't access the DiT model weights

### ISSUE THREAD

**Issue by carzacc** [microsoft/unilm#1228]
**Describe the bug**

I can't access the pretrained model weights for DiT. I get an HTTP 409 response instead.

The problem arises when using:
* [X] the official example scripts: (give details below)
* [X] my own modified scripts: (give details below)

**To Reproduce**
1. Take any of the PubLayNet model weight links from [the README](https://github.com/md-scanner/unilm/blob/master/dit/README.md)
2. Attempt to make a GET request
3. You will get HTTP 409 status and an error from the web server.

**Expected behavior**

I expected to be able to download the weights, as it I used to when testing some time ago.

- Platform: Linux
- Python version: irrelevant
- PyTorch version (GPU?): irrelevant

**Comment by chandailrc** [comment]
Hope there is an update on this soon... Same goes for the dataset links. Though they can still be sourced from the original sets.

**Comment by senthil-r-10** [comment]
https://github.com/microsoft/unilm/issues/1123
https://github.com/microsoft/unilm/issues/1141
wget get is not working for me, but you can download using this link

https://layoutlm.blob.core.windows.net/dit/dit-pts/dit-base-224-p16-500k-62d53a.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

**Comment by carzacc** [comment]
I hope they don't randomly close this issue like the previous ones, given the fact that the posted links do not cover all of the cases in the README, and even if they did, the README would need to be changed.

**Comment by donglixp** [comment]
The links have been fixed. https://github.com/microsoft/unilm/commit/5255d52de86dad642810f5849dd357769346c1d7

**Comment by SAOHPRWHG** [comment]
@donglixp

Thanks for you updated!

When I use this new weights in 5255d52, I meet a new bug:
......
--opts MODEL.WEIGHTS ./archive/data.pkl
Traceback (most recent call last):
  File "/mnt/backup2/home/szyu22/dit/object_detection/pdf2txt_dit.py", line 104, in <module>
    process_pdf(args.pdf_dir, args.save_images, args.outputs_dir, args.config_file, args.opts)
  File "/mnt/backup2/home/szyu22/dit/object_detection/pdf2txt_dit.py", line 62, in process_pdf
    detections = detect_objects(image_path, config_file, opts)
  File "/mnt/backup2/home/szyu22/dit/object_detection/pdf2txt_dit.py", line 29, in detect_objects
    weights = torch.load(weights_path)
  File "/mnt/home/szyu22/anaconda3/envs/dit/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/mnt/home/szyu22/anaconda3/envs/dit/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

Could you please tell me how to fix this bug? Thanks for your support!

**Comment by n0r4r0n** [comment]
> #1123 #1141 wget is not working for me, but you can download using this link
> 
> https://layoutlm.blob.core.windows.net/dit/dit-pts/dit-base-224-p16-500k-62d53a.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

This URL seems to not work anymore
