### ISSUE TITLE
Downloaded trocr-small-printed.pt, does not appear to be model weights

### ISSUE THREAD

**Issue by deanjgoldman** [microsoft/unilm#1239]
On downloading trocr-small-printed.pt, there don't seem to be any model weights, unless they are in a format I am unfamiliar with. Could anyone explain this, or update that download link with the model weights? The weights seem to be there for trocr-base-printed.pt, so my guess is there was just a small misstep somewhere on uploading the weights for the small model. Thanks.

The folder structure inside trocr-small-printed.pt shows:

/archive
  /data
    - 0
    - 1
    - ...
data.pkl
version

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/commit/5255d52de86dad642810f5849dd357769346c1d7

**Comment by donglixp** [comment]
The downloaded checkpoint is supposed to be a file.

**Comment by deanjgoldman** [comment]
I'm sorry, but the downloaded checkpoint isn't a file. As I said, its a folder called /archive with the above mentioned structure. Would anyone be able to either of the following?

- explain how the content in that folder makes up the model weights
or
- upload the weights in the usual .pt format

Thank you

**Comment by deanjgoldman** [comment]
Ah ok. I didn't realize you can just load the .zip file as is. Thanks.
