### ISSUE TITLE
[Suggestion] This repo is too heavy

### ISSUE THREAD

**Issue by SWHL** [microsoft/unilm#1247]
**Describe**
If I only want to use one of the models in the repo, I have to download the whole repo.
But this is not neccessary.
It is difficult to download the whole repo quickly in a short period of time.

It is recommended to split the repo for easy maintenance and learning.

**Comment by donglixp** [comment]
@SWHL Thanks for your suggestion. We are trying to slim the repo by moving the common parts to shared repos, such as https://github.com/microsoft/torchscale .
