### ISSUE TITLE
How to create a dev set

### ISSUE THREAD

**Issue by ChenZhounan** [microsoft/unilm#125]
I am using the **LayoutLM** to complete  the FUNSD Sequence Labeling Task by runing "python run_seq_labeling.py  --data_dir data --model_type layoutlm --model_name_or_path layoutlm-base-uncased --do_lower_case --max_seq_length 512 **--do_eval** --do_train --num_train_epochs 100.0 --logging_steps 10 --save_steps -1 --output_dir output --labels data/labels.txt --per_gpu_train_batch_size 8 --fp16 --overwrite_output_dir"
I add "--do_eval" because i wanna get the eval result.

But after the training completed, i just got the error that:
`Traceback (most recent call last):
  File "run_seq_labeling.py", line 856, in <module>
    main()
  File "run_seq_labeling.py", line 802, in main
    prefix=global_step,
  File "run_seq_labeling.py", line 309, in evaluate
    args, tokenizer, labels, pad_token_label_id, mode=mode
  File "run_seq_labeling.py", line 417, in load_and_cache_examples
    examples = read_examples_from_file(args.data_dir, mode)
  File "/home/czn/unilm/layoutlm/utils_seq_labeling.py", line 61, in read_examples_from_file
    with open(file_path, encoding="utf-8") as f, open(` 

`FileNotFoundError:[Errno 2] No such file or directory: 'data/dev.txt' ` 
So i wanna know if you can offer the way to generate the dev set.

Thanks a lot.

**Comment by JohnM-TX** [comment]
You can prepare an eval set similar to how you prepared the train set by supplying arguments to preprocess.py. For example,
  `python scripts/funsd_preprocess.py   --data_dir data/testing_data/annotations  --data_split dev`

This will produce dev.txt and dev_boxes.txt which you then put in the same directory as train.txt (or a specific eval directory.) See [funsd_preprocess.py#L138-L144](https://github.com/microsoft/unilm/blob/a9b3b921245731ad4c762d9140f0a1d490a6b56a/layoutlm/scripts/funsd_preprocess.py#L138-L144) for more info.

**Comment by ChenZhounan** [comment]
@JohnM-TX OK. Thank you so much!
