### ISSUE TITLE
[Vlmo]   ERROR -IndexError: list index out of range

### ISSUE THREAD

**Issue by CHB-learner** [microsoft/unilm#1256]
➜ TRANSFORMERS_OFFLINE=1 python run.py with data_root=/home/ubuntu/Zuolab/unilm/vlmo/data/data_arrows_root/ num_gpus=1 num_nodes=1 task_mlm_itm_itc_base whole_word_masking=True step200k per_gpu_batchsize=8 load_path=$INIT_CKPT log_dir=./out/

WARNING - VLMo - No observers have been added to this run
INFO - VLMo - Running command 'main'
INFO - VLMo - Started
Global seed set to 1
drop path rate: 0.1
window_size: (14, 14)
Load ckpt from: /home/ubuntu/Zuolab/unilm/vlmo/1_My_Vlmo/pth/vlmo_base_patch16_224_stage2.pt
Read state dict from ckpt. 
relative_position_bias_table = torch.Size([1126, 144])
relative_position_index = torch.Size([197, 197])
text_relative_position_index = torch.Size([196, 196])
text_imag_relative_position_index = torch.Size([393, 393])
text_embeddings.position_ids = torch.Size([1, 196])
text_embeddings.word_embeddings.weight = torch.Size([30522, 768])
text_embeddings.position_embeddings.weight = torch.Size([196, 768])
text_embeddings.token_type_embeddings.weight = torch.Size([2, 768])
text_embeddings.LayerNorm.weight = torch.Size([768])
text_embeddings.LayerNorm.bias = torch.Size([768])
token_type_embeddings.weight = torch.Size([2, 768])
transformer.cls_token = torch.Size([1, 1, 768])
transformer.patch_embed.proj.weight = torch.Size([768, 3, 16, 16])
transformer.patch_embed.proj.bias = torch.Size([768])
transformer.blocks.0.gamma_1 = torch.Size([768])
transformer.blocks.0.gamma_2 = torch.Size([768])
transformer.blocks.0.norm1.weight = torch.Size([768])
transformer.blocks.0.norm1.bias = torch.Size([768])
transformer.blocks.0.attn.q_bias = torch.Size([768])
transformer.blocks.0.attn.v_bias = torch.Size([768])
transformer.blocks.0.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.0.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.0.attn.proj.bias = torch.Size([768])
transformer.blocks.0.norm2_text.weight = torch.Size([768])
transformer.blocks.0.norm2_text.bias = torch.Size([768])
transformer.blocks.0.norm2_imag.weight = torch.Size([768])
transformer.blocks.0.norm2_imag.bias = torch.Size([768])
transformer.blocks.0.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.0.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.0.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.0.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.0.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.0.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.0.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.0.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.1.gamma_1 = torch.Size([768])
transformer.blocks.1.gamma_2 = torch.Size([768])
transformer.blocks.1.norm1.weight = torch.Size([768])
transformer.blocks.1.norm1.bias = torch.Size([768])
transformer.blocks.1.attn.q_bias = torch.Size([768])
transformer.blocks.1.attn.v_bias = torch.Size([768])
transformer.blocks.1.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.1.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.1.attn.proj.bias = torch.Size([768])
transformer.blocks.1.norm2_text.weight = torch.Size([768])
transformer.blocks.1.norm2_text.bias = torch.Size([768])
transformer.blocks.1.norm2_imag.weight = torch.Size([768])
transformer.blocks.1.norm2_imag.bias = torch.Size([768])
transformer.blocks.1.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.1.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.1.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.1.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.1.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.1.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.1.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.1.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.2.gamma_1 = torch.Size([768])
transformer.blocks.2.gamma_2 = torch.Size([768])
transformer.blocks.2.norm1.weight = torch.Size([768])
transformer.blocks.2.norm1.bias = torch.Size([768])
transformer.blocks.2.attn.q_bias = torch.Size([768])
transformer.blocks.2.attn.v_bias = torch.Size([768])
transformer.blocks.2.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.2.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.2.attn.proj.bias = torch.Size([768])
transformer.blocks.2.norm2_text.weight = torch.Size([768])
transformer.blocks.2.norm2_text.bias = torch.Size([768])
transformer.blocks.2.norm2_imag.weight = torch.Size([768])
transformer.blocks.2.norm2_imag.bias = torch.Size([768])
transformer.blocks.2.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.2.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.2.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.2.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.2.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.2.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.2.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.2.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.3.gamma_1 = torch.Size([768])
transformer.blocks.3.gamma_2 = torch.Size([768])
transformer.blocks.3.norm1.weight = torch.Size([768])
transformer.blocks.3.norm1.bias = torch.Size([768])
transformer.blocks.3.attn.q_bias = torch.Size([768])
transformer.blocks.3.attn.v_bias = torch.Size([768])
transformer.blocks.3.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.3.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.3.attn.proj.bias = torch.Size([768])
transformer.blocks.3.norm2_text.weight = torch.Size([768])
transformer.blocks.3.norm2_text.bias = torch.Size([768])
transformer.blocks.3.norm2_imag.weight = torch.Size([768])
transformer.blocks.3.norm2_imag.bias = torch.Size([768])
transformer.blocks.3.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.3.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.3.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.3.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.3.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.3.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.3.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.3.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.4.gamma_1 = torch.Size([768])
transformer.blocks.4.gamma_2 = torch.Size([768])
transformer.blocks.4.norm1.weight = torch.Size([768])
transformer.blocks.4.norm1.bias = torch.Size([768])
transformer.blocks.4.attn.q_bias = torch.Size([768])
transformer.blocks.4.attn.v_bias = torch.Size([768])
transformer.blocks.4.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.4.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.4.attn.proj.bias = torch.Size([768])
transformer.blocks.4.norm2_text.weight = torch.Size([768])
transformer.blocks.4.norm2_text.bias = torch.Size([768])
transformer.blocks.4.norm2_imag.weight = torch.Size([768])
transformer.blocks.4.norm2_imag.bias = torch.Size([768])
transformer.blocks.4.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.4.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.4.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.4.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.4.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.4.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.4.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.4.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.5.gamma_1 = torch.Size([768])
transformer.blocks.5.gamma_2 = torch.Size([768])
transformer.blocks.5.norm1.weight = torch.Size([768])
transformer.blocks.5.norm1.bias = torch.Size([768])
transformer.blocks.5.attn.q_bias = torch.Size([768])
transformer.blocks.5.attn.v_bias = torch.Size([768])
transformer.blocks.5.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.5.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.5.attn.proj.bias = torch.Size([768])
transformer.blocks.5.norm2_text.weight = torch.Size([768])
transformer.blocks.5.norm2_text.bias = torch.Size([768])
transformer.blocks.5.norm2_imag.weight = torch.Size([768])
transformer.blocks.5.norm2_imag.bias = torch.Size([768])
transformer.blocks.5.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.5.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.5.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.5.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.5.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.5.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.5.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.5.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.6.gamma_1 = torch.Size([768])
transformer.blocks.6.gamma_2 = torch.Size([768])
transformer.blocks.6.norm1.weight = torch.Size([768])
transformer.blocks.6.norm1.bias = torch.Size([768])
transformer.blocks.6.attn.q_bias = torch.Size([768])
transformer.blocks.6.attn.v_bias = torch.Size([768])
transformer.blocks.6.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.6.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.6.attn.proj.bias = torch.Size([768])
transformer.blocks.6.norm2_text.weight = torch.Size([768])
transformer.blocks.6.norm2_text.bias = torch.Size([768])
transformer.blocks.6.norm2_imag.weight = torch.Size([768])
transformer.blocks.6.norm2_imag.bias = torch.Size([768])
transformer.blocks.6.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.6.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.6.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.6.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.6.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.6.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.6.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.6.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.7.gamma_1 = torch.Size([768])
transformer.blocks.7.gamma_2 = torch.Size([768])
transformer.blocks.7.norm1.weight = torch.Size([768])
transformer.blocks.7.norm1.bias = torch.Size([768])
transformer.blocks.7.attn.q_bias = torch.Size([768])
transformer.blocks.7.attn.v_bias = torch.Size([768])
transformer.blocks.7.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.7.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.7.attn.proj.bias = torch.Size([768])
transformer.blocks.7.norm2_text.weight = torch.Size([768])
transformer.blocks.7.norm2_text.bias = torch.Size([768])
transformer.blocks.7.norm2_imag.weight = torch.Size([768])
transformer.blocks.7.norm2_imag.bias = torch.Size([768])
transformer.blocks.7.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.7.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.7.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.7.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.7.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.7.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.7.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.7.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.8.gamma_1 = torch.Size([768])
transformer.blocks.8.gamma_2 = torch.Size([768])
transformer.blocks.8.norm1.weight = torch.Size([768])
transformer.blocks.8.norm1.bias = torch.Size([768])
transformer.blocks.8.attn.q_bias = torch.Size([768])
transformer.blocks.8.attn.v_bias = torch.Size([768])
transformer.blocks.8.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.8.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.8.attn.proj.bias = torch.Size([768])
transformer.blocks.8.norm2_text.weight = torch.Size([768])
transformer.blocks.8.norm2_text.bias = torch.Size([768])
transformer.blocks.8.norm2_imag.weight = torch.Size([768])
transformer.blocks.8.norm2_imag.bias = torch.Size([768])
transformer.blocks.8.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.8.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.8.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.8.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.8.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.8.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.8.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.8.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.9.gamma_1 = torch.Size([768])
transformer.blocks.9.gamma_2 = torch.Size([768])
transformer.blocks.9.norm1.weight = torch.Size([768])
transformer.blocks.9.norm1.bias = torch.Size([768])
transformer.blocks.9.attn.q_bias = torch.Size([768])
transformer.blocks.9.attn.v_bias = torch.Size([768])
transformer.blocks.9.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.9.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.9.attn.proj.bias = torch.Size([768])
transformer.blocks.9.norm2_text.weight = torch.Size([768])
transformer.blocks.9.norm2_text.bias = torch.Size([768])
transformer.blocks.9.norm2_imag.weight = torch.Size([768])
transformer.blocks.9.norm2_imag.bias = torch.Size([768])
transformer.blocks.9.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.9.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.9.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.9.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.9.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.9.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.9.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.9.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.10.gamma_1 = torch.Size([768])
transformer.blocks.10.gamma_2 = torch.Size([768])
transformer.blocks.10.norm1.weight = torch.Size([768])
transformer.blocks.10.norm1.bias = torch.Size([768])
transformer.blocks.10.attn.q_bias = torch.Size([768])
transformer.blocks.10.attn.v_bias = torch.Size([768])
transformer.blocks.10.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.10.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.10.attn.proj.bias = torch.Size([768])
transformer.blocks.10.norm2_text.weight = torch.Size([768])
transformer.blocks.10.norm2_text.bias = torch.Size([768])
transformer.blocks.10.norm2_imag.weight = torch.Size([768])
transformer.blocks.10.norm2_imag.bias = torch.Size([768])
transformer.blocks.10.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.10.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.10.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.10.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.10.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.10.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.10.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.10.mlp_imag.fc2.bias = torch.Size([768])
transformer.blocks.11.gamma_1 = torch.Size([768])
transformer.blocks.11.gamma_2 = torch.Size([768])
transformer.blocks.11.norm1.weight = torch.Size([768])
transformer.blocks.11.norm1.bias = torch.Size([768])
transformer.blocks.11.attn.q_bias = torch.Size([768])
transformer.blocks.11.attn.v_bias = torch.Size([768])
transformer.blocks.11.attn.qkv.weight = torch.Size([2304, 768])
transformer.blocks.11.attn.proj.weight = torch.Size([768, 768])
transformer.blocks.11.attn.proj.bias = torch.Size([768])
transformer.blocks.11.norm2_text.weight = torch.Size([768])
transformer.blocks.11.norm2_text.bias = torch.Size([768])
transformer.blocks.11.norm2_imag.weight = torch.Size([768])
transformer.blocks.11.norm2_imag.bias = torch.Size([768])
transformer.blocks.11.mlp_text.fc1.weight = torch.Size([3072, 768])
transformer.blocks.11.mlp_text.fc1.bias = torch.Size([3072])
transformer.blocks.11.mlp_text.fc2.weight = torch.Size([768, 3072])
transformer.blocks.11.mlp_text.fc2.bias = torch.Size([768])
transformer.blocks.11.mlp_imag.fc1.weight = torch.Size([3072, 768])
transformer.blocks.11.mlp_imag.fc1.bias = torch.Size([3072])
transformer.blocks.11.mlp_imag.fc2.weight = torch.Size([768, 3072])
transformer.blocks.11.mlp_imag.fc2.bias = torch.Size([768])
transformer.norm.weight = torch.Size([768])
transformer.norm.bias = torch.Size([768])
pooler.dense.weight = torch.Size([768, 768])
pooler.dense.bias = torch.Size([768])
mlm_score.bias = torch.Size([30522])
mlm_score.transform.dense.weight = torch.Size([768, 768])
mlm_score.transform.dense.bias = torch.Size([768])
mlm_score.transform.LayerNorm.weight = torch.Size([768])
mlm_score.transform.LayerNorm.bias = torch.Size([768])
mlm_score.decoder.weight = torch.Size([30522, 768])
{'itm': 1, 'itc': 1, 'mlm': 1, 'textmlm': 0, 'vqa': 0, 'nlvr2': 0, 'irtr': 0}
text position_embeddings size: torch.Size([40, 768])
missing_keys: ['logit_scale', 'logit_vl_scale', 'transformer.blocks.10.mlp_vl.fc1.weight', 'transformer.blocks.10.mlp_vl.fc1.bias', 'transformer.blocks.10.mlp_vl.fc2.weight', 'transformer.blocks.10.mlp_vl.fc2.bias', 'transformer.blocks.10.norm2_vl.weight', 'transformer.blocks.10.norm2_vl.bias', 'transformer.blocks.11.mlp_vl.fc1.weight', 'transformer.blocks.11.mlp_vl.fc1.bias', 'transformer.blocks.11.mlp_vl.fc2.weight', 'transformer.blocks.11.mlp_vl.fc2.bias', 'transformer.blocks.11.norm2_vl.weight', 'transformer.blocks.11.norm2_vl.bias', 'itm_score.fc.weight', 'itm_score.fc.bias', 'itc_text_proj.fc.weight', 'itc_image_proj.fc.weight', 'itc_vl_text_proj.fc.weight', 'itc_vl_image_proj.fc.weight']
unexpected_keys: []
grad_steps: 128
resume_ckpt: None
ClusterPlugin: using Lightning Cluster Environment
plugin_list: [<pytorch_lightning.plugins.environments.lightning_environment.LightningEnvironment object at 0x7ff4a2652cd0>]
[W Context.cpp:70] Warning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (function operator())
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:59: LightningDeprecationWarning: Setting `Trainer(flush_logs_every_n_steps=10)` is deprecated in v1.5 and will be removed in v1.7. Please configure flushing in the logger instead.
  rank_zero_deprecation(
Global seed set to 1
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
INFO - root - Added key: store_based_barrier_key:1 to store for rank: 0
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/torchvision/transforms/transforms.py:803: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/torchvision/transforms/transforms.py:257: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
ERROR - VLMo - Failed after 0:00:05!
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "run.py", line 166, in main
    trainer.fit(model, datamodule=dm)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1134, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1434, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datamodules/multitask_datamodule.py", line 34, in setup
    dm.setup(stage)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datamodules/datamodule_base.py", line 150, in setup
    self.set_train_dataset()
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datamodules/datamodule_base.py", line 77, in set_train_dataset
    self.train_dataset = self.dataset_cls(
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datasets/vg_caption_dataset.py", line 15, in __init__
    super().__init__(*args, **kwargs, names=names, text_column_name="caption")
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datasets/base_dataset.py", line 53, in __init__
    self.table_names += [name] * len(tables[i])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 69, in <module>
    def main(_config):
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/experiment.py", line 190, in automain
    self.run_commandline()
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'

my data:

data_arrows_root
├── coco_caption_karpathy_restval.arrow
├── coco_caption_karpathy_test.arrow
├── coco_caption_karpathy_train.arrow
└── coco_caption_karpathy_val.arrow

checkpoint:

pth
└── vlmo_base_patch16_224_stage2.pt

**Comment by donglixp** [comment]
The error was caught during data loading. You could step into the function to see why `tables[i]` cannot be accessed.

self.table_names += [name] * len(tables[i])
IndexError: list index out of range
