### ISSUE TITLE
[Kosmos-2] inference warning

### ISSUE THREAD

**Issue by jun0wanan** [microsoft/unilm#1262]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
![(TF@W$(L`TA{8)A(`6D19EK](https://github.com/microsoft/unilm/assets/54523624/769e46cc-8139-4a12-8872-7b960fb5b19b)

this is warning ...

I would like to know if this question will affect the results? It seems like this is just a warning... 

**Expected behavior**

- Platform: linux
- Python version: python3.9
- PyTorch version (GPU?): the same with author

**Comment by pengzhiliang** [comment]
Hi, @jun0wanan. Thanks for the attention!

Don't worry about it, which is just a loger-information.
