### ISSUE TITLE
PublicAccessNotPermitted error on download links

### ISSUE THREAD

**Issue by sorenjakobsen** [microsoft/unilm#1263]
The links to download the pre-processed data and the pre-trained model are not working - clicking them results in an error with the message 'PublicAccessNotPermitted'.

**Comment by donglixp** [comment]
@sorenjakobsen  Could you add the link that you tried?

**Comment by sorenjakobsen** [comment]
@donglixp Yes, sorry it is on this project:

https://github.com/microsoft/unilm/tree/master/layoutreader

The links:

https://layoutlm.blob.core.windows.net/readingbank/dataset/ReadingBank.zip

https://layoutlm.blob.core.windows.net/readingbank/model/layoutreader-base-readingbank.zip

**Comment by donglixp** [comment]
If any file on this page fails to download, please add the following string as a suffix to the URL.

Suffix String: ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

**Comment by sorenjakobsen** [comment]
Great, thanks for the help!:)
