### ISSUE TITLE
Broken link toward Raven-IQ evaluation dataset

### ISSUE THREAD

**Issue by bsxxdw** [microsoft/unilm#1265]
Dear authors,
I sincerely admire your excellent work Kosmos-1 and really appreciate your hard work to curate  Raven-IQ test dataset.
However, the hyperlink toward Raven-IQ evaluation dataset in Kosmos-1's paper [https://aka.ms/kosmos-iq50](https://aka.ms/kosmos-iq50) now seems to be broken.
Where can I get the correct download link?
Looking for your reply and thanks in advance.

**Comment by donglixp** [comment]
Fixed. You could try the above link again.

**Comment by donglixp** [comment]
```bash
wget -O kosmos-iq50.zip "https://conversationhub.blob.core.windows.net/beit-share-public/kosmos-1/kosmos-iq50.zip?sv=2021-10-04&st=2023-06-08T11%3A16%3A02Z&se=2033-06-09T11%3A16%3A00Z&sr=c&sp=r&sig=N4pfCVmSeq4L4tS8QbrFVsX6f6q844eft8xSuXdxU48%3D"
```

**Comment by AceCHQ** [comment]
> @bsxxdw Fixed. You could try the above link again.

Hello, it's broken again. Can you share me with another one?

**Comment by YRdddream** [comment]
@AceCHQ 
Hi, please refer to this link. https://drive.google.com/file/d/1A8-Gts_ySOEw1ACmEwzjwOZ0ydmp_loY/view?usp=drive_link
