### ISSUE TITLE
E5 max legnth, position embeddings

### ISSUE THREAD

**Issue by JejuWayfarer** [microsoft/unilm#1273]
**Describe**

**I have a question regarding the E5 model and the associated paper.**

On page 15 of the E5 paper, it is mentioned that position embeddings were frozen, and the maximum text length for evaluation was set to 512. Towards the bottom of the page, there is a suggestion to set the max length to 128 for pre-training and 192 for fine-tuning. Could you please explain the rationale behind not using a consistent max length of 512 throughout?

My understanding is that the initialization with BERT led to a maximum length of 512. However, I'm curious whether the training involved reducing the max length to potentially increase the batch size. Given that the pre-training data contains numerous lengthy texts, is there a specific reason for opting for a max length of 128? If this is the case, am I correct in assuming that the latter part of lengthy texts remains unutilized due to this truncation? I would greatly appreciate any clarification regarding the approach to position embeddings and the varying max lengths employed during training.

**Comment by intfloat** [comment]
The main reason for using a max length of 128 for pre-training is to increase the batch size under the GPU memory constraint, as large batch size is often critical for contrastive pre-training.

We also tried a few variants but did not see improvements:
1. For longer texts, randomly select a contiguous span as input so that the model can see the latter part with some probability.
2. Set the maximum length to 512 in the second stage (supervised fine-tuning stage).

Both variants achieved comparable results as reported in the paper. The reason may be that most benchmarks only involve short passages instead of long documents.

**Comment by JejuWayfarer** [comment]
I understand, thanks for the answer.
Additionally, may I know which dense retriever (cross-enoder) you used for hard negative extraction and knowledge distillation when fine-tuning the mE5 model, and if the model is publicly available?

**Comment by intfloat** [comment]
We use the retriever from the [SimLM](https://arxiv.org/abs/2207.02578) paper for hard negative mining, and train separate ELECTRA based cross-encoder models for MS-MARCO and NQ. The one for MS-MARCO is available at https://huggingface.co/intfloat/simlm-msmarco-reranker, but the one for NQ is not made public.

**Comment by JejuWayfarer** [comment]
Thank you. I saw the dense retriever for the E5 model, but it's hard to see which one you used for the multilingualE5. Do you happen to know how you built the dense retriever for the mutilingual? Similarly, did they do cross-encoder training with XLM-RoBERTA as a base?

**Comment by intfloat** [comment]
Yes, for multilingual E5 models, we use the model after multilingual contrastive pre-training for hard negative mining, and train a cross-encoder for knowledge distillation with xlm-roberta as a base.

**Comment by JejuWayfarer** [comment]
Thank you for your answer. 
I'm curious about whether, for the multilingual model, a large amount of data was used for fine-tuning and whether mining and KD were applied separately after individual data training or all at once after combined training. If this model is made public, it seems like it would be very helpful for people using different languages. I'm wondering if there are any plans to release it.

**Comment by intfloat** [comment]
The multilingual retrievers are publicly available at https://github.com/microsoft/unilm/tree/master/e5#multilingual-pre-trained-models

The specific datasets for fine-tuning are listed at https://huggingface.co/intfloat/multilingual-e5-large#training-details

The cross-encoder teacher models will not be made public.

**Comment by JejuWayfarer** [comment]
Okay, that helped a lot. Thank you so much.
