### ISSUE TITLE
[LayoutLM] Minimum GPUs requirements and training time

### ISSUE THREAD

**Issue by nv-quan** [microsoft/unilm#128]
Hello,
I am trying to run fine tuning for the Sequence Labeling task but keep getting CUDA out of memory no matter how small batch size and max_seq_length are. I have only one Quadro K2000 2GB so I guess that's the problem. Now I'm thinking about going to cloud but I need an estimated computing power because my resources are limited. So has anyone succeed training it on a limited resource? what is your training time? And what would be a minimum requirements for fine tuning?
Thank you.

**Comment by wolfshow** [comment]
@nv-quan I think 2GB memory is too small for the fine-tuning. I suggest that you should at least use a GPU with 8GB memory and try again.

**Comment by nv-quan** [comment]
> @nv-quan I think 2GB memory is too small for the fine-tuning. I suggest that you should at least use a GPU with 8GB memory and try again.

Thank you. Also have you done fine tuning this model? How long did it take and what was your GPU?

**Comment by wolfshow** [comment]
@nv-quan Typically, we use the Tesla V100 GPUs and it should be very fast if you only fine-tune the model on tens of thousands of training samples.

**Comment by vibeeshan025** [comment]
> @nv-quan Typically, we use the Tesla V100 GPUs and it should be very fast if you only fine-tune the model on tens of thousands of training samples.

How much is very fast, days hours or minutes? 
Can you give me more details.

**Comment by nazreen** [comment]
bump
