### ISSUE TITLE
Unable to reproduce Kosmos 2

### ISSUE THREAD

**Issue by yuvalkirstain** [microsoft/unilm#1285]
Hello, I am trying to finetune Kosmos 2 but it seems like the code is not aligned with the instructions in the repo, and a new user will not be able to run experiments by following the given instructions. 

Some examples: 
1. There are arguments in the train command that are missing from the repo. For example [--no-freeze-all](https://github.com/microsoft/unilm/blob/master/kosmos-2/train.sh#L49) only appears in the bash script, but is missing from the actual code. This is also true for the `--init-from-file`.
2. [this else statement](https://github.com/microsoft/unilm/blob/master/kosmos-2/unilm/data/vl/laion2b_obj_loader.py#L246), why does a file path needs to include `laion2b_filtered_tsvs_v1` or `coyo_filtered_tsvs_v1`? This is not written in the README.

I was really impressed with the model and would like to build on this work, and will appreciate if the maintainers/authors will make sure that the instructions are aligned with the code, and that a new user can easily experiment with the model/repo.

**Comment by pengzhiliang** [comment]
Hi, @yuvalkirstain. Thanks for kind suggestions!
I will check the code again to align it with instructions.

**Comment by yuvalkirstain** [comment]
@pengzhiliang thank you so much! I also think that including a cmd for multinode/multigpu training and data files samples can help users make sure that they are reproducing/experimenting properly.
