### ISSUE TITLE
Question - Why TSVs and not webdatasets

### ISSUE THREAD

**Issue by yuvalkirstain** [microsoft/unilm#1289]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): Kosmos 2

Hello, I am wondering, currently our team uses webdatasets to iterate on text+image data. I see that Kosmos 2 uses tsvs. What are the benefits of tsvs? 

Thank you!

**Comment by wenhui0924** [comment]
There is no particular reason. I think webdataset is also a great choice.
