### ISSUE TITLE
LayoutLM for translation

### ISSUE THREAD

**Issue by renjithsasidharan** [microsoft/unilm#129]
Have you considered the use LayoutLM for translation task?

For example, the information extraction from documents could be modelled as translation task. This way model can learn to correct OCR errors(2,T0 -> 2.70, 18 4ug 2020 -> 18/08/2020)

**Comment by wolfshow** [comment]
@renjithsasidharan This is a good idea that we haven't tried yet. I think common OCR errors may have been fixed in today's SOTA OCR tools. Meanwhile, the labeled training samples in real-world document IE tasks may be not sufficient to train a LayoutLM translation model.
