### ISSUE TITLE
missing loss term about vq-kd beit-v2

### ISSUE THREAD

**Issue by sjtulyf123** [microsoft/unilm#1290]
Hello, in beit v2 paper, the vq-kd loss is
<img width="1050" alt="下载" src="https://github.com/microsoft/unilm/assets/49093737/2bd1819c-717b-49d9-a4b5-20c091cccff6">

but in the code https://github.com/microsoft/unilm/blob/master/beit2/modeling_vqkd.py#L213, it seems that the second loss term in the above figure is missing? Or is there any consideration on this loss?

**Comment by pengzhiliang** [comment]
Hi, @sjtulyf123. Thanks for the attention.

Actually, we use exponential moving averages (EMA) to update the codebook instead of the vq loss. 
Refer to [vqvae paper](https://arxiv.org/pdf/1711.00937.pdf) appendix for details.

**Comment by sjtulyf123** [comment]
> Hi, @sjtulyf123. Thanks for the attention.
> 
> Actually, we use exponential moving averages (EMA) to update the codebook instead of the vq loss. Refer to [vqvae paper](https://arxiv.org/pdf/1711.00937.pdf) appendix for details.

Got it, thanks.
