### ISSUE TITLE
beit-the question about the analysis of self-attention map

### ISSUE THREAD

**Issue by zwx519** [microsoft/unilm#1296]
if this piece of code about this part can be open source?
 which weights are used in this visualization. The scale display of patch size and image visualized in the paper should not be 224*224 for image size and 16 for patch.

**Comment by addf400** [comment]
model and code can be found in [here](https://github.com/microsoft/unilm/tree/master/beit2#code-for-analysis-of-self-attention-map)

**Comment by addf400** [comment]
> model and code can be found in [here](https://github.com/microsoft/unilm/tree/master/beit2#code-for-analysis-of-self-attention-map)

We use 480x480 for input and do interpolation for infering followed by [DINO](https://github.com/facebookresearch/dino)

**Comment by zwx519** [comment]
> > model and code can be found in [here](https://github.com/microsoft/unilm/tree/master/beit2#code-for-analysis-of-self-attention-map)
> 
> We use 480x480 for input and do interpolation for infering followed by [DINO](https://github.com/facebookresearch/dino)

Thank you very much. It helps me a lot!

**Comment by zwx519** [comment]
Hi, I tried this code, but if I set the img_size of the model to 480, it would cause a mismatch between the model and the parameters. The error is as follows:  
 File "E:\visualization\unilm\unilm-master\beit2\visualize_attention.py", line 145, in &lt; module&gt;
msg = model.load_state_dict(state_dict, strict=False)
File "D:\anaconda\lib\site-packages\torch\nn\modules\module.py", line 1497, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisionTransformerForMaskedImageModeling:
size mismatch for pos_embed:  copying a param with shape torch.Size([1, 197, 768]) from checkpoint, the shape in current model is torch.Size([1, 901,  768]).

But if I set the img_size of the model to 224 and the weights match, I get the following error:
File "E:\visualization\unilm\unilm-master\beit2\visualize_attention.py", line 182, in &lt; module&gt;
attentions = model.get_last_selfattention(img.to(device))
File "E:\visualization\unilm\unilm-master\beit2\modeling_pretrain.py", line 231, in get_last_selfattention
x = x + self.pos_embed
RuntimeError: The size of tensor a (901) must match the size of tensor b (197) at non-singleton dimension 1

self.pos_embed either 197 or 901 will give an error。I tried setting both input_size and img_size to 224 and it worked。

**Comment by addf400** [comment]
@zwx519 , the model is pre-trained under 224x224 and the `pos_embed`'s shape should be [1, 197, 768], it will do interpolation while inferring (more details in [code](https://github.com/microsoft/unilm/blob/master/beit2/modeling_pretrain.py#L252)).
It seems that the issue is caused by setting the img_size to 480 when creating the model. You can keep the img_size at 224 when creating the model, which allows you to deal with various resolutions using [online interpolation op]((https://github.com/microsoft/unilm/blob/master/beit2/modeling_pretrain.py#L252)).

**Comment by zwx519** [comment]
Thank you very much！this solved my problem perfectly.
