### ISSUE TITLE
does LayoutXLM supports Korean also?

### ISSUE THREAD

**Issue by kittyLunar** [microsoft/unilm#1301]
I am trying to extract the information from documents with LayoutXLM 
however, I could not find any list about all supported 53 languages
I could only find 7 languages that are in XFUND
So, does LayoutXLM supports Korean?

And how about Layoutlmv3? does it support Korean?

Thanks in advance

**Comment by donglixp** [comment]
![image](https://github.com/microsoft/unilm/assets/1070872/9fdc2614-63e0-4aab-84a5-be9b0c6602c9)
https://arxiv.org/pdf/2104.08836.pdf

Korean is also supported.

**Comment by kittyLunar** [comment]
How about the Layoutlmv3? I cannot find it even in paper
