### ISSUE TITLE
[Kosmos-2] Inference Script

### ISSUE THREAD

**Issue by soham-joshi** [microsoft/unilm#1304]
Great work by the team on the Kosmos-2 Project!

Is there an inference script (maybe in the form of a Colab notebook) already created? If yes, please could you share it? I wanted to infer the model just like in the HuggingFace [Demo](https://huggingface.co/spaces/ydshieh/Kosmos-2) (given an input image, the model outputs the predictions for different tasks).

Thanks!

**Comment by donglixp** [comment]
K-2 will be integrated into the Transformers library very soon, so you could call the module easily.

https://github.com/huggingface/transformers/pull/24709

**Comment by soham-joshi** [comment]
Okay Thanks @donglixp !
