### ISSUE TITLE
[vlmo] Step 1: Vision Pre-Training

### ISSUE THREAD

**Issue by CHB-learner** [microsoft/unilm#1305]
[Step 1: Vision Pre-Training](https://github.com/microsoft/unilm/tree/master/vlmo#step-1-vision-pre-training)

How do I train the  Vision Pre-Training model on my own data(For example, my data is stored like coco format)?

**Comment by donglixp** [comment]
You could follow steps 1-3 as shown in https://github.com/microsoft/unilm/tree/master/vlmo#pre-training .

**Comment by CHB-learner** [comment]
> You could follow steps 1-3 as shown in https://github.com/microsoft/unilm/tree/master/vlmo#pre-training .

[Step 1: Vision Pre-Training](https://github.com/microsoft/unilm/tree/master/vlmo#step-1-vision-pre-training)
Only pre-trained model weights are provided, no training commands are provided.

**Comment by donglixp** [comment]
There are step 2 and step 3 which show the training commands.
