### ISSUE TITLE
[kosmos-2] Unable to start the demo 

### ISSUE THREAD

**Issue by wendellgithub0206** [microsoft/unilm#1307]
Can kosmos-2 not run on Windows? Is it because of the error message 'Redirects are currently not supported in Windows or MacOs.?

![image](https://github.com/microsoft/unilm/assets/61726383/590d504e-692d-4fe4-b8fb-6b611e417993)

If this is a silly question, I apologize. I'm still learning.

**Comment by donglixp** [comment]
I found a solution at https://github.com/facebookresearch/llama/issues/497#issuecomment-1656525771, which could help.
