### ISSUE TITLE
sequence label predict

### ISSUE THREAD

**Issue by windar427** [microsoft/unilm#132]
hi:
  I ’ve trained the model, can I just write it as "--do_predict" instead of "--do_train \ --do_predict", otherwise I have to write the training again

**Comment by ranpox** [comment]
Yes. Please also remove the `--overwrite_output_dir` to avoid overwriting the saved models.

**Comment by elnazsn1988** [comment]
@ranpox can you ellaborate, does the output directory where the trained model exist, now count as the input to the predict? if so, where does the model direct the output of the prediction?
