### ISSUE TITLE
E5: what prompt is used in training and evaluation?

### ISSUE THREAD

**Issue by memray** [microsoft/unilm#1325]
@intfloat 
**Describe**
I tried to reproduce the E5 score on MTEB (particularly BEIR) using the released checkpoint, but I do observe a big gap on some datasets (e.g. on TREC-COVID reproduced 51.0 vs. reported 79.6). I suspect that the prompt can be the key (as in the eval [code](https://github.com/microsoft/unilm/blob/027f0eb1cedac529915721110ab9a8dbdfad4dd9/e5/mteb_eval.py#L27C24-L27C30)). It is not clearly stated in the paper (Sec 4.3, it mentions that "For tasks other than zero-shot text classification and retrieval, we use the query embeddings by default.").

So I wonder if you can elaborate what prompts are used in E5 training and MTEB evaluation? 
1.  What prompts are used in pretraining?
2. What prompts are used in fine-tuning?
3. What prompts are used in MTEB evaluation? Does the prompt applied to both query and doc ([line 32](https://github.com/microsoft/unilm/blob/027f0eb1cedac529915721110ab9a8dbdfad4dd9/e5/mteb_eval.py#L32) shows ['', 'query: ', 'passage: '])?

Thank you!
Rui

**Comment by intfloat** [comment]
For BEIR evaluation, please refer to the following code snippet. https://github.com/microsoft/unilm/blob/027f0eb1cedac529915721110ab9a8dbdfad4dd9/e5/mteb_beir_eval.py#L55-L65 
We prepend "query: " and "passage: " respectively.


For MTEB evaluation (except its BEIR subset), we simply prepend "query: " to all texts. https://github.com/microsoft/unilm/blob/027f0eb1cedac529915721110ab9a8dbdfad4dd9/e5/scripts/eval_mteb.sh#L21-L26

**Comment by memray** [comment]
Sounds good! Thank you!
