### ISSUE TITLE
[Kosmos-2] unable to build the environment

### ISSUE THREAD

**Issue by Leebh-kor** [microsoft/unilm#1326]
First of all, thank you for sharing the awesome code. I have an issue setting up the environment, so I have a question. I executed the container using the nvcr.io/nvidia/pytorch:22.10-py3 Docker image, as stated in the README, and cloned the repository. Then, I installed the packages line by line using the commands in `vl_setup_xl.sh`. However, when I run `pip install fairseq`, it seems that there is a dependency conflict after the torch version changes. In other words, after installing fairseq, the torch version changes from `1.13.0a0+d0d6b1f` to `2.1.0+cp38~` (I don't remember exactly). I'm wondering if this phenomenon can be a problem, and I would appreciate it if you could let me know how to solve it.

**Comment by donglixp** [comment]
@pengzhiliang

**Comment by donglixp** [comment]
@Leebh-kor  The pytorch version should be fine if you could run the code successfully.
