### ISSUE TITLE
Training Model For Custom Data Set

### ISSUE THREAD

**Issue by andrewcby** [microsoft/unilm#133]
Hi,
I'm wondering if there's a way to modify the model to train on custom data set. Since the model is based on BERT, and BERT supports custom data training. Namely, my dataset has far more classes than 16, which is what the trained model currently is expecting. Thanks!

**Comment by ranpox** [comment]
Sure, you may need to modify the [`get_labels` ](https://github.com/microsoft/unilm/blob/63ed32b9fb7c33df3e9beea427b54c0bfb196556/layoutlm/utils_classification.py#L149).
