### ISSUE TITLE
How to prepare the text data in Kosmos-2

### ISSUE THREAD

**Issue by wufan-tb** [microsoft/unilm#1330]
Hello, thanks for your great work.  I am trying to train kosmos-2, yet I don't know how to prepare text data, when I set the `/path/to/text config/` to `None`  (followed the instructions in train.sh), I got an error, it seems that the text data is necessary.

![image](https://github.com/microsoft/unilm/assets/34300920/65f24c58-9137-4d09-a63a-529802578b5c)

So how should I prepare this `train-nogithub-noarvix-nopubmed-mtnlg.json`,  any help will be appreciated.

**Comment by donglixp** [comment]
We only provided the GRiT data as shown in the repo. For text data and interleaved data, you can prepare your corpora and update the data loader following your data format. You can use RedPajama/RefinedWeb and mC4 for these two parts.

**Comment by wufan-tb** [comment]
> We only provided the GRiT data as shown in the repo. For text data and interleaved data, you can prepare your corpora and update the data loader following your data format. You can use RedPajama/RefinedWeb and mC4 for these two parts.

Thanks for your reply, I also want to consult you are the text data and interleaved data necessary, can I train the model only with GRiT data?

**Comment by donglixp** [comment]
Text data and interleaved data are mixed in to make sure that language capabilities and multimodal in-context learning can be retained. If you only need multimodal grounding capability, the GRiT dataset is enough for tuning. But you would expect more, the other corpora are needed.

**Comment by wufan-tb** [comment]
I see, thanks for your kindly reply!
