### ISSUE TITLE
Layoutlmft issue

### ISSUE THREAD

**Issue by AbdulDD** [microsoft/unilm#1340]
I am trying to use Layout LMv3 for object detection but following error is occurring.
"ModuleNotFoundError: No module named 'layoutlmft'"

when I try to install layoulmft with "!pip install layoutlmft", another error occurs as following:
"ERROR: Could not find a version that satisfies the requirement layoutlmft (from versions: none)
ERROR: No matching distribution found for layoutlmft"

**Comment by VBPMP** [comment]
Please Assign this issue to me
