### ISSUE TITLE
RetNet applications in LLMs?

### ISSUE THREAD

**Issue by zhoumengbo** [microsoft/unilm#1353]
I would like to know some applications and use cases of RetNet in LLMs, as it's currently difficult to find models and code that use RetNet for pretraining from scratch on the internet. Almost none of the models on Hugging Face clarify the use of RetNet.

**Comment by donglixp** [comment]
@zhoumengbo    We have been actively working on scaling up the architecture recently. As you know, most people are still trying to catch up with GPTs regarding model performance, whose bottleneck has not been the deployment cost. Stay tuned to more released models with large-scale training.
