### ISSUE TITLE
Please help. How to pre-train BEiT-Tiny or Small model on ImageNet-1k?

### ISSUE THREAD

**Issue by lianzheng-research** [microsoft/unilm#1356]
**Describe**
Model I am using BEiT / BEiT v2.
Thank you for your exellent work!
I need some help. How can I pre-train BEiT-Tiny or Small model on ImageNet-1k or 22k?
Thank you very much!

**Comment by pengzhiliang** [comment]
Hi, @lianzheng-research . Thanks for your attention.

For the ViT-Tiny or Small in BEiT-2, you need to change the architecture params in [here (pretraining model defination)](https://github.com/microsoft/unilm/blob/7ae2ee53bf7fff85e730c72083b7e999b0b9ba44/beit2/modeling_pretrain.py#L359) and [here  (finetuning model defination)](https://github.com/microsoft/unilm/blob/7ae2ee53bf7fff85e730c72083b7e999b0b9ba44/beit2/modeling_finetune.py#L474). Refer to [deit](https://github.com/facebookresearch/deit/blob/263a3fcafc2bf17885a4af62e6030552f346dc71/models.py#L64) for specific params.

**Comment by lianzheng-research** [comment]
Thanks for your help. I'll try it this week!

**Comment by lianzheng-research** [comment]
Thanks for you help and I have began the beitv2_tiny_patch16_224 model pre-training. But I find a Warning in the prints:

Epoch: [5]  [1650/2502]  eta: 0:08:27  lr: 0.000849  min_lr: 0.000849  mlm_acc_1: 0.0260 (0.0265)  mlm_acc_2: 0.0271 (0.0271)  loss_1: 6.9748 (7.0080)  loss_2: 6.9690 (6.9856)  loss: 13.9394 (13.9936)  loss_scale: 131072.0000 (68354.3259)  weight_decay: 0.0500 (0.0500)  grad_norm: 2.2521 (2.3745)  time: 0.6580  data: 0.0004  max mem: 7274
Warning: NaN or Inf found in input tensor.
Epoch: [5]  [1660/2502]  eta: 0:08:21  lr: 0.000850  min_lr: 0.000850  mlm_acc_1: 0.0279 (0.0265)  mlm_acc_2: 0.0284 (0.0271)  loss_1: 6.9524 (7.0076)  loss_2: 6.9326 (6.9851)  loss: 13.8876 (13.9927)  loss_scale: 131072.0000 (68692.4600)  weight_decay: 0.0500 (0.0500)  grad_norm: 2.2603 (inf)  time: 0.6585  data: 0.0004  max mem: 7274

"Warning: NaN or Inf found in input tensor."
Is this warning normal or not? Thank you again!

**Comment by pengzhiliang** [comment]
Take it easy! It's just a warning.

**Comment by lianzheng-research** [comment]
haha. Thanks a lot.

**Comment by papersuper** [comment]
could  you please  provide the version of the environment installation package? I got an error when I ran it, would like to refer to yours

**Comment by lianzheng-research** [comment]
I'm sorry to interupt you again. I have already pretrained BEiTv2-Tiny-patch16-224 model on ImageNet-1k after modifying modeling_pretrain.py and modeling_finetune.py.

modeling_pretrain.py

`
@register_model
def beitv2_tiny_patch16_224_8k_vocab_cls_pt(pretrained=False, **kwargs):
    if "num_classes" in kwargs:
        _ = kwargs.pop("num_classes")
    if "vocab_size" in kwargs:
        vocab_size = kwargs["vocab_size"]
        _ = kwargs.pop("vocab_size")
    else:
        vocab_size = 8192
    model = VisionTransformerForMaskedImageModelingCLS(
        patch_size=16, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4, qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6), vocab_size=vocab_size, **kwargs
    )
    model.default_cfg = _cfg()
    if pretrained:
        checkpoint = torch.load(
            kwargs["init_ckpt"], map_location="cpu"
        )
        model.load_state_dict(checkpoint["model"])
    return model

@register_model
def beitv2_tiny_patch16_224_8k_vocab(pretrained=False, **kwargs):
    if "num_classes" in kwargs:
        _ = kwargs.pop("num_classes")
    if 'vocab_size' in kwargs:
        vocab_size = kwargs['vocab_size']
        _ = kwargs.pop("vocab_size")
    else:
        vocab_size = 8192
    model = VisionTransformerForMaskedImageModeling(
        patch_size=16, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4, qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6), vocab_size=vocab_size, **kwargs
    )
    model.default_cfg = _cfg()
    if pretrained:
        checkpoint = torch.load(
            kwargs["init_ckpt"], map_location="cpu"
        )
        model.load_state_dict(checkpoint["model"])
    return model
`

modeling_finetune.py

`
@register_model
def beitv2_tiny_patch16_224(pretrained=False, **kwargs):
    model = VisionTransformer(
        patch_size=16, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4, # qkv_bias=True,
        norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
    model.default_cfg = _cfg()
    return model
`

I pretrained the model with command:

CUDA_VISIBLE_DEVICES=0,2,4,6 python -m torch.distributed.launch --nproc_per_node=4 run_beitv2_pretraining.py --data_set image_folder --data_path ./imagenet/train --output_dir ./outputs/beitv2_tiny_patch16_224/ --log_dir ./logs/beitv2_tiny_patch16_224/ --model beitv2_tiny_patch16_224_8k_vocab_cls_pt --shared_lm_head True --early_layers 9 --head_layers 2 --num_mask_patches 75 --second_input_size 224 --second_interpolation bicubic --min_crop_scale 0.2 --tokenizer_model vqkd_encoder_base_decoder_3x768x12_clip --tokenizer_weight ./beit_datasets/beit2/vqkd_encoder_base_decoder_3x768x12_clip-d5036aa7.pth --batch_size 128 --lr 1.5e-3 --warmup_epochs 10 --clip_grad 3.0 --drop_path 0.1 --layer_scale_init_value 0.1 --imagenet_default_mean_and_std --opt_betas 0.9 0.999 --opt_eps 1e-8 --epochs 300 --save_ckpt_freq 20

I pretrained BEiTv2-Tiny-patch16-224 for 300 epochs, and I got low mlm_acc when pretraining:

Epoch: [299]  [2501/2502]  eta: 0:00:00  lr: 0.000010  min_lr: 0.000010  mlm_acc_1: 0.0826 (0.0843)  mlm_acc_2: 0.0839 (0.0849)  loss_1: 5.5858 (5.5901)  loss_2: 5.5868 (5.5761)  loss: 11.1726 (11.1662)  loss_scale: 4096.0000 (4168.0320)  weight_decay: 0.0500 (0.0500)  grad_norm: 4.3930 (inf)  time: 0.5108  data: 0.0013  max mem: 7274

Now I begin to finetune this model on ImageNet-1k with classification task with command:

CUDA_VISIBLE_DEVICES=0,2,4,6 python -m torch.distributed.launch --nproc_per_node=4 run_class_finetuning.py --data_path ./imagenet/train --eval_data_path ./imagenet/val --nb_classes 1000 --data_set image_folder --output_dir ./outputs/beitv2_tiny_patch16_224_ft1k/ --log_dir ./logs/beitv2_tiny_patch16_224_ft1k/ --model beitv2_tiny_patch16_224 --weight_decay 0.05 --finetune outputs/beitv2_tiny_patch16_224/checkpoint-299.pth --batch_size 128 --lr 5e-5 --update_freq 1 --warmup_epochs 20 --epochs 50 --layer_decay 0.75 --drop_path 0.1 --mixup 0. --cutmix 0. --imagenet_default_mean_and_std --dist_eval --save_ckpt_freq 10 --enable_deepspeed

And I got pretty low accuracy in the first testing epoch:

`
Epoch: [0] Total time: 0:10:08 (0.2433 s / it)
Averaged stats: lr: 0.000002  min_lr: 0.000000  loss: 6.8203 (6.8854)  class_acc: 0.0000 (0.0101)  loss_scale: 32768.0000 (21170.8521)  weight_decay: 0.0500 (0.0500)
[2023-11-11 15:23:31,842] [INFO] [logging.py:60:log_dist] [Rank 0] Saving model checkpoint: ./outputs/beitv2_tiny_patch16_224_ft1k/checkpoint-0/mp_rank_00_model_states.pt
Test:  [ 0/66]  eta: 0:20:04  loss: 6.8132 (6.8132)  acc1: 2.0833 (2.0833)  acc5: 3.6458 (3.6458)  time: 18.2471  data: 17.9492  max mem: 2874
Test:  [10/66]  eta: 0:02:02  loss: 6.7919 (6.7900)  acc1: 0.0000 (0.9943)  acc5: 1.0417 (3.7405)  time: 2.1787  data: 2.0779  max mem: 2874
Test:  [20/66]  eta: 0:01:04  loss: 6.7919 (6.7933)  acc1: 0.0000 (0.5456)  acc5: 0.5208 (2.4802)  time: 0.5659  data: 0.4902  max mem: 2874
Test:  [30/66]  eta: 0:00:40  loss: 6.7994 (6.7918)  acc1: 0.0000 (0.3864)  acc5: 0.5208 (2.7722)  time: 0.5311  data: 0.4559  max mem: 2874
Test:  [40/66]  eta: 0:00:24  loss: 6.7905 (6.7914)  acc1: 0.0000 (0.3557)  acc5: 1.0417 (2.8328)  time: 0.4851  data: 0.4071  max mem: 2874
Test:  [50/66]  eta: 0:00:13  loss: 6.7909 (6.7925)  acc1: 0.0000 (0.4698)  acc5: 1.0417 (2.7880)  time: 0.4815  data: 0.4036  max mem: 2874
Test:  [60/66]  eta: 0:00:04  loss: 6.7978 (6.7939)  acc1: 0.0000 (0.4355)  acc5: 0.5208 (2.6212)  time: 0.4606  data: 0.3806  max mem: 2874
Test:  [65/66]  eta: 0:00:00  loss: 6.7978 (6.7940)  acc1: 0.0000 (0.5600)  acc5: 2.6042 (3.0960)  time: 0.4629  data: 0.3863  max mem: 2874
Test: Total time: 0:00:49 (0.7479 s / it)
* Acc@1 0.580 Acc@5 3.014 loss 6.794
Accuracy of the network on the 50000 test images: 0.6%
[2023-11-11 15:24:22,238] [INFO] [logging.py:60:log_dist] [Rank 0] Saving model checkpoint: ./outputs/beitv2_tiny_patch16_224_ft1k/checkpoint-best/mp_rank_00_model_states.pt
Max accuracy: 0.58%
`

I think there must be some problems in my training stages. Could you give me some advices? Thanks for your help.

**Comment by lianzheng-research** [comment]
> could you please provide the version of the environment installation package? I got an error when I ran it, would like to refer to yours

Hi!

```
Ubuntu 20.04.6 LTS
# pip list
Package                    Version
-------------------------- -----------
addict                     2.4.0
aiofiles                   23.1.0
aiohttp                    3.8.4
aiosignal                  1.3.1
altair                     4.2.2
aniso8601                  9.0.1
anyio                      3.6.2
asttokens                  2.0.5
astunparse                 1.6.3
async-timeout              4.0.2
attrs                      22.1.0
backcall                   0.2.0
beautifulsoup4             4.11.1
blobfile                   2.1.1
brotlipy                   0.7.0
cachetools                 5.3.0
certifi                    2022.9.24
cffi                       1.15.0
chardet                    4.0.0
charset-normalizer         2.0.4
click                      8.1.3
cmake                      3.26.1
colorama                   0.4.6
coloredlogs                15.0.1
comm                       0.1.3
conda                      22.9.0
conda-build                3.22.0
conda-content-trust        0+unknown
conda-package-handling     1.8.1
contourpy                  1.0.7
coverage                   7.2.2
cryptography               36.0.0
cssselect                  1.2.0
cycler                     0.11.0
dateutils                  0.6.12
debugpy                    1.6.6
decorator                  5.1.1
deepspeed                  0.4.0
diffusers                  0.14.0
dnspython                  2.3.0
docker                     6.0.1
duckduckgo-search          2.8.5
einops                     0.7.0
entrypoints                0.4
exceptiongroup             1.0.0
executing                  0.8.3
expecttest                 0.1.4
fastapi                    0.95.0
ffmpeg-python              0.2.0
ffmpy                      0.3.0
filelock                   3.6.0
flake8                     6.0.0
Flask                      2.1.3
flask-restx                1.0.6
flatbuffers                23.3.3
fonttools                  4.39.2
frozenlist                 1.3.3
fsspec                     2023.3.0
ftfy                       6.1.1
future                     0.18.2
glob2                      0.7
google-api-core            2.11.0
google-api-python-client   2.83.0
google-auth                2.17.3
google-auth-httplib2       0.1.0
googleapis-common-protos   1.59.0
gradio                     3.24.1
gradio_client              0.0.5
greenlet                   2.0.2
gTTS                       2.3.1
h11                        0.14.0
httpcore                   0.16.3
httplib2                   0.22.0
httpx                      0.23.3
huggingface-hub            0.13.3
humanfriendly              10.0
hypothesis                 6.56.4
idna                       3.3
importlib-metadata         6.1.0
importlib-resources        5.12.0
iniconfig                  2.0.0
inireader                  0.2.0
install                    1.3.5
ipykernel                  6.22.0
ipython                    8.4.0
itsdangerous               2.1.2
jedi                       0.18.1
Jinja2                     3.1.2
jsonschema                 4.17.3
jupyter_client             8.1.0
jupyter_core               5.3.0
kiwisolver                 1.4.4
libarchive-c               2.9
linkify-it-py              2.0.0
lit                        16.0.0
llvmlite                   0.39.1
loguru                     0.6.0
lxml                       4.9.2
markdown-it-py             2.2.0
MarkupSafe                 2.1.2
matplotlib                 3.2.1
matplotlib-inline          0.1.6
mccabe                     0.7.0
mdit-py-plugins            0.3.3
mdurl                      0.1.2
mkl-fft                    1.3.1
mkl-random                 1.2.2
mkl-service                2.4.0
mock                       5.0.1
more-itertools             9.1.0
mpmath                     1.2.1
multidict                  6.0.4
mypy                       1.6.1
mypy-extensions            1.0.0
nest-asyncio               1.5.6
ninja                      1.11.1.1
numba                      0.56.4
numpy                      1.22.3
onnx                       1.13.1
onnxruntime                1.14.1
openai                     0.27.2
opencv-python              4.7.0.72
orjson                     3.8.9
packaging                  23.0
pandas                     1.4.4
parso                      0.8.3
pexpect                    4.8.0
pickleshare                0.7.5
Pillow                     9.0.1
pinecone-client            2.2.1
pip                        23.3.1
pkginfo                    1.8.3
platformdirs               3.2.0
playsound                  1.2.2
pluggy                     1.3.0
prompt-toolkit             3.0.20
protobuf                   3.20.3
psutil                     5.8.0
psyl                       0.8.0
ptyprocess                 0.7.0
pure-eval                  0.2.2
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pycocotools                2.0.6
pycodestyle                2.10.0
pycosat                    0.6.3
pycparser                  2.21
pycryptodomex              3.19.0
pydantic                   1.10.7
pydub                      0.25.1
pyflakes                   3.0.1
Pygments                   2.11.2
pyOpenSSL                  22.0.0
pyparsing                  3.0.9
pyrsistent                 0.19.3
PySocks                    1.7.1
pytest                     7.4.3
python-dateutil            2.8.2
python-dotenv              1.0.0
python-multipart           0.0.6
pytz                       2022.1
PyYAML                     6.0
pyzmq                      25.0.2
readability-lxml           0.8.1
redis                      4.5.4
regex                      2023.3.23
requests                   2.28.2
rfc3986                    1.5.0
rsa                        4.9
ruamel-yaml-conda          0.15.100
scipy                      1.11.3
semantic-version           2.10.0
setuptools                 61.2.0
setuptools-scm-git-archive 1.4
six                        1.16.0
sniffio                    1.3.0
sortedcontainers           2.4.0
soupsieve                  2.3.2.post1
SQLAlchemy                 1.4.47
sqlhelp                    0.2.0
stack-data                 0.2.0
starlette                  0.26.1
supervision                0.3.2
supervisor                 4.2.5
sympy                      1.11.1
tensorboardX               1.8
tiktoken                   0.3.1
timm                       0.4.12
tokenizers                 0.13.2
toml                       0.10.2
tomli                      2.0.1
toolz                      0.11.2
torch                      1.7.1+cu110
torchtext                  0.14.0
torchvision                0.8.2+cu110
tornado                    6.2
tqdm                       4.65.0
traitlets                  5.9.0
transformers               4.27.4
triton                     2.0.0
tshistory                  0.18.0
tshistory-supervision      0.11.0
types-dataclasses          0.6.6
typing_extensions          4.3.0
uc-micro-py                1.0.1
ujson                      5.7.0
uritemplate                4.1.1
urllib3                    1.26.8
uvicorn                    0.21.1
wcwidth                    0.2.5
websocket-client           1.5.1
websockets                 10.4
Werkzeug                   2.2.3
wheel                      0.37.1
yapf                       0.32.0
yarl                       1.8.2
zipp                       3.15.0
```

**Comment by lianzheng-research** [comment]
> could you please provide the version of the environment installation package? I got an error when I ran it, would like to refer to yours

Could you provide your error details?
I create the environment following [BEiT](https://github.com/microsoft/unilm/tree/master/beit)

**Comment by lianzheng-research** [comment]
> I'm sorry to interupt you again. I have already pretrained BEiTv2-Tiny-patch16-224 model on ImageNet-1k after modifying modeling_pretrain.py and modeling_finetune.py.
> 
> modeling_pretrain.py
> 
> ```
> @register_model
> def beitv2_tiny_patch16_224_8k_vocab_cls_pt(pretrained=False, **kwargs):
>     if "num_classes" in kwargs:
>         _ = kwargs.pop("num_classes")
>     if "vocab_size" in kwargs:
>         vocab_size = kwargs["vocab_size"]
>         _ = kwargs.pop("vocab_size")
>     else:
>         vocab_size = 8192
>     model = VisionTransformerForMaskedImageModelingCLS(
>         patch_size=16, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4, qkv_bias=True,
>         norm_layer=partial(nn.LayerNorm, eps=1e-6), vocab_size=vocab_size, **kwargs
>     )
>     model.default_cfg = _cfg()
>     if pretrained:
>         checkpoint = torch.load(
>             kwargs["init_ckpt"], map_location="cpu"
>         )
>         model.load_state_dict(checkpoint["model"])
>     return model
> 
> @register_model
> def beitv2_tiny_patch16_224_8k_vocab(pretrained=False, **kwargs):
>     if "num_classes" in kwargs:
>         _ = kwargs.pop("num_classes")
>     if 'vocab_size' in kwargs:
>         vocab_size = kwargs['vocab_size']
>         _ = kwargs.pop("vocab_size")
>     else:
>         vocab_size = 8192
>     model = VisionTransformerForMaskedImageModeling(
>         patch_size=16, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4, qkv_bias=True,
>         norm_layer=partial(nn.LayerNorm, eps=1e-6), vocab_size=vocab_size, **kwargs
>     )
>     model.default_cfg = _cfg()
>     if pretrained:
>         checkpoint = torch.load(
>             kwargs["init_ckpt"], map_location="cpu"
>         )
>         model.load_state_dict(checkpoint["model"])
>     return model
> ```
> 
> modeling_finetune.py
> 
> ```
> @register_model
> def beitv2_tiny_patch16_224(pretrained=False, **kwargs):
>     model = VisionTransformer(
>         patch_size=16, embed_dim=192, depth=12, num_heads=3, mlp_ratio=4, # qkv_bias=True,
>         norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)
>     model.default_cfg = _cfg()
>     return model
> ```
> 
> I pretrained the model with command:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,2,4,6 python -m torch.distributed.launch --nproc_per_node=4 run_beitv2_pretraining.py --data_set image_folder --data_path ./imagenet/train --output_dir ./outputs/beitv2_tiny_patch16_224/ --log_dir ./logs/beitv2_tiny_patch16_224/ --model beitv2_tiny_patch16_224_8k_vocab_cls_pt --shared_lm_head True --early_layers 9 --head_layers 2 --num_mask_patches 75 --second_input_size 224 --second_interpolation bicubic --min_crop_scale 0.2 --tokenizer_model vqkd_encoder_base_decoder_3x768x12_clip --tokenizer_weight ./beit_datasets/beit2/vqkd_encoder_base_decoder_3x768x12_clip-d5036aa7.pth --batch_size 128 --lr 1.5e-3 --warmup_epochs 10 --clip_grad 3.0 --drop_path 0.1 --layer_scale_init_value 0.1 --imagenet_default_mean_and_std --opt_betas 0.9 0.999 --opt_eps 1e-8 --epochs 300 --save_ckpt_freq 20
> ```
> 
> I pretrained BEiTv2-Tiny-patch16-224 for 300 epochs, and I got low mlm_acc when pretraining:
> 
> ```
> Epoch: [299]  [2501/2502]  eta: 0:00:00  lr: 0.000010  min_lr: 0.000010  mlm_acc_1: 0.0826 (0.0843)  mlm_acc_2: 0.0839 (0.0849)  loss_1: 5.5858 (5.5901)  loss_2: 5.5868 (5.5761)  loss: 11.1726 (11.1662)  loss_scale: 4096.0000 (4168.0320)  weight_decay: 0.0500 (0.0500)  grad_norm: 4.3930 (inf)  time: 0.5108  data: 0.0013  max mem: 7274
> ```
> 
> Now I begin to finetune this model on ImageNet-1k with classification task with command:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,2,4,6 python -m torch.distributed.launch --nproc_per_node=4 run_class_finetuning.py --data_path ./imagenet/train --eval_data_path ./imagenet/val --nb_classes 1000 --data_set image_folder --output_dir ./outputs/beitv2_tiny_patch16_224_ft1k/ --log_dir ./logs/beitv2_tiny_patch16_224_ft1k/ --model beitv2_tiny_patch16_224 --weight_decay 0.05 --finetune outputs/beitv2_tiny_patch16_224/checkpoint-299.pth --batch_size 128 --lr 5e-5 --update_freq 1 --warmup_epochs 20 --epochs 50 --layer_decay 0.75 --drop_path 0.1 --mixup 0. --cutmix 0. --imagenet_default_mean_and_std --dist_eval --save_ckpt_freq 10 --enable_deepspeed
> ```
> 
> And I got pretty low accuracy in the first testing epoch:
> 
> ```
> Epoch: [0] Total time: 0:10:08 (0.2433 s / it)
> Averaged stats: lr: 0.000002  min_lr: 0.000000  loss: 6.8203 (6.8854)  class_acc: 0.0000 (0.0101)  loss_scale: 32768.0000 (21170.8521)  weight_decay: 0.0500 (0.0500)
> [2023-11-11 15:23:31,842] [INFO] [logging.py:60:log_dist] [Rank 0] Saving model checkpoint: ./outputs/beitv2_tiny_patch16_224_ft1k/checkpoint-0/mp_rank_00_model_states.pt
> Test:  [ 0/66]  eta: 0:20:04  loss: 6.8132 (6.8132)  acc1: 2.0833 (2.0833)  acc5: 3.6458 (3.6458)  time: 18.2471  data: 17.9492  max mem: 2874
> Test:  [10/66]  eta: 0:02:02  loss: 6.7919 (6.7900)  acc1: 0.0000 (0.9943)  acc5: 1.0417 (3.7405)  time: 2.1787  data: 2.0779  max mem: 2874
> Test:  [20/66]  eta: 0:01:04  loss: 6.7919 (6.7933)  acc1: 0.0000 (0.5456)  acc5: 0.5208 (2.4802)  time: 0.5659  data: 0.4902  max mem: 2874
> Test:  [30/66]  eta: 0:00:40  loss: 6.7994 (6.7918)  acc1: 0.0000 (0.3864)  acc5: 0.5208 (2.7722)  time: 0.5311  data: 0.4559  max mem: 2874
> Test:  [40/66]  eta: 0:00:24  loss: 6.7905 (6.7914)  acc1: 0.0000 (0.3557)  acc5: 1.0417 (2.8328)  time: 0.4851  data: 0.4071  max mem: 2874
> Test:  [50/66]  eta: 0:00:13  loss: 6.7909 (6.7925)  acc1: 0.0000 (0.4698)  acc5: 1.0417 (2.7880)  time: 0.4815  data: 0.4036  max mem: 2874
> Test:  [60/66]  eta: 0:00:04  loss: 6.7978 (6.7939)  acc1: 0.0000 (0.4355)  acc5: 0.5208 (2.6212)  time: 0.4606  data: 0.3806  max mem: 2874
> Test:  [65/66]  eta: 0:00:00  loss: 6.7978 (6.7940)  acc1: 0.0000 (0.5600)  acc5: 2.6042 (3.0960)  time: 0.4629  data: 0.3863  max mem: 2874
> Test: Total time: 0:00:49 (0.7479 s / it)
> * Acc@1 0.580 Acc@5 3.014 loss 6.794
> Accuracy of the network on the 50000 test images: 0.6%
> [2023-11-11 15:24:22,238] [INFO] [logging.py:60:log_dist] [Rank 0] Saving model checkpoint: ./outputs/beitv2_tiny_patch16_224_ft1k/checkpoint-best/mp_rank_00_model_states.pt
> Max accuracy: 0.58%
> ```
> 
> I think there must be some problems in my training stages. Could you give me some advices? Thanks for your help.

I got "* Acc@1 71.804 Acc@5 91.412 loss 1.174". No problem here!

**Comment by papersuper** [comment]
Thank you very much for your response. I've encountered this issue during runtime. Could you please help me with it?


[2023-11-13 10:30:13,615] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed info: version=0.4.0, git-hash=unknown, git-branch=unknown
[2023-11-13 10:30:13,628] [INFO] [utils.py:11:_initialize_parameter_parallel_groups] data_parallel_size: 2, parameter_parallel_size: 2
[2023-11-13 10:30:13,628] [INFO] [utils.py:11:_initialize_parameter_parallel_groups] data_parallel_size: 2, parameter_parallel_size: 2
[2023-11-13 10:30:13,682] [INFO] [engine.py:172:__init__] DeepSpeed Flops Profiler Enabled: False
Traceback (most recent call last):
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 448, in <module>
    main(opts, ds_init)
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 317, in main
    model, optimizer, _, _ = ds_init(
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/__init__.py", line 126, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 187, in __init__
Traceback (most recent call last):
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 448, in <module>
    main(opts, ds_init)
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 317, in main
    model, optimizer, _, _ = ds_init(
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/__init__.py", line 126, in initialize
        engine = DeepSpeedEngine(args=args,self._configure_optimizer(optimizer, model_parameters)

  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 689, in _configure_optimizer
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 187, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 689, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 763, in _configure_basic_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 763, in _configure_basic_optimizer
    optimizer = FusedAdam(model_parameters,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 72, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 233, in load
    optimizer = FusedAdam(model_parameters,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 72, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 233, in load
    return self.jit_load(verbose)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 248, in jit_load
    assert_no_cuda_mismatch()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 77, in assert_no_cuda_mismatch
    return self.jit_load(verbose)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 248, in jit_load
    raise Exception(
Exception: Installed CUDA version 11.6 does not match the version torch was compiled with 11.3, unable to compile cuda/cpp extensions without a matching cuda version.
    assert_no_cuda_mismatch()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 77, in assert_no_cuda_mismatch
    raise Exception(
Exception: Installed CUDA version 11.6 does not match the version torch was compiled with 11.3, unable to compile cuda/cpp extensions without a matching cuda version.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 42763) of binary: /storeData/USER/software/mq/anaconda3/envs/beit/bin/python
Traceback (most recent call last):
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_beit3_finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-13_10:30:19
  host      : gpu01
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 42764)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-13_10:30:19
  host      : gpu01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 42763)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================




environment：
cuda11.3，Driver version：11.6
torch：1.10.1
