### ISSUE TITLE
kosmos-2 has a low performance on local gradio app demo

### ISSUE THREAD

**Issue by LizzzMax** [microsoft/unilm#1357]
I tried to run run_gradio.sh on local server, but the performance seemed not good. 
Here is an example of my reproduction:
![image](https://github.com/microsoft/unilm/assets/25973094/3fd4ed03-91e7-4965-b664-a523f7982180)
![image](https://github.com/microsoft/unilm/assets/25973094/33b13251-83d4-44b3-bfc0-c1130be54bd8)
![image](https://github.com/microsoft/unilm/assets/25973094/b4ddcf3f-ba5b-4ba8-95eb-9249f144c2b0)

My configs are as follows:
model: 
kosmos-2.pt, downloaded from the checkpoint link

run_gradio.sh: 
(I use torchrun cause my torch version is 2.1.0+cu118)
model_path=/PATH/to/kosmos-2.pt
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 torchrun --master_port=$master_port  --nproc_per_node=1 demo/gradio_app.py None \
    --task generation_obj \
    --path $model_path \
    --model-overrides "{'visual_pretrained': '',
            'dict_path':'data/dict.txt'}" \
    --dict-path 'data/dict.txt' \
    --required-batch-size-multiple 1 \
    --remove-bpe=sentencepiece \
    --max-len-b 500 \
    --add-bos-token \
    --beam 1 \
    --buffer-size 1 \
    --image-feature-length 64 \
    --locate-special-token 1 \
    --batch-size 1 \
    --nbest 1 \
    --no-repeat-ngram-size 3 \
    --location-bin-size 32

Env:
I did not use the docker image provided in the setup, part of my env is as follows:
python 3.8
cuda:11.8
torch:2.1.0+cu118
pip install fairseq         instead of pip install fairseq/ 
pip install infinibatch    instead of pip install infinibatch/ 
pip install numpy tiktoken ftfy sentencepiece httpcore gradio spacy thinc pydantic==1.10.11 instead of \
pip install numpy==1.23.0 tiktoken ftfy sentencepiece httpcore==0.17.3 gradio==3.37.0 spacy==3.6.0 thinc==8.1.10 pydantic==1.10.11

**Comment by Dongjie-Cheng** [comment]
Same. And I found that kosmos-2 may have a very poor understanding of colors when I tried to ground an object with color words such as "blue jacket" using "run_example" function in the huggingface demo.
![bad](https://github.com/microsoft/unilm/assets/129379872/c60376f7-c37a-474d-a4a7-3111018a2446)

**Comment by wenhui0924** [comment]
@LizzzMax It seems that the demo is not started correctly. From your pictures, I see a lot of "None", do you know why?
![image](https://github.com/microsoft/unilm/assets/46838421/d770fdd7-4ad9-4242-87c4-3d3dc2588f40)

**Comment by LizzzMax** [comment]
> @LizzzMax It seems that the demo is not started correctly. From your pictures, I see a lot of "None", do you know why? ![image](https://user-images.githubusercontent.com/46838421/281242412-d770fdd7-4ad9-4242-87c4-3d3dc2588f40.png)

Sorry, I dont know why so many 'None's, could u tell me where to debug those 'None's or how to strart demo correctly?

**Comment by LizzzMax** [comment]
> @LizzzMax It seems that the demo is not started correctly. From your pictures, I see a lot of "None", do you know why? ![image](https://user-images.githubusercontent.com/46838421/281242412-d770fdd7-4ad9-4242-87c4-3d3dc2588f40.png)

@wenhui0924  hi, I just found those 'None's were printed because I printed model input var 'img_src_tokens', which I totally forgot
