### ISSUE TITLE
How to preprocess my own dataset?

### ISSUE THREAD

**Issue by KawhiZhao** [microsoft/unilm#136]
How to preprocess my own dataset if I want to use it for finetune and inference

**Comment by andrewcby** [comment]
I used `pytesseract.pytesseract.run_tesseract(imagePathfull, outpath, lang=None, config="hocr", extension='html')` to generate the hOCR embeddings. With Tesseract 4, it's very slow though. Took 22 hours for almost 20k images with Spark.

**Comment by wolfshow** [comment]
@KawhiZhao Yes, please use your own OCR tool to get the text as well as the position informaiton. Then, you may follow the FUNSD case for fine-tuning and inference.
