### ISSUE TITLE
[Kosmos-2] 关于Grounding数据的标注流程的疑问

### ISSUE THREAD

**Issue by Weiyun1025** [microsoft/unilm#1374]
你们在文中提到使用了spaCy抽取caption中的noun phrases，但是我发现对于`In this image, a dog is drinking`这样的句子，spaCy会把`image`这种不指代图中任何物体的名词也抽取出来，请问你们是怎么对noun phrase进行的过滤？

**Comment by pengzhiliang** [comment]
We did not further process the words such as image that you mentioned.

**Comment by Weiyun1025** [comment]
> We did not further process noun phrases such as image that you mentioned.

Thank you for your response!
