### ISSUE TITLE
What is the evaluation method in the paper?

### ISSUE THREAD

**Issue by persistforever** [microsoft/unilm#140]
Hi, thanks.

I find that the evaluation method in the paper and github code is not same.

For the evaluation method in paper, the output of the model is a dict like:
{'company': 'XXX', 'address': 'XXX', ...} and the evaluation (p/r/f1) is based on the exact match of the corresponding values.

However, for the evaluation method in the code, the output of the model is a list of the classification of each character. Thus, the evaluation (p/r/f1) is based on the classification of each character.

So, there are very different. How does the author get the results shown in the paper? Thanks

**Comment by wolfshow** [comment]
@persistforever Our eveluation is based on token-level, not character-level. In addition, different tasks have different evaluation metrics.

**Comment by persistforever** [comment]
Thanks, but, what is the evaluation metrics of the SROIE online judge?

**Comment by wolfshow** [comment]
@persistforever For SROIE task, the evaluation is based on entity-level, which means if and only if the whole entity is recognized correctly.

**Comment by persistforever** [comment]
OK, thanks a lot. 

So, when LayoutLM classifies each text chunk into 5 class. How do you get the final entity-level prediction. Do you group B-X I-X I-X E-X into an enity? 

By the way, I was confused with the 'TOTAL' class, if the value of 'total' is 9.08 and there are many 9.08 in a page. You will classify each 9.08 into the class 'TOTAL'?

**Comment by wolfshow** [comment]
@persistforever Yes, B-I-E tag sequences can be grouped into an entity. We also have post-processing steps for entities like "TOTAL".

**Comment by persistforever** [comment]
Thanks.

So, where is the post-processing step in the repo?

**Comment by YifeiYang210** [comment]
But we meet this situation: there are many S-TOTAL, (848.00 S, S-TOTAL), (48.00, S-TOTAL), (848.00, S-TOTAL). So I have no idea but mistake it as an wrong sample during prediction.

**Comment by wolfshow** [comment]
@persistforever @YifeiYang210, The post-processing part is not related to LayoutLM pre-training and fine-tuning as it depends on downstream tasks. So we will not provide this in the repo.

**Comment by YifeiYang210** [comment]
I think you are right. Thanks

**Comment by persistforever** [comment]
> But we meet this situation: there are many S-TOTAL, (848.00 S, S-TOTAL), (48.00, S-TOTAL), (848.00, S-TOTAL). So I have no idea but mistake it as an wrong sample during prediction.

Yes, I meet the same situation
