### ISSUE TITLE
What is the method about the preprocess of the SROIE data?

### ISSUE THREAD

**Issue by YifeiYang210** [microsoft/unilm#141]
[English]
Thanks a lot for your excellent work,

From your paper, for the receipt understanding tasts, LayoutLM predicts {B,I,S,E,O} tags for each token and use sequential labeling to detect each type of entity in the dataset.
But SROIE task needs sentence-level output for the results.

![image](https://user-images.githubusercontent.com/35833143/82404139-16b43400-9a93-11ea-997e-52303ab26b69.png)
As is shown in the picture, we get No.53 55,57 & 59, JALAN SAGU 18, for the input and the model labels B-address later.  We get TAMAN DAYA and the result is I-address. Also for 81100 JOHOR BAHRU as I-address, for JOHOR as E-address.

But  those  two I-address label tokens can not be decided the output sequence order by the model instead of the input order.

So I am curious about how the model outputs samples in the correct order. 

[Chinese]
按论文来看，LayoutLM模型对于关键信息提取任务输出的标签是词粒度的BIOSE标签。
 但SROIE要的是句粒度的输出结果。比如说票据上一个一个样本框依次是：门牌号，街道号，地区号，省市号。模型标注了门牌号是B-address,省市号是E-address，街道号和地区号是I-address

但这样组合无法输出句粒度的结果，因为I-address的标签没有规定街道号还是地区号放在前面。因此比较好奇模型是如何输出正确顺序的样本的，是否需要依赖于一步的对输入样本顺序的预处理。

谢谢

**Comment by wolfshow** [comment]
@YifeiYang210 yes, we further pre-processed the labeled data into token-level.

**Comment by YifeiYang210** [comment]
Thank you for your example code. I write the SROIE preprocess script successfully. But I found some OCR error in the dataset. So there are also some flaws and a problem of data. 

I will close the issue. Thank you for your answer
