### ISSUE TITLE
[TrOCR] Dealing with occasional multi-line images

### ISSUE THREAD

**Issue by aureliusnoble** [microsoft/unilm#1419]
Hi, I am using TrOCR to transcribe historical (18th century) handwritten French data.

I am feeding in text-line images which are segmented using doc-ufcn. However, due to the nature of the documents, sometimes this segmentation is not perfect, and the image contains multiple lines of text. These have been transcribed with the \n token. 

I know that ideally I would not pass in multi-line images, however these will be occasionally present in the data I want to run inference on. What are your thoughts on dealing with these when fine-tuning TrOCR? About 5-10% of lines include a "\n" character. It is currently not feasible to reduce this, though in future iterations I hope to reduce this issue.

I'm currently following Parres and Paredes (2023) in fine-tuning trocr-large-handwritten, but adding some custom tokens for accented characters. If anyone had any advice this would be much appreciated.

**Comment by MohamedLahmeri01** [comment]
care to share the solution taken ?
