### ISSUE TITLE
SROIE dataset

### ISSUE THREAD

**Issue by zanina14** [microsoft/unilm#143]
can I run your model on original SROIE dataset without modification ?

**Comment by wolfshow** [comment]
@zanina14 I am afraid not because the SROIE dataset does not have token-level annotation. So you may have to pre-process the dataset and get the token-level annoatation.

**Comment by zanina14** [comment]
can you provide further explanation on how to do it ? did you use regex expression to label tokens ?

**Comment by wolfshow** [comment]
@zanina14 SROIE provides the labels for OCR lines, but not tokens. You need to map the given labels to each token in the current dataset, so that the LayoutLM can be applied

**Comment by zanina14** [comment]
which type of labels did you use ?

**Comment by wolfshow** [comment]
@zanina14 We pre-process the dataset and use token-level annotations
