### ISSUE TITLE
some question about beit3 usage, help please

### ISSUE THREAD

**Issue by WalkerGoXQ** [microsoft/unilm#1434]
**Describe**
Model I am using BEIT3:
thanks for the great work, but some questions about it:

1.i tried to load .zip file directly, it works, and also i tried to change the file name from .zip to .pth and load it, it works too, i dont know which is better?
2.if i want to use model beit3_base_itc_patch16_224.zip to generate image or text features with lower dimension such as 256-d out(768-d original), can i add TwoLayerMLP directly as project layer, with no need to change others like loss?

**Comment by WalkerGoXQ** [comment]
.zip  file i mean is the model downlaoded from supported download link.  except for using wget to download, is there other way to download the  .pth model file directly?thanks

**Comment by wenhui0924** [comment]
Hi @WalkerGoXQ 

1) Please refer to the [download commond](https://github.com/microsoft/unilm/tree/master/kosmos-2#setup) to download the checkpoint.
2) Yes, you can add MLP as a projection layer. However, since the newly added MLP projection layer is initiated randomly, you need to train them.

**Comment by WalkerGoXQ** [comment]
> Hi @WalkerGoXQ
> 
> 1. Please refer to the [download commond](https://github.com/microsoft/unilm/tree/master/kosmos-2#checkpoints) to download the checkpoint.
> 2. Yes, you can add MLP as a projection layer. However, since the newly added MLP projection layer is initiated randomly, you need to train them.

thanks for reply, for querstion 1, shame that i have no envs to use wget to download, is there another ways?

**Comment by wenhui0924** [comment]
Hi, maybe you can also rename the .zip to .pth, but please double check the performance.

**Comment by WalkerGoXQ** [comment]
> Hi, maybe you can also rename the .zip to .pth, but please double check the performance.

ok, thanks again!
