### ISSUE TITLE
miss match hidden_size  assert state_dict[_k].shape[1] % config.hidden_size == 0 

### ISSUE THREAD

**Issue by Aniruddha-JU** [microsoft/unilm#146]

**Comment by Aniruddha-JU** [comment]
Hi i am geeting this error  File "run_seq2seq.py", line 495, in <module>
    main()
  File "run_seq2seq.py", line 348, in main
    args.bert_model,state_dict=model_recover,num_labels=cls_num_labels, num_rel=0, type_vocab_size=type_vocab_size, config_path=args.config_path, task_idx=3, num_sentlvl_labels=num_sentlvl_labels, max_position_embeddings=args.max_position_embeddings, label_smoothing=args.label_smoothing, fp32_embedding=args.fp32_embedding, relax_projection=relax_projection, new_pos_ids=args.new_pos_ids, ffn_type=args.ffn_type, hidden_dropout_prob=args.hidden_dropout_prob, attention_probs_dropout_prob=args.attention_probs_dropout_prob, num_qkv=args.num_qkv, seg_emb=args.seg_emb)
  File "/home/aniruddha/unilm/unilm-v1/src/biunilm/pytorch_pretrained_bert/modeling.py", line 812, in from_pretrained
    assert state_dict[_k].shape[1] % config.hidden_size == 0
AssertionError

**Comment by addf400** [comment]
@Aniruddha-JU Can you privode your running command?

**Comment by Aniruddha-JU** [comment]
thank you for your response


python run_seq2seq.py --do_train --num_workers 0 --bert_model bert-large-cased --new_segment_ids --data_dir /home/aniruddha/bert_eng/qg_data/train --src_file train.pa.tok.txt --tgt_file train.q.tok.txt  --output_dir /home/aniruddha/bert_eng/qg_data/train/bert_save/  --log_dir /home/aniruddha/bert_eng/qg_data/train/log --model_recover_path unilm1-base-cased.bin --max_seq_length 512 --max_position_embeddings 512 --mask_prob 0.7 --max_pred 48  --train_batch_size 32 --gradient_accumulation_steps 2 --learning_rate 0.00002 --warmup_proportion 0.1 --label_smoothing 0.1 --num_train_epochs 10

**Comment by addf400** [comment]
You use "--bert_model bert-large-cased"   "--model_recover_path unilm1-base-cased.bin" seems conflict. You can (1) change to "--bert_model bert-base-cased"  or (2) download unilm-large-cased ckpt.

**Comment by Aniruddha-JU** [comment]
Thank you
