### ISSUE TITLE
Broken link, Can't download the checkpoints associated with the Text Detection task for DiT

### ISSUE THREAD

**Issue by rm-asif-amin** [microsoft/unilm#1466]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): DiT

The problem arises when using:
* [ ] the official example scripts: 
   Can't download the checkpoints associated with the Text Detection task.

When trying to download checkpoints and weights listed under [this section](https://github.com/microsoft/unilm/tree/master/dit/text_detection#fine-tuned-models-on-funsd), Getting the following error-

> <Error>
> <Code>PublicAccessNotPermitted</Code>
> <Message>Public access is not permitted on this storage account. RequestId:0e386ff2-901e-0048-01e2-63f565000000 Time:2024-02-20T09:53:58.1972080Z</Message>
> </Error>

**To Reproduce**
1. Go to this section of the repo - https://github.com/microsoft/unilm/tree/master/dit/text_detection#fine-tuned-models-on-funsd
2.  Click on checkpoint or weight hyperlinks

**Expected behavior**
Download initialization on browser for the corresponding models.

**Comment by decadance-dance** [comment]
+1

**Comment by decadance-dance** [comment]
just add ?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D to the end of the link
