### ISSUE TITLE
[mE5] Finetuning multilingual E5 with Korean datasets

### ISSUE THREAD

**Issue by yjoonjang** [microsoft/unilm#1478]
Hi, @intfloat.
I'm trying to fine tune your me5-base model with my Korean dataset.
I've seen a lot of issues related to 'finetuning mE5' on this repository, however I do not know how to finetune this model.
What part of [simlm](https://github.com/microsoft/unilm/tree/master/simlm) should I look to finetune the me5 model?
Thank you.

**Comment by intfloat** [comment]
Suppose you already have a fine-tuning code base, then you simply need to replace the model initialization with our `multilingual-e5-*` models.

If you do not have such code base yet, please refer to the https://github.com/microsoft/unilm/tree/master/simlm#train-a-biencoder-retriever-with-bm25-hard-negatives part on contrastive training with hard negatives. [Tevatron](https://github.com/texttron/tevatron) is also a good open-source library to start with.

**Comment by yjoonjang** [comment]
Thanks for your help and response. @intfloat 

However, I'm not really sure what to do. My dataset looks like this:
{
"query": "~~",
"document": "~~",
"hard_negative": "~~"
}
I would be happy if there are some codes intuitively related to finetuning the **e5 model**
Would it be useful to reference this code ??: [ClusterLLM_finetune_e5](https://github.com/zhang-yu-wei/ClusterLLM/blob/main/perspective/2_finetune/finetune_e5.py)

Thank you.

**Comment by yjoonjang** [comment]
I think I got how to do this. Thanks for your support.

**Comment by bg51717** [comment]
> I think I got how to do this. Thanks for your support.

I want to know how to do this.I only have query , document and hard_negative.But I don't know how to fine tune the e5 model.Thanks.
