### ISSUE TITLE
Multi-GPU training stuck

### ISSUE THREAD

**Issue by andrewcby** [microsoft/unilm#148]
Hi! 
I ran into an issue with `DataParallel` and `DistributedDataParallel` though. I tried training on a 8 GPU cluster, and it just got stuck after loading data, at this step:

```
05/22/2020 03:35:44 - INFO - __main__ -   Saving features into cached file ../../data/cached_train_layoutLM_128_cdip
05/22/2020 03:35:52 - INFO - __main__ -   ***** Running training *****
05/22/2020 03:35:52 - INFO - __main__ -     Num examples = 14549
05/22/2020 03:35:52 - INFO - __main__ -     Num Epochs = 4
05/22/2020 03:35:52 - INFO - __main__ -     Instantaneous batch size per GPU = 16
05/22/2020 03:35:52 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 128
05/22/2020 03:35:52 - INFO - __main__ -     Gradient Accumulation steps = 1
05/22/2020 03:35:52 - INFO - __main__ -     Total optimization steps = 456

Epoch:   0%|          | 0/4 [00:00<?, ?it/s]
```
I have tried adjusting different models, parameters, etc. and nothing helped. Any idea why this is the case?

**Comment by andrewcby** [comment]
Oops closed by accident when I tried adding a comment. This still is an issue.

**Comment by ranpox** [comment]
Hi @andrewcby  ,
As I just updated the code and examples, please pull the latest code and try again.
Please create a new issue if you still have this issue.
Thanks.
