### ISSUE TITLE
About mini version of UniLM

### ISSUE THREAD

**Issue by ShengGuangzhi** [microsoft/unilm#15]

**Comment by ShengGuangzhi** [comment]
HI~I wanna try to generate text by UniLM  in our business, but hardware is really a problem. Will you release a mini version which is able to lower the requirement of hardware?

**Comment by gitnlp** [comment]
Yes. We are working on it. Stay tuned!

**Comment by donglixp** [comment]
Hi @ShengGuangzhi ,

Please refer to https://github.com/microsoft/unilm/tree/master/s2s-ft for the base-size model. We will also update a mini-size model at https://github.com/microsoft/unilm/tree/master/minilm (paper: https://arxiv.org/pdf/2002.10957.pdf ) .
