### ISSUE TITLE
run_seq_labeling eval fails

### ISSUE THREAD

**Issue by michaelroyzen** [microsoft/unilm#152]
After successfully fine-tuning layoutlm using:

`python run_seq_labeling.py  --data_dir data \
                            --model_type layoutlm \
                            --model_name_or_path models/layoutlm-base-uncased \
                            --do_lower_case \
                            --max_seq_length 512 \
                            --do_train \
                            --num_train_epochs 100.0 \
                            --logging_steps 10 \
                            --save_steps -1 \
                            --output_dir checkpoints \
                            --labels data/labels.txt \
                            --per_gpu_train_batch_size 16 \
                            --fp16`

attempting eval does not work. Running: 

`python run_seq_labeling.py  --do_predict --data_dir data \
                            --model_type layoutlm \
                            --model_name_or_path /home/unilm/layoutlm/checkpoints \
                            --do_lower_case \
                            --output_dir results \
                            --labels data/labels.txt \
                            --fp16`

gives this traceback: `Traceback (most recent call last):
  File "run_seq_labeling.py", line 855, in <module>
    main()
  File "run_seq_labeling.py", line 813, in main
    args.output_dir, do_lower_case=args.do_lower_case
  File "/opt/conda/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 286, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 351, in _from_pretrained
    list(cls.vocab_files_names.values())))
OSError: Model name 'results' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased). We assumed 'results' was a path or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.`

It is odd to me that it is looking for tokenizers in the output_dir argument. Help would be greatly appreciated.

**Comment by michaelroyzen** [comment]
@donglixp

**Comment by michaelroyzen** [comment]
I've been able to fix the issue by commenting out `os.makedirs(args.output_dir)` at line 688.

**Comment by AHardReset** [comment]
Hi! I had the same problem moments ago and I handle it as follows:
In run_seq_labeling.py
In line 812-814

`tokenizer = tokenizer_class.from_pretrained(
            args.output_dir, do_lower_case=args.do_lower_case
        )`

Is searching for the tokenizer in the directory in which we expect to see the predict results.
so i changed the args.output_dir for the correct one:

```
tokenizer = tokenizer_class.from_pretrained(
            args.model_name_or_path, do_lower_case=args.do_lower_case
        )
```

Similar issue in
Line 815

`model = model_class.from_pretrained(args.output_dir)`

Fixed:

model = model_class.from_pretrained(args.model_name_or_path)

No need to comment the line 688, but ensure that output_dir don't exist

out_dir = 'output'
model_path = folder

And all done!
Implementation (Note that was done in Jupyter):

```
!python run_seq_labeling.py  --data_dir data \
                            --model_type layoutlm \
                            --model_name_or_path {model_path} \
                            --do_lower_case \
                            --max_seq_length 512 \
                            --do_train \
                            --num_train_epochs 100.0 \
                            --logging_steps 10 \
                            --save_steps -1 \
                            --output_dir {out_dir} \
                            --labels data/labels.txt \
                            --per_gpu_train_batch_size 16 \
                            --fp16
```

`!python scripts/funsd_preprocess.py  --data_dir data/testing_data/annotations --data_split test`

```
pred_dir = "predictions"

!python run_seq_labeling.py  --do_predict \
                            --data_dir data \
                            --model_type layoutlm \
                            --model_name_or_path {out_dir} \
                            --do_lower_case \
                            --output_dir predictions \
                            --labels data/labels.txt \
                            --fp16
```

**Comment by AHardReset** [comment]
> Hi! I had the same problem moments ago and I handle it as follows:
> In run_seq_labeling.py
> In line 812-814
> 
> `tokenizer = tokenizer_class.from_pretrained( args.output_dir, do_lower_case=args.do_lower_case )`
> 
> Is searching for the tokenizer in the directory in which we expect to see the predict results.
> so i changed the args.output_dir for the correct one:
> 
> ```
> tokenizer = tokenizer_class.from_pretrained(
>             args.model_name_or_path, do_lower_case=args.do_lower_case
>         )
> ```
> 
> Similar issue in
> Line 815
> 
> `model = model_class.from_pretrained(args.output_dir)`
> 
> Fixed:
> 
> model = model_class.from_pretrained(args.model_name_or_path)
> 
> No need to comment the line 688, but ensure that output_dir don't exist
> 
> out_dir = 'output'
> model_path = folder
> 
> And all done!
> Implementation (Note that was done in Jupyter):
> 
> ```
> !python run_seq_labeling.py  --data_dir data \
>                             --model_type layoutlm \
>                             --model_name_or_path {model_path} \
>                             --do_lower_case \
>                             --max_seq_length 512 \
>                             --do_train \
>                             --num_train_epochs 100.0 \
>                             --logging_steps 10 \
>                             --save_steps -1 \
>                             --output_dir {out_dir} \
>                             --labels data/labels.txt \
>                             --per_gpu_train_batch_size 16 \
>                             --fp16
> ```
> 
> `!python scripts/funsd_preprocess.py --data_dir data/testing_data/annotations --data_split test`
> 
> ```
> pred_dir = "predictions"
> 
> !python run_seq_labeling.py  --do_predict \
>                             --data_dir data \
>                             --model_type layoutlm \
>                             --model_name_or_path {out_dir} \
>                             --do_lower_case \
>                             --output_dir predictions \
>                             --labels data/labels.txt \
>                             --fp16
> ```

@ranpox

**Comment by elnazsn1988** [comment]
@AHardReset Hey - I am facing the same issue in the latest repo, did you remove all the output_dir and replace them with args.model_name_or_path ?

**Comment by AHardReset** [comment]
I overwritten args.output_dir in lines 813-815 with args.model_name_or_path

**Comment by AHardReset** [comment]
> @AHardReset @ranpox  Hey - I am facing the same issue in the latest repo, did you remove all the output_dir and replace them with args.model_name_or_path ? 

@elnazsn1988 

I overwritten args.output_dir in lines 813-815 with args.model_name_or_path

**Comment by elnazsn1988** [comment]
@AHardReset ah thanks very much, applied same to new repo and predicts now - will check to make sure I havent messed up the training my mistake.... can I ask, how/if you were able to call --do_predict for any doc image other than FUNSD, and if so, how you over-stepped the eval part? This is assuming that your image unlike FUNSD, doesn't have labels, and therefor not labeled for evaluation.

**Comment by AHardReset** [comment]
@elnazsn1988 I haven't tried yet.

The process is called fine tuning... we need to make a dataset of the documents of interest, labeling and re train with the pre trained model from this repo. Then you can try to predict with unseen data, but that data came from your dataset.

**Comment by elnazsn1988** [comment]
> @elnazsn1988 I haven't tried yet.
> 
> The process is called fine tuning... we need to make a dataset of the documents of interest, labeling and re train with the pre trained model from this repo. Then you can try to predict with unseen data, but that data came from your dataset.

Hi ! so what some members have tried - which I am doing now - is replacing random classes in the input file to be able to bypass eval without having to alter the code for prediction....
