### ISSUE TITLE
Unable to download DiT model weights that were fine-tuned on PubLayNet

### ISSUE THREAD

**Issue by milan-qorvo** [microsoft/unilm#1528]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): DiT

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

Unable to download DiT model weights that were fine-tuned on PubLayNet, even when the query string suggested in #1466 has already been added. Clicking on this link: https://layoutlm.blob.core.windows.net/dit/dit-fts/publaynet_dit-b_cascade.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

Returns the following error: 
```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:61947591-201e-0010-3d45-932d3a000000 Time:2024-04-20T17:07:20.0399935Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was layoutlm r b o 2023-06-08T08:48:15Z 2033-06-08T16:48:15Z https 2022-11-02 </AuthenticationErrorDetail>
</Error>
```

**To Reproduce**
1.  Go to this section of the repo: [https://github.com/microsoft/unilm/tree/master/dit#fine-tuning-on-publaynet-document-layout-analysis](https://github.com/microsoft/unilm/tree/master/dit#fine-tuning-on-publaynet-document-layout-analysis)
2. Click on weight hyperlink.

**Expected behavior**
Model should begin downloading

**Comment by Holmes2002** [comment]
Hi, does anyone solve this problem?

**Comment by sebastianfernandezgarcia** [comment]
### Links have been fixed now!

Thanks for the quick response and action @HYPJUDY 
Thank you very much!

**Comment by johnathanchiu** [comment]
does someone have a way to wget this file?
