### ISSUE TITLE
unable download pre-trained BEiTv1 models (large fine-tuning on 1k Imagnet)

### ISSUE THREAD

**Issue by vietvo89** [microsoft/unilm#1529]
Hi

I cannot download pre-trained BEiTv1 models (large fine-tuning on 1k Imagnet). The link does not work anymore. Can you check?

**Comment by addf400** [comment]
@vietvo89  I have fixed it, it should works.

**Comment by vietvo89** [comment]
awesome! Thank you so much for your quick response.
