### ISSUE TITLE
Inference script for layoutlm

### ISSUE THREAD

**Issue by michaelroyzen** [microsoft/unilm#153]
What would be a fast and efficient way to run inference with layoutlm without also running eval? Ideally, the input to this script would be just the text with its bounding box. Help would be appreciated.

**Comment by michaelroyzen** [comment]
@donglixp

**Comment by ranpox** [comment]
Hi @michaelroyzen ,
If I understand correctly, you can directly use LayoutLM by 
`from layoutlm import LayoutlmForTokenClassification`
As I just updated the code and examples, please pull the latest code and update the dependencies.
Thanks.
