### ISSUE TITLE
This example code fine-tunes 12-layer MiniLM on SQuAD 2.0 dataset doesn't work.

### ISSUE THREAD

**Issue by jinsongpan** [microsoft/unilm#154]
the code:
![image](https://user-images.githubusercontent.com/33392010/83119931-eb6cbd00-a102-11ea-9277-be07fe9b7dc2.png)

The official recommended version is transfors-0.4.0, it's code:
![image](https://user-images.githubusercontent.com/33392010/83119990-fde6f680-a102-11ea-9f68-f883d60c15ed.png)

run_squad.py has different parameters.
Lately I try your code in the latest version of transformers-2.9.1, which has similar parameters:
![image](https://user-images.githubusercontent.com/33392010/83120087-24a52d00-a103-11ea-894f-87e82bb7fcfb.png)

the code still does not work. Why can't this script work, is there any mistake in the code?

**Comment by WenhuiWang0824** [comment]
Hi @jinsongpan 

Could you provide more error information?

Thanks,
Wenhui

**Comment by WenhuiWang0824** [comment]
The problem is because of the latest update of Transformers. Please use the version of 2.5.1 to run the example code.

Thanks
