### ISSUE TITLE
Not able to download the data through the given link as well as the suffix string mentioned in other Issues

### ISSUE THREAD

**Issue by rishabbbps** [microsoft/unilm#1546]
Trying to download the pre-trained model weights at https://layoutlm.blob.core.windows.net/readingbank/model/layoutreader-base-readingbank.zip results in an "PublicAccessNotPermitted" error.

` <Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:9b9c4a91-c01e-0055-4332-a4f8d9000000 Time:2024-05-12T06:06:03.8054052Z</Message>
</Error> ` 

And, I get a different error even when using the suffix string mentioned in https://github.com/microsoft/unilm/issues/1263 and https://github.com/microsoft/unilm/issues/1143 : 

` <Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:a949e78e-301e-008a-0632-a4b3e3000000 Time:2024-05-12T06:09:35.9823836Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was layoutlm r b o 2023-06-08T08:48:15Z 2033-06-08T16:48:15Z https 2022-11-02 </AuthenticationErrorDetail>
</Error> `

**Comment by shoshinL** [comment]
I'm having the same issue and am happy to see wolfshow has been assigned to this.
In the meantime @rishabbbps you might be able to access the weights here https://huggingface.co/nielsr/layoutreader-readingbank

**Comment by HYPJUDY** [comment]
Thanks for reporting this downloading issue. Please find the ReadingBank data and LayoutReader models at [this OneDrive link](https://mail2sysueducn-my.sharepoint.com/:f:/g/personal/huangyp28_mail2_sysu_edu_cn/EmHOkXN76dZMqrdr5pv6G4sBDyS8mvyBD72MUUb9VdkXYw?e=aeb4UR).

**Comment by rishabbbps** [comment]
Thanks a ton for everyone's help!
