### ISSUE TITLE
Is it possible to share the Kosmos-2.5 script that converts inference outputs to output image 

### ISSUE THREAD

**Issue by ydshieh** [microsoft/unilm#1547]
Hi! First, thank you for open sourcing the  `Kosmos-2.5` model.

I have run it and it run smoothly. 

The inference outputs look like

```
{'model': 'kosmos 2.5', 'task': 'ocr', 'width': 772, 'height': 1000, 'results': [{'text': '9', 'bounding box': {'x0': 702, 'y0': 35, 'x1': 708, 'y1': 48}}, {'text': '0', 'bounding box': {'x0': 103, 'y0': 250, 'x1': 107, 'y1': 262}}, {'text': 'π/2', 'bounding box': {'x0': 162, 'y0': 250, 'x1': 176, 'y1': 262}}, 
```
and I couldn't find the script to convert this to the output image like shared in the repository.

Is it possible for the team to share that conversion script? Thank you in advance!

<img src="https://github.com/microsoft/unilm/assets/2521628/aea793ca-5b13-4c00-95a9-72f429e5671e" width="300">

**Comment by Dod-o** [comment]
hi @ydshieh ,  I have uploaded the script we used for drawing bounding boxes, please find it [here](https://github.com/microsoft/unilm/blob/master/kosmos-2.5/draw_bbox.py) : )

**Comment by ydshieh** [comment]
Thank you a lot ^_^ !

**Comment by ydshieh** [comment]
I tried it once on a A10 machine.
