### ISSUE TITLE
Is Kosmos 2.5 better for image captioning than Kosmos 2? and a Gradio app we need

### ISSUE THREAD

**Issue by FurkanGozukara** [microsoft/unilm#1549]
I see only OCR but I want to be sure

Also can you publish a Gradio app for kosmos 2.5?

**Comment by Dod-o** [comment]
Kosmos 2.5 is designed for OCR and Markdown generation tasks. It doesn't have a caption generation feature.

**Comment by FurkanGozukara** [comment]
> Kosmos 2.5 is designed for OCR and Markdown generation tasks. It doesn't have a caption generation feature.

thanks for clarification
