### ISSUE TITLE
What would be the easiest way to extract attention vectors?

### ISSUE THREAD

**Issue by ZacKriegmanTR** [microsoft/unilm#156]
I have UniLM up and running to produce summaries based on input text.

What is the easiest way to extract the attention vectors showing which part of the input text the model was attending to most strongly while producing the summary?

Thanks!

**Comment by donglixp** [comment]
The attention distribution (tensor shape: [batch_size, attention_head, position, position]) of each Transformer block can be obtained at https://github.com/microsoft/unilm/blob/master/s2s-ft/s2s_ft/modeling_decoding.py#L431 .
