### ISSUE TITLE
(BEIT-3)  I can't find transformers.py

### ISSUE THREAD

**Issue by matsutaku44** [microsoft/unilm#1589]
Model I am using (UniLM, MiniLM, LayoutLM ...): BEIT-3

I tried to run this code :

```
from transformers import XLMRobertaTokenizer
tokenizer = XLMRobertaTokenizer("/your_beit3_model_path/beit3.spm")

```

However, I can't find transformers.py at unilm/beit3/

**Comment by donglixp** [comment]
from transformers import XLMRobertaTokenizer
tokenizer = XLMRobertaTokenizer("/your_beit3_model_path/beit3.spm")


The above code is used to load the tokenizer.

**Comment by donglixp** [comment]
The transformers package can be installed following the instruction https://github.com/microsoft/unilm/tree/master/beit3#setup . 

The package dependency is at  https://github.com/microsoft/unilm/blob/master/beit3/requirements.txt#L18 .

**Comment by matsutaku44** [comment]
@donglixp  Thank you very much!
