### ISSUE TITLE
Kosmos-2.5 Dependencies Should Be Updated

### ISSUE THREAD

**Issue by ahindy1234** [microsoft/unilm#1590]
**Describe**
I was able to implement Kosmos-2.5 on my GPU cluster, but had some serious package troubles that were not specified in the `requirements.txt` that I would like to outline for people. 

- If you want to use a real version of the Transformers library (not the custom version made just for this project), you can just port over the Pix2Struct files to your machine and import those instead.
- If you want to use a real version of the Fairseq library, you can just port over the generation.py file and use that as a custom task instead. 
- If you want to use numpy>1.24.0, you can't use the custom version of the Fairseq library, unless you update specific files within the site-packages (namely-change lines 124 and 312 of /site-packages/fairseq/data/indexed_dataset.py to np.float64 instead of np.float)

My suggestions for the authors:
- Update the requirements.txt folder so that people can more easily run Kosmos-2.5. Specify numpy<1.24.0, omegaconf<=2.1.0, torch, boto3.

**Comment by Dod-o** [comment]
Thank you for your suggestion; I will modify the requirements.txt file. Additionally, we plan to release Kosmos-2.5 on Hugging Face (possibly within the next couple of days), which should make it more convenient for the community to use.
