### ISSUE TITLE
[LayoutLM]Code and pre-trained model with image features.

### ISSUE THREAD

**Issue by w-cheng** [microsoft/unilm#163]
Thanks a lot for the great work and releasing pre-trained LayoutLM models! 

After playing with the two pre-trained models, they don't seem to have any image features. Is there a plan to release code and pre-trained models with image features? Thanks.

**Comment by wolfshow** [comment]
@w-cheng Thanks for your interests in LayoutLM! As mentioned in our paper, currently we do not pre-train the LayoutLM model with the image information, but sideload the image features after the pre-training step. So, you may integrate any fast(er) RCNN models and generate the image features that can be fine-tuned together with the LayoutLM.

**Comment by w-cheng** [comment]
@wolfshow Thanks for the answer, that makes a lot of sense.
