### ISSUE TITLE
Sample code to run MultiheadDiffAttn provided

### ISSUE THREAD

**Issue by VenkatSBitra** [microsoft/unilm#1645]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): UniLM DiffTransformer

I am need some sample code to see how to use MultiheadDiffAttn as I am planning to train some models using this model.

**Comment by YTianZHU** [comment]
Hi @VenkatSBitra 
Please refer to https://github.com/microsoft/unilm/blob/master/Diff-Transformer/multihead_flashdiff_1.py for our implementation. You can directly change model code of any LLMs to turn it into DIFF arch. :)
