### ISSUE TITLE
No module named 'triton'

### ISSUE THREAD

**Issue by MahmoudElsayedMahmoud** [microsoft/unilm#1647]
from rotary import apply_rotary_emb   File "D:\dino\rotary.py", line 7, in <module>     import triton ModuleNotFoundError: 
No module named 'triton'
iam using window 
i try to using diff transformer

**Comment by YTianZHU** [comment]
hi @MahmoudElsayedMahmoud 
You can refer to https://github.com/triton-lang/triton to install it
