### ISSUE TITLE
[Differential Transformer] How is it visualized?

### ISSUE THREAD

**Issue by yjoonjang** [microsoft/unilm#1654]
Hello, @YTianZHU . I read the Differential Transformer paper and found it very interesting.
Thank you so much for your work.

I was wondering how you visualized the attention scores in Figure 1:
![Image](https://github.com/user-attachments/assets/acb34f1d-b885-4fc6-a7df-f6ffdfece286)

Since there are a lot of attention scores (e.g. by layers, heads... etc) in transformer-based models, on whick layer and heads based score did you use?
Or is it the averaged score you used? 

Also, What was the dataset used in the visualized experiment?

Thank you.

**Comment by YTianZHU** [comment]
Hi @yjoonjang, the attention scores presented in Table 3 in paper is calculated as in the figure I attach. The same is applied to Figure 1 you paste.

![Image](https://github.com/user-attachments/assets/0a2d51df-647a-4897-ac38-2b9b911468c4)

The scores are averaged over heads and layers.
The visualized experiment is calculated on our validation dataset. The corpus follows StableLM-3B-4E1T [1].

[1]  Jonathan Tow, Marco Bellagente, Dakota Mahan, and Carlos Riquelme. StableLM 3B 4E1T. https://aka.ms/StableLM-3B-4E1T, 2023.

**Comment by yjoonjang** [comment]
Thank you for your response, @YTianZHU .
Looking at the training dataset posted on the blog you gave me: [https://aka.ms/StableLM-3B-4E1T](https://stability.wandb.io/stability-llm/stable-lm/reports/StableLM-3B-4E1T--VmlldzoyMjU4?accessToken=u3zujipenkx5g7rtcj9qojjgxpconyjktjkli2po09nffrffdhhchq045vp0wyfo), I don't really get how you used the corpus for visualization.

Shouldn't there be a gold answer context provided in the dataset for visualization? However, I couldn't find any dataset that provided the gold context. 

Could you explain what data you used for visualization? Thank you.

**Comment by YTianZHU** [comment]
@yjoonjang  I misunderstood your question. I thought you were asking the training corpus.
For the dataset in the visualized experiment, we use the magic number needle retrieval task proposed in LWM. You can refer to implementation in the paper's repo: https://github.com/LargeWorldModel/LWM/blob/main/scripts/eval_needle.py
