### ISSUE TITLE
unilmv2 pre-trained model

### ISSUE THREAD

**Issue by anshoomehra** [microsoft/unilm#166]
Team - Great work!! 

Was curious if you plan to share code and pre-trained models for unilmv2, if so, when would that be ?? I have been using unilmv1 and now at a stage to experiment further. 

Thanks,
Anshoo

**Comment by gitnlp** [comment]
Yes. We will release the fine-tuning recipe and pre-trained models. Stay tuned!

**Comment by jind11** [comment]
Ping again, it seems that after four months, the v2 is still not there. Do you have a more concrete timeline of releasing it? Thanks!
