### ISSUE TITLE
About how to submit SROIE competition

### ISSUE THREAD

**Issue by persistforever** [microsoft/unilm#178]
Sorry for disturbing the problem not related to this repo.

About how to submit SROIE competition.

I have finished my model for SROIE Task3, however, I do not know how to submit my results.

![image](https://user-images.githubusercontent.com/9996015/84476859-556b9180-acc1-11ea-82be-7f6c75a06372.png)

here is the snapshot about my results. My results pass the auto examination and reports 'The method is not calculated yet'. So, if there some thing wrong with my reuslts?

Can you help me. VERY THANKS.

**Comment by wolfshow** [comment]
@persistforever Sometimes the website will return this status. Please wait or resubmit the results

**Comment by kbrajwani** [comment]
@persistforever hey can you please help me how you preprocess the dataset and how you map the key-value.

**Comment by buiquangmanhhp1999** [comment]
@persistforever, I also give same issue. Did you solve this problem ?
