### ISSUE TITLE
Regarding Abstractive Summaries

### ISSUE THREAD

**Issue by tahmedge** [microsoft/unilm#18]
As mentioned in the paper, during fine-tuning, you masked some tokens in the summaries and then you predicted those tokens. But during inference (only test-data is given), you don't have the summaries. So, how did the prediction occur during inference time? I mean, how you gave the inputs for inference and how did the decoding work?

**Comment by donglixp** [comment]
The decoding procedure is similar to the vanilla seq2seq decoder. In each time step, we generate one token, and then feed it into the model for the next time step’s prediction. Both greedy search and beam search can be employed for decoding.
