### ISSUE TITLE
MiniLM - Question Generation, Extractive Summarization

### ISSUE THREAD

**Issue by anshoomehra** [microsoft/unilm#180]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): 

Team, 

1. Has the pre-trained MiniLM for Question Generation been Released? If not, can you please share and if feasible, also share the delta results in performance between MiniLM and UniLM?

2. I was curious if you have explored Extractive Summarization using MiniLM (or even UniLM) and any thoughts, pre-trained models on this front?

Great work as always, much appreciated your time and attention.

Best,
Anshoo

**Comment by donglixp** [comment]
For the second question, using extractive summarization or abstractive summarization depends on the dataset itself. The model also works well for extractive summarization, if the task tends to directly copy the input sentences. The training objective is to predict whether a sentence should be included in the output summary. One application example is shown in Figure 2 of https://arxiv.org/pdf/1911.03324.pdf .
