### ISSUE TITLE
how to use --do_predict layoutlm 

### ISSUE THREAD

**Issue by shreyaschim** [microsoft/unilm#183]
### **Describe**
Model I am using LayoutLM :
can you please explain --do_predict argument, i want to using model for sequence labeling on form for extracting question answer pair in it, I have run the scripts as given in read section, and have training output, when I run the command with --do_predict it gives me the same output as test.txt from data files in test_prediction.txt in output file, can anyone please explain me what is happening and how I be able to use it for key-value extraction in form document. I am very beginner to this.

**Comment by wolfshow** [comment]
@shreyaschim The current script will help you identify the spans of key and value, but you need post-processing to extract key-value pairs. Basically, you may build a binary classifier based on the LayoutLM output embeddings to detect whether a key and a value is a pair.

**Comment by shreyaschim** [comment]
@wolfshow Thank you so much for your valuable reply. I am really stuck on it. Can you please explain the process for predicting labels in short for sequence labeling.
I am using hocr output, in "test.txt" i am using plan text in hocr , in box file  iam using text coordinate  from hocr and text_image.txt i.am using, "word,  box coordinates, image width, length and filename" .
Does this is the right input for sequence labeling, coz I am not able to get prediction file for this document, it is using "cache_pretrained" file , and if i delete this file it is getting null value in label, which is error, after debugging I came to know that I am missing something very important, I have wrongly understand the process, can you please help me, so that I could able to predict labels like S-Answer, SQuestion S header etc for the given image document. Please guide were I its going wrong. 
I am sharing my mail-id  shreyas4329ay@gmail.com
If possible from your side, I would like to connect with you on this. 
Thankyou

**Comment by mdv3101** [comment]
@shreyaschim do you get any success in generating key-value pair? I am stuck with this.

**Comment by shreyaschim** [comment]
Yes, i am getting key-pairs.

**Comment by mdv3101** [comment]
@shreyaschim That's awesome. Can you please share the code. It would be very helpful. If you want, I can drop you a mail as well.
Thanks

**Comment by jingmouren** [comment]
> @shreyaschim The current script will help you identify the spans of key and value, but you need post-processing to extract key-value pairs. Basically, you may build a binary classifier based on the LayoutLM output embeddings to detect whether a key and a value is a pair.

How to sample the negativa pairs for training. And how to decide which pairs to be checked when do predicting? Say there are O(N) values, so there are O(N) real pairs, and O(N^2) pairs.
