### ISSUE TITLE
Choose the best model for question generation tasks

### ISSUE THREAD

**Issue by Aniruddha-JU** [microsoft/unilm#184]
I have finetuned on my dataset. I  have used no of epochs =10, now i am choosing the epoch, which is giving low loss value. Based on this model, I am evaluating it on test data.  Is it correct approach?

**Comment by WenhuiWang0824** [comment]
Hi @Aniruddha-JU,

You could directly use the checkpoint of the final epoch or select checkpoint based on the dev performance.

Thanks
