### ISSUE TITLE
[S2s_ft] error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by Dod-o** [microsoft/unilm#185]
**Describe the bug**
The model I am using S2s_ft: When I follow steps in the readme to install the environment in docker, I will get an error "**error: command 'gcc' failed with exit status 1**" because the latest version of the apex is no longer suitable here.

**Solution**
The solution is to roll back apex to the previous version before installing apex:
1. git clone https://github.com/NVIDIA/apex.git 
2. cd apex
3. **git reset --hard de6378f5dae8fcf2879a4be8ecea8bbcb9e59d53**
4. python setup.py install --cuda_ext --cpp_ext

This could make it work again.

**Comment by donglixp** [comment]
Thanks @Dod-o  I will update the document as suggested.
