### ISSUE TITLE
Can random initialization of LayoutLM work?

### ISSUE THREAD

**Issue by persistforever** [microsoft/unilm#187]
For LayoutLM model, I do not use LayoutLM pretrained model to initialize, replaced with random initialization, I cannot obtain good performance. Do you obtain the same reuslts? Or should I do some things to make random initialization work?

Thanks.

**Comment by wolfshow** [comment]
@persistforever Yes, please refer to our latest results with random initialzation [https://arxiv.org/abs/1912.13318](url)

**Comment by persistforever** [comment]
Thanks. So the Scratch is random initialization. However, the reuslts is on FUNSD dataset. What is the result on SROIE dataset?

**Comment by wolfshow** [comment]
@persistforever We only run the random initialized models on FUNSD dataset.

**Comment by persistforever** [comment]
OK, thanks
