### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by weili-ict** [microsoft/unilm#19]
When run the run_seq2seq.py to finetune the model on summarization datasets, the program will always crash and output "Segmentation fault (core dumped)". The command is as follow:

export CUDA_VISIBLE_DEVICES=0,1,2,3
python biunilm/run_seq2seq.py \
  --do_train --fp16 --amp --num_workers 0 \
  --bert_model ../bert-large-cased/ --new_segment_ids --tokenized_input \
  --output_dir ../summ_model/bert_save \
  --log_dir ../summ_model/bert_log \
  --model_recover_path ../storage/unilmv1-large-cased.bin \
  --max_seq_length 768 --max_position_embeddings 768 \
  --trunc_seg a --always_truncate_tail \
  --max_len_a 568 --max_len_b 200 \
  --mask_prob 0.7 --max_pred 140 \
  --train_batch_size 48 --gradient_accumulation_steps 2 \
  --learning_rate 0.00003 --warmup_proportion 0.1 --label_smoothing 0.1 \
  --num_train_epochs 30 

What causes the Segmentation fault error? Thanks for your help!

**Comment by donglixp** [comment]
Hi @weili-ict ,

Could you provide more details about the error and the docker environment? Thanks!

**Comment by weili-ict** [comment]
It seems that the error is caused by the mismatch between apex and the cuda version.

**Comment by donglixp** [comment]
### Docker

The recommended way to run the code is using docker under Linux:
```bash
alias=`whoami | cut -d'.' -f2`; docker run -it --rm --runtime=nvidia --ipc=host --privileged -v /home/${alias}:/home/${alias} pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel bash
```

The docker is initialized by:
```bash
. .bashrc
apt-get update
apt-get install -y vim wget ssh

PWD_DIR=$(pwd)
cd $(mktemp -d)
git clone -q https://github.com/NVIDIA/apex.git
cd apex
git reset --hard 1603407bf49c7fc3da74fceb6a6c7b47fece2ef8
python setup.py install --user --cuda_ext --cpp_ext
cd $PWD_DIR

pip install --user tensorboardX six numpy tqdm path.py pandas scikit-learn lmdb pyarrow py-lz4framed methodtools py-rouge pyrouge nltk
python -c "import nltk; nltk.download('punkt')"
pip install -e git://github.com/Maluuba/nlg-eval.git#egg=nlg-eval
```
The mixed-precision training code requires the specific version of [NVIDIA/apex](https://github.com/NVIDIA/apex/tree/1603407bf49c7fc3da74fceb6a6c7b47fece2ef8), which only supports pytorch<1.2.0.
