### ISSUE TITLE
label id of paddings are set to -100, which is not allowed in Pytorch

### ISSUE THREAD

**Issue by yangjinning2020** [microsoft/unilm#190]
According to the following error, it says the label should >= 0. However in Funsd.py, the label of paddings are -100 which makes error when the model is running. 

Labeling code in Funsd.py:
label_ids.extend( [label_map[label]] + [pad_token_label_id] * (len(word_tokens) - 1))

Padding Label Definition in run_seq_labeling.py:
pad_token_label_id = CrossEntropyLoss().ignore_index  # =-100

Error shows in command line:
Evaluating:   0%|                                                                                | 0/4 [00:00<?, ?it/s]C:/w/1/s/tmp_conda_3.6_095855/conda/conda-bld/pytorch_1579082406639/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/tmp_conda_3.6_095855/conda/conda-bld/pytorch_1579082406639/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/tmp_conda_3.6_095855/conda/conda-bld/pytorch_1579082406639/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/tmp_conda_3.6_095855/conda/conda-bld/pytorch_1579082406639/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/tmp_conda_3.6_095855/conda/conda-bld/pytorch_1579082406639/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/w/1/s/tmp_conda_3.6_095855/conda/conda-bld/pytorch_1579082406639/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
Evaluating:   0%|                                                                                | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run_seq_labeling.py", line 818, in <module>
    main()
  File "run_seq_labeling.py", line 779, in main
    args, model, tokenizer, labels, pad_token_label_id, mode="test"
  File "run_seq_labeling.py", line 360, in evaluate
    eval_loss += tmp_eval_loss.item()

**Comment by donglixp** [comment]
Using the same PyTorch version should be able to solve the issue.

**Comment by yangjinning2020** [comment]
Error is caused by the wrong setting in config file.

**Comment by hasansalimkanmaz** [comment]
which setting caused this error?
