### ISSUE TITLE
Do I need to run the example of LayoutLM on my GPU

### ISSUE THREAD

**Issue by vlall** [microsoft/unilm#194]
Do i need to use my GPU to run an example pre-trained model for LayoutLM on the sequential labeling task?

**Comment by wolfshow** [comment]
@vlall Yes, we recommend using GPU with at least 8GB memory to run the LayoutLM model.

**Comment by vlall** [comment]
Just to clarify, you recommend a GPU but is it a requirement if I only have CPU? I noticed partial CPU instructions here, but it doesn't provide full info: https://github.com/microsoft/unilm/issues/23

**Comment by ssherlins** [comment]
> @vlall Yes, we recommend using GPU with at least 8GB memory to run the LayoutLM model.

Hi, can you please provide the recommended GPU configurations?

**Comment by nazreen** [comment]
bump
