### ISSUE TITLE
[LayoutLM] Procedure of generating submission results on SROIE test dataset

### ISSUE THREAD

**Issue by w-cheng** [microsoft/unilm#195]
Hi,

As hinted by #168, LayoutLM can be fine-tuned on SROIE dataset by treating the task as a sequence labelling task. And a label is predicted for each word in the OCR results. 

However, to submit the prediction results on SROIE challenge website, one needs to convert the predictions at word level to field level. For instance, "company": "PETRON BKT LANJAN SB".

Could you guys share some information about the procedure to get the field level predictions? Thanks.

**Comment by wolfshow** [comment]
@w-cheng Like any sequence labeling task, you can do B-I-O classificaiton on token-level and use B- and I- for field-level prediction.

**Comment by w-cheng** [comment]
@wolfshow Thanks a lot for your quick reply, I'll try that and let you know if I have further questions.
