### ISSUE TITLE
LayoutLM-Can't reproduce to get the same accuracy on RVL-CDIP document classifcation

### ISSUE THREAD

**Issue by wendilinplay** [microsoft/unilm#197]
Following exactly the same steps in README for Document Image Classification Task, I only get 88% accuracy. Do you know what could be the cause? 
Could it be the 94% was created with an image embedding or there were some special preprocessing before TesseractOCR? If it's because of the image embedding, it's not good that the performance of LayoutLM embedding is even worse than BERT-Large.

**Comment by wolfshow** [comment]
@wendilinplay Did you use the same OCR results for LayoutLM and BERT-Large fine-tuning?

**Comment by wendilinplay** [comment]
I used TesseractOCR 4.1.1. and I haven't run with BERT-Large yet. But that makes sense, as there was probably a bug in my tesseract code, that I found a few documents failed to be transformed to HOCR. Thanks. That answered my question.

**Comment by Lele-Xie** [comment]
@wendilinplay hello~ I meet the similar problem. I get an accuracy of 87.9 on RVL dataset and also use TesseractOCR 4.1.1. So how did you find  the failed images of tesseract? Thanks a lot.

**Comment by wendilinplay** [comment]
> @wendilinplay hello~ I meet the similar problem. I get an accuracy of 87.9 on RVL dataset and also use TesseractOCR 4.1.1. So how did you find the failed images of tesseract? Thanks a lot.
Sorry, I didn’t, but only accept the low performance for now.
