### ISSUE TITLE
关于MiniLM

### ISSUE THREAD

**Issue by zhanghan1992** [microsoft/unilm#199]
请教下，MiniLM的蒸馏过程中只用了 attention 和 value-relation 的loss, 二者的对齐能否让student model 在语言模型上收敛？ 有没有尝试过把语言模型的loss加上会不会在下游任务上取得更好的效果？

**Comment by WenhuiWang0824** [comment]
Hi @zhanghan1992, 因为没有使用MLM的loss, 所以没有测试在语言模型上的效果, 但是MiniLM可以用于生成任务, 应该学习到了语言模型的知识. 如果同时和MLM loss一起训练, 结果会降低一些.
