### ISSUE TITLE
[Layout LM] - Visual Information 

### ISSUE THREAD

**Issue by bpucla** [microsoft/unilm#201]
Dear Authors,

Thank you for sharing the code! This Layout LM paper emphasizes the **joint training with text and visual information**. But it seems that the released code does not include any component that extract visual features and process the visual information. Is it possible to open source these components of your code?  Otherwise, it might be hard to reproduce the reported results and take the advantage of your good model considering both text and visual information. 

Thanks!

**Comment by wolfshow** [comment]
@bpucla, Thanks for the interests in LayoutLM! As visual information is not part of the LayoutLM pre-training, we did not release the code for the image embeddings. You may use any state-of-the-art CV models and add them with the LayoutLM output to reproduce the results.
