### ISSUE TITLE
[LayoutLM] Return just the word embeddings of a token using LayoutLM

### ISSUE THREAD

**Issue by vlall** [microsoft/unilm#202]
Given a random token found in a document, i want to obtain the document-specific embedding using LayoutLM. Is this possible with the current tool? And if so, any tips on how to do it.

**Comment by wolfshow** [comment]
@vlall Yes, you can use the last layer's output for the specific token, which is a document-specifc embedding with the contextual information.

**Comment by vlall** [comment]
That makes sense! I noticed the two examples in the documentation are examples that require **labeled** data. Is there a way to use this model with unlabeled data? I want to load the pre-trained model, fine-tune it to my PDFs, then input a token with its coordinates, and want to get the word embedding for a particular token in a particular location in the PDF. Can this project help with that, and if so are there instructions I can follow to use the pre-trained model this way?

**Comment by wolfshow** [comment]
@vlall Our examples are designed for downstream tasks that need to be finetuned using labeled datasets. If you only need the token embeddings, you can just load the model and get the output from the last layer. The labeled data is not required.
