### ISSUE TITLE
Script directory not found?

### ISSUE THREAD

**Issue by elnazsn1988** [microsoft/unilm#207]
HI - am trying to find preprocess code for the FUNSD dataset under scripts and cannot find the directory, has it been removed?

**Comment by wolfshow** [comment]
@elnazsn1988 have you found that?

**Comment by elnazsn1988** [comment]
> @elnazsn1988 have you found that?

Hi yes it was renamed, the name mentioned in the readme instructions is from the older commit, needs to be updated. Happy to do and submit, not sure how.
