### ISSUE TITLE
About SROIE dataset preprocessing 

### ISSUE THREAD

**Issue by mohamedMO347** [microsoft/unilm#208]
I was just to preprocess SROIE after I've seen FUNSD preprocessing code.
Can you tell me how you dealt with the 2D box coordinates of each token ( they didn't provide the annotation of each word ) or share the word-level (box-level) annotations.
Thank you in advance.

**Comment by wolfshow** [comment]
@mohamedMO347 You may get the 2D coordinates by splitting the text line into individual tokens with some heuristic rules, but it is difficult to get 100% accuracy.

**Comment by mohamedMO347** [comment]
@wolfshow sorry I didn't get it , what do you mean by heuristic rules ? can you give me an example please.

**Comment by purnasai** [comment]
@mohamedMO347, heuristic means to self discover some practical approach to get the 2D coordinates. One suggestion I could give is you can use annotation tools like [LabelImg](https://github.com/tzutalin/labelImg).
