### ISSUE TITLE
Can't set attribute tokenizer.max_len

### ISSUE THREAD

**Issue by vishal-burman** [microsoft/unilm#214]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): MiniLM

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

**To Reproduce**
```
! export CUDA_VISIBLE_DEVICES=0
! python decode_seq2seq.py \
  --model_type minilm --tokenizer_name minilm-l12-h384-uncased --input_file sample.json --split validation --do_lower_case \
  --model_path output_dir/ckpt-32000 --max_seq_length 464 --max_tgt_length 48 --batch_size 1 --beam_size 5 \
  --length_penalty 0 --forbid_duplicate_ngrams --mode s2s --forbid_ignore_word "."
```

**Expected behavior**
Here is the trace:
```
2020-08-05 06:30:16.386075: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
08/05/2020 06:30:18 - INFO - transformers.tokenization_utils -   loading file https://unilm.blob.core.windows.net/ckpt/minilm-l12-h384-uncased-vocab.txt from cache at /root/.cache/torch/transformers/c6a0d170b6fcc6d023a402d9c81e5526a82901ffed3eb6021fb0ec17cfd24711.0af242a3765cd96e2c6ad669a38c22d99d583824740a9a2b36fe3ed5a07d0503
Traceback (most recent call last):
  File "decode_seq2seq.py", line 296, in <module>
    main()
  File "decode_seq2seq.py", line 161, in main
    tokenizer.max_len = args.max_seq_length
AttributeError: can't set attribute
```

- Platform:
- Python version:
- PyTorch version (GPU?):

**Comment by othman-zennaki** [comment]
Hi @vishal-burman,
Please, did you solve this problem?
thanks

**Comment by vishal-burman** [comment]
Hi @othman-zennaki No, I wasn't able to get a solution for this problem. Do let me know if you find a fix.

**Comment by guijuzhejiang** [comment]
I have the same error. Is this project not maintained

**Comment by addf400** [comment]
@guijuzhejiang @vishal-burman @othman-zennaki 

https://github.com/microsoft/unilm/blob/master/s2s-ft/decode_seq2seq.py#L152
Change this line into:
``` bash
    if hasattr(tokenizer, 'model_max_length'):
        tokenizer.model_max_length = args.max_seq_length
    elif hasattr(tokenizer, 'max_len'):
        tokenizer.max_len = args.max_seq_length
```

Or 
``` bash
pip install transformers==2.2.1
```

This issue is caused by the interface change after the update of transformers package

**Comment by guijuzhejiang** [comment]
Add the decorator in tokenization_utils.py 
@max_len.setter
    def max_len(self, value):
        self.model_max_length = value

**Comment by guijuzhejiang** [comment]
> @guijuzhejiang @ vishal -burman @ othman-zennaki
> 
> https://github.com/microsoft/unilm/blob/master/s2s-ft/decode_seq2seq.py#L152
> 将此行更改为：
> 
> ```shell
>     如果hasattr（tokenizer，' model_max_length '）：
>         tokenizer.model_max_length = args.max_seq_length elif hasattr（tokenizer，' max_len '）：
>         tokenizer.max_len = args.max_seq_length
>     
> ```
> 
> 要么
> 
> ```shell
> 点安装变压器== 2.2.1
> ```
> 
> 此问题是由更新变形金刚软件包后的接口更改引起的

Thank you for your reply. I resolved it by adding a decorator.
