### ISSUE TITLE
Is LayoutLM pretrained fine-tuning models available?

### ISSUE THREAD

**Issue by 7fantasysz** [microsoft/unilm#215]
We are using your per-trained LayoutML model to extract "question-answer" pairs from document. We also want to try other fine-tuning models you mentioned. However, we are constrained by not having enough capacity to train these fine-tuning models (don't have a good GPU to train and have to reduce batch size to 4). 
I am wondering if you could give us access to your fine-tuning LayoutLM models on datasets including FUNSD, SROIE, and RVL-CDIP?

**Comment by wolfshow** [comment]
@7fantasysz We do not have plan to release downstream models in the near future. Please try some cloud-based GPU machines for the finetuning step.
