### ISSUE TITLE
Where is bert pretrained cache?

### ISSUE THREAD

**Issue by alibi123** [microsoft/unilm#22]
`export PYTORCH_PRETRAINED_BERT_CACHE=/{tmp_folder}/bert-cased-pretrained-cache`
From this command I can't understand where can I find bert-cased-pretrained-cache. I tried to pip install separately, but there's no `bert-cased-pretrained-cache`

**Comment by donglixp** [comment]
`${PYTORCH_PRETRAINED_BERT_CACHE}` should be a temporary folder path used to store the cached files.
