### ISSUE TITLE
Training data for Multi-lingual LayoutLM

### ISSUE THREAD

**Issue by kwokwangliu** [microsoft/unilm#221]
LayoutLM is pre-trained on  IIT-CDIP.  If I want to pre-train it with other language, e.g. Chinese or Japanese, do we have some similar dataset for this purpose. If not, how do you pre-train  LayoutLM for other languages?
@wolfshow @donglixp 

Thanks

**Comment by wolfshow** [comment]
@kwokwangliu We are working on the multilingual version and will release a pre-trained multilingual LayoutLM model soon.

**Comment by yaoliUoA** [comment]
@wolfshow it seems to me the layoutLM does not release the pre-training code (only the training code for downstream tasks are available), I wonder if it is possible to release the pre-training code so that people can pre-training layoutLM on different datasets?

**Comment by SibtainRazaJamali** [comment]
@wolfshow  what is the expected release date?

**Comment by qiansi** [comment]
@wolfshow great! and what is the pre-training code release date?

**Comment by SibtainRazaJamali** [comment]
@qiansi  they won't release pre training code.

**Comment by qiansi** [comment]
> @qiansi they won't release pre training code.

em...  I believe the pre-training code is more useful for custom scene enhancement， How do you pre-train the model?

**Comment by wolfshow** [comment]
@SibtainRazaJamali @qiansi We need to run some experiments on our in-house multilingual benchmark. It may take some time and no ETA right now.

**Comment by wolfshow** [comment]
LayoutXLM is coming by extending the LayoutLM into multilingual support!

https://arxiv.org/abs/2104.08836

**Comment by ruifcruz** [comment]
Hi @wolfshow this is great news, a big thank you to your team for this big contribution! 

Do you have an idea when code and model for XLM and v2 will be available (days? weeks? months?). To know this would be crucial to plan my students research

**Comment by wolfshow** [comment]
> Hi @wolfshow this is great news, a big thank you to your team for this big contribution!
> 
> Do you have an idea when code and model for XLM and v2 will be available (days? weeks? months?). To know this would be crucial to plan my students research

Both will be released in the comming weeks and LayoutLMv2 will be released in the coming days.
