### ISSUE TITLE
AssertionError at the start of the training

### ISSUE THREAD

**Issue by hasansalimkanmaz** [microsoft/unilm#223]
**Describe**
Model I am using LayoutLM:

I prepared my dataset according to your docs. But I got AssertionError, traceback is below.

    (layoutlm_env) hasan@faktionGPU:/media/faktion/fastdisk/hasan/layoutLM$ python       unilm/layoutlm/examples/seq_labeling/run_seq_labeling.py --data_dir bestelbonen_dataset/    --model_type layoutlm   --model_name_or_path layoutlm-base-uncased/ --do_lower_case                             --max_seq_length 1024                             --do_train                             --num_train_epochs 100.0                             --logging_steps 10                             --save_steps -1                             --output_dir output_dir_bestelbonen/                             --labels bestelbonen_dataset/labels.txt                             --per_gpu_train_batch_size 8                             --per_gpu_eval_batch_size 8                             --fp16                             --overwrite_output_dir
    Traceback (most recent call last):
      File "unilm/layoutlm/examples/seq_labeling/run_seq_labeling.py", line 811, in <module>
        main()
       File "unilm/layoutlm/examples/seq_labeling/run_seq_labeling.py", line 701, in main
         args, tokenizer, labels, pad_token_label_id, mode="train"
       File "/media/faktion/fastdisk/hasan/layoutLM/layoutlm_env/lib/python3.6/site-packages/layoutlm/data/funsd.py", line 46, in __init__
         pad_token_label_id=pad_token_label_id,
       File "/media/faktion/fastdisk/hasan/layoutLM/layoutlm_env/lib/python3.6/site-packages/layoutlm/data/funsd.py", line 336, in convert_examples_to_features
         assert len(label_ids) == max_seq_length
     AssertionError

**Comment by r000bin** [comment]
I guess that max_seq_length can't be higher than 512

**Comment by hasansalimkanmaz** [comment]
It also didn't work with 512

**Comment by hasansalimkanmaz** [comment]
Duplicate of  https://github.com/microsoft/unilm/issues/188
