### ISSUE TITLE
LayoutLM Pretrained model creation

### ISSUE THREAD

**Issue by PamelaVQ** [microsoft/unilm#228]
I need to use a LayoutLM model for German. I have the data to train it.
How do I create a base German LayoutLM model with this data?

**Comment by wolfshow** [comment]
@PamelaVQ We will release the multilingual LayoutLM soon, which includes German. Please stay tuned.

**Comment by Sharathmk99** [comment]
@wolfshow is multilingual LayoutLM is available now?
