### ISSUE TITLE
What is the difference between Layout MVLM and Image MVLM?

### ISSUE THREAD

**Issue by mfxss** [microsoft/unilm#230]
**Describe**
Model I am using LayoutLM. I your paper, models are trained in different ways.
Which way is the two open source model are pretrained with ? Text+Layout+MVLM+MDC or Text+Layout+Image+MVLM?

**Comment by wolfshow** [comment]
@mfxss The released models are pre-trained without images. Image information can be integrated with the LayoutLM output.

**Comment by mfxss** [comment]
> @mfxss The released models are pre-trained without images. Image information can be integrated with the LayoutLM output.

So the code doesn't include the Faster R-CNN part?

**Comment by wolfshow** [comment]
@mfxss Yes, you may integrate any Faster R-CNN implementation with the LayoutLM output.

**Comment by mfxss** [comment]
期待早日出中文模型
