### ISSUE TITLE
MiniLM pre-training

### ISSUE THREAD

**Issue by deepaknlp** [microsoft/unilm#233]
Hi @WenhuiWang0824 @donglixp @nyanyanya,

I wanted to pre-train the MiniLM for my own task. In this regard,  I am looking for the pre-training details of MiniLM model. It seems the code is not available for that, but can you provide more details of pre-training or refer the appropriate literature for the same.

Thank you.

**Comment by RyanHuangNLP** [comment]
I just change the code base huawei's tiny bert for just use the last layer's attention, but I cannot reproduce, would you like to release the pretrain code of minilm? @WenhuiWang0824

**Comment by donglixp** [comment]
@RyanHuangNLP Please refer to the paper for the details. MiniLM uses Attention Transfer and Value-Relation Transfer, rather than "just use the last layer's attention".
