### ISSUE TITLE
Multilingual LayoutLM Release

### ISSUE THREAD

**Issue by wangqihanginthesky** [microsoft/unilm#236]
**Describe**
I think you will release the multilingual LayoutLM soon.Will it include a Chinese version and a Japanese version?
Thank you.

**Comment by wolfshow** [comment]
@wangqihanginthesky, The multilingual LayoutLM is pre-trained with a huge amount of mulingual documents that includes Chinese and Japanese.

**Comment by JosPolfliet** [comment]
Hi @wolfshow, do you have any indication when the multilingual model would be released? Days, weeks, months?

**Comment by wolfshow** [comment]
@JosPolfliet We are working on the multilingual datasets and evaluation. It should be within several weeks.

**Comment by archwolf118** [comment]
@

> @JosPolfliet We are working on the multilingual datasets and evaluation. It should be within several weeks.

we are waiting! Thanks a lot.

**Comment by JosPolfliet** [comment]
Hi @wolfshow, I know you are all busy people. Any update on the multilingual LayoutLM model? Would love to benchmark it !

**Comment by wolfshow** [comment]
@JosPolfliet We are actively working on that not only the mulingual LayoutLM models but also some labeled multilingual benchmark datasets.

**Comment by hasansalimkanmaz** [comment]
Hi @wolfshow, I really appreciate your work and thank you very much. I am subscribed to this thread, but unfortunately I couldn't see any activity about multilingual layoutlm model for a long time. Is there any news about multilingual model? I think community is looking forward to using it.

**Comment by wolfshow** [comment]
@hasansalimkanmaz We will have an update for the multilingual version in the coming weeks. The main blocking issue is we are working on a human labeled benchmark for the multilingual document understanding. It takes a lot of time to label and check for the vendors.

**Comment by hasansalimkanmaz** [comment]
Thank you very much for your reply @wolfshow I am looking forward to using it.

**Comment by dreamhighchina** [comment]
大佬，我想问下这个多语言的模型，是单独分成汉语日语等，还是合并在一个模型里面？

**Comment by wolfshow** [comment]
> 大佬，我想问下这个多语言的模型，是单独分成汉语日语等，还是合并在一个模型里面？

will be a single model

**Comment by knitemblazor** [comment]
i have started a github repo regarding the training and prediction flow as there are limitations on labelled dataset
i would suggest you build a small set for testing in your particular languages
I have currently tested it for hindi, malayalam, english combinations.
https://github.com/knitemblazor/Multilingual_LayoutLM

**Comment by wolfshow** [comment]
LayoutXLM is coming by extending the LayoutLM into multilingual support!

https://arxiv.org/abs/2104.08836
