### ISSUE TITLE
Further pre-training of LayoutLM

### ISSUE THREAD

**Issue by tshrjn** [microsoft/unilm#239]
The current codebase only has code for [fine-tuning](https://github.com/microsoft/unilm/tree/master/layoutlm#fine-tuning-example) the provided [LayoutLM](https://github.com/microsoft/unilm/tree/master/layoutlm) model. However, no code for pretraining is there. It'd be greatly helpful for us if there's a need to further pre-train our model on some other corpus.

It's also mentioned in [issue 205](https://github.com/microsoft/unilm/issues/205) but had no conclusive solution.

**Comment by wolfshow** [comment]
@tshrjn We do not have bandwidth for wrap up the pre-training code right now, but may release in the future.
