### ISSUE TITLE
Multi GPU Training doesnot work

### ISSUE THREAD

**Issue by ankit-chadha** [microsoft/unilm#25]
It uses a single GPU with the command line for multiple gpus even when visible devices are 0,1.

Any suggestions?

**Comment by donglixp** [comment]
What command did you run? Posting the results of `nvidia-smi` could also be helpful.

**Comment by ankit-chadha** [comment]
DATA_DIR=data/cnn_dm
OUTPUT_DIR=output/
MODEL_RECOVER_PATH=pretrained/cnndm_model.bin
export PYTORCH_PRETRAINED_BERT_CACHE=/tmp/bert-cased-pretrained-cache
export CUDA_VISIBLE_DEVICES=0,1
python unilm/src/biunilm/run_seq2seq.py --do_train --fp16 --amp --num_workers 0 \
  --bert_model bert-large-cased --new_segment_ids --tokenized_input \
  --data_dir ${DATA_DIR} \
  --output_dir ${OUTPUT_DIR}/bert_save_bl \
  --log_dir ${OUTPUT_DIR}/bert_log_bl \
  --model_recover_path ${MODEL_RECOVER_PATH} \
  --max_seq_length 768 --max_position_embeddings 768 \
  --trunc_seg a --always_truncate_tail \
  --max_len_a 568 --max_len_b 200 \
  --mask_prob 0.7 --max_pred 140 \
  --train_batch_size 8 --gradient_accumulation_steps 8 \
  --learning_rate 0.00003 --warmup_proportion 0.1 --label_smoothing 0.1 \
  --num_train_epochs 30

Here is the command line I have been using.

**Comment by donglixp** [comment]
I checked the outputs of `nvidia-smi` you shared with me. The GPU-1 is not found by pytorch.

- Was the program run in the docker as in README.md?

- Whether did the other multi-gpu pytorch test cases successfully run?

**Comment by ankit-chadha** [comment]
Hi Ali,

I am running this outside of the docker container but I have installed all
the dependencies.

Is there any specific customization for multi GPU in your docker?

Thanks,
Ankit

**Comment by donglixp** [comment]
We used pytorch's official docker, which sets up the required environment.

**Comment by Hannabrahman** [comment]
> We used pytorch's official docker, which sets up the required environment.

Hi,

I have the same problem, Though I set both GPU to be visible, only one GPUs is working.
I can run other codes with multiple GPUs. Do you know any fix to the code to solve this?

Thanks

**Comment by donglixp** [comment]
@Hannabrahman  Could you post the command used for multi-gpu running?
