### ISSUE TITLE
Missing vocab and config files for unilm1.2-base-uncased model

### ISSUE THREAD

**Issue by zafercavdar** [microsoft/unilm#258]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): UniLM v1.2 base-uncased

I couldn't find vocab.txt and config.json files for this model on repo storage folder or Hugging Face's model hub.

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/s2s-ft/s2s_ft/tokenization_unilm.py#L46

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/s2s-ft/s2s_ft/configuration_unilm.py#L41
