### ISSUE TITLE
Segmentation fault in uniLM-v1 while fine tuning for question generation

### ISSUE THREAD

**Issue by RocKeTG** [microsoft/unilm#259]
Model I am using (UniLM-v1):
I do not have root access, so I have created an environment for running the code. Here is the list of installed packages in the environment.

![image](https://user-images.githubusercontent.com/24287627/95680121-cfbb0c80-0bf4-11eb-9561-98fa9a671d5a.png)

I am getting segmentation fault while fine tuning the unilm-v1 for question generation. For simiplicity, I took small dataset of size = 15.  Here is the log
![image](https://user-images.githubusercontent.com/24287627/95680211-7acbc600-0bf5-11eb-9550-6d8dfb176d4c.png)
Could you please point out what can be the reason for segmentation fault in this case?

**Comment by donglixp** [comment]
Docker is recommended for the environment configuration.  https://github.com/microsoft/unilm/tree/master/unilm-v1#environment
