### ISSUE TITLE
Source sequence padding inconsistency between the training and decoding in seq2seq

### ISSUE THREAD

**Issue by yuewang-cuhk** [microsoft/unilm#26]
Hi, I find that during decoding in seq2seq, you will pad the source sequence into the length of `max_src_length` with '[PAD]'. But during the training, there is no such padding in the source sequence. Would it introduce any inconsistency problems?

**Comment by nyanyanya** [comment]
The padding is masked out using masks, and has no effect on the results. It is implemented to make the start of target sequences aligned in a batch during decoding.
