### ISSUE TITLE
**Request** | model outputs for Gigawords and CNN-DM test sets

### ISSUE THREAD

**Issue by priyamtejaswin** [microsoft/unilm#266]
Hi folks,

Thanks for releasing the code and checkpoints.
I'm doing some analysis on the model generated hypothesis.
If you have the model outputs for the Gigawords and CNN-DM test sets, could you please share them?

Regards,
Priyam

**Comment by donglixp** [comment]
@priyamtejaswin Hi Priyam, we can share the outputs via email. Thanks!

**Comment by StevenTang1998** [comment]
Hello, our group also want to study the UniLM-Large outputs of GigaWord, however the given code failed due to cuda version. Could you sent it to steven_tang@ruc.edu.cn.

**Comment by donglixp** [comment]
> Hello, our group also want to study the UniLM-Large outputs of GigaWord, however the given code failed due to cuda version. Could you sent it to [steven_tang@ruc.edu.cn](mailto:steven_tang@ruc.edu.cn).

@StevenTang1998 Replied via email.

**Comment by StevenTang1998** [comment]
Thanks for your help.
