### ISSUE TITLE
Is unilm mask_prob_eos not used?

### ISSUE THREAD

**Issue by qiansi** [microsoft/unilm#267]
when i use unilm in a abstract task , the eos can't predict well, The text often repeats the last server words, and i haven't  see the mask_prob_eos used in this file , https://github.com/microsoft/unilm/blob/master/unilm-v1/src/biunilm/run_seq2seq.py
 is it nessary for nlg task?

**Comment by donglixp** [comment]
Hi @qiansi , the argument mask_prob_eos is ignored in the implementation. The EOS token is masked and predicted in the same probability as other tokens. The refactored code at https://github.com/microsoft/unilm/tree/master/s2s-ft should be easier to use.
