### ISSUE TITLE
LayoutLM： how to update or add new to vocab.txt

### ISSUE THREAD

**Issue by Johnson-yue** [microsoft/unilm#274]
**Describe**
Model I am using ( LayoutLM ...):

but the character of I will recognition is not in it. So How I update the  **vocab.txt**  and any other operations like finetune or something else?

**Comment by wolfshow** [comment]
The LayoutLM models are based on the BPE vocab and it is not thay easy to add the new character as well as its embeddings.

**Comment by Johnson-yue** [comment]
@wolfshow  emmm， it must be retrain on the new vocab for new embedding ？ right？

**Comment by wolfshow** [comment]
if you have new word pieces, then the tokenizer and embeddings are both need to be updated.

**Comment by Johnson-yue** [comment]
ok， maybe it has muchhard work to do .....
