### ISSUE TITLE
Can not run  train FUNSD dataset with finetune

### ISSUE THREAD

**Issue by Johnson-yue** [microsoft/unilm#275]
**Describe**
Model I am using (LayoutLM ...):

![Screenshot from 2020-12-14 14-25-49](https://user-images.githubusercontent.com/10268274/102047575-7485e000-3e18-11eb-8a73-15ba74189116.png)

BertConfig has no attribute **'pretrained_coonfig_archive_map'**

I occur a error with no module named "transforms" and I fixed with `pip install transforms` and install huggingface/transforms

**Comment by wolfshow** [comment]
@Johnson-yue Which version of pytorch and huggingface are you using?

**Comment by Johnson-yue** [comment]
@wolfshow  torch == 1.4.0, torchvision==0.5.0,   transformers == 4.0.1

**Comment by ft3020997** [comment]
> @wolfshow torch == 1.4.0, torchvision==0.5.0, transformers == 4.0.1

The version of transformers should be 2.9.0. Follow the LayoutLM's requirements.

**Comment by Johnson-yue** [comment]
@ft3020997  Hi ,thank you for your relpy,  I don't see any requirements for LayoutLM 

I will try with transformers==2.9.0 

And where is the requirements.txt for LayoutLM  would you tell me ?

**Comment by croari** [comment]
> @ft3020997 Hi ,thank you for your relpy, I don't see any requirements for LayoutLM
> 
> I will try with transformers==2.9.0
> 
> And where is the requirements.txt for LayoutLM would you tell me ?

maybe you should try this:
first get into the "/unilm/layoutlm"
and try this command: pip install .
I think it might be useful, because i try this way to solve the problem before.

**Comment by Johnson-yue** [comment]
@croari  thank you ， I will try it
