### ISSUE TITLE
how to add ImageEmbedding layer in LayoutLM

### ISSUE THREAD

**Issue by thisisppn** [microsoft/unilm#285]
Hi, can you show some guideance on how to add an ImageEmbedding layer in your code as described in the paper? As I have read from comments on other issues, you have not included that piece as it's not pre trained.

**Comment by wolfshow** [comment]
@thisisppn Yes, in LayoutLM 1.0, image embeddings are not pre-trained, so you may add any pre-trained image embeddings with the LayoutLM output for downstream tasks. For example, using the OCR bbox as the ROI to extract image embeddings from Faster-RCNN models.

**Comment by thisisppn** [comment]
> @thisisppn Yes, in LayoutLM 1.0, image embeddings are not pre-trained, so you may add any pre-trained image embeddings with the LayoutLM output for downstream tasks. For example, using the OCR bbox as the ROI to extract image embeddings from Faster-RCNN models.

Thank you for your response. So we have to crop the ROIs from the image, and then pass it to the Faster-RCNN models and get the embedding of that cropped ROI? Did u understand that correctly?

**Comment by dreamhighchina** [comment]
> @thisisppn Yes, in LayoutLM 1.0, image embeddings are not pre-trained, so you may add any pre-trained image embeddings with the LayoutLM output for downstream tasks. For example, using the OCR bbox as the ROI to extract image embeddings from Faster-RCNN models.

这里有点疑惑，从原图中抠出来的一个个roi区域，然后送到fasterrcnn网络中，然后得到[batchsize,channels,H,W]然后怎么处理？？
