### ISSUE TITLE
LayoutLM_Image embedding, seqeunce linking, input-output

### ISSUE THREAD

**Issue by SY-JI** [microsoft/unilm#286]
First of all, thank you for providing useful code.

I am using LayoutLM and I have 3questions.

1. Image Embedding
   According to your "LayoutLM: Pre-training of Text and Layout for Document Image Understanding"  document , it makes image embedding token by Faster R-CNN but I can't find any code related with Faster R-CNN in LayoutLM code. 
   Then it means when I using LayoutLM(for Form understanding task) I only use 2-D position Embedding and not using Image embeddings. So, where can I find code related with Image embeddings.

2. Seqeunce-Linking
   Your current code is related with sequence labeling and not related with sequence linking. I think sequence linking is important when extracting useful information from document or papers. So, how can I get sequence linking(key-value pair) results.
   Also you mentioned before issues;  just check Funsd dataset paper and add binary classifier layer at the end of the output embeddings. But, I can't understand it and how to make it as a code. So can you let me know any certain code related about it?

3. Input-Output
   LayoutLM - seq_labeling is aiming about making right BIOES tag to each words. But when I check the code input, Input also contains BIOES tag. Then I think there is no meaning because our goal is to make BIOES tag but actually input already contains BIOES tag. So, Can you explain why the input has BIOES-tag?

I'm sorry about that there was too many questions but I hope you reply to all theses questions. Thank you!!

**Comment by wolfshow** [comment]
1. As the image embeddings are not pre-trained in LayoutLM 1.0. You may add any off-the-shelf pre-trained image embeddings such as Faster-RCNN with the LayoutLM output for downstream tasks.
2. We only release the code to host our pre-trained models. For the downstream linking tasks, you may need to add another layer on top of the key and value spans for binary classification.
3. I don't understanding your questions. We do not have BIOES in the input.

**Comment by SY-JI** [comment]
> 3. I don't understanding your questions. We do not have BIOES in the input.
Then which format I have to use when I want to make a predictions(inference).

For example, 
when **training** I have to use "--do_train" and inside of "--data_dir" 
there should be 3 type of txt files
1) train.txt(it contains BIOES-tags like B-Answer, E-Answer ....)
![image](https://user-images.githubusercontent.com/59797030/104424390-a8dcef80-55c2-11eb-8272-4bbab924fa67.png)
2) train_box.txt
3) train_image.txt 

Then when **predicting** which data format of txt.files should be in "--data_dir" ?? 
there also should be 3 txt files(test.txt, test_box.txt, test_image.txt)??
and if there should be 3 txt files then test.txt files format should be look like train.txt files or not ??

Thanks for your reply!!

**Comment by SY-JI** [comment]
> 3. I don't understanding your questions. We do not have BIOES in the input.
Then which format I have to use when I want to make a predictions(inference).

For example, 
when **training** I have to use "--do_train" and inside of "--data_dir" 
there should be 3 type of txt files
1) train.txt(it contains BIOES-tags like B-Answer, E-Answer ....)
![image](https://user-images.githubusercontent.com/59797030/104424390-a8dcef80-55c2-11eb-8272-4bbab924fa67.png)
2) train_box.txt
3) train_image.txt 

Then when **predicting** which data format of txt.files should be in "--data_dir" ?? 
there also should be 3 txt files(test.txt, test_box.txt, test_image.txt)??
and if there should be 3 txt files then test.txt files format should be look like train.txt files or not ??

Thanks for your reply!!

**Comment by dreamhighchina** [comment]
> > 1. I don't understanding your questions. We do not have BIOES in the input.
> >    Then which format I have to use when I want to make a predictions(inference).
> 
> For example,
> when **training** I have to use "--do_train" and inside of "--data_dir"
> there should be 3 type of txt files
> 
> 1. train.txt(it contains BIOES-tags like B-Answer, E-Answer ....)
>    ![image](https://user-images.githubusercontent.com/59797030/104424390-a8dcef80-55c2-11eb-8272-4bbab924fa67.png)
> 2. train_box.txt
> 3. train_image.txt
> 
> Then when **predicting** which data format of txt.files should be in "--data_dir" ??
> there also should be 3 txt files(test.txt, test_box.txt, test_image.txt)??
> and if there should be 3 txt files then test.txt files format should be look like train.txt files or not ??
> 
> Thanks for your reply!!

how to add another layer on top of the key and value spans for binary classification? we need add numbers of keys binary classification???
