### ISSUE TITLE
Segmentation Fault Core dump

### ISSUE THREAD

**Issue by jaytsien** [microsoft/unilm#29]
After  installing the environment，I run the run_seq2seq.py. When I load the model,Segmentation Fault Core dump occurs. My environment is pytorch 1.1.0, cuda 10.1, torch-vision 0.3.0. so why the core dump occurs?

**Comment by donglixp** [comment]
Hi @jaytsien ,

Could the docker (https://github.com/microsoft/unilm#docker) successfully run the program?

**Comment by jaytsien** [comment]
I have no authority to install docker, my colleague also meet this problem. Can you show the environment requirements?

**Comment by donglixp** [comment]
https://hub.docker.com/layers/pytorch/pytorch/1.1.0-cuda10.0-cudnn7.5-devel/images/sha256-1be771bff6d18ede7d98c171c577ae8fcbaf6f53b59a3e5fe5cee9e36e188fbc
