### ISSUE TITLE
unilMv2 for question generation

### ISSUE THREAD

**Issue by liyang1127** [microsoft/unilm#292]
thanks for your greate creation。i want to learn where i can got the source code for uniLM v2。i  want to test it in QG。thanks

**Comment by liyang1127** [comment]
in Chinese data, whether the qg for uniLM v2 source code can be open?

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/s2s-ft#example-cnn--daily-mail-with-unilm12-base-uncased

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/minilm#question-generation---squad
