### ISSUE TITLE
SROIE results

### ISSUE THREAD

**Issue by juvebogdan** [microsoft/unilm#293]
Hello,

I don't know if this is the right place to ask this question but I am a bit confused why layoutlm achieves good results on SROIE. In fact I am not sure how even just BERT makes to 91%. These models are pretrained on some large corpus but sroie dataset contains some pretty meaningless text. Names of companies and some weird addresses. There is no context in that text. What is that these models learn in a dataset such as SROIE? Layoutlm uses bounding boxes with positions so that helps but what about BERT? My intuition would suggest results would be way worse than 91% and still it manages to work well.

Thank you

**Comment by ruifcruz** [comment]
Hi @juvebogdan,

I also made that question to myself when I started studying layoutlm. My thoughts is that the fields the model classifies may have a strong 1D relation. For example, it' expected that the total amount comes right after "Total" or "Amount" words. It is also expectable that dates have similar structures (dd-mm-yyyy, yyyy/mm/dd, etc). About the company name and address, I'd say the fact that they usually come first (and addresses also have a similar structure, where the city name is probably repeated many times) also has a strong influence. 

You can grab all those features with Bert. Of course 2D features provide better results (and the authors show that), but maybe 1D positions are already influencing a lot the quality of the model.

Best

**Comment by monuminu** [comment]
totally agree with @ruifcruz
