### ISSUE TITLE
Missing dependecy version specification for LayoutLM run_seq_labeling: transformers

### ISSUE THREAD

**Issue by gongliyu** [microsoft/unilm#294]
Which version fo the "transformers" package should I install to run "run_seq_labeling.py" example? I use the latest version installed from pypi, but got the following error:

ModuleNotFoundError: No module named 'transformers.modeling_bert'

**Comment by aritzLizoain** [comment]
Hi,

I'm having the same issue. Which version should we use?

Thanks!

**Comment by tengerye** [comment]
One way you can do is replacing `BertLayerNorm` with `nn.LayerNorm`
