### ISSUE TITLE
How to save a fine-tuned model

### ISSUE THREAD

**Issue by aritzLizoain** [microsoft/unilm#301]
Hi!

I am fine-tuning LayoutLM and I would like to know how should the fine-tuned model be saved and loaded in order to use it for inference in the future.

I load the model that I am fine-tuning in the following way: 
`model = LayoutLMForTokenClassification.from_pretrained("microsoft/layoutlm-large-uncased", num_labels=num_labels)`

I don't see any files (weights, metrics, etc.) created after the model is fine-tuned.

Thanks in advance!

**Comment by KaiserW** [comment]
After training:
`torch.save(model.state_dict(), '<model path>')`

For inference:
```
model = LayoutLMForTokenClassification.from_pretrained("microsoft/layoutlm-base-uncased",
                                                                                                num_labels=num_labels)
model.load_state_dict(torch.load("<model path>"))
```
