### ISSUE TITLE
Positional embedding: shape [1000,...] in paper vs [1024,...] in code

### ISSUE THREAD

**Issue by fredo838** [microsoft/unilm#304]
In the paper you rescale the bboxes to `[0,1000]`
 ```
Considering that
the document layout may vary in different page size, we scale the
actual coordinate to a “virtual” coordinate: the actual coordinate is
scaled to have a value from 0 to 1,000.
```
but the positional embedding layers are of size `[1024,...]` when I load the pre trained weights.
Are the `24` last dimensions just unused? Or did you actually pre-train by rescaling to `1024`?

**Comment by wolfshow** [comment]
The last dimensions are unused.
