### ISSUE TITLE
Can I have the pre-training code for LayoutLM2?

### ISSUE THREAD

**Issue by runorz** [microsoft/unilm#307]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): LayoutLM
Hi. Thanks for your great work on LayoutLMv2.

I am trying to do some experiment on LayoutLMv2 especially in the pre-trainning stage, so I wonder if it is possible to have the pre-training code?

**Comment by wolfshow** [comment]
Duplicate of #279
