### ISSUE TITLE
How to start a multi-GPU training on unilmv1?

### ISSUE THREAD

**Issue by ElderWanng** [microsoft/unilm#312]
**Describe**
I am using unilm-v1
I have some GPU and how to start a multi-GPUs fine-tune with run_seq2seq.py?

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/s2s-ft

The package `s2s-ft` is easier to use with various models. You could follow the instructions to start multi-gpu jobs.

```bash
python -m torch.distributed.launch --nproc_per_node=4 run_seq2seq.py
```

**Comment by ElderWanng** [comment]
> https://github.com/microsoft/unilm/tree/master/s2s-ft
> 
> The package `s2s-ft` is easier to use with various models. You could follow the instructions to start multi-gpu jobs.
> 
> ```shell
> python -m torch.distributed.launch --nproc_per_node=4 run_seq2seq.py
> ```

Thank your light-speed reply!
