### ISSUE TITLE
MINILM Distillation Code

### ISSUE THREAD

**Issue by ShoufaChen** [microsoft/unilm#316]
Hi,
Thanks very much for these wonderful works.

I noticed that the KD implementation in MINILM can not be found.

As the main contributions in MINILM are about KD, I think it'll be much better if this part code can be released.

Similar question: https://github.com/microsoft/unilm/issues/105  https://github.com/microsoft/unilm/issues/224

Thanks.

**Comment by LiuChiachi** [comment]
Same as above.
