### ISSUE TITLE
when will layoutlmv2 be released ?

### ISSUE THREAD

**Issue by monuminu** [microsoft/unilm#318]

**Comment by RyosukeSakaguchi** [comment]
I want it to be released too!

**Comment by monuminu** [comment]
waiting

**Comment by dongxuewang-123** [comment]
waiting for a lot of time

**Comment by wolfshow** [comment]
The code and model will be released soon.

**Comment by victor-ab** [comment]
This is becoming disrespectful. Let's give the developers the time they need.
Keep asking over and over for the release won't speed it up.

**Comment by NormXU** [comment]
Guys, please stop pushing the developers so hard. They indeed need more time for an awesome release. Please take your time.

**Comment by wolfshow** [comment]
The LayoutLMv2 model and code has been released at https://github.com/microsoft/unilm/tree/master/layoutlmv2
