### ISSUE TITLE
Inference problem LayoutLMv2 (and fix proposition)

### ISSUE THREAD

**Issue by alexmt-scale** [microsoft/unilm#321]
On the new LayoutLMv2 model, I encountered a problem while doing inference on a private dataset:
That line ((https://github.com/microsoft/unilm/blob/563ae17d661bbcb3b456f12549b037d80c843c39/layoutlmv2/src/layoutlm/modeling/layoutlmv2/modeling_layoutlmv2.py#L849))
sometimes returns `ValueError: too many values to unpack (expected 2)` 

This is because it assumes that `outputs[0].size(1) <= 2 * input_ids.size(1)` which I believe is not always true (e.g. when there is almost no text in a page).

A very simple fix is to replace that line by: 
`sequence_output = outputs[0][:, :input_ids.size(1)]`
`image_output = outputs[0][:, input_ids.size(1):]`

Hopefully that helps, thanks a lot for releasing your model!

**Comment by ranpox** [comment]
Fixed. Thanks!
