### ISSUE TITLE
Tagging Scheme used in LayoutLMv2 NER - FUNSD dataset

### ISSUE THREAD

**Issue by sreejith3534** [microsoft/unilm#324]
Model I am using (UniLM, MiniLM, LayoutLM ...): LayoutLMv2

Unlike LayoutLM which uses B,I,O,E,S tagging here in LayoutLMv2 it has only used B,I,O tagging for model training. Is there any particular reason for going by this approach as I guess including E and S could have improved the model performance as it could have included much more information as to where are the words ending there position and if it is single word(S tag) or multiple, these sort of information would have further improved model accuracy.
What's your take on this?

**Comment by wolfshow** [comment]
@sreejith3534 LayoutLMv2 is currently using BIO tagging, but you may compare different tagging schemes for downstream tasks.

**Comment by ron4u1998** [comment]
@sreejith3534  is there any open-source tool for BIOES tagging for layoutlmv2?
