### ISSUE TITLE
Porting Layoutlm2 to Huggingface

### ISSUE THREAD

**Issue by atahmasb** [microsoft/unilm#325]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): Layoutlm2

I'd like to thank the team for open sourcing the model and the weights. I was wondering if there is a plan for porting layoutlm2 to hugging-face  like what you did with layoutlm1?

**Comment by wolfshow** [comment]
Yes, we hope the models will be integrated in to hugging face later.

**Comment by monuminu** [comment]
I am working on this . Will be ready soon .

**Comment by monuminu** [comment]
I am working on this . Will be ready soon .
