### ISSUE TITLE
“Help” I want to read the code for InfoXLM but I can’t find it

### ISSUE THREAD

**Issue by Qnlp** [microsoft/unilm#327]
**Describe**
Thank you for your interesting work. I am very interested in the code implementation of infoXLM.  I want to read this part of the code but I can’t find it?

**Comment by CZWin32768** [comment]
Thanks for your interest. We have uploaded the pretrained InfoXLM / [XLM-Align](https://github.com/CZWin32768/XLM-Align) models to huggingface. Model links: ([InfoXLM-base](https://huggingface.co/microsoft/infoxlm-base), [InfoXLM-large](https://huggingface.co/microsoft/infoxlm-large), [XLM-Align-base](https://huggingface.co/microsoft/xlm-align-base))

For the pretraining code, I have just created a new PR [here](https://github.com/microsoft/unilm/pull/377). So, you can find the pretraining code at [this page](https://github.com/microsoft/unilm/tree/master/infoxlm) soon.
