### ISSUE TITLE
How to get back the identified words from LayoutLMForTokenClassification?

### ISSUE THREAD

**Issue by karandua2016** [microsoft/unilm#328]
I am using LayoutLMForTokenClassification as described [here](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Fine_tuning_LayoutLMForTokenClassification_on_FUNSD.ipynb). In the end, the tutorial shows an annotated image with identified classes for various tokens. 
How can I get back the original words as well to be annotated along with the labels?

**Comment by karandua2016** [comment]
I tried to read the words with tokenizer.decode(input_ids).split(" ") but the tokenizer broke words into multiple tokens which it wasn't supposed to. So, I have more words/outputs/boxes that I am supposed to have.

**Comment by zecknos** [comment]
input_ids = tokenizer.convert_tokens_to_ids

> I tried to read the words with tokenizer.decode(input_ids).split(" ") but the tokenizer broke words into multiple tokens which it wasn't supposed to. So, I have more words/outputs/boxes that I am supposed to have.

Refer to this great work by @NielsRogge here https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Fine_tuning_LayoutLMForTokenClassification_on_FUNSD.ipynb 

Once you have ```input_ids``` from the tokenizer,

```
word_list = []
for id in input_ids.squeeze().tolist():
    word_list.append(tokenizer.decode([id])

word_list1 = ' '.join([x for x in word_list if x!='[PAD]' and x!='[CLS]' and x!='[SEP]'])
text = word_list.replace(" ##","")
```

**Comment by dcyoung** [comment]
I modified the dataset code to include and propagate a `sample_id`. This id can be used to aggregate and visualize results at a word level for each original sample:

```bash
if training_args.do_predict:
        logger.info("*** Predict ***")

        predictions, labels, metrics = trainer.predict(test_dataset)
        predictions = np.argmax(predictions, axis=2)

        trainer.log_metrics("test", metrics)
        trainer.save_metrics("test", metrics)

        if trainer.is_world_process_zero():
            inference_results_by_sample_id = (
                {}
            )  # these will be world level... one result for each original dataset sample. If large enough, each dataset sample is actually split into multiple inference inputs. These results concatenate the results on all inference inputs for the same sample.
            named_token_preds = [
                [label_list[p] for p in prediction] for prediction in predictions
            ]
            for token_preds, example in zip(named_token_preds, test_dataset):
                word_level_predictions = (
                    []
                )  # let's turn them into word level predictions
                final_boxes = []
                for id, token_pred, box in zip(
                    example["input_ids"], token_preds, example["bbox"]
                ):
                    if (tokenizer.decode([id]).startswith("##")) or (
                        id
                        in [
                            tokenizer.cls_token_id,
                            tokenizer.sep_token_id,
                            tokenizer.pad_token_id,
                        ]
                    ):
                        # skip prediction + bounding box
                        continue
                    else:
                        word_level_predictions.append(token_pred)
                        final_boxes.append(box)

                sample_id = example["sample_id"]
                if sample_id not in inference_results_by_sample_id:
                    inference_results_by_sample_id[sample_id] = {
                        "sample_id": sample_id,
                        "image_path": example["image_path"],
                        "word_level_predictions": [],
                    }
                inference_results_by_sample_id[sample_id]["word_level_predictions"] += [
                    {
                        "label": pred_word_label,
                        "bbox_norm": [1.0 * v / 1000.0 for v in final_box],
                    }
                    for pred_word_label, final_box in zip(
                        word_level_predictions, final_boxes
                    )
                ]
```

**Comment by Momentum-TN** [comment]
I am facing the same problem. I tried to add the words as tokens using `tokenizer.add_tokens(word)` but the classification went totally wrong.

I used also @NielsRogge code for deleting special tokens but the number of predictions is still greater than the words

**Comment by dcyoung** [comment]
> I am facing the same problem when making inference. I tried to add the words as tokens using `tokenizer.add_tokens(word)` but the classification went totally wrong.
> 
> I used also @NielsRogge code for deleting special tokens but the number of predictions is still greater than the words

not entirely sure what process you're referring to, but the model is making predictions at a token level... rather than a word level. Beyond accounting for "special" tokens (cls_token, sep_token, pad_token), you'll also need to account for the sub-word tokens the tokenizer may create during tokenization. 

A visual example: http://jalammar.github.io/images/distilBERT/bert-distilbert-tokenization-1.png

I don't know if there is a more efficient method to identify these sub-word tokens, but all trailing sub-word tokens seem to start with "##". So to identify these tokens, I'm using: 
```python
tokenizer.decode([id]).startswith("##")
```

**Comment by Momentum-TN** [comment]
I am asking if there is anyway to pass from token level predictions to word level predictions. (Maybe by combining a all the token predictions together or something else)

**Comment by dcyoung** [comment]
Hmmm. Perhaps I misunderstand your goals, but the snippet I posted above iterates over the token level predictions to yield word level predictions. It does this by noting the pred from the first token of a word as the pred for the word, and ignoring preds for any subsequent wordpieces. For most applications I think this suffices, given NER tags are annotated at the word level... and there shouldn't be a pred change between word pieces.   

If you are concerned about the assumptions made in that process, perhaps you could use the "mode" of the predicted tags among the pieces of a word, coupled with some simple tie breaker logic.

**Comment by Momentum-TN** [comment]
> 
> 
> Hmmm. Perhaps I misunderstand your goals, but the snippet I posted above iterates over the token level predictions to yield word level predictions. It does this by noting the pred from the first token of a word as the pred for the word, and ignoring preds for any subsequent wordpieces. For most applications I think this suffices, given NER tags are annotated at the word level... and there shouldn't be a pred change between word pieces.

Thank you for the explanation. But, if you have ,for example, the word `"python"`   tokenized as `["py","th","on"]`, it will be considered as 3 words as the `##` doesn't exist. Is there any way to circumvent this problem?

>
> 
> If you are concerned about the assumptions made in that process, perhaps you could use the "mode" of the predicted tags among the pieces of a word, coupled with some simple tie breaker logic.

Could you please explain more? I did not understand.

**Comment by dcyoung** [comment]
> the word `"python"` tokenized as `["py","th","on"]`, it will be considered as 3 words as the `##` doesn't exist

I'm operating under the assumption that all trailing pieces of a word would have the "##" prefix. Based on [this link](https://huggingface.co/transformers/tokenizer_summary.html) which states: 

> Consequently, the tokenizer splits "gpu" into known subwords: ["gp" and "##u"]. "##" means that the rest of the token should be attached to the previous one, without space (for decoding or reversal of the tokenization).

If word pieces do not follow this patter, then i do not know how to reconstruct word level predictions.
