### ISSUE TITLE
Empty predicted sequences being generated. 

### ISSUE THREAD

**Issue by DhanshreeA** [microsoft/unilm#33]
I have a very limited data set- 225 samples. The task is similar to Gigaword headline generation. The statistics for my source and target sequences look like this: 

**Source:**
(After BERT tokenizer)
- Max token length: 380 
- Min token length: 5
- Average token length: 97.53

**Target:**
(After BERT tokenizer)
- Max token length : 85
- Min token length: 5
- Average token length: 29.8

I used an 80-20 split and trained on 180 samples and tested on 45. I tried running decoding with different values for `max_tgt_length`, and got the following results:
- 40 tokens : output sequences generated for 37 samples out of 45.
- 60 tokens :  output sequences generated for 35 samples.
- 100 tokens: output sequences generated for 34 samples.

What's happening here and what is a good work around given the variations in my data?

**Comment by donglixp** [comment]
If your dataset is similar to gigaword, you could try to first fine-tune the model on a subset of gigaword, and then fine-tune the obtained checkpoint on your data.

**Comment by donglixp** [comment]
The flag `--min_len 1` can also be used for `python biunilm/decode_seq2seq.py` to disable empty outputs.

**Comment by DhanshreeA** [comment]
Thanks @donglixp this worked!
