### ISSUE TITLE
How to load Pre-trained model

### ISSUE THREAD

**Issue by VisheshKaushik** [microsoft/unilm#330]
How to get the pre-trained LayoutLMv2 model? Is it's code publicly available ?

**Comment by ranpox** [comment]
Yes, we show the pre-trained model in [this](https://github.com/microsoft/unilm/tree/master/layoutlmv2#models) section. If you use the script in [the fine-tuning example](https://github.com/microsoft/unilm/tree/master/layoutlmft/examples), it will automatically download and load the pre-trained model.
