### ISSUE TITLE
LayoutLMv2 for CORD dataset

### ISSUE THREAD

**Issue by tanay2001** [microsoft/unilm#333]
Hi, 

My custom dataset resembles the CORD dataset used in the paper , I am trying to fine tune it but can't find the exact code/approach used for fine tuning  , the paper doesn't mention any information in the supplementary section, I would appreciate your help if someone could shed some light on this

Thanks

**Comment by wolfshow** [comment]
@tanay2001 you may directly use the script for fine-tuning FUNSD
