### ISSUE TITLE
using MinLM s2s_ft core dump when l load the model

### ISSUE THREAD

**Issue by lonelydancer** [microsoft/unilm#338]
**Describe the bug**
Model I am using MiniLM in s2s_ft core dump

The problem arises when using:
# path of training data
TRAIN_FILE=data/xsum.train.json
# folder used to save fine-tuned checkpoints
OUTPUT_DIR=./checkpoints/
# folder used to cache package dependencies
CACHE_DIR=./transformer_package_cache

export CUDA_VISIBLE_DEVICES=2
#,3
python run_seq2seq.py \
                                   --train_file ${TRAIN_FILE} --output_dir ${OUTPUT_DIR} \
                                   --model_type minilm --model_name_or_path minilm-l12-h384-uncased \
                                   --do_lower_case --fp16 --fp16_opt_level O2 --max_source_seq_length 464 --max_target_seq_length 48 \
                                   --per_gpu_train_batch_size 16 --gradient_accumulation_steps 1 \
                                   --learning_rate 7e-5 --num_warmup_steps 500 --num_training_steps 32000 --cache_dir ${CACHE_DIR}
![image](https://user-images.githubusercontent.com/548443/121478373-8a591400-c9fb-11eb-9715-b1660ddbc2ca.png)

**To Reproduce**
1.  run the scripts above

- Platform:
- Python version:Python 3.6.9
- PyTorch version (GPU?):1.2.0
- transformes version=2.9.1

**Comment by addf400** [comment]
@lonelydancer It may be the problem caused by the version of sentencepiece, you can try
```bash
pip install sentencepiece==0.1.85
```

**Comment by lonelydancer** [comment]
it works ! thank you
