### ISSUE TITLE
How is the relation extraction done for FUNSD/XFUN dataset? 

### ISSUE THREAD

**Issue by ravilkashyap** [microsoft/unilm#339]
I went through the papers for both LayoutLM/v2 and LayoutXLM. I don't understand how the relation extraction part of the FUNSD/XFUN dataset is tackled. Can someone please guide me on how to go about it? What method can be used to train the model for relation extraction?

**Comment by stjaco** [comment]
you have an example here:
https://github.com/microsoft/unilm/blob/master/layoutlmft/examples/run_xfun_re.py
