### ISSUE TITLE
Regarding Mask Matrix M

### ISSUE THREAD

**Issue by tahmedge** [microsoft/unilm#34]
I am a bit confused regarding the implementation of equation 3 of the paper where the Mask Matrix M was used. Can you please describe, how is the Mask Matrix M implemented in the code and in which portion of the code equation 3 was used?

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/src/biunilm/seq2seq_loader.py#L271

**Comment by tahmedge** [comment]
Thanks. :)

**Comment by tahmedge** [comment]
Hi, I need one more help: Can you please mention in which portion of the code equation 3 was used?

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/src/pytorch_pretrained_bert/modeling.py#L355

**Comment by tahmedge** [comment]
Thanks again.
