### ISSUE TITLE
KeyError: 'layoutlmv2' in AutoTokenizer

### ISSUE THREAD

**Issue by sindhuattaiger** [microsoft/unilm#340]
I get key error, when I try to run `AutoTokenizer.from_pretrained("microsoft/layoutlmv2-base-uncased")`
same is the case even when I download the files to local and run the above with path to the config folder

I also do not find layoutlmv2 in the AutoTokenizer.from_pretrained Documentation.

Any leads on how to use it the right way would be helpful

**Comment by nkrot** [comment]
have you had a look at the script: `https://github.com/microsoft/unilm/blob/master/layoutlmft/examples/run_funsd.py`

It used `AutoTokenizer` as you describe and the script works.

**Comment by sindhuattaiger** [comment]
The script at `examples/run_funsd.py` works.
However, if I only import `AutoTokenizer` from `transformers` and run `AutoTokenizer.from_pretrained("microsoft/layoutlmv2-base-uncased")` it does not work.

Is there something that I am missing here?

ps: I have also installed all dependencies from `layoutlmft`

**Comment by nkrot** [comment]
> I also do not find layoutlmv2 in the AutoTokenizer.from_pretrained Documentation

this is because it is not in transformers but in layoutlm. the latter adds new symbols in `layoutlmft/layoutlmft/__init__.py`.

The snippet below worked for me. Well, at least it did not produce an error. And I did not try to run the tokenizer itself :)

```
import layoutlmft
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('microsoft/layoutlmv2-base-uncased')
```

I have to say, the library is kind of shit in terms of documentation. I am learning it by trial and error, by disassembling the code. the script `run_funsd.py` and grep are very handy :)

Good luck in your exploration!

**Comment by littletomatodonkey** [comment]
> > I also do not find layoutlmv2 in the AutoTokenizer.from_pretrained Documentation
> 
> this is because it is not in transformers but in layoutlm. the latter adds new symbols in `layoutlmft/layoutlmft/__init__.py`.
> 
> The snippet below worked for me. Well, at least it did not produce an error. And I did not try to run the tokenizer itself :)
> 
> ```
> import layoutlmft
> from transformers import AutoTokenizer
> tokenizer = AutoTokenizer.from_pretrained('microsoft/layoutlmv2-base-uncased')
> ```
> 
> I have to say, the library is kind of shit in terms of documentation. I am learning it by trial and error, by disassembling the code. the script `run_funsd.py` and grep are very handy :)
> 
> Good luck in your exploration!

Hi, i encountered the same problem, the following code does not work for me when if i do not change any source code of transformer package, could you please show more details of your solution? Thanks!

```shell
import layoutlm
from transformers import AutoTokenizer, AutoModel
# the model is downloaded from hugging-face
tokenizer = AutoTokenizer.from_pretrained("layoutlm-base-uncased", do_lower_case=True)
print(tokenizer)
```

**Comment by nkrot** [comment]
@littletomatodonkey , shouldnt it be `'microsoft/layoutlmv2-base-uncased'`?

**Comment by littletomatodonkey** [comment]
> @littletomatodonkey , shouldnt it be `'microsoft/layoutlmv2-base-uncased'`?

Thanks for youre reply. The demo i run is layoutlmv1`, and so `layoutlm-base-uncased` is downloaded for the case.

**Comment by NielsRogge** [comment]
Hi @nkrot, I am encountering a similar issue, your solution doesn't seem to work for me.

I've made a Google Colab that reproduced it: https://colab.research.google.com/drive/1g-57x22Oh83h3wOt-n1Id5vPQyTguJ5T?usp=sharing

I've made it editable, so feel free to edit!

**Comment by nkrot** [comment]
@NielsRogge ,

1) there is an example of how to initialize `AutoModelForTokenClassification` in `run_funsd.py`. There are more parameters passed together with `model_name_or_path`. I know my short comment does not answer your question but ... (see 2)

2) I cannot edit the notebook. I wanted to leave a comment that can be wrong and I do not want to pollute this thread with inaccurate information.

**Comment by NielsRogge** [comment]
Hi @nkrot, thanks for the quick reply. Apologies, the notebook was indeed not set to be editable.

I figured it out, here's a notebook that works: https://colab.research.google.com/drive/1g-57x22Oh83h3wOt-n1Id5vPQyTguJ5T?usp=sharing

**Comment by nkrot** [comment]
@NielsRogge , 
I have seen in your notebook that you are receiving message `You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.` I insist that you look into `run_funsd.py` that has an example of training :)

**Comment by NielsRogge** [comment]
Yes I know, the model that I'm initializing has a random initialized classification head. I just wanted to test a forward pass of the model.

**Comment by sindhuattaiger** [comment]
> > I also do not find layoutlmv2 in the AutoTokenizer.from_pretrained Documentation
> 
> this is because it is not in transformers but in layoutlm. the latter adds new symbols in `layoutlmft/layoutlmft/__init__.py`.
> 
> The snippet below worked for me. Well, at least it did not produce an error. And I did not try to run the tokenizer itself :)
> 
> ```
> import layoutlmft
> from transformers import AutoTokenizer
> tokenizer = AutoTokenizer.from_pretrained('microsoft/layoutlmv2-base-uncased')
> ```
> 
> I have to say, the library is kind of shit in terms of documentation. I am learning it by trial and error, by disassembling the code. the script `run_funsd.py` and grep are very handy :)
> 
> Good luck in your exploration!

This solved the issue
