### ISSUE TITLE
deployment in the real industry environment

### ISSUE THREAD

**Issue by lonelydancer** [microsoft/unilm#342]
**Describe the bug**
Model I am using UniLM,

The problem arises when using:
In the real word， is there any solution for the deployment in T4 GPU.
The pytorch code is too slow for the industry environment.
do i need to develop the inference program using TensorRT ?

**Comment by gitnlp** [comment]
You may try [MiniLM models](https://github.com/microsoft/unilm/tree/master/minilm) which are distilled from large models using task-agnostic knowledge distillation.
