### ISSUE TITLE
Question about BEiT visual tokenizer's ground truth. Thank you very much.

### ISSUE THREAD

**Issue by guotong1988** [microsoft/unilm#344]
I am new to visual pre-training.

https://github.com/microsoft/unilm/tree/master/beit

How do the visual tokenizer's ground truth tokens come from?

**Comment by donglixp** [comment]
Hi @guotong1988 , please refer to Sec 2.1.2 of https://arxiv.org/pdf/2106.08254.pdf

**Comment by donglixp** [comment]
released at https://github.com/microsoft/unilm/tree/master/beit

**Comment by guotong1988** [comment]
Thank you.
