### ISSUE TITLE
A QG task problem

### ISSUE THREAD

**Issue by kailiwu** [microsoft/unilm#35]
Hi, I have a problem with the QG task when I evaluate the performance. I use your released evaluation scripts can achieve your performance. But, I use https://github.com/xinyadu/nqg. 

![image](https://user-images.githubusercontent.com/15731867/69636149-ed40bf80-1090-11ea-8410-1abcf10d963c.png)

Why I get this result?
Thank you for your help.

**Comment by nyanyanya** [comment]
Have you tried to lower case the output of our model? The reference provided by xinyadu is lower-cased and the output of our model is cased.

**Comment by kailiwu** [comment]
@nyanyanya My problem is solved. Thank for your help again.
