### ISSUE TITLE
Can LayoutLM be used for commercial purpose?

### ISSUE THREAD

**Issue by rohitchoudhary-magicfinserv** [microsoft/unilm#352]
**Can LayoutLM be used for commercial purposes? And how LayoutLM license is different than other versions of LayoutLM (LayoutLMv2, LayoutLMFT, layoutXLM)
Will license hold for both train model and code. 
Or one can use a trained model provide by other sources such as Docbank for commercial purposes.

I have noticed that the LayoutLM folder is showing deprecated. What does that mean in terms of use and license?
**

Model I am using (LayoutLM):

**Comment by wolfshow** [comment]
@rohitchoudhary-magicfinserv Only LayoutLMv1 can be used for commercial purpose, while others are currently under the CC-BY-NC-SA license.

**Comment by rohitchoudhary-magicfinserv** [comment]
Does LayoutLMv1 is deprecated?

**Comment by wolfshow** [comment]
> Does LayoutLMv1 is deprecated?

Only the previous fine-tuning code is deprecated as we move to layoutlmft, the model is not deprecated

**Comment by aa-morgan** [comment]
The license on the `layoutlmv2-base-uncased` model hosted on [HuggingFace](https://huggingface.co/microsoft/layoutlmv2-base-uncased) is `cc-by-sa-4.0`. Does this mean that this model can be used commercially? Do you know why it differs from this GitHub repo?
Thanks,
Alex

**Comment by brandenkmurray** [comment]
It would be great to get some additional clarification on the licensing. I'm finding different licensing in different places and it is confusing.

- **LayoutLMv1** https://github.com/microsoft/unilm/tree/master/layoutlm
"This project is licensed under the license found in the LICENSE file in the root directory of this source tree."
I take this to mean this falls under the MIT License file that is in the root of the `unilm` repo.

- **LayoutLMv2** https://github.com/microsoft/unilm/tree/master/layoutlmv2
"The content of this project itself is licensed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
There is no code in this portion of the repo, so not sure exactly what this applies to besides the README.

- **LayoutLMFT** https://github.com/microsoft/unilm/tree/master/layoutlmft
"The content of this project itself is licensed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)"
None of this can be used for commerical use.

- **Hugginface LayoutLMv2** https://github.com/huggingface/transformers/tree/master/src/transformers/models/layoutlmv2
Each of the files here has an Apache 2.0 License at the top. These files look nearly identical to the LayouLMv2 files that are in [LayoutLMFT](https://github.com/microsoft/unilm/tree/master/layoutlmft/layoutlmft/models/layoutlmv2) but Apache 2.0 is less restrictive license that allows commerical use.

- As noted by @aa-morgan https://huggingface.co/microsoft/layoutlmv2-base-uncased is `cc-by-sa-4.0` (which would allow for commercial use).  Additionally, https://huggingface.co/microsoft/layoutlmv2-large-uncased doesn't have a license listed at all.

So does this mean that even LayouLMv1 cannot be fine-tuned fore commercial use using this repo? Or does that only apply to LayoutLMv2?

Does this mean that the `LayouLMv2` code in `huggingface` is fine for commercial use even though the [nearly identical] code in `unilm` cannot be used for commercial use? This is what I find most confusing. Or does `huggingface` need to change the licenses in their LayouLMv2 files?

Thanks!

**Comment by colintoal** [comment]
Will the pre-trained models be made available for commercial use at some time in the future ? It severely limits the applicability and desirability of using these models to make them NC only. Is this a liability mitigation by Microsoft that will be lifted in the future or is this a decision to effectively close-source these models ?

**Comment by YedidyahD** [comment]
@wolfshow Is it possible to use the pre train model and fine tune it for commercial use? or at least just use the architecture and train the model from scratch (for commercial use)?
Thanks!

**Comment by PolinaYA** [comment]
> @rohitchoudhary-magicfinserv Only LayoutLMv1 can be used for commercial purpose, while others are currently under the CC-BY-NC-SA license.

@wolfshow, could you please clarify one more time one thing: is it okay to use code from the LayoutLMv3/2 repo for commercial purposes?

**Comment by DiddyC** [comment]
@PolinaYA -  Yes, the license has changed to MIT in both huggingface website and the original unlim repo. Have fun!

**Comment by qiaoliang6** [comment]
> 

It seems to be changed into CC BY-NC-SA again?

**Comment by nbgit10** [comment]
Using this commit LayoutLM3 was distributed with MIT license: 
https://github.com/microsoft/unilm/tree/2239a415aacfaff3af37c7d43995a4f0a9c41c04/

This might have been by accident as it switched back to CC-BY-NC-SA a few days after but it was still released with that license. Also the very first release of LayoutLM3 was released under MIT license. Again, might have been by accident but the claim that LayoutLM3 never has been available for commercial use seems to not hold up. Might be worth talking to a lawyer before using the code in a commercial setting but it could be that you can in fact use it.

**Comment by sudhitpanchal** [comment]
So can we use Layout XLM or Layout XLM 2?

**Comment by sudhitpanchal** [comment]
I came to know that layoutLM v1 is commercial available rest LayoutLMs V2,V3 are not commerical available i got this from their offical github repo

**Comment by sudhitpanchal** [comment]
> 

No you can't use LayoutLM V2/V3 for commercial purpose you can use LayoutLmV1 but that is too old not as good as V2, V3

**Comment by mllife** [comment]
@sudhitpanchal , are you sure? i think its only about model weights, if we train on our own data; it will be different weights.
@wolfshow can you confirm it?

**Comment by sudhitpanchal** [comment]
> I read that in the documentation and even asked in Public python off-topic groups, Still would work on it if it seems to be legal.

**Comment by sumanth9977** [comment]
Hi, can we buy Layoutlmv3 model license for commercial use?
