### ISSUE TITLE
How can I start using BEIT？

### ISSUE THREAD

**Issue by Pter61** [microsoft/unilm#353]
I am very interested in your outstanding work after reading BEIT: BERT Pre-Training of Image Transformers. 
I want to learn your method, but I don’t know how to install BEIT, nor can I find the code and pre-training model in your directory. 

Could you tell me where are the codes and pre-trained models of BEIT? Is it not released? When will it be released? Thank you!

**Comment by jizxny** [comment]
@donglixp Hi, will the code of BEIT be released recently?

**Comment by donglixp** [comment]
Our plan is to release the code and pretrained checkpoints in the next week.

**Comment by donglixp** [comment]
released at https://github.com/microsoft/unilm/tree/master/beit
