### ISSUE TITLE
F1-score is not convincing when i finetune the model on the `seq_labeling` task.

### ISSUE THREAD

**Issue by littletomatodonkey** [microsoft/unilm#355]
Hi, thanks for your excellent job!

I train model with this [tutorial](https://github.com/microsoft/unilm/blob/master/layoutlm/deprecated/README.md). ON the seq_labeling task, the final f1-score is just 0.202, which seems too low compared with that in the thesis.

There are 2 differences.
* Here, i use the `test_*.txt` for evaluation rather than `dev_*.txt`.
* I reduce the lr from `5e-5` to `1.25e-5` because i just train the model using single gpu card. However, even if the lr is not changed, the final f1-score is also `~22%`

The shell i run is as follows.

```shell
export CUDA_VISIBLE_DEVICES=0
python3.7 run_seq_labeling.py  --data_dir data \
                            --model_type layoutlm \
                            --model_name_or_path ./layoutlm-base-uncased/ \
                            --do_lower_case \
                            --max_seq_length 512 \
                            --do_train \
                            --num_train_epochs 100.0 \
                            --logging_steps 10 \
                            --save_steps -1 \
                            --output_dir ./output \
                            --overwrite_output_dir \
                            --labels data/labels.txt \
                            --learning_rate 1.25e-5 \
                            --per_gpu_train_batch_size 16 \
                            --per_gpu_eval_batch_size 16 \
                            --evaluate_during_training \
                            --fp16
```

I uploaded the `train.log`, could you please help me see what the problem is? Thanks!

[train.log](https://github.com/microsoft/unilm/files/6759719/train.log)

**Comment by wolfshow** [comment]
This is a good tutorial for reference.

https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLM/Fine_tuning_LayoutLMForTokenClassification_on_FUNSD.ipynb
