### ISSUE TITLE
Quick question about BEIT paper

### ISSUE THREAD

**Issue by greeneggsandyaml** [microsoft/unilm#358]
Hello,

Thank you for your great work on the BEIT paper. I had a quick question. In the paper, you say that you tokenize the image from 224px to 14x14 image patches using the DALL-E VQ-VAE. However, the DALL-E tokenizer only downsamples 8x, meaning that you would get 28x28 image patches. Do you downsample the image to 112px before passing it through the DALL-E VQ-VAE? 

Thank you for your assistance,

**Comment by greeneggsandyaml** [comment]
Thanks for the quick response. That makes sense -- it's what I figured and I just wanted to confirm. 

I'll post again if I have more questions about the repo, but for now I'm closing this issue. 

Thanks again!

**Comment by donglixp** [comment]
released at https://github.com/microsoft/unilm/tree/master/beit
