### ISSUE TITLE
BEIT on ImageNet1K

### ISSUE THREAD

**Issue by Vickeyhw** [microsoft/unilm#364]
Hello,  @donglixp @addf400 

Thank you for your great work and open-source code on BEIT. I've found that your published pre-trained models and logs are based on the ImageNet22K. And you know, it's hard to finish one experiment with limited computation resource on 22K dataset.

So, can you provide more details, like pre-trained models, logs, training hyper-parameters and others, on ImageNet 1K dataset, as you mentioned in your BEIT paper?

Thank u very much!

**Comment by donglixp** [comment]
Hi @Vickeyhw ,

Sure, we can add the instructions for pre-training on INet-1k.

**Comment by Vickeyhw** [comment]
That would be great and look forward to your update. 
Thank u~

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/beit#example-pre-training-beit-base-on-imagenet-1k

**Comment by donglixp** [comment]
@Vickeyhw The instructions have been added.

**Comment by normster** [comment]
Hi @donglixp,

Would it be possible to share BeiT weights pretrained on ImageNet-1K?

Thanks!
