### ISSUE TITLE
[CLS] and [SEP] tokens not added in LAYOUTXLM

### ISSUE THREAD

**Issue by lumliolum** [microsoft/unilm#371]
So while running the code `run_xfun_ser.py` in the `layoutlmft/examples` folder using this command

```bash
python run_xfun_ser.py --model_name_or_path microsoft/layoutxlm-base --output_dir test-ner/ --do_train --do_eval --lang fr --max_steps 1000 --warmup_ratio 0.1
```

The py file uses the `LayoutXLMTokenClassification` model. I have casually seen the inputs the model gets. I checked in the `input_ids` the model gets and this is what it looks like
![image](https://user-images.githubusercontent.com/28287182/127456220-43eecce6-1950-4479-a4cb-3d07c5ea2db6.png)

The shape of input_ids is `(8, 512)` where 8 represents batch size used. After filtering 1 (this is the id of pad token) from `input_ids`, the remaining ids are stored in the variable name `mkju`.

Now you can see the code didn't add `[CLS]` and `[SEP]` token ids (which are 0 and 2 respectively). Can I know why this is the case? (I didn't see any mention of this in layoutxlm paper).
From Fig 2 in the `layoutlm v2` paper, I can see that `[CLS]` and `[SEP]` have been shown.

**Comment by wolfshow** [comment]
The reason is that we did not run the classificaiton task using LayoutXLM. You may add [CLS] and [SEP] tokens if you have tasks using these.
