### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by DaraOrange** [microsoft/unilm#372]
Hello! Can you explain how to train BeIT on custom dataset? The format is segmentation masks.

**Comment by donglixp** [comment]
Hi @DaraOrange , the instruction of BEiT pre-training can be found at https://github.com/microsoft/unilm/tree/master/beit#example-pre-training-beit-base-on-imagenet-22k

**Comment by DaraOrange** [comment]
But it is instruction for image classification, not semantic segmentation
