### ISSUE TITLE
error while training

### ISSUE THREAD

**Issue by DivyaWadehra** [microsoft/unilm#38]
ModuleNotFoundError: No module named 'pytorch_pretrained_bert'

**Comment by ranjeetds** [comment]
@DivyaWadehra Copy the folder contained in src directory named 'pytorch_pretrained_bert' to 'biunilm'.

**Comment by donglixp** [comment]
@DivyaWadehra 

```bash
cd ~/code/unilm/src
pip install --user --editable .
```

**Comment by DivyaWadehra** [comment]
ModuleNotFoundError: No module named 'apex.optimizers'

and I am running the code on CPU

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/issues/23

**Comment by DivyaWadehra** [comment]
I am ruuning code for question generation, that's for summarization
I am not using fp flag

**Comment by donglixp** [comment]
The code change should be the same for both qg and summ in order to run the program on cpus.

**Comment by DivyaWadehra** [comment]
By default it is taking fp into consideration how to disable the use of it while training QG model

**Comment by donglixp** [comment]
In order to run the code on CPU, we can remove the `--fp16` and `--amp` flags. Moreover, we need to delete `.cuda()`, and `apex` package usage.

**Comment by DivyaWadehra** [comment]
But in the script itself we are not using these flags, can you generate a code for cpu?

**Comment by DivyaWadehra** [comment]
Hi
I am getting this error, can you help?

ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
