### ISSUE TITLE
LayoutXLM - pretrained model for FUNSD

### ISSUE THREAD

**Issue by sindhuattaiger** [microsoft/unilm#381]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): LayoutXLM

I cannot find pretrained LayoutXLM **Relation Extraction** model for **FUNSD** dataset. It is only available for XFUN

**Comment by wolfshow** [comment]
The pre-trained LayoutXLM model can be used for both entity recognition and relation extraction. You may just fine-tuned the LayoutXLM on FUNSD.
