### ISSUE TITLE
A question about LayoutLMv2 QG data

### ISSUE THREAD

**Issue by QimingPeng** [microsoft/unilm#385]
I found a DocVQA trick in LayoutLMV2 paper.
"The QG dataset contains almost one million question-answer pairs generated by a generation model trained on the SQuAD dataset."

The DocVQA dataset only has 13 thousands documents, It seems difficult to generate one million question-answer pairs.
Which data source is the QG data generated from?

**Comment by wolfshow** [comment]
@QimingPeng The QG data is generated from SQuAD, not DocVQA.

**Comment by QimingPeng** [comment]
@wolfshow But the SQuAD doesn't have images, Is there no image input when training QG data?

**Comment by wolfshow** [comment]
@QimingPeng actually you can train the model without images with QG data, followed by real data from DocVQA.

**Comment by QimingPeng** [comment]
@wolfshow ok, thanks for your reply.
