### ISSUE TITLE
how to set drop path rate for different beit models and input resolution?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [microsoft/unilm#386]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...):

**Comment by donglixp** [comment]
Hi @zimenglan-sysu-512 , the drop path rate can be set by the argument `--drop_path`.

**Comment by zimenglan-sysu-512** [comment]
> Hi @zimenglan-sysu-512 , the drop path rate can be set by the argument `--drop_path`.

i mean that how to set the value for argument `--drop_path`.

**Comment by donglixp** [comment]
A general rule is that the deeper TRMs usually use larger values. You could refer to https://arxiv.org/abs/1603.09382 and https://arxiv.org/pdf/1909.11556.pdf for more details.
