### ISSUE TITLE
pad position embedding in layout LM

### ISSUE THREAD

**Issue by allanj** [microsoft/unilm#390]
Model: Layout LM

What's the coordinates of a padded/special token, for example, for `<CLS>, <PAD>`? I think we need to know that to set the coordinates for these tokens.

I couldn't find it on the paper either.

**Comment by ranpox** [comment]
We use [0, 0, 0, 0] to pad the bbox sequence. https://github.com/microsoft/unilm/blob/99a1338fbf7197d8fba1b9ddf2eb6be8eac8658a/layoutlmft/examples/run_funsd.py#L193
