### ISSUE TITLE
Question about DeltaLM's vocabulary size.

### ISSUE THREAD

**Issue by wuleizi** [microsoft/unilm#392]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...) DeltaLM:

I used the spm model, dicts and checkpoint wich is given in the repo and followed the steps. But when I started to fine-tune in my data, I met the vocabulary size issue. Just like blow:

  File "~/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for XLMTDecoderVariantModel:
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([250104, 1024]) from checkpoint, the shape in current model is torch.Size([250008, 1024]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([250104, 1024]) from checkpoint, the shape in current model is torch.Size([250008, 1024]).

Could you kindly help check it?

Thanks,
Wuleizi

**Comment by shumingma** [comment]
Hi @wuleizi ,

Thanks for reporting the issue. This is because Deltalm contains some extra special tokens in the vocabulary. I have fixed it by automatically adjusting the vocabulary to fit in different settings (#393 ).

Thanks,
Shuming

**Comment by wuleizi** [comment]
Thanks Shuming.
