### ISSUE TITLE
Using LayoutLM for Relation Extraction on FUNSD

### ISSUE THREAD

**Issue by RishabhMaheshwary** [microsoft/unilm#394]
**Question**
Is there an implementation of LayoutLM for relation extraction on FUNSD? 
If not, what are the steps I should follow to perform relation extraction with LayoutLM.

**Comment by wolfshow** [comment]
@RishabhMaheshwary please refer to the code at https://github.com/microsoft/unilm/tree/master/layoutxlm

**Comment by RishabhMaheshwary** [comment]
@wolfshow the link https://github.com/microsoft/unilm/tree/master/layoutxlm is for finetuning on XFUND dataset. XFUND and FUNSD has different formats. Is there a script to convert or load FUNSD in XFUND format?

**Comment by RishabhMaheshwary** [comment]
Also, for the LayoutLM model only the TokenClassifiction head is available while fine-tuning, the relation extraction head is not available for LayoutLM as it is for LayoutLMv2 or LayoutXLM.

**Comment by munish0838** [comment]
> Also, for the LayoutLM model only the TokenClassifiction head is available while fine-tuning, the relation extraction head is not available for LayoutLM as it is for LayoutLMv2 or LayoutXLM.

Hi @RishabhMaheshwary, could you get through the issue and convert FUNSD to XFUND format?

**Comment by RishabhMaheshwary** [comment]
Hi, No I was unable to that. Maybe you can convert relations to question answer pairs. and finetune LayoutLM on FUNSD using [this huggingface model. ](https://huggingface.co/docs/transformers/model_doc/layoutlm#transformers.LayoutLMForQuestionAnswering)

**Comment by munish0838** [comment]
> Hi, No I was unable to that. Maybe you can convert relations to question answer pairs and finetune LayoutLM on FUNSD using [this huggingface model. ](https://huggingface.co/docs/transformers/model_doc/layoutlm#transformers.LayoutLMForQuestionAnswering)

I found this related issue, might be helpful  https://github.com/microsoft/unilm/issues/586

**Comment by Muhammad-Hamza-Jadoon** [comment]
> > Hi, No I was unable to that. Maybe you can convert relations to question answer pairs and finetune LayoutLM on FUNSD using [this huggingface model. ](https://huggingface.co/docs/transformers/model_doc/layoutlm#transformers.LayoutLMForQuestionAnswering)
> 
> I found this related issue, might be helpful #586

Hi munish. were you able to figure out the differences in funsd and xfund datasets? i am trying to finetune funsd for relation extraction
