### ISSUE TITLE
How can I unzip IIT CDIP dataset

### ISSUE THREAD

**Issue by WenmuZhou** [microsoft/unilm#395]
I downloaded the CDIP dataset from https://ir.nist.gov/cdip/  to train the LayoutLM2 model, but I don’t know how to decompress it. The data set is as follows 
![image](https://user-images.githubusercontent.com/12406017/129552739-248b4203-accd-463f-bb21-464402de1df7.png)

**Comment by ranpox** [comment]
You can unzip them with [7zip](https://www.7-zip.org/).
