### ISSUE TITLE
BEiT with smaller patch sizes

### ISSUE THREAD

**Issue by linden-li** [microsoft/unilm#396]
I tried training a ViT model with the BEiT procedure using smaller patch sizes (i.e. 8 x 8) by changing `args.second_input_size` to 224 instead of 112 - was this tried before in the experiments accompanying this behavior? The loss seems to decrease to a higher number than the default run with 16 x 16 patches.

**Comment by donglixp** [comment]
Hi @linden-li , we haven't tried the above setting. The argument `--num_mask_patches` can also be changed to keep the masking probability the same.

**Comment by xiao2mo** [comment]
> Hi @linden-li , we haven't tried the above setting. The argument `--num_mask_patches` can also be changed to keep the masking probability the same.

Hi，have u testified  the effect of mask ratio for beit.
