### ISSUE TITLE
Where can I download the dataset of IIT-CDIP?

### ISSUE THREAD

**Issue by WenmuZhou** [microsoft/unilm#397]
The download from the link https://ir.nist.gov/cdip/ is only xml information, not the original image, how can I download the  IIT-CDIP image？

**Comment by wolfshow** [comment]
The .cdr files contain the documents.

**Comment by lyc728** [comment]
> The .cdr files contain the documents.

hello  I can download the IIT-CDIP-annotations. How do images correspond to json？
<img width="571" alt="企业微信截图_17101610043571" src="https://github.com/microsoft/unilm/assets/88084847/5cd39bc0-7499-4932-a258-b9f5dc4679ad">
but I want to download the diagram corresponding to json and not the original img
<img width="707" alt="企业微信截图_171016109629" src="https://github.com/microsoft/unilm/assets/88084847/729b66ee-0eac-4ec1-860e-5834e3ba6d6a">
