### ISSUE TITLE
Customizing configuration file

### ISSUE THREAD

**Issue by tiennvuit** [microsoft/unilm#402]
I am trying the LayoutLMv2 model but I don't know how to pass a JSON file when running the command:
```
python -m torch.distributed.launch --nproc_per_node=4 examples/run_funsd.py \
        --model_name_or_path microsoft/layoutlmv2-base-uncased \
        --output_dir /tmp/test-ner \
        --do_train \
        --do_predict \
        --max_steps 1000 \
        --warmup_ratio 0.1 \
        --fp16
``` 
Could you show me how to create a configuration file or an example?

**Comment by ranpox** [comment]
Currently, the training script does not support passing training arguments as a JSON file.
