### ISSUE TITLE
About _sinkhorn_iter in XLM-Align

### ISSUE THREAD

**Issue by zhangliang-04** [microsoft/unilm#404]
**Describe**
Model I am using XLM-Align:
hello, i found that the implementation of XLM-Align define a method called `_sinkhorn_iter` at
[here](https://github.com/microsoft/unilm/blob/cafac9e97ffeec7f817abc9b8e1ddaf14339029c/infoxlm/src-infoxlm/infoxlm/tasks/xlm_align.py#L30). But it seems that it has never been called. i am not sure where and how the sinkhorn algorithm is implemented?

**Comment by CZWin32768** [comment]
Thank you for opening this issue! It seems a mistake emerged during code refactoring. I will fix it soon.

**Comment by donglixp** [comment]
@zhangliang-04 The issue has been fixed by https://github.com/microsoft/unilm/pull/413
