### ISSUE TITLE
Adding AdaLM models to the Hugging Face model hub

### ISSUE THREAD

**Issue by viswavi** [microsoft/unilm#405]
**Describe**
I read the AdaLM paper and would love to try this model for some experiments. Are there any plans to add this model to [HuggingFace's model hub](https://huggingface.co/models)? This would make it really easy for me, and other users, to use your language model (and then cite your great work 😄)

**Comment by buaahsh** [comment]
Thanks for your interest. 
We have put our AdaLM models into [HuggingFace's model hub](https://huggingface.co/cowTodd). You can use them through transformers directly.

**Comment by viswavi** [comment]
Amazing, thank you!!
