### ISSUE TITLE
When training on IIT-CDIP or RVL-CDIP with LayoutLM

### ISSUE THREAD

**Issue by TaekyungKi** [microsoft/unilm#406]
Hi. Thank you for the interesting work. Can i ask some question when training on IIT or RVL ? 
I think the number of words on each document is very diverse. Some documents include only 0~10 words (i used Tesseract as the paper said), while some documents include more than 1000 words. Did you use all IIT-CDIP data? regardless of the number of words? I think the distribution of the number of OCR is too diverse. Many OCR results are not a big problem since we can truncate it, but in case of a few OCR results, i think it gives a noise to the model, since unavoidably fill almost all tokens with padding tokens.
Can you explain your approach?

Thank you for reading.
Best.

**Comment by wolfshow** [comment]
@TaekyungKi Basically, if the lengh of the document is less than 512, we do the padding. Otherwise, we split the document into multiple segment where each of them is 512 or less.
