### ISSUE TITLE
How to create inference code for DocVQA task

### ISSUE THREAD

**Issue by tiennvcs** [microsoft/unilm#407]
I run **LayoutLMv2** for DocVQA but I don't see any **available inference file**.
How do I create inference code for the **DocVQA task**?

**Comment by dongxuewang-123** [comment]
I have the code,but I can‘t reach the score as the paper describe

**Comment by wolfshow** [comment]
@dongxuewang-123 To achieve good results in DocVQA leaderboard, you need to have good OCR results. Meanwhile, you also need to map the answers back to the OCR outputs, which is beyond the scope of this repo. So, please consider improving your own pre-processing to improve the results.

**Comment by wolfshow** [comment]
You many also find the fine-tuning code at https://github.com/anisha2102/docvqa
