### ISSUE TITLE
Some question about BEIT

### ISSUE THREAD

**Issue by pengzhiliang** [microsoft/unilm#408]
Hello, thank u for your great work again! @donglixp 

I meet some small questions when use BEIT:
1. When I changed backbone to other tranformer, I encountered loss=nan, can you give some suggestions based on previous experience? The counterpart backbone has nearly half params and MACs compared of ViT-B.
2. How many images do you use in the 21k dataset? 14M, 13M or 12M?

**Comment by donglixp** [comment]
Hi @pengzhiliang , for the second question, could you explain a bit more about the differences between the various data sizes mentioned above? (We directly use the default 21k data. I am wondering whether using the subsets would benefit the results?) Thanks!

**Comment by pengzhiliang** [comment]
Oh, I just found that the official ViT used the 12.4M imagenet21k dataset mentioned in this [issue](https://github.com/google-research/vision_transformer/issues/28#issuecomment-732890832). So I'd like to know the version of 21k you used. As the authors of ViT saied, they further processed 21k, which undoubtedly improved performance under full supervision, but I’m not sure if it’s effective in BEIT. Thank u!

**Comment by pengzhiliang** [comment]
Hi, Mr Dong~ @donglixp , I am the author of the [Conformer](https://github.com/pengzhiliang/Conformer), which is a backbone network combines vit and cnn. And recently I try to use the BEIT method to train conformer but the result is far from satisfactory. Therefore, I‘d like to know if CNN is not suitable for this agency task? Or, have you tried BEIT on CNN?

**Comment by donglixp** [comment]
> Oh, I just found that the official ViT used the 12.4M imagenet21k dataset mentioned in this [issue](https://github.com/google-research/vision_transformer/issues/28#issuecomment-732890832). So I'd like to know the version of 21k you used. As the authors of ViT saied, they further processed 21k, which undoubtedly improved performance under full supervision, but I’m not sure if it’s effective in BEIT. Thank u!

Thanks for the pointer. Similar data filtering is worth trying.

**Comment by donglixp** [comment]
> Hi, Mr/Miss Dong~ @donglixp , I am the author of the [Conformer](https://github.com/pengzhiliang/Conformer), which is a backbone network combines vit and cnn. And recently I try to use the BEIT method to train conformer but the result is far from satisfactory. Therefore, I‘d like to know if CNN is not suitable for this proxy task? Or, have you tried BEIT on CNN?

The method would be general for various backbones. The NaN issue you mentioned above would be caused by numerical instability.

**Comment by pengzhiliang** [comment]
Ok. Emm, when encountering nan, I can only continue training from the checkpoint. Thanks for reply. But I still want to know that the performance of BEIT on the CNN-based network.

**Comment by pengzhiliang** [comment]
Ok, maybe I need to try something new.  Thank you very much!
