### ISSUE TITLE
model only training for 512 words

### ISSUE THREAD

**Issue by lalitr994** [microsoft/unilm#409]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

- Platform:
- Python version:
- PyTorch version (GPU?):

**Comment by lalitr994** [comment]
@ranpox ???

**Comment by wolfshow** [comment]
@lalitr994 You have two ways for enlarge the input length. First, you may directly fine-tune the LayoutLM models using your labeled data with a much longer sequence such as 1024, but the position embeddings need to be randomly initilaized after the first 512 tokens. Second, you may pre-train your own model with a window size which is larger than 512.
