### ISSUE TITLE
Question about finetuning LayoutLMv2 on DocVQA

### ISSUE THREAD

**Issue by Cppowboy** [microsoft/unilm#410]
In the Layoutlmv2 paper, it says when using both train and dev set as fine-tuning set, the ANLS increases from 83.48 to 85.29. The question is, when using both train and dev set as fine-tuning set, how do you select the best model?

**Comment by dongxuewang-123** [comment]
HI,Do you fine-tune the layoutlm v2 on the docvqa?do you have reproduce the result on the docvqa? when I use the layoutlmv2-base to finetue,I can‘t get the ANLS score as the paper described,can we discuss the question?

**Comment by wolfshow** [comment]
@Cppowboy Just a fixed number of epochs.
