### ISSUE TITLE
cannot reproduce the result of DocVQA

### ISSUE THREAD

**Issue by dongxuewang-123** [microsoft/unilm#415]
Model I am using LayoutLMv2,I want to reproduce the result on DocVQA,but I don't know how to process the dataset,can you give the Layoutlmv2 model fine-tune example on the DocVQA ?Many thanks!

**Comment by wolfshow** [comment]
This question has nothing to do with this repo. You should ask the author of DocVQA about how to process the dataset.

**Comment by dongxuewang-123** [comment]
can you give the Layoutlmv2 model fine-tune example on the DocVQA?

**Comment by wolfshow** [comment]
@dongxuewang-123 DocVQA is a complex problem which includes OCR and answer mapping, which is not provided by the official dataset. Different people may have different pre-processing for that, which is out of the scope of this repo.
