### ISSUE TITLE
Question about the dataset statistics info

### ISSUE THREAD

**Issue by littletomatodonkey** [microsoft/unilm#422]
Hi, thanks for your excellent work! I am reproducing the xlm model recently, found that for the Xfun dataset, ZH dataset statistic info is same as JA dataset you provided in the thesis, so I was wondering that whether there are typos for the dataset statistics? (question number, answer number and so on.)

<img width="506" alt="f67fdab604f55a997191ba863149ed13" src="https://user-images.githubusercontent.com/14270174/131629928-4270b7d1-71e4-4a09-b826-106d7c34f7b4.png">

**Comment by ranpox** [comment]
Hi, 
I've moved this line up and updated the preprint version https://arxiv.org/pdf/2104.08836.pdf. Thank you for your help!
Yiheng
