### ISSUE TITLE
the input of visualBackbone

### ISSUE THREAD

**Issue by dongxuewang-123** [microsoft/unilm#423]
**Describe**
Model I am using  LayoutLMv2:when I finetune the Layoutlmv2,I put the original picture into the visual backbone,is this a right practice？
"""
def forward(self, images):
        images_input = (images.tensor - self.pixel_mean) / self.pixel_std
        features = self.backbone(images_input)
        features = features[self.out_feature_key]
        features = self.pool(features).flatten(start_dim=2).transpose(1, 2).contiguous()
        return features
"""

**Comment by wolfshow** [comment]
@dongxuewang-123 You need to resize the image into 224x224, which is mentioned in the LayoutLMv2 paper.
