### ISSUE TITLE
why do you not use mmdet version fp16?

### ISSUE THREAD

**Issue by miracle-fmh** [microsoft/unilm#425]
In "https://github.com/microsoft/unilm/blob/master/beit/semantic_segmentation/configs/beit/upernet/upernet_beit_base_12_512_slide_160k_ade20k_pt2ft.py#L69"

So, why do you not use mmdet version fp16?

**Comment by addf400** [comment]
@miracle-fmh  We follow the implementation of Swin's [repo](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/swin/cascade_mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py#L131).

https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/1
