### ISSUE TITLE
LayoutXLM pretraining data

### ISSUE THREAD

**Issue by rpowalski** [microsoft/unilm#426]
Hello,
Thanks for the great work with the LayoutXLM.

I wonder if you could share some of your work with the dataset used for pretraining. I know this is not possible to share dataset itself, due to Common Crawl policy, but can you share code which was used for obtaining the data?

**Comment by wolfshow** [comment]
@rpowalski Thanks for asking! For now, we do not have plans to share the dataset and the code to obtain the data.
