### ISSUE TITLE
is it related to the "Cross-Lingual Natural Language Generation via Pre-Training" project ?

### ISSUE THREAD

**Issue by Neuronys** [microsoft/unilm#43]
Hi
I've notice some name in common between the 2 papers (https://arxiv.org/pdf/1905.03197.pdf and https://arxiv.org/pdf/1909.10481v3.pdf). How these 2 projects are related ?
Thanks and congrats for such an impressive work !
Philippe

**Comment by donglixp** [comment]
Thanks for your interest in our work! XNLG is another intern project, which is also from our group.
