### ISSUE TITLE
How to infer Layout Reading order on a custom image

### ISSUE THREAD

**Issue by satheeshkatipomu** [microsoft/unilm#432]
Hi

I am trying to use predict reading order using pre-trained LayoutReader model on my own images. But I have no idea how to pass Image as input. Do we need to do some kind of pre-processing on the image? In the decoding instructions `ReadingBank\test` as input is used. They are text and layout json files. Can anyone please help me whether it is possible given an image, we get reading order as output?

**Comment by wolfshow** [comment]
@satheeshkatipomu The LayoutReader is a post-processing tool for OCR output. So, you need to run any OCR with your image and  get the bbox of each token, and then LayoutReader will take as input and generate the reading order for the bboxes.

**Comment by satheeshkatipomu** [comment]
Okay, thank you for your response.
