### ISSUE TITLE
Any plan to release the hugginface version of DeltaLM

### ISSUE THREAD

**Issue by Doragd** [microsoft/unilm#435]
Hi, Mr. Dong and co-authors,
I would like to know if there is any plan to release the `hugginface` version of DeltaLM.

**Comment by shumingma** [comment]
Thanks for your interest in DeltaLM!

This is on our roadmap, but currently there is no ETA. We also welcome any contributions to release it on the huggingface.

**Comment by R4ZZ3** [comment]
Any update on this?
