### ISSUE TITLE
Reproduce BEiT on ADE20K

### ISSUE THREAD

**Issue by yuhui-zh15** [microsoft/unilm#443]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): BEiT

Congrats on your awesome work! I have two questions regarding reproducing the segmentation result on ADE20k.

1. The paper mentioned the segmentation task layer is SETR-PUP, but both fine-tuning tutorial and released models use UperNet. 

2. I trained the model with the following script on 1 GPU. It seems the numbers I reproduced cannot match the released model or the paper. 

```
CUDA_VISIBLE_DEVICES=0 bash tools/dist_train.sh \
    configs/beit/upernet/upernet_beit_base_12_640_slide_160k_ade20k_pt2ft.py 1 \
    --work-dir models --seed 0  --deterministic \
    --options model.pretrained=https://unilm.blob.core.windows.net/beit/beit_base_patch16_224_pt22k_ft22k.pth
```

|                                                              | mIoU  | mAcc  | aAcc  |
| ------------------------------------------------------------ | ----- | ----- | ----- |
| upernet_beit_base_12_640_slide_160k_ade20k_pt2ft (our finetuned at 160000 steps) | 48.87 | 63.22 | 83.01 |
| upernet_beit_base_12_640_slide_160k_ade20k_pt2ft (official release) | 53.61 | 64.82 | 84.62 |
| upernet_beit_base_12_640_slide_160k_ade20k_ms (official release) | 54.26 | 65.28 | 84.90 |
| Supervised Pre-Training on ImageNet                          | 45.3  |       |       |
| DINO                                                         | 44.1  |       |       |
| BEiT                                                         | 45.6  |       |       |
| BEiT + Intermediate Fine-Tuning                              | 47.7  |       |       |

This is probably because I'm missing something at my end, but could you explain these differences? Thanks a lot for your help!

**Comment by addf400** [comment]
@yuhui-zh15 The effective batch size of mmseg is  `number of GPUs * samples_per_gpu`.
We conduct our experiments on ADE20k with an 8GPUs server and samples_per_gpu is 2, the effective batch size is 16. More details can be found at [there]. (https://github.com/microsoft/unilm/blob/master/beit/semantic_segmentation/configs/beit/upernet/upernet_beit_base_12_512_slide_160k_ade20k_pt2ft.py#L65)
On your side, your batch size is 2, which may need some adjustment for reproduction.

**Comment by donglixp** [comment]
The code and pre-trained models of BEiT-3 can be found at [aka.ms/beit3](https://aka.ms/beit3).
