### ISSUE TITLE
TrOCR: Example for doing actual predictions

### ISSUE THREAD

**Issue by stefan-it** [microsoft/unilm#448]
Hi guys,

thanks for releasing models and implementation of TrOCR :hugs: 

I would like to know, if you could also provide an example of how to do actual predictions with a TrOCR model, e.g. given an input image how is it possible to do predictions (= getting OCR'ed text).

Would be awesome if you could provide a kind of code snippet, would really like to play with the different models.

Many thanks in advance :heart:

**Comment by wolfshow** [comment]
Thanks @stefan-it! Typically, an off-the-shelf OCR tool should includes both detection (need to be done) and recognition (like TrOCR) modules. For now, I think you may need to leverage other text detectors to crop the text images and feed into TrOCR to get the text information. We hope to provide a detection model later to compose a complete OCR solution.

**Comment by Dod-o** [comment]
@stefan-it  The inference example has been uploaded, please see details in [pic_inference.py](https://github.com/microsoft/unilm/blob/master/trocr/pic_inference.py)
