### ISSUE TITLE
trOCR run example

### ISSUE THREAD

**Issue by vozdemir** [microsoft/unilm#451]
Many thanks for trOCR!! I couldn't run trOCR on text. How to run it, can you give an exaample pls.

Model I am using trOCR.

**Comment by wolfshow** [comment]
@vozdemir Can you provide more details about your questions? You may just download the dataset provided and do the inference with the base/large models. Meanwhile, please refer to https://github.com/microsoft/unilm/issues/448 for more details.

**Comment by NielsRogge** [comment]
@wolfshow would be great if you can fix my notebook to run inference with TrOCR on one particular image: https://colab.research.google.com/drive/1BHkOBUGHr1xlVQ9pLVLZPA0VvAxF4Zo_?usp=sharing

**Comment by wolfshow** [comment]
> @wolfshow would be great if you can fix my notebook to run inference with TrOCR on one particular image: https://colab.research.google.com/drive/1BHkOBUGHr1xlVQ9pLVLZPA0VvAxF4Zo_?usp=sharing

@Dod-o will help providing an inference example on that.

**Comment by Dod-o** [comment]
@NielsRogge The inference example has been uploaded, please see details in [pic_inference.py](https://github.com/microsoft/unilm/blob/master/trocr/pic_inference.py)

**Comment by SeifeddineGharbi** [comment]
@Dod-o when running pic_inference.py, I get the following error: urllib.error.HTTPError: HTTP Error 404: Not Found
it occurs when the script tries to download: Downloading: "https://github.com/pytorch/fairseq/archive/master.zip"

Any help please, thank you!!

**Comment by NielsRogge** [comment]
@SeifeddineGharbi I figured it out (I had to create a custom fork of Fairseq in order to make it work).

Except TrOCR to be added to Transformers soon ;)

**Comment by SeifeddineGharbi** [comment]
@NielsRogge Thank you so much for replying but can you explain a bit further, please?

**Comment by wolfshow** [comment]
> @SeifeddineGharbi I figured it out (I had to create a custom fork of Fairseq in order to make it work).
> 
> Expect TrOCR to be added to Transformers soon ;)

We found the fairseq model cannot be easily converted into the hf format. So we need to take more time to re-train the models with the hf library.

**Comment by NielsRogge** [comment]
@nithinreddyy haha I wrote that page 😅

**Comment by nithinreddyy** [comment]
> @nithinreddyy haha I wrote that page 😅 

Yaaa 😬😬. I gone through the 3 notebooks, but you haven't written code for testing the image and extracting the text (For fine tuning model with IAM dataset). In the 2nd notebook you trained the model with IAM dataset, in 3rd notebook you just checked the test evaluation scores. But how to take one image from test data and extract the text?

**Comment by NielsRogge** [comment]
My notebook includes an "inference" part, which does exactly what you want.

**Comment by nithinreddyy** [comment]
> My [inference notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/TrOCR/Inference_with_TrOCR_%2B_Gradio_demo.ipynb) does exactly what you want.

But you are directly loading the model from hugging face. What if we have our own dataset and want to train the model with data? In 2nd notebook You've trained the custom model with IAM dataset and you haven't written code how to extract text from one of the test images. I'm looking for that.

**Comment by NielsRogge** [comment]
Sorry, I thought you were talking about recognizing text, but you mean extracting text. 

The IAM dataset only contains single-line text images, hence one doesn't need to perform any text extraction anymore. However, if you want to apply TrOCR on an entire PDF document, then you first need a text extraction algorithm.

You can for example take a look at this one: https://github.com/qurator-spk/sbb_textline_detection
