### ISSUE TITLE
Inference of TrOCR

### ISSUE THREAD

**Issue by Artif-Inteller** [microsoft/unilm#454]
Thanks for sharing such great tool.
I want to extract texts from JPG images using pretrained model(`trocr-large-printed.pt`).
Of course those images are cropped by other text detector.
You described about how to fine tune and evaluate the model using `fairseq-generate`, but no about actual inference.
Even they seem need other informations such as `dict.label.txt`, `gpt2.dict.txt`(If these files are mandatory, how can I get those information from raw images?)
Could you please tell me how to run the pretrained model on raw JPG images(text cropped) using fairseq or using pure torch method?

Regards,

**Comment by wolfshow** [comment]
@Artif-Inteller, Thanks for the interests! We are working on an inference example, please stay tuned.

**Comment by Dod-o** [comment]
@Artif-Inteller The inference example has been uploaded, please see details in "pic_inference.py"

**Comment by Artif-Inteller** [comment]
Thanks a lot.

**Comment by zhanglinc** [comment]
the issue is still existed,coule you tell me how to find the dict.txt
