### ISSUE TITLE
Unclear license for  `layoutmlv2`

### ISSUE THREAD

**Issue by angel-langdon** [microsoft/unilm#456]
**Describe**
I am using the `layoutmlv2` model  with the `huggingface.tranformers` library.

In the `layoutmlv2` [readme](https://github.com/microsoft/unilm/tree/master/layoutlmv2) it says that all the project is licensed under the [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) ](https://creativecommons.org/licenses/by-nc-sa/4.0/) (Non-commercial use)

However the `transformers` library has the Apache License V.2 (free commercial use). If I use the `layoutmlv2` using the `transformers` interface ¿can I use it for commercial use?

**Comment by wolfshow** [comment]
@angel-langdon, Thanks for the interests! The pre-trained LayoutLMv2 models from our repo are licensed under the CC-BY-NC-SA 4.0. But if you would like to pre-train a model yourself with huggingface, You may follow the huggingface license.

**Comment by ManuelFay** [comment]
@wolfshow With the new LayoutLMV3 weights that are newly out with a MIT license, any updates on whether or not the LayoutLMv2 and LayoutXLM weights are going to be released with a more permissive (MIT/Apache2) license in the near future ? 

Best, and thanks for the great work as always !

**Comment by wolfshow** [comment]
@ManuelFay Thanks for the interest in LayoutLM! LayoutLMv3 will use the same license as LayoutLMv2 and LayoutXLM for now, but we will consider changing to a more permissive license for v2 models in the future.

**Comment by riteshKumarUMass** [comment]
Hi @wolfshow 
Would this license change apply to model weights/code downloaded after sept 19 (the day when you changed the license)? Can people who downloaded it prior to the license modification date continue to use for commercial purpose?
