### ISSUE TITLE
Issue with InfoXLM

### ISSUE THREAD

**Issue by sumanthd17** [microsoft/unilm#457]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): InfoXLM

The problem arises when using:
* [x] the official example scripts: (give details below) - with minor changes to work with latest fairseq
* [ ] my own modified scripts: (give details below)

I'm trying to run InfoXLM with the latest fairseq master branch, but looks like the code is outdated quite a bit. I made the required fairseq changes to be able to run it. But I observed the function [prepare_train](https://github.com/microsoft/unilm/blob/c218ba234728ae609f9e9fc8af3d20060aacf54a/infoxlm/src-infoxlm/infoxlm/tasks/infoxlm.py#L111) is not being used anywhere. This is supposed to initialise the queue, but currently not being used. Am I missing something?

**Expected behavior**
The queue initialisation is not being called, therefore the queue is empty and getting None in the loss

- Platform: Linux
- Python version: 3.7
- PyTorch version (GPU?): 1.9

@CZWin32768 Can you please let me know if I'm missing something here

**Comment by CZWin32768** [comment]
Thanks for opening this issue. The fairseq toolkit updates frequently. So, we recommend using fairseq provided here, which is based on fairseq-v0.9.0 with several modifications.

The original fairseq does not contain a "pretrain_train" stage. If you want to add a "prepare_train" phase to the other versions of fairseq, you can refer to [here](https://github.com/microsoft/unilm/blob/4ed561d5961e4c90a17b8ecad17d1f64db107e97/infoxlm/fairseq/train.py#L73).

**Comment by sumanthd17** [comment]
If I use the older version of fairseq let's say 0.9.0, will it be possible to convert the ckpt to HuggingFace format?
Given that the model definitions are slightly different in both the versions!

**Comment by sumanthd17** [comment]
I tried to run the code on multi GPU with given invocation, but the code is stuck here
<img width="822" alt="Screenshot 2021-10-06 at 10 57 41 PM" src="https://user-images.githubusercontent.com/28291870/136253719-132ef723-7ed3-4140-8c28-3447459cbd9a.png">

When I remove the `distributed-no-spawn` argument, I get this error `RuntimeError: Input, output and indices must be on the current device`

Can you please let me know what I'm doing wrong?

Thanks
