### ISSUE TITLE
TrOCR for multi-lines text image

### ISSUE THREAD

**Issue by Artif-Inteller** [microsoft/unilm#461]
The inference result for a single line text image(text localized) seems good.
But when I feed a multi line text image into the pretrained model, the output is terrible.

Does the TrOCR model require single line text images only as input?

**Comment by wolfshow** [comment]
@Artif-Inteller, As most text detection models usually output single line images, the TrOCR model is pre-trained with single line texts. If you would like to multi-line images, it is better to detect single-lines and feed into the models.

**Comment by Artif-Inteller** [comment]
Got it. Thanks for your helpness.
