### ISSUE TITLE
How to get LayoutLMv2 output as key-value pairs?

### ISSUE THREAD

**Issue by avinashok** [microsoft/unilm#465]
**Describe**
Model I am using is LayoutLMv2:

(Link of the demo for reference: https://huggingface.co/spaces/nielsr/LayoutLMv2-FUNSD )

I do get 'questions' & 'answers' as separate colored boxes in output image. But is there a way to get it as a python dictionary (key-value pairs), as in questions become keys & answers become its corresponding values?

**Comment by wolfshow** [comment]
@avinashok You may refer to the relation extracton example in LayoutXLM at https://github.com/microsoft/unilm/tree/master/layoutxlm#fine-tuning-for-relation-extraction
