### ISSUE TITLE
LayoutReader can't be evaluated on a dataset smaller than the batchsize

### ISSUE THREAD

**Issue by WhoAteDaCake** [microsoft/unilm#488]
**Describe the bug**
Model I am using **LayoutReader**

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. Download test dataset and reduce a file down to smaller than batch size value
2. Run, error will be thrown when results are read due to the fact that output file is missing

**Expected behavior**

Either use the `first_batch` variable like:

```python
first_batch = True
while first_batch or (next_i + args.batch_size <= len(input_lines)):
    first_batch = False
```
or throw a warning

- Platform: Shouldn't matter
- Python version:  Shouldn't matter
- PyTorch version (GPU?):  Shouldn't matter

**Comment by HYPJUDY** [comment]
Done. Thanks for your kind suggestion!
