### ISSUE TITLE
Is there a way to optimize while loop within BertForSeq2SeqDecoder?

### ISSUE THREAD

**Issue by antocapp** [microsoft/unilm#49]
Hello, 

I noticed the BertForSeq2SeqDecoder to be slow on CPU and this is mainly due to the while looping inside the forward method, where basically it iterates N times where N is the difference between next_pos and output_length, and next_pos increments by 1 at each iteration.

Can you explain me what are: 
- curr_length
- next_pos and input_length
- output_length
- token_type_ids

Do you have any idea on how to optimize the code in order to get rid of the while loop?

Thanks a lot, any help with the explanation of those variables will be appreciated

**Comment by nyanyanya** [comment]
Hi @antocapp :

Unfortunately, the loop in decoding cannot be easily removed. When decoding, the output sequence is not known in advance. Our decoder, like commonly used decoder in seq2seq, must decode the output sequence one word at a time, and feed the predicted word back to the input, thus the loop. Such decoder is called "auto regressive" in research literature.

If you want a faster decoder without the loop, you might want to look up "non-auto regressive" sequence-to-sequence models, which is an active area of research. (e.g. https://arxiv.org/abs/1711.02281; you can google for more). But be aware that changing to non-auto regressive requires re-training the model and substantial code changes, and most likely the result would be worse than the current auto-regressive model.

-Nan

**Comment by nyanyanya** [comment]
@antocapp 

And for the variables:
- input_length: the length of the input sequence. If the input is [x0,x1,..x4], input_length is 5.
- next_pos: the position of the token to be predicted in the next step. If the input is [x0,x1,...,x4] and the partial output sequence is [y0, y1], then next_pos is 5+2=7.
- curr_length: the length of curr_ids. It equals to input_length in the first step of decoding, and always equals to one afterwards.
- output_length: the pre-set limit of output sequence length. It prevents the decoding from going forever. The actually generated sequence can be shorter by generating a special ending token <SEP>.
- token_type_ids: it is a number denoting the input/output sequence. 0 means input, and 1 means output.

You can also see my explanation of the decoding process here for better understanding.
https://github.com/microsoft/unilm/issues/40#issuecomment-561935693

-Nan

**Comment by antocapp** [comment]
Hi @nyanyanya, thanks for the explanation.

What do you think about using decoder transformer instead of the classical seq2seq decoder? I am referring to newest approaches like this https://arxiv.org/abs/1911.10677, which are per definition non autoregressive.

Anyway, thanks for this wonderful work. I will try to implement this transformer part in the future.
