### ISSUE TITLE
Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by cloudfool** [microsoft/unilm#507]
Model I am using LayoutXLM:
I have trained LayoutXLM successfully, while today I have met this problem "Assertion `srcIndex < srcSelectDimSize` failed.".
I didn't change anything, Do you have any advice for me? thanks!

**Comment by jpWang** [comment]
Hi, have you solved this problem？I have met the same issue...

**Comment by cloudfool** [comment]
Today I trained it again and it worked correctly..
