### ISSUE TITLE
Additional details on task_idx

### ISSUE THREAD

**Issue by jpilaul** [microsoft/unilm#52]
Hello, 
First of all, thank you so much for open sourcing your code. This is great work! I have a quick question on the tasks in 
https://github.com/microsoft/unilm/blob/master/src/pytorch_pretrained_bert/modeling.py#L1214-L1217
Can you define `task_idx`? I see from `seq2seq_loader.py` that `task_idx=3` is for seq2seq LM and left2right LM. I think that  `task_idx=0` is for bidirectional LM. However, I am not sure about 1 and 2.
I really appreciate your help!

**Comment by donglixp** [comment]
1: left-to-right LM; 2: right-to-left LM

These two `task_idx`s are not used during fine-tuning.
