### ISSUE TITLE
WavLM Large

### ISSUE THREAD

**Issue by david-macleod** [microsoft/unilm#520]
Hi, thanks for sharing the pretrained models! Is there any timescale for when the Large version might be available?

**Comment by MarkWuNLP** [comment]
> Hi, thanks for sharing the pre-trained models! Is there any timescale for when the Large version might be available?

Because SUPERB benchmark has three additional tasks, speech separation, enhancement, and translation. Our plan is to release the large model after we get the numbers of the three tasks. I think in the next week, the large model will be released.
