### ISSUE TITLE
BEIT load checkpoint

### ISSUE THREAD

**Issue by nhathoang0110** [microsoft/unilm#521]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): Beit
When I train beit on my dataset, the checkpoint is saved with format *.pt. How can I load it for evaluation?
![image](https://user-images.githubusercontent.com/55668910/142362452-45c721c1-de28-4ae1-8900-cdef4af7a021.png)

**Comment by addf400** [comment]
If you want to eval performance on a classification task (e.g. ImageNet), you can refer to [this](https://github.com/microsoft/unilm/blob/master/beit/get_started_for_image_classification.md#fine-tuning), where `--nb_classes` option specifies the number of categories to be classified.

**Comment by nhathoang0110** [comment]
![image](https://user-images.githubusercontent.com/55668910/142742939-16378d10-4dd3-4011-8fc3-792f912a9fb7.png)
I have finetune according to your instructions, but the checkpoint is saved in the form above and I can't load the checkpoint, is there any problem in saving your checkpoint?

**Comment by nhathoang0110** [comment]
i found out since i use deepspeed the save model will be in the format as above. And I can't load such saved checkpoint. Do you have any solution?

**Comment by addf400** [comment]
> i found out since i use deepspeed the save model will be in the format as above. And I can't load such saved checkpoint. Do you have any solution?

It looks like you are using `--resume /path/to/checkpoint`, I recommend using `--finetune /path/to/checkpoint`

**Comment by nhathoang0110** [comment]
i used exactly --finetune when training. When I use deepspeed it saves checkpoint like that. And when I load the model I trained for inference, the result is not good. If deepspeed is not used, it will be saved in the format checkpoint-n.pth ( n=1,2,3,4,...etc) but that's not enough memory for training. I don't know if saving the checkpoint as above has any effect?
