### ISSUE TITLE
The intuition behind the tokenizer.

### ISSUE THREAD

**Issue by zeakey** [microsoft/unilm#523]
I know it might be not proper to discuss here, but I'm still curious about the intuition behind the `tokenizer`.

**Comment by donglixp** [comment]
Motivation: "pixel-level recovery task tends to waste modeling capability on pre-training short-range dependencies and high-frequency details"

Solution: "BEiT overcomes the above issue by predicting discrete visual tokens, which summarizes the details to high-level abstractions." (i.e., the dVAE tokenizer constructs a representation bottleneck, which pushes information of pixel-level details into the tokenizer)

refer to https://arxiv.org/pdf/2106.08254.pdf
