### ISSUE TITLE
The last FFN of MiniLM is not supervised by any signals, is this proper?

### ISSUE THREAD

**Issue by GeneZC** [microsoft/unilm#525]
**Describe**
I am using MiniLM, but I find that the last FFN of MiniLM is not supervised by any signals.
I am wondering whether this matters or not?

**Comment by WenhuiWang0824** [comment]
Hi @GeneZC,

During the task-agnostic distillation of MiniLM, the last FFN is not supervised.

If you use MiniLM for fine-tuning on downstream tasks, it will be fine and we have conducted experiments on monolingual and multilingual benchmarks to verify it.

Thanks

**Comment by GeneZC** [comment]
Get it. Thank you.
