### ISSUE TITLE
How to train WavLM

### ISSUE THREAD

**Issue by A-New-Page** [microsoft/unilm#526]
**Describe**
Model I am using (WavLM):Could you please tell me where to understand how you train WavLM? Which file includes code used to train WavLM

**Comment by MarkWuNLP** [comment]
> **Describe** Model I am using (WavLM):Could you please tell me where to understand how you train WavLM? Which file includes code used to train WavLM

Thank you for your interest in WavLM. Currently, we don't have a plan to release the pre-training code, but it is easy for you to reproduce our results based on the HuBERT pre-training recipe. Sorry for the inconvenience.
