### ISSUE TITLE
KeyError: 'num_classes'

### ISSUE THREAD

**Issue by xiaomore** [microsoft/unilm#528]
**Describe the bug**
Model I am using (UniLM-BEiT):

The problem arises when using:
* [ ] the official example scripts: (give details below)

**To Reproduce**
1. OUTPUT_DIR=...
2. DATA_PATH=...
3. TOKENIZER_PATH=...
4. wget -o $TOKENIZER_PATH/encoder.pkl https://cdn.openai.com/dall-e/encoder.pkl
wget -o $TOKENIZER_PATH/decoder.pkl https://cdn.openai.com/dall-e/decoder.pkl

5. OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=2 run_beit_pretraining.py \
        --data_path ${DATA_PATH} --output_dir ${OUTPUT_DIR} --num_mask_patches 75 \
        --model beit_base_patch16_224_8k_vocab --discrete_vae_weight_path ${TOKENIZER_PATH} \
        --batch_size 128 --lr 1.5e-3 --warmup_steps 10000 --epochs 1 \
        --clip_grad 3.0 --drop_path 0.1 --layer_scale_init_value 0.1

**Expected behavior**
`and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
| distributed init (rank 0): env://, gpu 0
| distributed init (rank 1): env://, gpu 1
Namespace(abs_pos_emb=False, auto_resume=True, batch_size=128, clip_grad=3.0, color_jitter=0.4, data_path='/home/data2/lh/document_relevant/unilm/beit/data', device='cuda', discrete_vae_type='dall-e', discrete_vae_weight_path='/home/data2/lh/document_relevant/unilm/beit/model_save/dall_e_tokenizer_weight', dist_backend='nccl', dist_on_itp=False, dist_url='env://', distributed=True, drop_path=0.1, epochs=1, gpu=0, imagenet_default_mean_and_std=False, input_size=224, layer_scale_init_value=0.1, local_rank=0, log_dir=None, lr=0.0015, max_mask_patches_per_block=None, min_lr=1e-05, min_mask_patches_per_block=16, model='beit_base_patch16_224_8k_vocab', momentum=0.9, num_mask_patches=75, num_workers=10, opt='adamw', opt_betas=None, opt_eps=1e-08, output_dir='/home/data2/lh/document_relevant/unilm/beit/model_save', pin_mem=True, rank=0, rel_pos_bias=True, resume='', save_ckpt_freq=20, second_input_size=112, second_interpolation='lanczos', seed=0, start_epoch=0, train_interpolation='bicubic', warmup_epochs=5, warmup_lr=1e-06, warmup_steps=10000, weight_decay=0.05, weight_decay_end=None, world_size=2)
Creating model: beit_base_patch16_224_8k_vocab
------------kwargs-------------
{'drop_path_rate': 0.1, 'use_shared_rel_pos_bias': True, 'use_abs_pos_emb': False, 'init_values': 0.1}
Traceback (most recent call last):
  File "run_beit_pretraining.py", line 282, in <module>
Traceback (most recent call last):
  File "run_beit_pretraining.py", line 282, in <module>
    main(opts)
  File "run_beit_pretraining.py", line 167, in main
    model = get_model(args)
  File "run_beit_pretraining.py", line 146, in get_model
    main(opts)
  File "run_beit_pretraining.py", line 167, in main
    init_values=args.layer_scale_init_value,
  File "/home/ldf/anaconda3/envs/yolo/lib/python3.6/site-packages/timm/models/factory.py", line 81, in create_model
    model = get_model(args)
    model = create_fn(pretrained=pretrained, **kwargs)
  File "run_beit_pretraining.py", line 146, in get_model
  File "/home/data2/lh/document_relevant/unilm/beit/modeling_pretrain.py", line 142, in beit_base_patch16_224_8k_vocab
    init_values=args.layer_scale_init_value,
  File "/home/ldf/anaconda3/envs/yolo/lib/python3.6/site-packages/timm/models/factory.py", line 81, in create_model
    _ = kwargs.pop("num_classes")
KeyError: 'num_classes'
    model = create_fn(pretrained=pretrained, **kwargs)
  File "/home/data2/lh/document_relevant/unilm/beit/modeling_pretrain.py", line 142, in beit_base_patch16_224_8k_vocab
    _ = kwargs.pop("num_classes")
KeyError: 'num_classes'`
- Platform: ubuntu 18.04
- Python version: python 3.6
- PyTorch version (GPU?): cuda10.2 , torch==1.10.0 and torchvision==0.11.1

Thanks~

**Comment by L-xiaolu** [comment]
I have the same problem with my own dataset

**Comment by addf400** [comment]
https://github.com/microsoft/unilm/pull/541 @xiaomore  @L-xiaolu  We have updated our code. Please pull the latest code and try again.
