### ISSUE TITLE
torch.hub.load() raises HTTPError: HTTP Error 404: Not Found when loading model

### ISSUE THREAD

**Issue by eafaizal** [microsoft/unilm#533]
**Describe the bug**
404 error happens with models on fairseq while testing pic_inference.py

The problem arises when using:
                logger.info('Load pre-trained decoder parameters from roberta.large')
                roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
                >> Errored 

                roberta = torch.hub.load('pytorch/fairseq:main', 'roberta.large')
                >> Worked

                fairseq folks decided to change the default branch of their GitHub repository from master to main

**Comment by ranpox** [comment]
Fixed in https://github.com/microsoft/unilm/pull/522.
