### ISSUE TITLE
[Ask]About the souce code of XLM-E: Cross-lingual Language Model Pre-training via ELECTRA

### ISSUE THREAD

**Issue by LangDaoAI** [microsoft/unilm#534]
Hi Team,

Thanks outstanding work for Cross-lingual Language Model Pre-training!

I have a question :  whether the souce code of XLM-E: Cross-lingual Language Model Pre-training via ELECTRA is published or not?

Thanks !

---Tang

**Comment by donglixp** [comment]
Thanks for your interest in our work. The xlm-e paper is still under review. I recommend to use the infoxlm-base/large checkpoints for experiments, which is also developed by us. Infoxlm has already been integrated into huggingface so it would be very easy to use them.

**Comment by dadelani** [comment]
I think the paper has been accepted. Is the code and model now available ? @donglixp

**Comment by ir2718** [comment]
Any updates on this?
