### ISSUE TITLE
How to load xfun data locally?

### ISSUE THREAD

**Issue by vincezengqiang** [microsoft/unilm#539]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...):

i m runing the code examples/run_xfun_ser.py, but some wrong with the internet that can not download xfun data online , i have downloaded the xfun data  to local, how to load data locally?

**Comment by aditya11ad** [comment]
Hi,

I am using a locally available XFUN dataset (downloaded from [here](https://github.com/doc-analysis/XFUND/releases/tag/v1.0) )
FYI: (dataset content ===> fr.train.zip , fr.train.json , fr.val.zip , fr.val.json)

and i want to use:
load_dataset("XFUN.py")
[XFUN.PY](https://github.com/microsoft/unilm/blob/42100e11bdd3ac8e9ca2e9b506af8c9231a0c6d6/layoutlmft/layoutlmft/data/datasets/xfun.py#L48)
what should be the changes in XFUN.PY

buz i am getting this error:

FileNotFoundError: [Errno 2] No such file or directory:
'/root/.cache/huggingface/datasets/downloads/extracted/f8224153aa2566a5505e78e5209e2e1aa49188389d3607d021f492a7164f9cc4/fr_train_0.jpg'
DatasetGenerationError
