### ISSUE TITLE
Different Questions using trace file

### ISSUE THREAD

**Issue by Tprasanthi** [microsoft/unilm#54]
I would like to generate different questions trace file, I need top 3 questions for each answer using beam search. You are taking top-k elements in trace file but can you please help me with the code to get the top n questions for each particular answer.

Thank You,
Prasanthi

**Comment by nyanyanya** [comment]
Hi Prasanthi,

If you need questions for different answers in one input passage, you can repeat the input passage several times with different answers as input. In this way the model will generate k questions for each answer.

Thanks,
Nan

**Comment by gdgovinddaga6** [comment]
I have the same issue as Prasanthi does. I think @nyanyanya  got the question wrong. What if I need different questions using the same keyphrase or answer?

Keyphrase: **Sacramento**
Eg: _Which city do you live in?
       Where do you reside?
       Where do you live?_
   I think we can do it with beam search, the author has given me a solution for this, but I'm a rookie and I couldn't implement it, Can you help?

It's much like paraphrasing. But I thought to implement using beam.

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/blob/master/src/biunilm/gen_seq_from_trace.py#L56
In L56, we use ` if s > max_score:` to save the best beam search result. Instead, we can maintain a sorted list to save the top-K results (L60&L61: frame_id and frame_id). Then L65-L69 can recover them to tokens.
