### ISSUE TITLE
Time for extraction of Text from a particular document 

### ISSUE THREAD

**Issue by rajsaraiya009** [microsoft/unilm#540]
What is the time taken for extraction of text from a document? I tried to extract text from an invoice using the trocr-base-printed model the time taken on GPU is 1 minute per page which is very time-consuming is there any way we can reduce the extraction time in trocr model ??

**Comment by wolfshow** [comment]
@rajsaraiya009 We are working on small models and small vocabs to reduce the latency. Please stay tuned.
