### ISSUE TITLE
MarkupLM: missing setup.py file?

### ISSUE THREAD

**Issue by buhii** [microsoft/unilm#542]
**Describe the bug**

Hi,
it seems that MarkupLM doesn't have setup.py in the repository, and the installation failed.

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**

I tried the installation command described in [README.md](https://github.com/microsoft/unilm/tree/master/markuplm#installation)
```
git clone https://github.com/microsoft/unilm.git
cd unilm
cd markuplm
pip install -r requirements.txt
pip install -e .
```

and the last command, `pip install -e .` failed with the below error message:
```
WARNING: Ignoring invalid distribution -bsl-py (/opt/conda/lib/python3.7/site-packages)
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/jupyter/unilm/markuplm
```

**Comment by lockon-n** [comment]
Thanks for reminding! We have added the missing `setup.py` in markuplm.
