### ISSUE TITLE
Could you please release PDF parser that was used in LayoutXLM pretraining ?

### ISSUE THREAD

**Issue by AQA6666** [microsoft/unilm#545]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...):
We are now trying to finetune LayoutXLM with our own PDF dataset, but we have some promblems when parsing PDFs.

**Comment by ranpox** [comment]
As mentioned in section 2.3, we used https://github.com/pymupdf/PyMuPDF to parse PDFs.
