### ISSUE TITLE
[AdaLM] What metrics for adalm cs data?

### ISSUE THREAD

**Issue by renmada** [microsoft/unilm#546]
Some result from paper
![image](https://user-images.githubusercontent.com/43545086/143809293-7efafbaf-acf0-4490-ab78-e9b850750c34.png)

There's 3 metrics, macro_f1, acc, acc_and_f1, which one used in the table?

**Comment by buaahsh** [comment]
We followed [Don’t Stop Pretraining](https://arxiv.org/pdf/2004.10964.pdf)'s setting and used macro_f1 as our evaluation metrics.
