### ISSUE TITLE
Attribute error : module 'apex ' has no attribute 'amp'

### ISSUE THREAD

**Issue by Zepharchit** [microsoft/unilm#548]
Hi,
Thanks for the great repo.
I was trying to run layoutreader, I followed the steps provided in the repo for it but  I am getting this error while running the script.
Likewise can you please share about "features_train.pt" I wasn't able to find it when I download the Reading Bank Dataset.
![Screenshot from 2021-11-29 12-21-06](https://user-images.githubusercontent.com/51807559/143821409-ff2be8b0-4f10-4369-831b-6c98e5164d8a.png)

**Comment by ranpox** [comment]
According to the image you provided, you did not install `apex` correctly. You can delete the `apex` folder and try again.
