### ISSUE TITLE
Overall Performance Optimization

### ISSUE THREAD

**Issue by anshoomehra** [microsoft/unilm#55]
Researchers,

Are there any suggestions to improve the performance of the overall pipeline? I am using one Tesla V100, and the performance is about 187 questions per minute by running two instances in parallel. 

Though the outcomes are simply great! I am running showstopper making use of this in production. With some leverage of assumptions, I am able to process roughly 2000 documents per day. per GPU We chunk each document (every doc has different # of chunks) & each chunk has n th hints.

My goal is to target roughly 20,000 docs per GPU per day. If so I should be able to scale fabric of 5 GPUs, to keep the operational cost under check. We receive roughly doc 100k updates per day.

Thank you,
Anshoo

**Comment by donglixp** [comment]
How long are your input documents? If the running couldn't meet your requirement, the input length can be reduced to save prediction time.

**Comment by anshoomehra** [comment]
Documents are chunked and chunks are semantic i.e. contextual with varied length, and I see that question quality is very good with this logic, I am bit hesitant forcing fixed length as it may impact the quality. Though this is a good suggestion and I will try to see I can fix the doc length. Few other ideas in my mind and if you can please weigh in?

1. Each run instance is costing roughly about 5G GPU Memory, can we reduce the footprint and this can possibly boost the number of parallel threads per GPU, along with inference time. At the moment I can run 2 instances on one GPU, 3rd one fails with Out Of Memory Error. 

2. I tried running on DGX with 8 V100s, for some reason I can't pass 4 running instances of docker, and these instances only use 4 GPUs out of 8 available. I do not see visible limitation in the code, any thoughts here?

3. There some groundbreaking performance optimization work going on for Transformer Models, can we look into optimizing our pre-trained models ?? Examples below.
 **Microsoft** : https://cloudblogs.microsoft.com/opensource/2020/01/21/microsoft-onnx-open-source-optimizations-transformer-inference-gpu-cpu/
**Albert** 

Thank you!
Anshoo

**Comment by kbrajwani** [comment]
@anshoomehra  Have you found any solution. i am going through same production sitaution where model is taking much gpu memory so i can't increase my worker to make multiprocess. Can you advise something?

**Comment by anshoomehra** [comment]
> @anshoomehra Have you found any solution. i am going through same production sitaution where model is taking much gpu memory so i can't increase my worker to make multiprocess. Can you advise something?

@kbrajwani not very clear on your problem statement, GPU memory is tied to input load, not sure if you are batching or not, try to analyze there first & fine tune. GPUs are expensive & hence they being fully utilized to max is good, do not be afraid on that front!! Just be watchful of overloading, memory errors, & be creative to dynamically handle load should any of this happen. Few tips in general:

1. Switch to T4 GPUs that would save you on cost and hopefully you can procure GPUs if needed.
2. Beam Size is a critical hyperparameter, the lowest gives you best performance, not necessarily quality, find the right balance of quality & performance here for your domain of input text.
3. It's been awhile & I see many lighter versions of unilm, not sure if you have tried them?
4. Batching (if feasible) will give you the best performance.

I followed the custom approach over unilm generating questions, and had good success with it. Let me pen this down as it may help many & even share the code. It will take me a while to do so, FYI.

Good luck!

**Comment by kbrajwani** [comment]
Thanks man
