### ISSUE TITLE
Infer The Model

### ISSUE THREAD

**Issue by AhmedHashish123** [microsoft/unilm#552]
**Describe**
Model I am using (BEiT):
Hello, I appreciate the work on display here. I was just wondering how I could simply inference the model on a single image. I trained a model on a custom dataset and was trying to infer it.

**Comment by donglixp** [comment]
The model and implementation have been integrated into huggingface (https://huggingface.co/docs/transformers/model_doc/beit ). It would be easier to host for inference.
