### ISSUE TITLE
BEiT zero v_bias

### ISSUE THREAD

**Issue by Alxead** [microsoft/unilm#558]
Hi, I notice that in BEiT self attention, you fix `v_bias` to zero. 
https://github.com/microsoft/unilm/blob/2a20fde235c9cba57a1aa074311d4ca84f8b13da/beit/modeling_finetune.py#L124

This is different from the original self attention code in Transformer. Why are you doing this? Will this make the accuracy higher?

**Comment by addf400** [comment]
@Alxead  Refer to https://github.com/microsoft/unilm/issues/510.
