### ISSUE TITLE
Getting Bad results, random words in Inference outputs for question generation. What am I doing wrong? 

### ISSUE THREAD

**Issue by swanand30** [microsoft/unilm#56]
Hi
When I am running test files for inference on qg_model.bin provided [here](https://drive.google.com/file/d/1JN2wnkSRotwUnJ_Z-AbWwoPdP53Gcfsn/view) in git, I am getting very unexpected results in qg_model.bin.test file as an output
sample result:-
",s Sungs ,s ,s ,s , ,s ,s , s , ss , s s s s s s s s s s s s s s s s s s s s s s s s s s s"
I am not able to figure out why the model is not generating grammatically sound questions.

**Comment by wazzy** [comment]
I had the same problem when I tried it 4 days back. I trained the question generation model with these setting and command.

```
python biunilm/run_seq2seq.py --do_train --num_workers 0 \
--bert_model bert-large-cased --new_segment_ids --tokenized_input \
--data_dir ${DATA_DIR} --src_file train.pa.tok.txt --tgt_file train.q.tok.txt \
--output_dir ${OUTPUT_DIR}/bert_save \
--log_dir ${OUTPUT_DIR}/bert_log \
--model_recover_path ${MODEL_RECOVER_PATH} \
--max_seq_length 512 --max_position_embeddings 512 \
--mask_prob 0.7 --max_pred 48 \
--train_batch_size 4 --gradient_accumulation_steps 2 \
--learning_rate 0.00002 --warmup_proportion 0.1 --label_smoothing 0.1 \
--num_train_epochs 10
```
only batch size was kept as 4 while training.
Config output.
```
{
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "ffn_type": 0,
  "fp32_embedding": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "intermediate_size": 4096,
  "label_smoothing": 0.1,
  "max_position_embeddings": 512,
  "new_pos_ids": false,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "num_qkv": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "relax_projection": 0,
  "seg_emb": false,
  "task_idx": 3,
  "type_vocab_size": 6,
  "vocab_size": 28996
}
```

I was wondering how other folks has got better output as mentioned in the paper. 
I tried the pre-trained **qa_model.bin** also but the output remains the same at the time of decoding.

Please help

**Comment by donglixp** [comment]
Batch_size = 4 is too small for fine-tuning. I recommend to enlarge the --gradient_accumulation_steps while remaining the original batch size.

**Comment by donglixp** [comment]
Could you provide more information about how you ran the decoding? If you followed the instructions, the exactly same outputs as others should be expected.
