### ISSUE TITLE
DeltaLM Fine-tune Model Path Error

### ISSUE THREAD

**Issue by mahfuzibnalam** [microsoft/unilm#560]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): DeltaLM

The problem arises when using:
* [When using the official example script] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. I have run unilm/deltalm/examples/train_iwslt14.sh in a cluster where I have set --pretrained-deltalm-checkpoint to this: "cluster_directory/models/multi/pre-trained/deltalm-base.pt"
2. After fine-tuning I have got some checkpoints that I have copied to my local PC.
3. Now if I run unilm/deltalm/examples/evaluate_iwslt14.sh in my local PC setting the --path as one of the checkpoints.
4. I get this error: "OSError: Model file not found: cluster_directory/models/multi/pre-trained/deltalm-base.pt"
5. This should not be the case. I have fixed this by adding "args.pretrained_deltalm_checkpoint="local_directory/models/multi/pre-trained/deltalm-base.pt" in line 112 of unilm/deltalm/deltalm/models/deltalm.py.

**Expected behavior**
There should be a config option to change --pretrained_deltalm_checkpoint.

- Platform:
- Python version:3.6.9
- PyTorch version (GPU?):1.10.0

**Comment by shumingma** [comment]
Hi,

Thanks for reporting the issue. Could you please try if setting **--model-overrides {'pretrained_deltalm_checkpoint': ''}** can solve this?

**Comment by mahfuzibnalam** [comment]
I have tried this. This gives the following error:
"generate.py: error: unrecognized arguments: local_directory/models/multi/pre-trained/deltalm-base.pt"

**Comment by shumingma** [comment]
> 

This should be some problems regarding the format of arguments. Could you try **--model-overrides "{'pretrained_deltalm_checkpoint': ''}"** ?

This can enable fairseq to override _pretrained_deltalm_checkpoint_ when loading checkpoints:

https://github.com/pytorch/fairseq/blob/e3fafbdfc9a39ba8339ebde98aa01c5349ab060d/fairseq_cli/generate.py#L92

**Comment by mahfuzibnalam** [comment]
This fixes it. Thanks.
