### ISSUE TITLE
Question about hyperparameters on ADE20K-val

### ISSUE THREAD

**Issue by Bryce-HJ** [microsoft/unilm#561]
Hello, now i'm want to reproduct the results on ade20k-val, and I see the basic settings are BEiT-L + UperNet, so I wonder that what the number of epoch or iteration and the whole batch_size can get the 57.0 miou result? 
I'll so pleased If you can release the relevent training log !!
Thanks !!

**Comment by addf400** [comment]
Please use this [config](https://github.com/microsoft/unilm/blob/master/beit/semantic_segmentation/configs/beit/upernet/upernet_beit_large_24_640_slide_160k_ade20k_pt2ft.py)

**Comment by Bryce-HJ** [comment]
> Please use this [config](https://github.com/microsoft/unilm/blob/master/beit/semantic_segmentation/configs/beit/upernet/upernet_beit_large_24_640_slide_160k_ade20k_pt2ft.py), the fine-tuning log also can be found by this [URL](https://paste.ubuntu.com/p/sdsWCDRzk2/)

Thanks!!
