### ISSUE TITLE
When I use s2s_ft, I coudn't decoding to validate my result after training.

### ISSUE THREAD

**Issue by quirecan** [microsoft/unilm#568]
I follow the README to build environment, and I can train on my own dataset. But when I run the decoding bash, it reports  
**No module named 'unilm'** 
on this code  **from unilm.tokenization_unilm import UnilmTokenizer** in decode_seq2seq.py.
Please help me, thank you.

**Comment by addf400** [comment]
I have created a PR(https://github.com/microsoft/unilm/pull/569), please update the code and have a try.

**Comment by quirecan** [comment]
yeah, I have tried this way hours ago. While there exists some other mistakes, maybe it is because the different pytorch version, but I can validate after change some codes.
After all, thank you for your quick help.
