### ISSUE TITLE
LayoutLMv2 for CORD dataset

### ISSUE THREAD

**Issue by ealmazanm** [microsoft/unilm#578]
Hello I am trying to replicate the results reported in the paper, but I have a doubt regarding the number of classes that were used in CORD. In the paper it mentions that 30 classes were used, however in the notebook of hugging face (https://colab.research.google.com/github/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/CORD/Fine_tuning_LayoutLMv2ForTokenClassification_on_CORD.ipynb#scrollTo=dVuQ73870FMF) they aggregate a few classes with few instances giving a total of 23 classes. I wonder whether you are grouping classes too?

**Comment by MarkusDressel** [comment]
Hi @ealmazanm  
I could replicate the results from the original paper using all of the 30 classes. I think the most important part if ROI alignment. This give a good boost in performance. 
Inspired by Niels Rogges Transformer Tutorial, I have created a similar version including ROI alignment. https://github.com/MarkusDressel/ML-Tutorials/blob/main/LayoutLMv2ForTokenClassificaiton/CORD/Fine_tuning_LayoutLMv2ForTokenClassification_on_CORD_solution.ipynb

Hope that helps
