### ISSUE TITLE
A question about vocabulary size

### ISSUE THREAD

**Issue by peiyingxin** [microsoft/unilm#580]
i want to know why vocabulary size is set to |V| = 8192 ？

thank you~~

**Comment by NielsRogge** [comment]
Hi,

This is a choice that OpenAI made when creating DALL-E. From the [paper](https://arxiv.org/pdf/2102.12092.pdf):

> We use a large vocabulary size of 8192 to mitigate the loss of information. (...) This reduces
the context size of the transformer by a factor of 192 without a large degradation in visual quality.

**Comment by peiyingxin** [comment]
Ok thank you~ I will read this paper~
