### ISSUE TITLE
How to use LayoutLM with digit-born documents such as WORD?

### ISSUE THREAD

**Issue by wangxin0718** [microsoft/unilm#584]
**Describe**
Model : LayoutLM 
I want to use LayoutLM to extract information from WORD. I can parse  text from WORD with python-docx.  But how to get bound box?Do I have to use OCR ? Thanks.

**Comment by wolfshow** [comment]
@wangxin0718 The python-docx will not provide the 2d positions for each token in WORD. To use LayoutLM, you may need to convert the WORD into PDF, and use any PDF parser to extract texts as well as the 2d positions.
