### ISSUE TITLE
StructuralLM copy related work from layoutlmv2

### ISSUE THREAD

**Issue by paulpaul91** [microsoft/unilm#591]
**Describe**
Model I am using LayoutLM:
layoutlmv2 related work
![image](https://user-images.githubusercontent.com/22076188/148679468-e098cbdb-56d5-4034-a700-9727fb439211.png)
structralLM related work
![image](https://user-images.githubusercontent.com/22076188/148679486-4ed6e1c8-8768-4f12-8335-2d6101434182.png)

**Comment by paulpaul91** [comment]
Both accepted by ACL2021， who copy who

**Comment by wolfshow** [comment]
![pic1](https://user-images.githubusercontent.com/3775235/148680615-4f0e80b0-739b-48e8-9e7d-2566371b403e.png)
![pic2](https://user-images.githubusercontent.com/3775235/148680617-79b0902c-1493-4c6a-8f14-25172ea45e56.png)


https://arxiv.org/abs/2012.14740
https://arxiv.org/abs/2105.11210

Thanks for the question. My boy. Who copy who? 

While, the most interesting part is that, Table 1 in StructuralLM copies the numbers of Table 1 in LayoutLMv2, but changes the name from UniLMv2 to RoBERTa.

**Comment by paulpaul91** [comment]
> changes the name from UniLMv2 to RoBERTa.

How do you feel about such bad plagiarism

**Comment by wolfshow** [comment]
> > changes the name from UniLMv2 to RoBERTa.
> 
> How do you feel about such bad plagiarism？ https://github.com/alibaba/AliceMind

I suggest you should post it on zhihu.com

**Comment by paulpaul91** [comment]
> > > changes the name from UniLMv2 to RoBERTa.
> > 
> > 
> > How do you feel about such bad plagiarism？ https://github.com/alibaba/AliceMind
> 
> I suggest you should post it on zhihu.com

那我要得罪很多人，圈子太小

**Comment by lcl6679292** [comment]
Thank you for your interest in our work. StructuralLM and LayoutLM propose different solutions to the problem of visually-rich document modeling. The StructuralLM approach is original and distinct from LayoutLM in document types, model architectures and research findings. Our StructuralLM paper has properly cited the previous work of LayoutLM(v1), and referred to the baseline models used in the v1 paper, including the name RoBERTa. LayoutLM(v2) later replaced the baseline from RoBERTa to UniLMv2, which led to the discrepancy in the model names. As StructuralLM and LayoutLM both address the same research problem, which is an emerging topic with limited studies in the past, that results in the similarity in citations of the related work sections.
We sincerely appreciate the contribution of LayoutLM to this research field.

**Comment by wolfshow** [comment]
Thanks @lcl6679292 for the clarification! We have also fixed the typo which is mentioned in https://github.com/microsoft/unilm/issues/592.

**Comment by paulpaul91** [comment]
very interesting

**Comment by James-Branigan** [comment]
It's not clear how the cell-level embeddings are different from the word-level embeddings used in LayoutLM. Your paper doesn't talk about the specifics of generating the cell-level embeddings from the unstructured training data. Is it based on the x, y coordinates of the word-level bounding boxes being close enough to one another?

For example, a quote from your paper:

> Therefore, we need to reprocess the scanned document images to obtain the layout information of cells. Like the pre processing method of LayoutLM, we similarly process the dataset by using Tesseract 1, which is an opensource OCR engine.

It seems like you are saying that you do the exact same thing as LayoutLM. Please help me understand what I am missing.
