### ISSUE TITLE
a question about the baseline  in LayoutLMv2  and LayoutLM?

### ISSUE THREAD

**Issue by shichengustc** [microsoft/unilm#592]
**LayoutLM** 
FUNSD DateSet：Basline Roberta
![图片](https://user-images.githubusercontent.com/97426007/148722241-8344b020-a8a4-422b-9124-9a65e7fadc60.png)

**LayoutLM v2** 
FUNSD DateSet：Basline UniLMv2
![图片](https://user-images.githubusercontent.com/97426007/148722144-30baa96c-7200-4b6f-a728-fbfa1ba7929a.png)

**Comment by wolfshow** [comment]
@shichengustc Yes, this is a typo in the LayoutLMv2, we have updated the ArXiv version and will be online tmr.

![image](https://user-images.githubusercontent.com/3775235/148724336-2c21b070-b2f4-4138-a539-765114c6deb4.png)

**Comment by paulpaul91** [comment]
interesting

**Comment by shichengustc** [comment]
> interesting

yep，this typo is interesting！
