### ISSUE TITLE
BeiT-base pre-train: NaN grad_norm

### ISSUE THREAD

**Issue by srikar2097** [microsoft/unilm#598]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): BeIT

Hi @donglixp and @laojiangwei, I am pre-training BeiT-base on Imagenet-1k using exact same recipe in your README to replicate the results. In the log I get `grad_norm` as `nan` is this expected? Is the training still happening as expected?

Epoch: [115]  [1298/1299]  eta: 0:00:00  lr: 0.001435  min_lr: 0.001435  mlm_acc: 0.0333 (0.0344)  loss: 6.5993 (6.5971)  loss_scale: 8192.0000 (8646.0600)  weight_decay: 0.0500 (0.0500)  **grad_norm: 0.3922 (nan)**  time: 0.4944  data: 0.0001  max mem: 19152

Averaged stats: lr: 0.001435  min_lr: 0.001435  mlm_acc: 0.0333 (0.0345)  loss: 6.5993 (6.5925)  loss_scale: 8192.0000 (8646.0600)  weight_decay: 0.0500 (0.0500)  **grad_norm: 0.3922 (nan)**

Looking forward to hearing from you.

----
Issued pre-train command for reference (taken from here: https://github.com/microsoft/unilm/tree/master/beit#example-pre-training-beit-base-on-imagenet-1k)
```
OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=8 run_beit_pretraining.py \
        --data_path ${DATA_PATH} --output_dir ${OUTPUT_DIR} --num_mask_patches 75 \
        --model beit_base_patch16_224_8k_vocab --discrete_vae_weight_path ${TOKENIZER_PATH} \
        --batch_size 128 --lr 1.5e-3 --warmup_epochs 10 --epochs 800 \
        --clip_grad 3.0 --drop_path 0 --layer_scale_init_value 0.1 \
        --imagenet_default_mean_and_std \
        --num_workers=27 \
        --save_ckpt_freq=100 \
        ;
```

**Comment by addf400** [comment]
@srikar2097 The same happens in our experiments and does not affect the results.

**Comment by srikar2097** [comment]
@addf400 thank you for your reply. Good to know this metric does not affect results. 

Can you help us understand what does this metric measure and its significance?

**Comment by addf400** [comment]
@srikar2097  pre-training [log](https://gist.github.com/addf400/981ce608020ee72ce4cae9cc09ed82ec)
