### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by DivyaWadehra** [microsoft/unilm#61]
key error while generating questions on my text

**Comment by donglixp** [comment]
Could you provide more details of the error message?

**Comment by deora786** [comment]
I put few sentences from processed src-test file provided with this repo (processed).
but when I try to generate question over it it gives following errot.
similar thing happened for other words also, so it might be vocab issue. But when I run the code with mentioned file test.pa.tok.txt the code works fine.
  File "biunilm/decode_seq2seq.py", line 269, in <module>
    main()
  File "biunilm/decode_seq2seq.py", line 220, in main
    instances.append(proc(instance))
  File "/nq_gen/src/biunilm/seq2seq_loader.py", line 390, in __call__
    input_ids = self.indexer(tokens)
  File "/nq_gen/src/pytorch_pretrained_bert/tokenization.py", line 117, in convert_tokens_to_ids
    ids.append(self.vocab[token])
KeyError: 'notre'

these are the sentences:
atop the main building 's gold dome is a golden statue of the virgin mary .
begun as a one-page journal in september 1876 , the scholastic magazine is issued twice monthly and claims to be the oldest continuous collegiate publication in the united states .
the other magazine , the juggler , is released twice a year and focuses on student literature and artwork .
the newspapers have varying publication interests , with the observer published daily and mainly reporting university and other news , and staffed by students from both notre dame and saint mary 's college .
the nine student-run outlets include three newspapers , both a radio and television station , and several magazines and journals .

**Comment by cocaer** [comment]
@deora786  You can change the line 117 of pytorch_pretrained_bert/tokenization.py  like this
  
`            if token not in self.vocab:
                ids.append(self.vocab['[UNK]'])
            else:
                ids.append(self.vocab[token])
`

**Comment by donglixp** [comment]
@deora786   The input texts need to be tokenized before we input them to the model.

**Comment by donglixp** [comment]
> @deora786 You can change the line 117 of pytorch_pretrained_bert/tokenization.py like this
> 
> ` if token not in self.vocab: ids.append(self.vocab['[UNK]']) else: ids.append(self.vocab[token])`

It seems that the input texts are not pre-tokenized. So replacing the token with '[unk]' results in incorrect outputs.

**Comment by deora786** [comment]
Thank you, it worked when I removed '--tokenized_input' argument. Because of this change it used a tokenizer to tokenize the data before processing it.
