### ISSUE TITLE
layoutxlm inference

### ISSUE THREAD

**Issue by mao-jy** [microsoft/unilm#610]
I failed to find the inference code for layoutxlm, neither ser task nor re task. Could you please provide the inference code for these two part? Or can you give me some advice on how to perform the inference pipeline?

**Comment by congphu2511995** [comment]
Same question.

**Comment by taosean** [comment]
I'd like the inference too.

**Comment by Dod-o** [comment]
The inference is basically the same as the other code of the LayoutLM series, please refer to that code. If you have further questions about this, feel free to reopen this. :)
