### ISSUE TITLE
MarkupLM: Question about custom training

### ISSUE THREAD

**Issue by Misterion777** [microsoft/unilm#611]
Hello, thank you very much for a release of a great model!
Have couple questions:
1. How do you think is it possible to fine-tune MarkupLM on dataset containing types of form inputs (username/password etc.)? As inputs don't contain text it can lead to poor convergence, am I right?
2. Therefore have you considered using not only text of a webelement but also its attributes (css, id, etc.)? It should improve performance, isn't it?

**Comment by wolfshow** [comment]
1. Currently, MarkupLM is designed for information extraction and question answering tasks, where the required information needs to be represented using texts.
2. Yes, web attributes will be helpful especially where text information is missing.

**Comment by Misterion777** [comment]
Thanks, will continue my research on that
