### ISSUE TITLE
hi, where to download pretrained models for Japanese, Korean, etc.? steve8000818@gmail.com

### ISSUE THREAD

**Issue by nissansz** [microsoft/unilm#619]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): Trocr
hi, where to download pretrained models for Japanese, Korean, etc.? steve8000818@gmail.com

**Comment by wolfshow** [comment]
@nissansz Multilingual TrOCR models are our on-going efforts, please stay tuned.
