### ISSUE TITLE
Not able to execute last line of requirements.txt file in unilm/trocr. could not clone https://github.com/liminghao1630/fairseq.git. It throws error Repository not found

### ISSUE THREAD

**Issue by Devendranathhosur** [microsoft/unilm#623]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

- Platform:
- Python version:
- PyTorch version (GPU?):

**Comment by liminghao1630** [comment]
@yellowjs0304 @Devendranathhosur Hi, the code of TrOCR is adapted to the official version of fairseq and we have just updated the requirements file.
