### ISSUE TITLE
[MarkupLM] Model pruning

### ISSUE THREAD

**Issue by Misterion777** [microsoft/unilm#633]
Model I am using (UniLM, MiniLM, LayoutLM ...): MarkupLM

Are you planning to release pruned/distilled model for running on cpu? 
If not, maybe you can give some advice on how to increase inference performance?
Thank you.

**Comment by wolfshow** [comment]
@Misterion777 It is possible to pre-train MarkupLM small/tiny models once we have some bandwidth.
