### ISSUE TITLE
LayoutLMV2/LayoutXLM DocVQA Evaluation

### ISSUE THREAD

**Issue by oguz-akkas-deepsee** [microsoft/unilm#634]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...):  LayoutLMV2 and LayoutXLM models for DocVQA task.

I am wondering what metrics is being used for the evaluation. The original QA tasks use exact match and F1 score and transformer library provides metrics for squad tasks based on exact match and F1 score. But it requires some additional ground truth data. I am wondering anyone tried DocVQA with LayoutLMV2 or LayoutXLM and applied metrics.

**Comment by wolfshow** [comment]
@oguz-akkas-deepsee The metrics for DocVQA is introduced at https://rrc.cvc.uab.es/?ch=17&com=tasks
