### ISSUE TITLE
Downstream Task:Relation Extraction about layoutlmv2

### ISSUE THREAD

**Issue by lawsonxwl** [microsoft/unilm#636]
Thanks for solid work!
The question is that when we are training the RE module of layoutlmv2,one input is the token label (e.g question answer…),which is given in the dataset.If I do predictions, where can I get the token label? If I get it from the prediction of NER head of layoutlmv2 , should I train 2 models,one is for NER,one is for RE? Or jointly train the model? I can’t find the joint training code of the task!

谢谢你们的工作！
当我需要使用关系提取这个下游任务时，我需要输入关系中的head和tail，如何去获取这类信息？如果要通过layoutlmv2下游的ner去获取的话，那我是要分开训练两个模型去完成两个任务，还是做多任务学习，联合训练ner和re两个task？没有在release里面看到联合训练的代码 所以想知道怎么去做这个关系提取的任务！

**Comment by NielsRogge** [comment]
Hi,

The best information regarding relation extraction with LayoutLMv2 can be found [here](https://github.com/huggingface/transformers/issues/15451). It includes a Colab notebook with more info.

**Comment by lawsonxwl** [comment]
> Hi,
> 
> The best information regarding relation extraction with LayoutLMv2 can be found [here](https://github.com/huggingface/transformers/issues/15451). It includes a Colab notebook with more info.

Thanks a lot! I will check it out asap

**Comment by sujit420** [comment]
LayoutLMv2ForRelationExtraction is this head present in transformers now? i get import error.
