### ISSUE TITLE
When will DeepNorm release code ?

### ISSUE THREAD

**Issue by sean-zhuh** [microsoft/unilm#639]
As the title asks.

**Comment by donglixp** [comment]
The code will be updated at https://github.com/microsoft/unilm/tree/master/deepnet soon

**Comment by sean-zhuh** [comment]
Thanks.

**Comment by iiLaurens** [comment]
Any updates here?

**Comment by shumingma** [comment]
The code will be ready very soon. Please stay tuned!

**Comment by donglixp** [comment]
@sean-zhuh @iiLaurens https://github.com/microsoft/torchscale
