### ISSUE TITLE
Alternative Download Link

### ISSUE THREAD

**Issue by NoviScl** [microsoft/unilm#64]
Dear authors,

I can't access and download the pretrained model via the provided download link. Could you please provide an alternative download link that allows quick download access in mainland China? 

Thanks!

**Comment by donglixp** [comment]
You could try the following link https://unilm.blob.core.windows.net/ckpt/unilm1-large-cased.bin . 
 
unilm1-large-cased: 24-layer, 1024-hidden, 16-heads, 340M parameters
