### ISSUE TITLE
 got an unexpected keyword argument '_configuration_file'

### ISSUE THREAD

**Issue by sibrun** [microsoft/unilm#640]
**Describe the bug**
got an unexpected keyword argument '_configuration_file'

The problem arises when using:
model_xlm= LayoutLMv2ForTokenClassification.from_pretrained("microsoft/layoutxlm-base")

TypeError                                 Traceback (most recent call last)
Input In [3], in <cell line: 8>()
      5 tokenizer_xlm = LayoutXLMTokenizer.from_pretrained("microsoft/layoutxlm-base")
      6 processor_xlm = LayoutXLMProcessor(feature_extractor_xlm, tokenizer_xlm)
----> 8 model_xlm= LayoutLMv2ForTokenClassification.from_pretrained("microsoft/layoutxlm-base")

File ~/PycharmProjects/receiptlayoutlm/venv/lib/python3.9/site-packages/transformers/modeling_utils.py:1489, in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   1487 else:
   1488     with no_init_weights(_enable=_fast_init):
-> 1489         model = cls(config, *model_args, **model_kwargs)
   1491 if from_pt:
   1492     # restore default dtype
   1493     if dtype_orig is not None:

TypeError: __init__() got an unexpected keyword argument '_configuration_file'

**To Reproduce**
1. from transformers import LayoutLMv2ForTokenClassification
2. model_xlm= LayoutLMv2ForTokenClassification.from_pretrained("microsoft/layoutxlm-base")

**Expected behavior**

- Platform: Mac arm (M1 max), Mac OS 12.2.1
- Python version: Python 3.9.8 x86

**Comment by NielsRogge** [comment]
Hi,

We fixed this recently, please upgrade Transformers to v4.17: `pip install --upgrade transformers `
