### ISSUE TITLE
vlmo release

### ISSUE THREAD

**Issue by tanshy17** [microsoft/unilm#650]
Looking forward to your open-source code!
 Thanks a lot!

**Comment by onejune2018** [comment]
Looking forward to your open-source code! +1

**Comment by zsmmsz99** [comment]
Thanks for your excellent work! I am really looking forward to your open-source code to help me understand your work.

**Comment by xhyandwyy** [comment]
Looking forward to your open-source code!
Thanks a lot!

**Comment by addf400** [comment]
Hi everyone, [VLMo code & models](https://github.com/microsoft/unilm/tree/master/vlmo) has been released. Thanks for your attention!
