### ISSUE TITLE
some requirements about Utterance Mixing?

### ISSUE THREAD

**Issue by A-New-Page** [microsoft/unilm#652]
Model I am using (WavLM):
Recently, I had read the paper about WavLM. A data augmentation named Utterance Mixing was proposed in this paper.
I wonder that how does Utterance Mixing process data label?
Could you please share the code about Utterance Mixing?
Thanks a lot

**Comment by Sanyuan-Chen** [comment]
Hi @A-New-Page , the utterance mixing method only processes the input audio but the label. For the detailed codes, please refer to [here](https://github.com/microsoft/UniSpeech/blob/295c961c0c08c135b2b145c0c9ae0f9836e37729/src/fairseq/data/audio/utterance_mixing_dataset.py#L373)~
