### ISSUE TITLE
Use LayoutXLM without prior OCR 

### ISSUE THREAD

**Issue by LucaWeissbeck** [microsoft/unilm#656]
**Describe**
Hi, 

I am trying to use the LayoutXLM model from Huggingface. For the LayoutLMv2 model there is a "no-ocr" revision available, allowing me to skip the OCR step when instantiating the processor like this:
 
`LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")`.

There is however no "no-ocr" revision available for the LayoutXLM model and I was wondering if there was a way to skip the OCR step when loading in the model? The reason being that I want to train it with my own OCR annotations.

Thank you!

**Comment by ManuelFay** [comment]
Yup !
```
tokenizer = LayoutXLMTokenizerFast.from_pretrained(self.processor_name, use_auth_token=self.use_auth_token)
processor_no_ocr = LayoutXLMProcessor(LayoutLMv2FeatureExtractor(apply_ocr=False), tokenizer)
```
