### ISSUE TITLE
System configuration for running abstractive summarization inference

### ISSUE THREAD

**Issue by chandrasekharan98** [microsoft/unilm#66]
Hi there
I'm trying to run the decoding for abstractive summarization (CNN/DM) on CPU mode after referring [#23 ](https://github.com/microsoft/unilm/issues/23#issuecomment-549788510). 

I don't have a CUDA capable device and would like to know the required system configuration to run it. I'd like to know if there are other ways to run the decoding other than beam search too.

Thanks,
M Chandrasekharan

**Comment by donglixp** [comment]
Decoding on GPUs would be much faster than CPU. The beam size can be set to 1 for greedy search.
