### ISSUE TITLE
Markuplm output

### ISSUE THREAD

**Issue by tejaShreeDevathoti** [microsoft/unilm#669]
**Describe**
What is the exact output which will be given by markuplm model?
I was looking at the websrc dataset and there are some csv files which have question, id, element id, answer start and answer. what do the fields id,element id and answer start represent here?

**Comment by lockon-n** [comment]
Hi.
MarkupLM is an encoder, and the output depends on the downstream task. In the case of WebSRC, the element id and answer start are used to locate the answer in the page, and you can find more details in WebSRC's baseline repo. Our code is adapted from there.
