### ISSUE TITLE
Rouge version 

### ISSUE THREAD

**Issue by zhenduow** [microsoft/unilm#67]
Hi, I got the following error when I ran the cnn_dm evaluation. It's a potential version issue of the rouge package. Do you suggest any fix? Thank you!

`Traceback (most recent call last):`
`File "cnndm/eval.py", line 60, in <module>`
`limit_length=False, apply_avg=True, weight_factor=1.2)`
`TypeError: __init__() got an unexpected keyword argument 'max_n'`

**Comment by donglixp** [comment]
there's an instruction at https://gist.github.com/donglixp/d7eea02d57ba2e099746f8463c2f6597

**Comment by donglixp** [comment]
The error is thrown by the python-version rouge. The package can be installed by `pip install pyrouge`

**Comment by Doragd** [comment]
i got the same error and fix it. maybe the right command is `pip install py-rouge` rather than `pyrouge`

**Comment by donglixp** [comment]
> i got the same error and fix it. maybe the right command is `pip install py-rouge` rather than `pyrouge`

`pip install --user methodtools py-rouge pyrouge nltk`
