### ISSUE TITLE
Layoutlmv2 has worse performance than Layoutlm in my application

### ISSUE THREAD

**Issue by weicheng113** [microsoft/unilm#673]
Hi, Thanks for the great effort on these models and sharing them. We have been using Layoutlm for some time in our application for processing documents and recently we were trying to upgrade to layoutlmv2. But the performance of Layoutlmv2 model is worse than Layoutlm in our application. I did a thorough check on possible issues. Especially the image part, which did not seem to help in our case. I noticed FUNDSD images are in 8-bit png and the images from our application are 24-bit png. They are using same approach to load image `read_image(image_path, format="BGR")`. I wonder if the pre-training was all happening in 8-bit single-channel documents and does not help with 24-bit 3-channels images?

I checked source code of visual embedding, LayoutLMv2Model._calc_img_embeddings. I printed out the first element of `visual_embeddings` below:

```python
visual_embeddings = self.visual_proj(self.visual(image))
```

**A image(8-bit png) from FUNDSD:**
```python
[ -3.1740, -19.5325, -17.6258, -41.0830,  14.8796, -16.7890,   8.2852,
          4.3023,  -1.5895, -27.1117,  -7.7672, -11.5292,   7.7387,   8.7509,
         -4.2084,  43.6889,   2.6693, -28.2799,  -0.9754,  19.2036,   6.1338,
         -2.0944,  -1.0661,  -1.0726, -11.1030, -19.9556,  11.4620, -19.2465,
         -3.3918,  31.1710,  -4.0068,  -5.4833, -29.0767,   5.6156,  -2.0539,
          3.7459,  -5.1293, -41.6844,   1.3231, -38.7568,  23.4855,  13.4585,
         30.6572, -29.0449,   3.1046,  24.3876,  -0.0715,   4.8418,  -3.2398,
         22.1056,  11.8907,  16.0874,  -7.6768, -31.6189,   4.7176, -10.2356,
        -11.5233,  -9.7202,  18.3381, -24.3413,  10.1119,   2.4823,  -3.4822...]
```

**An image(24-bit png) from our application**
```
[    -2.7996,    -19.3788,    -17.6382,    -41.4484,     15.3426,    -16.7949,      8.3348,      3.1472,
            -1.4723,    -25.9805,     -7.6889,    -11.5520,      8.0384,      8.9263,     -4.2765,     43.7596,
             2.5592,    -27.5958,     -0.5952,     19.6237,      7.0326,     -2.8496,     -1.0592,     -0.5172,
           -10.7896,    -20.2233,     11.8002,    -18.4645,     -3.5781,     31.6387,     -3.5289,     -5.5921,
           -29.1544,      5.7319,     -1.7204,      3.9475,     -4.8967,    -41.0276,      1.4746,    -38.8907,
            24.1194,     13.6168,     29.9929,    -29.1921,      3.3811,     22.4722,      0.0899,      5.9834,
            -3.6405,     20.4297,     11.8799,     16.2553,     -7.4934,    -31.4496,      4.6958,    -10.3268,
           -11.1490,    -10.0465,     18.8328,    -24.3179,     10.1716,      2.8778,     -3.7097,     33.4953,
           -18.7539,     24.8221,     -1.2665,    -18.5354,     12.6866,     -9.2096,     17.5006,     30.9514...]
```

It does not look too much different between the two. Any suggestions will be highly appreciated. 

Thanks,
Cheng

**Comment by wolfshow** [comment]
Yes, the pre-training data is IIT-CDIP, which are documents in black and white colors.

**Comment by weicheng113** [comment]
@wolfshow , Thanks a lot. I am trying to write pre-training code and do pre-training myself at the moment. Although the paper gives the formulas, it will be to write a correct implementation. If I put my attempt code somewhere, is it possible to get some help or confirmation from you? Thanks.
