### ISSUE TITLE
How to pretrain wavLM ? 

### ISSUE THREAD

**Issue by StephennFernandes** [microsoft/unilm#675]
Hey there, i have around 7K hours of labelled and 10K hours of unlabelled speech corpus for a total of 22 languages. Can someone please show me how could I pretrain wavLM on the following dataset. also would 10K hours of pretraining data suffice in pretraining a reasonable good enough multi lingual wavLM ?

**Comment by Sanyuan-Chen** [comment]
Hi @StephennFernandes ,

As for the WavLM pre-training, you can follow the instructions of HuBERT pre-training as [here](https://github.com/pytorch/fairseq/tree/main/examples/hubert), and implement the noisy/overlapped speech simulation method as [here](https://github.com/microsoft/UniSpeech/blob/main/src/fairseq/data/audio/utterance_mixing_dataset.py#L373) and the gated relative position bias as [here](https://github.com/microsoft/UniSpeech/blob/295c961c0c08c135b2b145c0c9ae0f9836e37729/src/fairseq/modules/multihead_attention.py#L259).
