### ISSUE TITLE
Fine-tune the currently released WavLM base+ for non-English ASR

### ISSUE THREAD

**Issue by bitMyron** [microsoft/unilm#678]
Hi there, I would like to learn if you have done experiments using your currently released WavLM Base+ model (trained with English-only audios) to fine-tune an ASR for non-English language, say Chinese. If you have experimented with other languages, what's the best performance you get? From your point of view, do you think it makes sense to fine-tune an English-only pre-trained model for ASR for other languages, especially non-Germanic languages?

Besides, do you have any plan of releasing a multilingual version of pre-trained WavLM model?

**Comment by MarkWuNLP** [comment]
> Hi there, I would like to learn if you have done experiments using your currently released WavLM Base+ model (trained with English-only audios) to fine-tune an ASR for non-English language, say Chinese. If you have experimented with other languages, what's the best performance you get? From your point of view, do you think it makes sense to fine-tune an English-only pre-trained model for ASR for other languages, especially non-Germanic languages?
> 
> Besides, do you have any plan of releasing a multilingual version of pre-trained WavLM model?

Hi, we did not try to fine-tune wavlm for non-English ASR, and I don't think it makes sense.  You can use other pre-trained models, such as cross-lingual wav2vec for this purpose. 

Until now, we don't have a plan to release multilingual pre-trained wavlm models.
