### ISSUE TITLE
How to pretrain mT6 from scratch on a custom dataset 

### ISSUE THREAD

**Issue by StephennFernandes** [microsoft/unilm#681]
Hi there, I am looking forward to pretraining mT6 on a custom text corpus, could someone please show me the step on how to pretrain the mT6 model . 

Following i have a large text corpus of 22 langauges how should the dataset be arranged should the dataset be sorted completely, that mixes all the languages together where one sentence/paragraph is eg: french, german, hungarian,french etc ... 

Or should I keep the corpus sequential as in, one langauges entire text followed by another langauges entire text ?

**Comment by jsl5710** [comment]
Where can I find the mT6 model?
