### ISSUE TITLE
gt_valid.txt  can't get IAM dataset

### ISSUE THREAD

**Issue by kissSuperMan** [microsoft/unilm#682]
**Describe**
my error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/dataset/gt_valid.txt'
```
I want use IAM uder this url:
https://fki.tic.heia-fr.ch/databases/download-the-iam-handwriting-database
on this web dataset update to v3.0.I can't get the dataset that your use. where can get the IAM dataset that you use?

**Comment by liminghao1630** [comment]
You should prepare the IAM dataset following the instruction on this link: https://github.com/jpuigcerver/Laia/tree/master/egs/iam. 
And the dataset dir structure should be like:
```
dataset_dir
│   gt_test.txt
|   gt_train.txt
|   gt_valid.txt
└───image
    │   image001.jpg
    │   image002.jpg
    │   ...
```
while the gt_{train, valid, test}.txt is in the line format of "{image filename}\t{ground text}\n" for each image file.
