### ISSUE TITLE
LayoutReader: random mask of training

### ISSUE THREAD

**Issue by tengerye** [microsoft/unilm#683]
**Describe**
Model I am using is LayoutReader, and happened to find perhaps there is something wrong with the random mask part of training.

The [corresponding code](https://github.com/microsoft/unilm/blob/e4929f812398207b7fefb4dda6e9debcb8ce34b9/layoutreader/s2s_ft/utils.py#L205) is as follows:
```
pseudo_ids = []
for tk_id in target_ids:
    p = random.random()
    if p < self.keep_prob:
        pseudo_ids.append(tk_id)
    elif p < self.keep_prob + self.random_prob:
        pseudo_ids.append([random.randint(0, self.vocab_size - 1)] + [0, 0, 0, 0])  # tk_id[1:])
    else:
        pseudo_ids.append([self.mask_id] + [0, 0, 0, 0])  # tk_id[1:])
```
With the positional embeddings [0, 0, 0, 0], the model could easily find it is not the original token ids, isn't it? Why not keep the original coordinates as in comments.

**Comment by zlwang-cs** [comment]
Thanks for your interests in our work. In this masking, it's true that this makes it easier to distinguish whether a word is original or replaced. However, the pretraining is to ask the model to recover the tokens so I think it is not a big issue if we use the 0000 as the position embedding.

**Comment by tengerye** [comment]
@zlwang-cs Hi, thank you for your kind reply. I understand it is not a big issue. However, why don't you fix it since you have already found it as in comments.
