### ISSUE TITLE
Hyperparameters for finetuning LayoutXLM relationExtraction on FUNSD

### ISSUE THREAD

**Issue by BaharSalamatian** [microsoft/unilm#685]
Hi all, 

Many thanks for your excellent work on the LayoutXLM paper.

I am reproducing LayoutXLM relation extraction fine-tuning on the FUNSD dataset. (Training in FUNSD and test on FUNSD)

The best f1-score I get is about 0.39, although the paper mentioned that it is 0.54. Can you please share the hyperparameters that you used on paper?

**Comment by wolfshow** [comment]
https://github.com/microsoft/unilm/issues/586

**Comment by munish0838** [comment]
> Hi all,
> 
> Many thanks for your excellent work on the LayoutXLM paper.
> 
> I am reproducing LayoutXLM relation extraction fine-tuning on the FUNSD dataset. (Training in FUNSD and test on FUNSD)
> 
> The best f1-score I get is about 0.39, although the paper mentioned that it is 0.54. Can you please share the hyperparameters that you used on paper?

Hi @BaharSalamatian could you please share the process/code for training LayoutXLM for RE on FUNSD. I have been unsuccessful in figuring out how to get it working. IT would be really helpful
