### ISSUE TITLE
DiT object detectoin with custom data test data register 

### ISSUE THREAD

**Issue by jigsawcoder** [microsoft/unilm#688]
I am using Dit Base Cascade R-CNN to train my custom data for table detection using the config file :                        icdar19_configs/cascade/cascade_dit_base.yaml                                                                                                                    
I have replaced publaynet and icdar data path to my own custom data path in config file to register my dataset as follows:                                                                                           
In train_net.py                                                                                                          

******************** code *************************                                                                             
  def main(args):
      register_coco_instances(
          "publaynet_train",
          {},
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/train.json",
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/train_img"
      )
  
      register_coco_instances(
          "publaynet_val",
          {},
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/val.json",
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/val_img"
      )
  
      register_coco_instances(
          "icdar2019_train",
          {},
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/train.json",
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/train_img"
      )
  
      register_coco_instances(
          "icdar2019_test",
          {},
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/val.json",
          "/content/drive/MyDrive/tabelcell_detection_dert/dataset/val_img"
      )                                                                                                                   

******************** code *************************                                                                                                                                         

The problem arises when using:
During evaluation, its shows this error...                                                                                                     
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/tablecell_dit/unilm/dit/object_detection/data/test/cTDaR_t00000.xml'                                                                                                    

I am assuming that the model is looking for icdar dataset in the data/test folder for evaluation.                                                           

I want to know to register my own custom data for evaluation.

Here is the environment configuration:                                                                            
sys.platform            linux
Python                  3.7.13 (default, Mar 16 2022, 17:37:17) [GCC 7.5.0]
numpy                   1.21.5
detectron2              0.6 @/usr/local/lib/python3.7/dist-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5, 8.0, 8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.10.0+cu111 @/usr/local/lib/python3.7/dist-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   Tesla K80 (arch=3.7)
Driver version          460.32.03
CUDA_HOME               /usr/local/cuda
Pillow                  7.1.2
torchvision             0.11.1+cu111 @/usr/local/lib/python3.7/dist-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220414
iopath                  0.1.9
cv2                     4.1.2

**Comment by Dod-o** [comment]
Hi @jigsawcoder, you can modify the dataset name [here](https://github.com/microsoft/unilm/blob/bf6ae628b44d743f4b0b398090fb050ecbc8426e/dit/object_detection/icdar19_configs/Base-RCNN-FPN.yaml#L40) and make sure there is no "icdar" in the new name.
If "icdar" is in your dataset name, it will use the icdar evaluator. Or you can modify the code [here](https://github.com/microsoft/unilm/blob/bf6ae628b44d743f4b0b398090fb050ecbc8426e/dit/object_detection/ditod/mytrainer.py#L600) to use a custom evaluator.

**Comment by jigsawcoder** [comment]
Can you please guide me how to change the labels as well, I want to fine-tune Dit Base Cascade R-CNN (ICDAR 19 Table Detection) on custom data with 2 classes.

**Comment by jigsawcoder** [comment]
Also, I want to add that while inferring Dit Base Cascade R-CNN (ICDAR19 Table Detection), the results shows only 'text' as label where it was supposed to be 'table'.
