### ISSUE TITLE
Visual Tokens LayoutLMv2

### ISSUE THREAD

**Issue by LucaWeissbeck** [microsoft/unilm#689]
Hi,

I am using LayoutLMv2 as part of a uni assignment and I am trying to make sense of how the visual embeddings work within LayoutLMv2. It made total sense to me that there was **one** visual token for each word in LayoutLMv1.

I don't entirely understand how it works in LayoutLMv2? I understand that the main difference between v1 and v2 is that in v2 visual and text tokens are treated **completely separately** for the model input and v2 also takes in visual embeddings during the pre-training stage. However, I don't understand what the visual tokens are entirely in v2? Is there one visual token for each text token?(I don't think so) Judging from the original source in which LayoutLMv2 was published, the visual tokens are of length W*H. I believe that W and H are both 224 pixels, as that represents the down-scaled image. 

**_How is the model making sense of just random visual tokens that don't necessarily belong to a text token?_**

I have tried researching online but could not find a good source for this question. I would highly appreciate it if anybody could help me on this. Thank you! :)

**Comment by wolfshow** [comment]
LayoutLMv2 split the input images with 224x224 into 7x7=49 visual tokens, where each visual token (32x32) usually contains information with more than one text token. The overall image-text correlation learning is achieved by the text-image matching&alignment pre-training tasks.

**Comment by LucaWeissbeck** [comment]
Hi wolfshow, I really appreciate your answer! I hope you don't mind me asking a follow up question; The TIA and TIM makes sense to me during the pre-training stage. Am I correct in saying that through TIA, LayoutLMv2 knows during the Fine Tuning stage which visual token a specific text token most likely belongs to? This way LMv2 would know about the visual context of a token, which would make sense to me, as it would mean, that LMv2 could calculate an attention score that includes the visual context. Please correct me if I am wrong!
