### ISSUE TITLE
Hi @MarouaneMaachou, we did not use the official OCR provided by SROIE dataset, so we cannot provide the pre-processing script for SROIE dataset. If you would like to use the official SROIR dataset, you need to break down the textline OCR into token-level OCR, and map the sequence labels to the input tokens.

### ISSUE THREAD

**Issue by PushpaYa** [microsoft/unilm#691]
Hi @MarouaneMaachou, we did not use the official OCR provided by SROIE dataset, so we cannot provide the pre-processing script for SROIE dataset. If you would like to use the official SROIR dataset, you need to break down the textline OCR into token-level OCR, and map the sequence labels to the input tokens.

_Originally posted by @wolfshow in https://github.com/microsoft/unilm/issues/100#issuecomment-610838599_

**Comment by PushpaYa** [comment]
Hi ,I want to reproduce layoutLM V2 results for SROIE .
But I can see opensource version of dateset need to be prepossessed and mapped with entities present in another file.
at the end resulted dateset results are not matching with paper mentioned F1 score .
Can you please guide me how to reproduce results .
is it possible to share dateset used ?

**Comment by wolfshow** [comment]
@PushpaYa You may need to use some OCR tools with higher accuracy so that the overall information extraction results can be improved.
