### ISSUE TITLE
Can not download LayoutLMv3 from huggingface

### ISSUE THREAD

**Issue by buptcjj** [microsoft/unilm#697]
There is some trouble when I download LayoutLMv3 from huggingface
But I can correctly download microsoft/layoutlm-base-uncased from huggingface.

My Python code:
tokenizer = AutoTokenizer.from_pretrained("microsoft/layoutlmv3-base", do_lower_case=True, model_max_length=128)

The error :
Tokenizer class LayoutLMv3Tokenizer does not exist or is not currently imported.

My transformer'version is 4.18.0, torch's version is 1.6.0.

**Comment by seanbenhur** [comment]
The model is not yet available in transformers, you have to copy all the code from this [repo](https://github.com/microsoft/unilm/tree/master/layoutlmv3/layoutlmft/models) to the transformers directory and then try using it.

**Comment by HYPJUDY** [comment]
Thanks @seanbenhur for the clarification. Yes currently we only support loading models of LayoutLMv3 from the Hugging Face Model Hub with codes of [unilm/layoutlmv3](https://github.com/microsoft/unilm/blob/master/layoutlmv3/README.md) but not with [huggingface/transformers](https://github.com/huggingface/transformers).
For example, the following code will successfully initialize `PreTrainedTokenizerFast(name_or_path='microsoft/layoutlmv3-base', ...)` by setting `--model_name_or_path microsoft/layoutlmv3-base` following [the README to fine-tuning the FUNSD](https://github.com/microsoft/unilm/blob/f6e1cc904c/layoutlmv3/README.md#receipt-understanding-on-funsd).
https://github.com/microsoft/unilm/blob/f6e1cc904ce342066f152f1cfd74005008dbeaa1/layoutlmv3/examples/run_funsd_cord.py#L263-L271

**Comment by wolfshow** [comment]
@buptcjj please also follow these:

https://github.com/huggingface/transformers/issues/16914
https://github.com/huggingface/transformers/issues/16949

**Comment by wolfshow** [comment]
@NielsRogge is working on adding LayoutLMv3.

https://github.com/huggingface/transformers/pull/17060

**Comment by renjithsasidharan** [comment]
I have used @NielsRogge PR and trained the model on CORD dataset.
Here is the code if you want to have a look at it. https://github.com/renjithsasidharan/layoutlmv3_cord/blob/main/Finetune_LayoutLMV3_on_CORD.ipynb
