### ISSUE TITLE
The performance of the self-supervised model pretrained on ImageNet-22k

### ISSUE THREAD

**Issue by ZhangYikaii** [microsoft/unilm#698]
**Describe**

Hi, I am using BEiT. Can you provide the performance of the self-supervised model pretrained on ImageNet-22k?
Thank you.
![image](https://user-images.githubusercontent.com/46623714/165014819-f8d4c8fc-8f88-4218-93e6-db24284ac770.png)

**Comment by donglixp** [comment]
The results can be found at https://github.com/microsoft/unilm/tree/master/beit#fine-tuning-on-imagenet-1k-image-classification and https://github.com/microsoft/unilm/tree/master/beit#fine-tuning-on-imagenet-1k-image-classification
