### ISSUE TITLE
Replacing 1 by #

### ISSUE THREAD

**Issue by Colanim** [microsoft/unilm#7]
In this line (code for evaluation of CNNDM) 

https://github.com/microsoft/unilm/blob/d22a233978842b824b449bcce6a5bd71aa98f952/src/gigaword/eval.py#L239

`1` is replaced by `#`.

I don't understand it. **Can someone explain me the reason of such post-processing ?**

**Comment by donglixp** [comment]
The file unilm/src/gigaword/eval.py follows the gigaword data preprocessing as in https://github.com/harvardnlp/sent-summary, which substitutes all the digits to `#`. However, our bpe tokenizer uses `#` to indicate subwords. So we preprocess the special token `#` to `1`, and then replace them back after prediction. Notice that the unilm/src/cnndm/eval.py script doesn't use the preprocess.
