### ISSUE TITLE
'task' variable/parameter is not defined in the script run_seq_labeling.py

### ISSUE THREAD

**Issue by al281** [microsoft/unilm#70]
`task` variable in he function call 

```
read_examples_from_file(args.data_dir, mode, task)
```
in the script `run_seq_labeling.py` is not defined.

https://github.com/microsoft/unilm/blob/7f931fcfb965bf60f0fbe2ddd37798f356e6ee5e/layoutlm/run_seq_labeling.py#L417

**Comment by ranpox** [comment]
Hi @al281,
Thanks for your feedback. We have fixed this error in https://github.com/microsoft/unilm/commit/c657b003366c2d6eb79b147f4827a1c56446287a. Please update and try again.
