### ISSUE TITLE
Question about "TrOcr" at "Fine-tuning on IAM"

### ISSUE THREAD

**Issue by Fyzjym** [microsoft/unilm#706]
### Describe
When I type the command following the tutorial, the terminal shows the following.
Please help me, why is this happening? The code seems to be missing parameters.

![`LZPGW)E 4$Z_II@045`NOJ](https://user-images.githubusercontent.com/45482176/166189271-e786df91-48d1-4eae-9309-800fb6b112ed.png)
![6FA67TTPQDM BDF5PTH_%19](https://user-images.githubusercontent.com/45482176/166189471-1c4d51f8-66b7-4661-bb2f-2cf82a8c0e80.png)

**Comment by liminghao1630** [comment]
Remove the space and comment after "--arch trocr _large \".  @Fyzjym
