### ISSUE TITLE
LayoutLMv3 License Clarification

### ISSUE THREAD

**Issue by calebripley** [microsoft/unilm#707]
Looking to explore the use of LayoutLMv3 in a commercial application. The unilm repo is under the MIT license, but there is a comment in the LayoutLMv3 repo README mentioning it is licensed under a different license that does not allow commercial use. This same comment is in all of the LayoutLM repos.

Can LayoutLMv3 or any other versions be used under the same license as its parent directory? If not, is it within the realm of possibility to change the license to MIT?

Thanks.

**Comment by calebripley** [comment]
https://github.com/microsoft/unilm/issues/352

**Comment by agiulianomirabella** [comment]
Can LayoutLMv3 be used in a commercial application?

**Comment by ppaanngggg** [comment]
> Can LayoutLMv3 be used in a commercial application?

No, I think
