### ISSUE TITLE
size mismatch MiniLM hidden size and bert embeddings

### ISSUE THREAD

**Issue by adfi** [microsoft/unilm#71]
Hi, 

Thanks for open sourcing all the code and writing the documentation to use it. I managed to get most of it working. However, when running the decode step for MiniLM on the summarization task I'm getting the following error:

03/03/2020 16:28:27 - INFO - s2s_ft.modeling_decoding -   n_config_pos_emb*config.hidden_size != state_dict[bert.embeddings.position_embeddings.weight] (1*768 != 384)
Traceback (most recent call last):
  File "decode_seq2seq.py", line 319, in <module>
    main()
  File "decode_seq2seq.py", line 217, in main
    no_segment_embedding=args.no_segment_embedding,
  File "/home/adnan_fiaz/code/unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 913, in from_pretrained
    assert state_dict[_k].shape[1] % config.hidden_size == 0
AssertionError

The model config (which is printed just before the error) looks like this:
03/03/2020 16:28:24 - INFO - s2s_ft.modeling_decoding -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "ffn_type": 0,
  "fp32_embedding": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "label_smoothing": null,
  "max_position_embeddings": 150,
  "new_pos_ids": false,
  "no_segment_embedding": false,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "num_qkv": 0,
  "relax_projection": 0,
  "seg_emb": false,
  "task_idx": 3,
  "type_vocab_size": 2,
  "vocab_size": 28996
}

Just wondering if the hidden size is correct, shouldn't that be 384? Have the wrong pre-trained weights been downloaded? I downloaded the pre-trained MiniLM-L12-H384-uncased model as that was the only one available.

**Comment by WenhuiWang0824** [comment]
It seemed that the config file is loaded incorrectly. Could you share with me the decoding script you used?

**Comment by adfi** [comment]
`python decode_seq2seq.py \
  --fp16 --tokenizer_name ${VOCAB_PATH}/minilm-l12-h384-uncased-vocab-nlg.txt \
  --input_file ${INPUT_JSON} --split $SPLIT --do_lower_case \
  --model_recover_path ${MODEL_PATH} --max_seq_length 150 --max_tgt_length 20 --min_len 5 --batch_size 32 --beam_size 5 \
  --length_penalty 0 --forbid_duplicate_ngrams --mode s2s --forbid_ignore_word "." --need_score_traces`

**Comment by WenhuiWang0824** [comment]
If you use the s2s-ft package to perform training on the summarization task, the config file will be automatically saved into the output model path so that it can be loaded during decoding. Could you verify that the MODEL_PATH/ contains the config JSON file saved during training?

**Comment by adfi** [comment]
There is a `train_opt.json` in the MODEL_PATH folder with the following contents:

{
  "adam_epsilon": 1e-08,
  "cache_dir": "transformer_package_cache",
  "cached_train_features_file": null,
  "config_name": "MiniLM-L12-H384-uncased/minilm-l12-h384-uncased-config.json",
  "do_lower_case": true,
  "fp16": true,
  "fp16_opt_level": "O2",
  "gradient_accumulation_steps": 1,
  "keep_prob": 0.1,
  "label_smoothing": 0.1,
  "learning_rate": 0.0001,
  "local_rank": -1,
  "log_dir": null,
  "logging_steps": 500,
  "max_grad_norm": 1.0,
  "max_source_seq_length": 150,
  "max_target_seq_length": 20,
  "model_name_or_path": "MiniLM-L12-H384-uncased/minilm-l12-h384-uncased.bin",
  "model_type": "bert",
  "no_cuda": false,
  "num_training_epochs": 10,
  "num_training_steps": 1000,
  "num_warmup_steps": 500,
  "output_dir": "model_minilm",
  "per_gpu_train_batch_size": 16,
  "random_prob": 0.1,
  "save_steps": 1500,
  "seed": 42,
  "server_ip": "",
  "server_port": "",
  "tokenizer_name": "MiniLM-L12-H384-uncased/minilm-l12-h384-uncased-vocab-nlg.txt",
  "train_file": "train.json",
  "weight_decay": 0.01 }

That looks different from the config file that is loaded when decoding.

**Comment by adfi** [comment]
After a little more digging, the config that is loaded comes from `bert-base-cased.tar.gz` which is downloaded from https://s3.amazonaws.com/models.huggingface.co/bert/ when the model is loaded in.  

Is that the correct config or should it point to somewhere else?

**Comment by WenhuiWang0824** [comment]
Thank you for the information.  We are working on the updates and will fix the issue ASAP.

**Comment by WenhuiWang0824** [comment]
Hi, we have updated the s2s-ft package. The saved path for the fine-tuned models is slightly different from the previous version. If you would like to run decoding using the previously trained models, please rename the model.${step}.bin file into pytorch_model.bin, and put the [config file](https://github.com/microsoft/unilm/files/4303383/config.zip) into the same folder or specify the config path in the decoding script.

**Comment by adfi** [comment]
That did the trick, thanks!
