### ISSUE TITLE
Training on RVL-CDIP Dataset for image/document classification - LayoutLMv3

### ISSUE THREAD

**Issue by sudheendrabk** [microsoft/unilm#710]
Hi, 
I would like to know the steps to train rvl-cdip dataset for document classification in layoutlmv3.

**Comment by HYPJUDY** [comment]
Hi, thanks for your question.
We have released the [`class LayoutLMv3ForSequenceClassification`](https://github.com/microsoft/unilm/blob/master/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py#L1177) for the document image classification task, but we currently have no plan to release our OCR data or fine-tuning code of the RVL-CDIP dataset. 
You may try to use the [officially provided images and OCR data](https://www.cs.cmu.edu/~aharley/rvl-cdip/) firstly. Then, you can write the fine-tuning codes with your custom dataloader and trainer for RVL-CDIP. Please find the training hyperparameters and data splits in the [paper (Section 3.3)](https://arxiv.org/pdf/2204.08387.pdf).
You can also refer to the codes for [fine-tuning LayoutLMv3 on other datasets](https://github.com/microsoft/unilm/blob/master/layoutlmv3/examples/run_funsd_cord.py), for [fine-tuning DiT on RVL-CDIP](https://github.com/microsoft/unilm/tree/master/dit/classification) or [other sequence classification codes](https://github.com/huggingface/transformers/tree/main/examples/pytorch/text-classification).

**Comment by sudheendrabk** [comment]
Hi, Thanks for your reply.

Please let me know the process for commercial usage of layoutlmv3. I can start the process using my official email id.
let me know otherwise.

**Comment by HYPJUDY** [comment]
Please refer to https://github.com/microsoft/unilm/issues/707. Thanks.
