### ISSUE TITLE
UniLM v2 checkpoint

### ISSUE THREAD

**Issue by natuan** [microsoft/unilm#711]
**Describe**
I would like to try out the UniLM v2 model but am unable to find it. Is the checkpoint available (here or from HuggingFace)? Thank you!

**Comment by addf400** [comment]
Thanks for your kind words. You can find the checkpoint at [there](https://github.com/microsoft/unilm/tree/master/s2s-ft#pre-trained-models).

**Comment by natuan** [comment]
Thanks!
