### ISSUE TITLE
Isn't LayoutXLM-large is the public model?

### ISSUE THREAD

**Issue by yellowjs0304** [microsoft/unilm#712]
Hi, Thank you for sharing your work. I'm using the layoutxlm-base model.
I wanna check the layoutxlm-large too, but I can't find the models in huggingface.
Can't I try the model?

**Comment by wolfshow** [comment]
@yellowjs0304, LayoutXLM large is not publicly available right now.

**Comment by yellowjs0304** [comment]
Thank you. I understood.
