### ISSUE TITLE
pip freeze for trocr

### ISSUE THREAD

**Issue by PatrickSteinmueller** [microsoft/unilm#713]
Hi,

currently facing pips/pythons unfathomable dependency hell while trying to install unilm/trocr on a python3.7 environment.

Does anyone have any tips or could anyone provide a pip freeze for their respective environment?

Kind Regards

**Comment by liminghao1630** [comment]
@PatrickSteinmueller Can you provide more details?

**Comment by filipggg** [comment]
@PatrickSteinmueller 
I managed to run TrOCR with the following requirements: https://github.com/filipggg/trocr-runner/blob/master/requirements.txt
(but read the comments inside).
Also note that it was tested for distributed training.
