### ISSUE TITLE
Is layloutlmv3 support for SER and RE work for xfund dataset?

### ISSUE THREAD

**Issue by githublsk** [microsoft/unilm#714]
Model description:
LayoutLMV3 is the successor of the LayoutLM models.  I have a question that dose layoutlmv3 support for SER and RE work for xfund dataset?

**Comment by wolfshow** [comment]
@githublsk, LayoutLMv3 supports SER and RE tasks, but it is an English model while XFUND is used to evaluate the LayoutXLM model.

**Comment by githublsk** [comment]
@wolfshow Oh,yes, do you have a plan to support multi-language like layoutxlm for layoutmv3? because layoutxlm model is a little heavy

**Comment by githublsk** [comment]
@[wolfshow](https://github.com/wolfshow)
Thank you for your answer, I have a question that can I use LayoutLMv3 English model for finetuning my Chinese task?

**Comment by wolfshow** [comment]
LayoutLMv3 is pre-trained with English documents only. For Chinese tasks, it is better to use LayoutXLM.

**Comment by SuXuping** [comment]
thanks for your answer. but i did find the RE code in layoutlmv3 file.  is there someone show me where is the RE task code in layoutlmv3?

**Comment by phamkhactu** [comment]
@wolfshow I have question that: "if I want to fintune other language that not in pretrained, such as: vietnamese, how to fintune layoutv3"
Thank you.
