### ISSUE TITLE
LayoutLMv3 has to depend on Detectron2?

### ISSUE THREAD

**Issue by 7fantasysz** [microsoft/unilm#715]
I am using LayoutLMv3. 

If I am not interested in the layout/object detection task, but only form recogniser and document classification tasks, could I be spared for the Detectron2 installation? It's hard to install on a VM without direct public internet connection and this installation will add unnecessary burden to our pipeline that's running everyday.

**Comment by HYPJUDY** [comment]
Hi, thanks for your question!

The current version of the unilm/layoutlmv3 implementation uses Detectron2 in the following two aspects:
1) To load images in datasets (e.g., FUNSD, CORD).
You can avoid installing Detectron2 ([reference](https://huggingface.co/datasets/nielsr/funsd-layoutlmv3/blob/main/funsd-layoutlmv3.py#L8-L15)) by modifying the following codes
https://github.com/microsoft/unilm/blob/ca82fd4e5c7b0e4594eee33f8dd08388183787cd/layoutlmv3/layoutlmft/data/image_utils.py#L9-L10
https://github.com/microsoft/unilm/blob/ca82fd4e5c7b0e4594eee33f8dd08388183787cd/layoutlmv3/layoutlmft/data/image_utils.py#L21-L27
  to
    ``` python
    from PIL import Image
    def load_image(image_path):
        image = Image.open(image_path).convert("RGB")
        w, h = image.size
        return image, (w, h)
    ```
2. To support detection tasks.
The current version of the unilm/layoutlmv3 implementation has set [`detection=False`](https://github.com/microsoft/unilm/blob/ca82fd4e5c7b0e4594eee33f8dd08388183787cd/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py#L693), which does not use detection components. Removing all codes related to `detection` in [`modeling_layoutlmv3.py`](https://github.com/microsoft/unilm/blob/master/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py) will also work. For example, [@NielsRogge](https://github.com/NielsRogge) has removed is_detection logic in [this PR](https://github.com/huggingface/transformers/pull/17060).

**Comment by 7fantasysz** [comment]
@HYPJUDY 

Your answer is really helpful! That's what I was looking for. Two follow-up questions:

1. After removal of this dependency, would it affect the accuracy of different tasks (form/receipt understanding, image classification, DocVQA)? If it is, do you have a metrics about how much accuracy will differ from the one on paper? 

2. By reading the paper, my understanding is that adding Detectron2 is only to finetune and compare with other models on PubLayNet dataset, not a fundamental part of this layoutlmv3 for other tasks, right?

Thanks for your help!

**Comment by HYPJUDY** [comment]
I'm glad it helped.
1. The two snippet of codes should be equivalent, so switching from one to the other will not affect accuracy. I haven't verified this conclusion experimentally, but @NielsRogge's experimental results (e.g., [FUNSD](https://huggingface.co/nielsr/layoutlmv2-finetuned-funsd)) support this conclusion.
2. You are right.

**Comment by 7fantasysz** [comment]
That's great to know. Also appreciate your insightful research work, which is the key enabler of our project. Thank you!

**Comment by HYPJUDY** [comment]
My pleasure : ) Good luck with your project!
