### ISSUE TITLE
How to fine-tune wavlm on my dataset?

### ISSUE THREAD

**Issue by shanmon110** [microsoft/unilm#717]
**Describe**
Model I am using (WavLM）:I want to load WavLM-Base+.pt and fine-tune it on my chinese speech dataset, could I modifiy the weight？

**Comment by MarkWuNLP** [comment]
Hi! Of course, you can modify the model weight in fine-tuning, but I don't think WavLM performs well on the non-English data, especially Chinese.

**Comment by shanmon110** [comment]
> Hi! Of course, you can modify the model weight in fine-tuning, but I don't think WavLM performs well on the non-English data, especially Chinese.

Hello, your mean extract representation of each layer and weighted sum the representations? Or load the WavLM-Base model and continue training on my Chinese dataset to modify weights?

**Comment by MarkWuNLP** [comment]
You can try both. Maybe loading the WavLM-Base model and continue training is a better choice.

**Comment by Abhi-2809** [comment]
Could you please share any link to a code, which i can follow to fine tune the WavLM Model on my own dataset.
Thanks.

**Comment by yijingshihenxiule** [comment]
Hello， @Abhi-2809 . Have you finetuned model in chinese dataset？ How about the result？I also want  to train a model in chainese dataset。Need your help！

**Comment by Abhi-2809** [comment]
Thank you for the email!
But i have not finetuned the model in chinese dataset

Thank you,
Abhinav

**Comment by jtzhao5** [comment]
> Hi! Of course, you can modify the model weight in fine-tuning, but I don't think WavLM performs well on the non-English data, especially Chinese.

Hey, why don`t you think WavLM performs well on Chinese data (even after fine-tuning on chinese speech dataset)? Can you please share your ideas in detail, thanks!
