### ISSUE TITLE
[AdaLM] Any plan to release pre-training stage code?

### ISSUE THREAD

**Issue by Xiyuer2198** [microsoft/unilm#718]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): UniLM

Hi, @buaahsh 

Is there any plan to release pre-training code? Such as mentioned in paper:

> The embedding vector of ‘lymphoma’ is initialized by the average embedding vector of ‘lym’, ‘##pho’ and ‘##ma’.

Thanks for your great work.

**Comment by buaahsh** [comment]
Hello @Xiyuer2198, thank you for your interest in our work. Now, we don't have a plan to release the pre-training code.
I recommend to follow the [incremental BPE builder](https://github.com/microsoft/unilm/tree/master/adalm/incr_bpe) to create your own domain-specific vocabulary and use the [infoxlm pre-training code](https://github.com/microsoft/unilm/tree/master/infoxlm#pretraining) to continual pretrain.
