### ISSUE TITLE
XLM-E on Huggingface Model Hub

### ISSUE THREAD

**Issue by nu11us** [microsoft/unilm#725]
According to #534, XLM-E's code and checkpoints were not uploaded here / to the Huggingface model hub as XLM-E was currently under review. Now that it has been fully published, at least to my knowledge, is there any chance that it can be uploaded to the Huggingface model hub?

Thanks for all the work in developing all these models, it's well appreciated.

**Comment by RuanVisser** [comment]
Any update on this would be greatly appreciated.

**Comment by jessica-baik** [comment]
And here are one more person who are looking forward any new updates on XLM-E in the late October. 😃 Is there any news for integrating XLM-E to Huggingface model hub? @donglixp Thank you!

**Comment by donglixp** [comment]
@nu11us  @RuanVisser @jessica-baik 
We have been working on this. The base- and large-size checkpoints will be released soon according to our current plan.

**Comment by ricardorei** [comment]
These models were never released or am I missing something?

**Comment by yyxx1997** [comment]
Three years have passed. Do you have any plans to release models and code?

**Comment by tresiwald** [comment]
Same question here?
