### ISSUE TITLE
layoutlmv3 pretrain code?

### ISSUE THREAD

**Issue by pocca2048** [microsoft/unilm#733]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): layoutlmv3

Hello authors! Thank you for sharing your great work!
It seems that there is no pre-train code available at https://github.com/microsoft/unilm/tree/master/layoutlmv3.
(Please let me know if actually there is)
Could you share your pretrain code as well?

Thank you.

**Comment by wolfshow** [comment]
@pocca2048 Thanks for the interest in LayoutLMv3! We do not have plans to release the pre-training code right now.

**Comment by ChristiaensBert** [comment]
> **Describe** Model I am using (UniLM, MiniLM, LayoutLM ...): layoutlmv3
> 
> Hello authors! Thank you for sharing your great work! It seems that there is no pre-train code available at https://github.com/microsoft/unilm/tree/master/layoutlmv3. (Please let me know if actually there is) Could you share your pretrain code as well?
> 
> Thank you.

@pocca2048 If you manage to make your own pre-training script, please let me know! I would also be interested to contribute!

**Comment by nashid** [comment]
@pocca2048 @ChristiaensBert curious to know whether you made any progress on pre-training. I will not mind to join hands and contribute.

**Comment by ChristiaensBert** [comment]
@nashid @pocca2048 
ATM I'm not yet working on a script, mainly since I need a model in a different language and might wait for the multi-lingual model (might use XLM, based on the v2 model or wait for the v3 version to be released).
However, I'm still interested in helping.
