### ISSUE TITLE
LayoutLMv2's FeatureExtrator equivalent of LayoutLMv3

### ISSUE THREAD

**Issue by sudheendrabk** [microsoft/unilm#735]
Hi,

I was wondering if there is a similar function to layoutlmv2's FeatureExtractor in layoutlmv3? I would like to input images and extract image embeddings. Could it be possible to guide me in the right direction.

**Comment by HYPJUDY** [comment]
Please have a check on [LayoutLMv3FeatureExtractor](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv3#transformers.LayoutLMv3FeatureExtractor) and [this example](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv3/Fine_tune_LayoutLMv3_on_FUNSD_(HuggingFace_Trainer).ipynb).

**Comment by sudheendrabk** [comment]
Thanks much.
