### ISSUE TITLE
LayoutLMv3 document layout train error

### ISSUE THREAD

**Issue by yuumiin** [microsoft/unilm#737]
**Describe**
Model I am using LayoutLMv3

after running object_detection/train_net.py  
cuda error `RuntimeError: CUDA out of memory` 

Error occurred after adjusting IMS_PER_BATCH in cascade_layoutlmv3.yaml
**`TypeError: save_for_backward can only save variables, but argument 6 is of type bool`**

How to solve it???

**Comment by HYPJUDY** [comment]
It is hard to locate the cause of errors and debug without error stack traces.
Have you set `IMS_PER_BATCH` to a multiple of your GPU size? For example, if you are using 8 GPUs, then you could set `IMS_PER_BATCH` to 8, 16, etc.

**Comment by wyc2015fq** [comment]
@HYPJUDY 
![image](https://user-images.githubusercontent.com/24956765/180422279-1c5daa5c-cf30-47ab-bfb0-5e057bfec0e2.png)
I also encountered this problem，How can I solve it？

**Comment by haolibai** [comment]
same here. interesting.

**Comment by mllife** [comment]
Windows: set 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'

Linux: export 'PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512'
