### ISSUE TITLE
[unused99] occurs two times in unilm1.2-base-uncased-vocab.txt

### ISSUE THREAD

**Issue by GentleSmile** [microsoft/unilm#74]
when running s2s-ft, [unused99] occurs two times in unilm1.2-base-uncased-vocab.txt, which makes incorrect seq2seq_loader.Preprocess4Seq2seqDecoder.vocab_words

**Comment by addf400** [comment]
Can you privode your running command for decoding ?

**Comment by GentleSmile** [comment]
decode command:
python decode_seq2seq.py \
--model_type unilm --tokenizer_name unilm1.2-base-uncased --do_lower_case \
--input_file input.txt \
--split $SPLIT \
--model_path ${MODEL_PATH} --max_seq_length 64 --max_tgt_length 32 --batch_size 40 --beam_size 5 \
--length_penalty 0 --forbid_duplicate_ngrams --mode s2s --forbid_ignore_word "."

it causes wrong output of logger at line 131 in s2s-ft/s2s_loader.py

**Comment by addf400** [comment]
Can you provide the first few lines of the file?

**Comment by GentleSmile** [comment]
in method '__call__' Preprocess4Seq2seqDecoder, if 'tokens' is '['bo']', then self.vocab_words[self.indexer(tokens)[0]] will be 'dock', you can find 'bo' is at line 8946 of unilm1.2-base-uncased-vocab.txt, and  'dock' is at line 8947 of unilm1.2-base-uncased-vocab.txt

**Comment by addf400** [comment]
A quick fix if you do not use '[X_SEP]' token and 'SEP_*' tokens, you can directly use bert-base-uncased tokenizer to rerun this program.
'--model_type bert', 'tokenizer_name bert-base-uncased'

**Comment by GentleSmile** [comment]
May I ask when will you release the code of UNiLMv2, thanks.

**Comment by addf400** [comment]
Can you provide the first few lines of the file 'input.txt'?
Can you just post a picture or post some lines for 'input.txt'?

**Comment by addf400** [comment]
> May I ask when will you release the code of UNiLMv2, thanks.

@donglixp

**Comment by GentleSmile** [comment]
boheme taupe upholstery dine
unit designation location
animation motion collide droplet

these three lines are "src", I modified the code to read from plain text

**Comment by addf400** [comment]
> boheme taupe upholstery dine
> unit designation location
> animation motion collide droplet
> 
> these three lines are "src", I modified the code to read from plain text

Do you tokenizer the input before call seq2seq_loader.Preprocess4Seq2seqDecoder?

**Comment by GentleSmile** [comment]
yes, boheme become bo ##hem ##e

**Comment by donglixp** [comment]
@GentleSmile Nice catch! Thanks for the issue. We've updated the file https://unilm.blob.core.windows.net/ckpt/unilm1.2-base-uncased-vocab.txt . Please check whether the problem still exists.

**Comment by addf400** [comment]
> @GentleSmile Nice catch! Thanks for the issue. We've updated the file https://unilm.blob.core.windows.net/ckpt/unilm1.2-base-uncased-vocab.txt . Please check whether the problem still exists.

You need to delete the cache file in your cache dir

**Comment by GentleSmile** [comment]
it's ok now, thanks!  and will the code of UNiLMv2 be released recently?

**Comment by donglixp** [comment]
> it's ok now, thanks! and will the code of UNiLMv2 be released recently?

We will push them to the repo. Thanks for your feedback!
