### ISSUE TITLE
Traceback (most recent call last):   File "unilm/layoutlm/examples/seq_labeling/run_seq_labeling.py", line 52, in <module>     from layoutlm import FunsdDataset, LayoutlmConfig, LayoutlmForTokenClassification ImportError: cannot import name 'LayoutlmConfig' from 'layoutlm' (/usr/local/lib/python3.7/dist-packages/layoutlm/__init__.py)

### ISSUE THREAD

**Issue by jyotiyadav94** [microsoft/unilm#742]
**Describe the bug**
Model I am using (UniLM,LayoutLM) 

The problem arises when I run the below code for making prediction
! python unilm/layoutlm/examples/seq_labeling/run_seq_labeling.py  --do_predict \
                            --data_dir data \
                            --model_type layoutlm \
                            --model_name_or_path output \
                            --output_dir output \
                            --labels data/labels.txt \
                            --fp16

Error 
Traceback (most recent call last):
  File "unilm/layoutlm/examples/seq_labeling/run_seq_labeling.py", line 52, in <module>
    from layoutlm import FunsdDataset, LayoutlmConfig, LayoutlmForTokenClassification
ImportError: cannot import name 'LayoutlmConfig' from 'layoutlm' (/usr/local/lib/python3.7/dist-packages/layoutlm/__init__.py)

**To Reproduce**
I run the below notebook 

![image](https://user-images.githubusercontent.com/72126242/171209889-125698b9-a369-495e-9b45-98fc55bb17c1.png)

Tried: 

**Expected behavior**
[LayoutLM_model.zip](https://github.com/microsoft/unilm/files/8806482/LayoutLM_model.zip)

- Platform:
- Python version: 3.7
- PyTorch version (GPU?): Google collab

**Comment by qiujiu123** [comment]
how do you reslove the problem?
