### ISSUE TITLE
Is there any tool to annotate data in the form of LAyoutLMV1 or LayoutLMv2?

### ISSUE THREAD

**Issue by jyotiyadav94** [microsoft/unilm#743]
I am using this tool UBIAI to annotate the dataset in FUNSD form for LayoutLMv1 .
Are there any open source tools too ?

**Comment by wolfshow** [comment]
You might try this https://github.com/microsoft/OCR-Form-Tools

**Comment by jyotiyadav94** [comment]
@wolfshow 

How do you get the dataset from OCR form tools in JSON for the only selected tags . 
I was able to provide the tags, and train the model.But then how do you get the extracted JSON values for only the selected values as below. 

My idea is not to get the layout analyse results.

![image](https://user-images.githubusercontent.com/72126242/173683171-69746290-5753-4bc8-a94a-58fc5172a2fa.png)

**Comment by wgx998877** [comment]
Hi @jyotiyadav94,

I am not quite sure the way of your current usage.
Basically, the official usage with this tool is connect it with Azure Cognitive Service and you can setup your blob storage from Azure. After that, you can label the OCRed document and find the label file from your blob storage directly from my previous usage.

If you prefer a hacker way, you might need to setup this tool locally, and convert your OCR results to the required format correctly. I don't have such experience before, but I think it's doable but required a lot of future development of this tool or data conversion script efforts.

**Comment by wgx998877** [comment]
BTW, I do recommend you try the form recognizer API with this open-source labeling tool, and there is a newer version tool: https://formrecognizer.appliedai.azure.com/studio you can also have a try on it.

And for the pricing part, there are some free trial quota https://azure.microsoft.com/en-us/pricing/details/form-recognizer/#pricing and you might not pay it with fewer cases.
