### ISSUE TITLE
Pretrain about DiT

### ISSUE THREAD

**Issue by Randy-1009** [microsoft/unilm#745]
**Describe**
I want to re-pretrain the DiT with the data you list in the paper, but i found that there is no pretrain code in the dit repo.
After reading the paper about BEiT, I wonder if the pretrain code of beit can be used for dit?
Another question is that are you willing to provide the dVAE model in the DiT or the code for traing the VAE?
Looking forward to your response, thank you~

**Comment by wolfshow** [comment]
@Randy-1009 Thanks for the interest!  Currently, we do not have plans to release the code for pre-training.
