### ISSUE TITLE
VL-BEiT and VLMo code release?

### ISSUE THREAD

**Issue by ShiYaya** [microsoft/unilm#747]
**Describe**
Thanks for your excellent work! I am really looking forward to your open-source code to help me understand your work.

**Comment by donglixp** [comment]
We will upload them to the repo. Stay tuned.

**Comment by ShiYaya** [comment]
will you update the code in the next few days, or longer?

**Comment by xiao2mo** [comment]
+1 any timestamp?

**Comment by xiao2mo** [comment]
+1 any update?

**Comment by xiao2mo** [comment]
+1 any timestamp?

**Comment by Mr-Hu-cqupt** [comment]
Looking forward to your open-source code!
Thanks a lot!

**Comment by GuangtaoLyu** [comment]
Looking forward to your open-source code!
Thanks a lot!

**Comment by xiao2mo** [comment]
+1 any timestamp?

**Comment by addf400** [comment]
Hi everyone, [VLMo code & models](https://github.com/microsoft/unilm/tree/master/vlmo) has been released. Thanks for your attention!
