### ISSUE TITLE
Finetuning on Chinese document for image/document classification - LayoutLMv3

### ISSUE THREAD

**Issue by githublsk** [microsoft/unilm#749]
Hi @[HYPJUDY](https://github.com/HYPJUDY),
I want to finetuning on Chinese document for image/document classification - LayoutLMv3, because LayoutLMv3 pretraining model is just English language, is it effective for chinese document classification?

**Comment by wolfshow** [comment]
@githublsk LayoutLMv3 for Chinese will be released very soon. Please stay tuned.

**Comment by ChristiaensBert** [comment]
@wolfshow Awesome!! Which other languages will be released? Will there come a multi-lingual (XLM) version of v3?

**Comment by wolfshow** [comment]
The LayoutLMv3 for Chinese has been released at https://huggingface.co/microsoft/layoutlmv3-base-chinese

Details at https://github.com/microsoft/unilm/tree/master/layoutlmv3
