### ISSUE TITLE
Replicate Question Generation Results

### ISSUE THREAD

**Issue by MilkyLatte** [microsoft/unilm#76]
Hi, am trying to replicate the results you show in the qg.test.output.txt. In the test data, you input the same sequence multiple times and the questions generated for each of them is different. When trying to do this, the questions generated are all equal. Is there a flag that avoids this repetition? Thanks in advance and great work!

**Comment by WenhuiWang0824** [comment]
Hi, the input for the answer-aware question generation task is the concatenation of passage and answer (passage_tokens [SEP] answer_tokens). The output is the generated question that asks for the answer. The input answer can be seen as a "flag" to guide the generation of questions.

For SQuAD 1.1 dataset, one passage contains several different question and answer pairs. A passage may appear in different examples (their answers are different) and therefore the input may look similar. Could you check whether your input contains the answer tokens?

**Comment by MilkyLatte** [comment]
I see now you included the answers in a different file: src-test.txt. Thanks a lot.

**Comment by WenhuiWang0824** [comment]
The files under nqg_processed_data/ are the processed data from [Du et al. (2017)](https://github.com/xinyadu/nqg/tree/master/data/processed). You could find our processed data at train/ and test/ folders. Each line in our input files (train.pa.tok.txt, dev.pa.tok.txt, and test.pa.tok.txt) concatenate the passage and answer tokens by the [SEP] token.
