### ISSUE TITLE
LayoutLMv2 Class label -100 less than -1 Issue

### ISSUE THREAD

**Issue by M1chT** [microsoft/unilm#760]
Currently, trying to train LayoutLMv2 model on my custom dataset however, I have faced the issue as seen below when preparing the dataset. I have tried running on FUNSD dataset as well but faced the same issue. Not sure what's the problem.

ValueError                                Traceback (most recent call last)
[<ipython-input-11-62bbdc182df5>](https://localhost:8080/#) in <module>()
     27 
     28 train_dataset = datasets['train'].map(preprocess_data, batched=True, remove_columns=datasets['train'].column_names,
---> 29                                       features=features)
     30 test_dataset = datasets['test'].map(preprocess_data, batched=True, remove_columns=datasets['test'].column_names,
     31                                       features=features)

13 frames
[/usr/local/lib/python3.7/dist-packages/datasets/features/features.py](https://localhost:8080/#) in cast_storage(self, storage)
   1016             min_max = pc.min_max(storage).as_py()
   1017             if min_max["min"] < -1:
-> 1018                 raise ValueError(f"Class label {min_max['min']} less than -1")
   1019             if min_max["max"] >= self.num_classes:
   1020                 raise ValueError(

ValueError: Class label -100 less than -1

**Comment by Prithivee7** [comment]
I am Facing the same issue. 
![image](https://user-images.githubusercontent.com/55012450/173839490-5cd5c474-c3e7-4d69-99e3-23c10848b0d2.png)

**Comment by romainremyb** [comment]
I have the same issue... I ran the exact same code with the same data yesterday and it worked just fine! the library must have changed some code... hope it will be fixed this week before my semester project deadline^^Please let me know if you found a solution!

**Comment by jswapnil10** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-bfd7a3492b2e> in <module>
     14     batched=True,
     15     remove_columns=column_names,
---> 16     features=features,
     17 )
     18 eval_dataset = dataset["test"].map(

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/arrow_dataset.py in map(self, function, with_indices, with_rank, input_columns, batched, batch_size, drop_last_batch, remove_columns, keep_in_memory, load_from_cache_file, cache_file_name, writer_batch_size, features, disable_nullable, fn_kwargs, num_proc, suffix_template, new_fingerprint, desc)
   2392                 new_fingerprint=new_fingerprint,
   2393                 disable_tqdm=disable_tqdm,
-> 2394                 desc=desc,
   2395             )
   2396         else:

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/arrow_dataset.py in wrapper(*args, **kwargs)
    549             self: "Dataset" = kwargs.pop("self")
    550         # apply actual function
--> 551         out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
    552         datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [out]
    553         for dataset in datasets:

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/arrow_dataset.py in wrapper(*args, **kwargs)
    516         }
    517         # apply actual function
--> 518         out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
    519         datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [out]
    520         # re-apply format to the output

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/fingerprint.py in wrapper(*args, **kwargs)
    456             # Call actual function
    457 
--> 458             out = func(self, *args, **kwargs)
    459 
    460             # Update fingerprint of in-place transforms + update in-place history of transforms

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/arrow_dataset.py in _map_single(self, function, with_indices, with_rank, input_columns, batched, batch_size, drop_last_batch, remove_columns, keep_in_memory, load_from_cache_file, cache_file_name, writer_batch_size, features, disable_nullable, fn_kwargs, new_fingerprint, rank, offset, disable_tqdm, desc, cache_only)
   2779                                 writer.write_table(batch)
   2780                             else:
-> 2781                                 writer.write_batch(batch)
   2782                 if update_data and writer is not None:
   2783                     writer.finalize()  # close_stream=bool(buf_writer is None))  # We only close if we are writing in a file

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/arrow_writer.py in write_batch(self, batch_examples, writer_batch_size)
    501             col_try_type = try_features[col] if try_features is not None and col in try_features else None
    502             typed_sequence = OptimizedTypedSequence(batch_examples[col], type=col_type, try_type=col_try_type, col=col)
--> 503             arrays.append(pa.array(typed_sequence))
    504             inferred_features[col] = typed_sequence.get_inferred_type()
    505         schema = inferred_features.arrow_schema if self.pa_writer is None else self.schema

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib._handle_arrow_array_protocol()

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/arrow_writer.py in __arrow_array__(self, type)
    196                 # Also, when trying type "string", we don't want to convert integers or floats to "string".
    197                 # We only do it if trying_type is False - since this is what the user asks for.
--> 198                 out = cast_array_to_feature(out, type, allow_number_to_str=not self.trying_type)
    199             return out
    200         except (TypeError, pa.lib.ArrowInvalid) as e:  # handle type errors and overflows

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/table.py in wrapper(array, *args, **kwargs)
   1673             return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
   1674         else:
-> 1675             return func(array, *args, **kwargs)
   1676 
   1677     return wrapper

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/table.py in cast_array_to_feature(array, feature, allow_number_to_str)
   1812                     return pa.FixedSizeListArray.from_arrays(_c(array.values, feature.feature), feature.length)
   1813             else:
-> 1814                 casted_values = _c(array.values, feature.feature)
   1815                 if casted_values.type == array.values.type:
   1816                     return array

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/table.py in wrapper(array, *args, **kwargs)
   1673             return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
   1674         else:
-> 1675             return func(array, *args, **kwargs)
   1676 
   1677     return wrapper

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/table.py in cast_array_to_feature(array, feature, allow_number_to_str)
   1785         array = array.storage
   1786     if hasattr(feature, "cast_storage"):
-> 1787         return feature.cast_storage(array)
   1788     elif pa.types.is_struct(array.type):
   1789         # feature must be a dict or Sequence(subfeatures_dict)

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/datasets/features/features.py in cast_storage(self, storage)
   1016             min_max = pc.min_max(storage).as_py()
   1017             if min_max["min"] < -1:
-> 1018                 raise ValueError(f"Class label {min_max['min']} less than -1")
   1019             if min_max["max"] >= self.num_classes:
   1020                 raise ValueError(

ValueError: Class label -100 less than -1


I am also facing the similar issue. Can anyone please look into it?

**Comment by pragati2112** [comment]
I am facing the same issue while training "LayoutLMv3"  on the FUNSD dataset.




ValueError                                Traceback (most recent call last)
/tmp/ipykernel_967/200433852.py in <module>
     10 })
     11 
---> 12 train_dataset = dataset["train"].map(
     13     prepare_examples,
     14     batched=True,

~/Envs/ml/lib/python3.8/site-packages/datasets/arrow_dataset.py in map(self, function, with_indices, with_rank, input_columns, batched, batch_size, drop_last_batch, remove_columns, keep_in_memory, load_from_cache_file, cache_file_name, writer_batch_size, features, disable_nullable, fn_kwargs, num_proc, suffix_template, new_fingerprint, desc)
   2374 
   2375         if num_proc is None or num_proc == 1:
-> 2376             return self._map_single(
   2377                 function=function,
   2378                 with_indices=with_indices,

~/Envs/ml/lib/python3.8/site-packages/datasets/arrow_dataset.py in wrapper(*args, **kwargs)
    549             self: "Dataset" = kwargs.pop("self")
    550         # apply actual function
--> 551         out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
    552         datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [out]
    553         for dataset in datasets:

~/Envs/ml/lib/python3.8/site-packages/datasets/arrow_dataset.py in wrapper(*args, **kwargs)
    516         }
    517         # apply actual function
--> 518         out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
    519         datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [out]
    520         # re-apply format to the output

~/Envs/ml/lib/python3.8/site-packages/datasets/fingerprint.py in wrapper(*args, **kwargs)
    456             # Call actual function
    457 
--> 458             out = func(self, *args, **kwargs)
    459 
    460             # Update fingerprint of in-place transforms + update in-place history of transforms

~/Envs/ml/lib/python3.8/site-packages/datasets/arrow_dataset.py in _map_single(self, function, with_indices, with_rank, input_columns, batched, batch_size, drop_last_batch, remove_columns, keep_in_memory, load_from_cache_file, cache_file_name, writer_batch_size, features, disable_nullable, fn_kwargs, new_fingerprint, rank, offset, disable_tqdm, desc, cache_only)
   2779                                 writer.write_table(batch)
   2780                             else:
-> 2781                                 writer.write_batch(batch)
   2782                 if update_data and writer is not None:
   2783                     writer.finalize()  # close_stream=bool(buf_writer is None))  # We only close if we are writing in a file

~/Envs/ml/lib/python3.8/site-packages/datasets/arrow_writer.py in write_batch(self, batch_examples, writer_batch_size)
    501             col_try_type = try_features[col] if try_features is not None and col in try_features else None
    502             typed_sequence = OptimizedTypedSequence(batch_examples[col], type=col_type, try_type=col_try_type, col=col)
--> 503             arrays.append(pa.array(typed_sequence))
    504             inferred_features[col] = typed_sequence.get_inferred_type()
    505         schema = inferred_features.arrow_schema if self.pa_writer is None else self.schema

~/Envs/ml/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

~/Envs/ml/lib/python3.8/site-packages/pyarrow/array.pxi in pyarrow.lib._handle_arrow_array_protocol()

~/Envs/ml/lib/python3.8/site-packages/datasets/arrow_writer.py in __arrow_array__(self, type)
    196                 # Also, when trying type "string", we don't want to convert integers or floats to "string".
    197                 # We only do it if trying_type is False - since this is what the user asks for.
--> 198                 out = cast_array_to_feature(out, type, allow_number_to_str=not self.trying_type)
    199             return out
    200         except (TypeError, pa.lib.ArrowInvalid) as e:  # handle type errors and overflows

~/Envs/ml/lib/python3.8/site-packages/datasets/table.py in wrapper(array, *args, **kwargs)
   1673             return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
   1674         else:
-> 1675             return func(array, *args, **kwargs)
   1676 
   1677     return wrapper

~/Envs/ml/lib/python3.8/site-packages/datasets/table.py in cast_array_to_feature(array, feature, allow_number_to_str)
   1812                     return pa.FixedSizeListArray.from_arrays(_c(array.values, feature.feature), feature.length)
   1813             else:
-> 1814                 casted_values = _c(array.values, feature.feature)
   1815                 if casted_values.type == array.values.type:
   1816                     return array

~/Envs/ml/lib/python3.8/site-packages/datasets/table.py in wrapper(array, *args, **kwargs)
   1673             return pa.chunked_array([func(chunk, *args, **kwargs) for chunk in array.chunks])
   1674         else:
-> 1675             return func(array, *args, **kwargs)
   1676 
   1677     return wrapper

~/Envs/ml/lib/python3.8/site-packages/datasets/table.py in cast_array_to_feature(array, feature, allow_number_to_str)
   1785         array = array.storage
   1786     if hasattr(feature, "cast_storage"):
-> 1787         return feature.cast_storage(array)
   1788     elif pa.types.is_struct(array.type):
   1789         # feature must be a dict or Sequence(subfeatures_dict)

~/Envs/ml/lib/python3.8/site-packages/datasets/features/features.py in cast_storage(self, storage)
   1016             min_max = pc.min_max(storage).as_py()
   1017             if min_max["min"] < -1:
-> 1018                 raise ValueError(f"Class label {min_max['min']} less than -1")
   1019             if min_max["max"] >= self.num_classes:
   1020                 raise ValueError(

ValueError: Class label -100 less than -1

**Comment by pragati2112** [comment]
Yes I have checked datasets library, they recently have added a check to the ClassLabel type to ensure the values are in the valid label range -1, 0, ..., num_classes-1 (-1 is used for missing values). The error in your case happens only if the labels column is of type Sequence(ClassLabel(...)) before the map call and can be avoided by calling dataset = dataset.cast_column("labels", Sequence(Value("int"))) beforehand. The token-classification examples in Transformers introduce a new labels column, so their type is also Sequence(Value("int")), which doesn't lead to an error as this type unbounded.

**Comment by M1chT** [comment]
After pip installing datasets==2.2.2, my model is able to work now. Thank you

**Comment by SyedMuhammadHamza** [comment]
> This worked for me

This worked for me aswell
