### ISSUE TITLE
How to use layoutlmv3 in  industry environment?

### ISSUE THREAD

**Issue by matthew-wei** [microsoft/unilm#765]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...):

I want to ues layoutlmv3 for the Document Layout Detection task.   https://github.com/microsoft/unilm/tree/master/layoutlmv3
But i can not find the depoly  way to accelerate the model.  There is no infomation about deploy, for example transform the model to onnx or TensorRT.

So, please teach me the way to accelerate layoutlmv3.    @HYPJUDY

**Comment by wolfshow** [comment]
@matthew-wei Exporting LayoutLMv3 models into ONNX is not difficult because LayoutLMv3 only used standard operators in Transformers.

**Comment by moyans** [comment]
> You can easily deploy LayoutLMv3 to the ONNX format using the Hugging Face Transformers library, see [here](https://github.com/huggingface/transformers/pull/17953).

@regisss tokenization_layoutlmv3 can not support "layoutlmv3-base-chinses" model ，see [here](https://github.com/huggingface/transformers/issues/18307) , will it be repaired later?

**Comment by regisss** [comment]
> > You can easily deploy LayoutLMv3 to the ONNX format using the Hugging Face Transformers library, see [here](https://github.com/huggingface/transformers/pull/17953).
> 
> @regisss tokenization_layoutlmv3 can not support "layoutlmv3-base-chinses" model ，see [here](https://github.com/huggingface/transformers/issues/18307) , will it be repaired later?

Not sure about this, could you ask @NielsRogge in the issue you pointed to?

**Comment by iweirman** [comment]
@matthew-wei I am also grappling with this problem and was curious if you've come across any novel solutions.

**Comment by qrsssh** [comment]
> @matthew-wei I am also grappling with this problem and was curious if you've come across any novel solutions.

How did you solve it, please?

**Comment by murilosimao** [comment]
> @matthew-wei I am also grappling with this problem and was curious if you've come across any novel solutions.

#1274 https://github.com/microsoft/unilm/issues/1274
