### ISSUE TITLE
Will you put LayoutLM Pre-trained Model on google drive or amazon ?

### ISSUE THREAD

**Issue by ljch2018** [microsoft/unilm#77]
Thank you for publishing LayoutLM Pre-trained Model.
I failed to download them from [https://onedrive.live.com/](url), because my network can't connect to live.com.
Will you have any plan to put the models on google drive or amazon cloud ? Thank you very much.

**Comment by liuyukid** [comment]
same problem

**Comment by donglixp** [comment]
@wolfshow

**Comment by ranpox** [comment]
Hi, @ljch2018 and @liuyukid,
Thanks for your feedback. We have added Google Drive download links for pre-trained LayoutLM. Please try it again. :)

**Comment by ljch2018** [comment]
@ranpox @donglixp

**Comment by ljch2018** [comment]
Hi, @ranpox, I have downloaded the models.

**Comment by ljch2018** [comment]
Hi, @ranpox and @donglixp , Thanks for your help. I have downloaded the pre-trained models successfully.
