### ISSUE TITLE
Layoutlmv3 Large Model Yaml Config

### ISSUE THREAD

**Issue by naourass** [microsoft/unilm#773]
In `layoutlmv3/examples/object_detection` there's a sample config file `cascade_layoutlmv3.yaml` but it works only with the _base_ model. Is there any equivalent yaml config example for `large` model of layoutlmv3 ?

**Comment by HYPJUDY** [comment]
Please refer to [DiT](https://github.com/microsoft/unilm/tree/master/dit/object_detection) for `large` configs. For example [publaynet large model config](https://github.com/microsoft/unilm/blob/master/dit/object_detection/publaynet_configs/cascade/cascade_dit_large.yaml).
The main difference is in the following lines: https://github.com/microsoft/unilm/blob/745eabb6feb1668840f71b5ffe3d8d0fb9cc7613/dit/object_detection/publaynet_configs/cascade/cascade_dit_large.yaml#L5-L11

**Comment by virdiprateek** [comment]
> publaynet large model config

How did you test cascade_layoutlmv3.yaml but it works only with the base model?? Can you please add 
I wasnt able to find weights for that :- 

cfg = get_cfg()
add_vit_config(cfg)
cfg.MODEL.WEIGHTS =  "/path/to/models/layoutlmv3/pts/layoutlmv3-base/pytorch_model.bin"

what is the Model Weights path to be used this one is incorrect

**Comment by naourass** [comment]
@HYPJUDY Got it thank you for pointing me to the right direction !

@virdiprateek I just followed the docs and the example here :
https://github.com/microsoft/unilm/tree/master/layoutlmv3

**Comment by laminggg** [comment]
> Please refer to [DiT](https://github.com/microsoft/unilm/tree/master/dit/object_detection) for `large` configs. For example [publaynet large model config](https://github.com/microsoft/unilm/blob/master/dit/object_detection/publaynet_configs/cascade/cascade_dit_large.yaml). The main difference is in the following lines:
> 
> https://github.com/microsoft/unilm/blob/745eabb6feb1668840f71b5ffe3d8d0fb9cc7613/dit/object_detection/publaynet_configs/cascade/cascade_dit_large.yaml#L5-L11

@HYPJUDY hello, I want to train layoutlmv3-large model on my custom dataset, and I modified base model yaml to large model yaml as you mentioned, but I meet the non-convergence situation, meanwhile train the base model everything is ok. Do you have any idea about this problem? Thanks!
