### ISSUE TITLE
Issue in Object Detection using LayoutLMV3

### ISSUE THREAD

**Issue by virdiprateek** [microsoft/unilm#775]
from unilm.layoutlmv3.examples.object_detection.ditod import add_vit_config

It gives me error:
ModuleNotFoundError: No module named 'layoutlmft'

I have installed all the requirements mentioned in installation as well as requirements for LayoutLMV3

**Comment by wolfshow** [comment]
You may follow the object detection pipeline in DiT https://github.com/microsoft/unilm/tree/master/dit/object_detection

**Comment by virdiprateek** [comment]
Thanks, will try that out and compare which one works better: DiT or LayoutLMV3

**Comment by HYPJUDY** [comment]
1. `ModuleNotFoundError: No module named 'layoutlmft'`: please try `pip install -e .` following the [installation instruction](https://github.com/microsoft/unilm/tree/master/layoutlmv3#installation).
2. `Not Found for url...`: please manually download `model_final.pth` from `https://huggingface.co/HYPJUDY/layoutlmv3-base-finetuned-publaynet/` to your local path and change this path correspondingly: `cfg.MODEL.WEIGHTS = "/path/to/layoutlmv3-base-finetuned-publaynet/model_final.pth"`. [More instructions](https://github.com/microsoft/unilm/tree/master/layoutlmv3#document-layout-analysis-on-publaynet).

**Comment by virdiprateek** [comment]
Thanks for the guidance @HYPJUDY 

Also, like I was trying to compare LayouLMV3 and DiT on Document Layout Analysis, my objective is to segment the document and get text for each segment

Is there a way to get directly the text representation besides the tensor information related to bounding boxes or we might have to separately do OCR on top

**Comment by Kinlyran** [comment]
> from unilm.layoutlmv3.examples.object_detection.ditod import add_vit_config
> 
> It gives me error: ModuleNotFoundError: No module named 'layoutlmft'
> 
> I have installed all the requirements mentioned in installation as well as requirements for LayoutLMV3



> Thanks for the guidance @HYPJUDY
> 
> Also, like I was trying to compare LayouLMV3 and DiT on Document Layout Analysis, my objective is to segment the document and get text for each segment
> 
> Is there a way to get directly the text representation besides the tensor information related to bounding boxes or we might have to separately do OCR on top

>Hello, I meet the same question with you,"ModuleNotFoundError: No module named 'layoutlmft'",but I can not deal with this problem even I tried "pip install -e". 

>can you tell me how do you deal with it?

**Comment by Kinlyran** [comment]
Hello, I meet the same question with you,"ModuleNotFoundError: No module named 'layoutlmft'",but I can not deal with this problem even I tried "pip install -e".

can you tell me how do you deal with it?

**Comment by HYPJUDY** [comment]
I am not sure how to "get directly the text representation besides the tensor information related to bounding boxes", but it is easy to get text segments/lines by OCR engines (see https://github.com/microsoft/unilm/issues/838).
