### ISSUE TITLE
Dynamic data sampling scheduler implementation

### ISSUE THREAD

**Issue by JJJJane** [microsoft/unilm#776]
Hi, I noticed that the paper mentions you used a dynamic data sampling scheduler for cross-lingual machine translation, could you please point out where you implement this strategy? Thanks!

**Comment by shumingma** [comment]
Hi, our implementation of machine translation is based on the Fairseq repo. Please refer to https://github.com/facebookresearch/fairseq/blob/main/fairseq/data/multilingual/sampling_method.py for the details of the data sampling method.
