### ISSUE TITLE
How to use layoutLM3-base-chinese?

### ISSUE THREAD

**Issue by foxcow** [microsoft/unilm#777]
HI, I found that I was using layoutLMV3-base-chinese, missing vocab.json and merges.txt. But I also found the file sentencepiece.bpe.model, which is the same as layoutXML, so is it using the layoutLMV3-base-chinese model , must use LayoutXLMTokenizer to build the tokenizer?

**Comment by wolfshow** [comment]
You may follow the XFUND example at https://github.com/microsoft/unilm/tree/master/layoutlmv3#form-understanding-on-xfund

**Comment by foxcow** [comment]
thanks
