### ISSUE TITLE
look forward vlmo

### ISSUE THREAD

**Issue by Mr-Hu-cqupt** [microsoft/unilm#787]
Thanks for your excellent work! I am really looking forward to your open-source code to help me understand your work.When will the code and models of VLMo be released?

Thanks~

**Comment by xiao2mo** [comment]
+1

**Comment by GuangtaoLyu** [comment]
> Thanks for your excellent work! I am really looking forward to your open-source code to help me understand your work.When will the code and models of VLMo be released?
> 
> Thanks~

+1

**Comment by GuangtaoLyu** [comment]
+1

**Comment by sarath-mutnuru** [comment]
+1

**Comment by longkukuhi** [comment]
+1

**Comment by xiao2mo** [comment]
+1

**Comment by xiao2mo** [comment]
+1

**Comment by sangjun-Leee** [comment]
+1

**Comment by addf400** [comment]
Hi everyone, [VLMo code & models](https://github.com/microsoft/unilm/tree/master/vlmo) has been released. Thanks for your attention!
