### ISSUE TITLE
[layoutreader] can I use the [layoutlmv3-base-chinese] for reading order detection task?

### ISSUE THREAD

**Issue by Faye-Chiang** [microsoft/unilm#796]

**Comment by zlwang-cs** [comment]
The LayoutReader uses the weight of LayoutLM(v1) as the initial states and is further trained on the ReadingBank for the reading order detection. Theoretically, it is possible to integrate the layoutlmv3 to the architecture as the initial state, but you still need to further train the model on the reading order dataset which is ReadingBank.
