### ISSUE TITLE
Truncating predictions

### ISSUE THREAD

**Issue by Colanim** [microsoft/unilm#8]
Thanks for open-sourcing the repo, code is **great** and **really easy** to reproduce thanks to docker, your detailed explanations in the README and your finetuned checkpoints !

---

_I have a question about predictions post-processing._

I could reproduce paper's results on CNN/DM datasets with the command provided in the README. My results are :

| R-1   | R-2   | R-L   |
|-------|-------|-------|
| 43.06 | 20.42 | 40.32 |

But if I run the same command removing the truncation (`--trunc_len 0` instead of   
`--trunc_len 70`), results are much lower :

 | R-1   | R-2   | R-L   |
|-------|-------|-------|
| 42.05 | 19.90 | 39.44 |

---

**Is this normal ?**

In other codebase, I've never seen predictions being truncated. I'm wondering why it is necessary with UniLM.

I'm also curious to hear your opinion about the **reason why** the score is lower without truncation.

**Comment by donglixp** [comment]
We use the F1 version of ROUGE, which penalizes the length. For the dataset, it's a common practice to set a minimum length and a maximum length to control the output. For example, in the code https://github.com/sebastianGehrmann/OpenNMT-py/blob/copy_constraint/opts.py#L416 , there are `-min_length` and `-max_length` flags used for this purpose.

**Comment by Colanim** [comment]
Ha right !

You are completely right !

---

In other code, this "truncation" is mostly done *while* predicting.

It seemed odd to me to truncate *after* predicting.  
But indeed it's completely equivalent...

Thank you for the clarification and sorry for the bother..

**Comment by donglixp** [comment]
Yes, they are equivalent implementations for better flexibility. Thanks for the comments.
