### ISSUE TITLE
LayoutLM and image features

### ISSUE THREAD

**Issue by efinkel** [microsoft/unilm#80]
Hi after reading the paper on LayoutLM I was under the impression that image features would be used when doing sequence labeling (and not just document classification). However after digging through run_seq_labeling.py it does not actually require the images, just the bounding boxes. How do I use LayoutLM to use text features, bounding box features, and image features to do sequence labeling?

**Comment by wolfshow** [comment]
@efinkel Yes, image features are also used when doing sequence labeling, but as the image features are not pre-trained with the text and layout features, we only reelase the pre-trained models as well as fine-tuning code that loads the models. If you would like to use image features, you may plug in any faster-rcnn implementations, given the output of pre-trained models.

**Comment by efinkel** [comment]
@wolfshow I see, thanks for the clarification.
