### ISSUE TITLE
Model I am using LayoutLMv3 on Article Regions dataset

### ISSUE THREAD

**Issue by Howardqlz** [microsoft/unilm#808]
**Describe**
Model I am using LayoutLmv3:
I downloaded base model, and use the config file based on Publaynet. I training the model on [Article Regions dataset](https://github.com/cxsoto/article-regions),a little object detection dataset based on PubMed Central,but the result is much lower than faster rcnn(bbox map 65 vs 72). So it's there any sensitive parameters to change for small dataset? Or something important about finetuning on other dataset?

**Comment by wolfshow** [comment]
@Howardqlz you may start with DiT models for object detection which is easier for training/testing.
