### ISSUE TITLE
preprocessing format??

### ISSUE THREAD

**Issue by SibtainRazaJamali** [microsoft/unilm#81]
how to preprocess sroie dataset to finetune this model?

**Comment by wolfshow** [comment]
@SibtainRazaJamali We did not provide the preprocessing because we used the ground truth OCR reuslts coming from the manual check of official release. If you do not would like to check the results manually, please just organize the sroie dataset in the reading order.

**Comment by SibtainRazaJamali** [comment]
But i am asking for labeled data format to finetune the model. Can i label each word with labels like COMPANY_NAME,DATE,OTHER etc? or we need to label according to {S,B,I,E,O} tags?

**Comment by wolfshow** [comment]
@SibtainRazaJamali  Typically, we use the BIO tags for each category. For example, B-DATE, I-DATE, B-Com, I-Com and O for others.
