### ISSUE TITLE
Using layoutlmv3 to carry out NER task, in the result of model predict, some entities only have 'I-' and no 'B-'

### ISSUE THREAD

**Issue by 413542484** [microsoft/unilm#810]
output：“ O O O O O I-医院名称 I-医院名称 O I-医院名称 I-医院名称 I-医院名称 I-医院名称 I-医院名称 I-医院名称 O O O O O O O ”
The dataset and input data are correct.
A total of 13 entity categories

**Comment by gjj123** [comment]
@413542484 我也遇到这个问题，你解决了吗

**Comment by 413542484** [comment]
> @413542484 我也遇到这个问题，你解决了吗

没解决，我在发现其他ner模型存在同样的问题，应该就是普通的模型预测错误。可以写一个简单的策略处理这种情况。

**Comment by mosay95** [comment]
How to train NER task with layoutlmv3? Could you share the reference link?

**Comment by 413542484** [comment]
> 
The explanation here is very clear，The '-- task' parameter is the NER task by default and it can be left blank.

**Comment by 413542484** [comment]
> 如何使用 layoutlmv3 训练 NER 任务？你能分享参考链接吗？

https://github.com/microsoft/unilm/blob/master/layoutlmv3/README.md
The explanation here is very clear，The '-- task' parameter is the NER task by default and it can be left blank

**Comment by gjj123** [comment]
> > @413542484 我也遇到这个问题，你解决了吗
> 
> 没解决，我在发现其他ner模型存在同样的问题，应该就是普通的模型预测错误。可以写一个简单的策略处理这种情况。
应该是预处理的问题，按照它的dataload 里面的方法组织数据，结果是对的有B- I-

**Comment by 413542484** [comment]
> 

可以详细解释一下么，我确实改动了他dataload的代码，不过我在二分类问题上没出现这种情况，在多分类的时候才出现这个问题，你是dataload哪一部分出了问题

**Comment by gjj123** [comment]
> > 
> 
> 可以详细解释一下么，我确实改动了他dataload的代码，不过我在二分类问题上没出现这种情况，在多分类的时候才出现这个问题，你是dataload哪一部分出了问题

我调的是v3 训练的dataload 我没动应该，推理的时候 组织数据刚开始input_ids好像 没给csl 和sep ，推理也按那个dataload 里的给数据就行
