### ISSUE TITLE
Layoutlmv3 | Question

### ISSUE THREAD

**Issue by k-for-code** [microsoft/unilm#812]
**Describe**
Model I am using (Layoutlmv3.):
the output embedding size is (709, 768). which is greater than the max_position_embeddings = 512.

So I was wondering if the rest (709-512) = 197 is for image embeddings?
Where does that 197 come from
I read the paper it says
```
, the last layer outputs text-and-image
contextual representations
```
So is there a way we can separate image and text embedding as we could in layoutlmv2
thanks

**Comment by HYPJUDY** [comment]
You are right. `197 = 14 x 14 + 1`, where `14 x 14` is the number of image patches, and `1` represents a special token. Figure 3 in the LayoutLMv3 paper gives an overview of the embedding.
You can separate image and text by splitting the output embedding (e.g.,  [-196:, :] represents image embedding).

**Comment by k-for-code** [comment]
Thanks a lot  @HYPJUDY
