### ISSUE TITLE
No huggingface_hub attribute hf_api

### ISSUE THREAD

**Issue by tonylin52** [microsoft/unilm#823]
Hi,

I am using LayoutLMv3. I follow the README steps and get following issue:

Traceback (most recent call last):
  File "examples/run_xfund.py", line 10, in <module>
    from datasets import ClassLabel, load_dataset, load_metric
  File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/__init__.py", line 37, in <module>
    from .builder import ArrowBasedBuilder, BeamBasedBuilder, BuilderConfig, DatasetBuilder, GeneratorBasedBuilder
  File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/builder.py", line 44, in <module>
    from .data_files import DataFilesDict, _sanitize_patterns
  File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/data_files.py", line 122, in <module>
    allowed_extensions: Optional[list] = None,
  File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/huggingface_hub/__init__.py", line 105, in __getattr__
    raise AttributeError(f"No {package_name} attribute {name}")
AttributeError: No huggingface_hub attribute hf_api

Here is my env:
torch                     1.10.0+cu111             pypi_0    pypi
torchvision               0.11.1+cu111             pypi_0    pypi
transformers              4.21.1                   pypi_0    pypi
huggingface-hub           0.8.1                    pypi_0    pypi

**Comment by Invoker1992** [comment]
> Hi,
> 
> I am using LayoutLMv3. I follow the README steps and get following issue:
> 
> Traceback (most recent call last): File "examples/run_xfund.py", line 10, in from datasets import ClassLabel, load_dataset, load_metric File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/**init**.py", line 37, in from .builder import ArrowBasedBuilder, BeamBasedBuilder, BuilderConfig, DatasetBuilder, GeneratorBasedBuilder File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/builder.py", line 44, in from .data_files import DataFilesDict, _sanitize_patterns File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/data_files.py", line 122, in allowed_extensions: Optional[list] = None, File "/home/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/huggingface_hub/**init**.py", line 105, in **getattr** raise AttributeError(f"No {package_name} attribute {name}") AttributeError: No huggingface_hub attribute hf_api
> 
> Here is my env: torch 1.10.0+cu111 pypi_0 pypi torchvision 0.11.1+cu111 pypi_0 pypi transformers 4.21.1 pypi_0 pypi huggingface-hub 0.8.1 pypi_0 pypi

Hello, have you solved this problem? I met the same situation as you. All the environments were installed as required

**Comment by HYPJUDY** [comment]
Can you check if [these answers](https://bytemeta.vip/repo/huggingface/datasets/issues/4117) are helpful?

**Comment by Invoker1992** [comment]
Thank you. I have solved the problem and finished running the model. But now I face a problem, how to extract the content in the image to be recognized? Display results like paddleocr (see attachment)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/unilm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月3日(星期六) 中午1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/unilm] No huggingface_hub attribute hf_api (Issue #823)





 
Can you check if these answers are helpful?

**Comment by HYPJUDY** [comment]
Hi @Invoker1992, is your new question related to https://github.com/microsoft/unilm/issues/839? As this question is unrelated to this issue, I will close it.

**Comment by YFAN1020** [comment]
> 谢谢。我已经解决了问题并完成了模型的运行。但是现在我面临一个问题，如何提取图像中的内容才能被识别？显示结果，如桨（见附件）
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/unilm" ***@***.***&gt;; 发送时间:&nbsp;2022年9月3日(星期六) 中午1:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [microsoft/unilm] No huggingface_hub attribute hf_api (Issue #823) Can you check if these answers are helpful? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&
请问最后是怎么解决的呢，我目前也遇到了这个问题

**Comment by Invoker1992** [comment]
时间太久远了，有些不记得了。印象中是改了某个依赖包的版本号就可以了，尝试一下



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 19, 2023 09:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/unilm] No huggingface_hub attribute hf_api (Issue#823)




  
谢谢。我已经解决了问题并完成了模型的运行。但是现在我面临一个问题，如何提取图像中的内容才能被识别？显示结果，如桨（见附件）
 ...
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "microsoft/unilm" @.&gt;; 发送时间:&nbsp;2022年9月3日(星期六) 中午1:20 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [microsoft/unilm] No huggingface_hub attribute hf_api (Issue #823) Can you check if these answers are helpful? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&amp;
 请问最后是怎么解决的呢，我目前也遇到了这个问题

**Comment by YFAN1020** [comment]
谢谢你的回复，我尝试一下，或许是transformers的版本问题
