### ISSUE TITLE
English and French form understanding using LayoutLM

### ISSUE THREAD

**Issue by Neelesh1121** [microsoft/unilm#825]
We are getting very good accuracy on English documents for form understanding using LayoutLMv3 but now we have to extract information from French documents also, so please suggest me which LayoutLM series model should I prefer, also can we train LayoutLMV3 on English and French dataset?

**Comment by wolfshow** [comment]
@Neelesh1121 You may try LayoutXLM which can be trained with English and French data at the same time.
