### ISSUE TITLE
do discrete visual tokens in codebook have semantic infomations in BEiT v2?

### ISSUE THREAD

**Issue by liangzimei** [microsoft/unilm#829]
thanks for your great work firstly~ 
in BEiTv2, will the discrete tokens have semantically meaningful representations，id=1 in 8192 tokens represents a dog's head for example. do you have any interesting observations?
thanks in advance.

**Comment by kacwin** [comment]
Awesome paper!
I would also be interested in visualizations of codebook entries. Maybe it could be possible to compute images that maximize the occurence of a specific codebook entry? Similar to maximization of neuron activation in https://openai.com/blog/multimodal-neurons/

**Comment by kacwin** [comment]
Hmm. After thinking it through a bit, I think that my comment from above does not make that much sense at all. I am wondering in which way the codebook entries are storing the positional information. Because for reconstruction, each token has to "know" which feature from the teacher model has to be reconstructed. 
This could potentially result in a drastic reduction of codebook depth, because each discrete entry needs to encode the positional information as well.
A statistic on "appearing codebook entries per position" would be interesting here.

**Comment by donglixp** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1070872/185739549-f2ebde33-0520-4c72-a032-ee0ce023ef53.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1070872/185739557-a9f9f320-5ddb-46ed-85a5-6f5ec66fa92d.png)

**Comment by donglixp** [comment]
> thanks for your great work firstly~ in BEiTv2, will the discrete tokens have semantically meaningful representations，id=1 in 8192 tokens represents a dog's head for example. do you have any interesting observations? thanks in advance.

Yes, they do!

**Comment by liangzimei** [comment]
> > thanks for your great work firstly~ in BEiTv2, will the discrete tokens have semantically meaningful representations，id=1 in 8192 tokens represents a dog's head for example. do you have any interesting observations? thanks in advance.
> 
> Yes, they do!

thanks for your reply and visualization. From the two images, id=7443 indeed represents the dog's nose. But I also have two questions:
1. will id = 7443 also appear in other no dog images ? and in other images, whether 7443 represents other object's part or   7443 is just a black round block region?
2. if every id can represent such fine-grained objects (7443=dog nose), Can 8192 tokens totally cover all objects' parts in the imagenet dataset? ( many tokens also shoud be filled in the background at the same time)

**Comment by kacwin** [comment]
Awesome! Cannot wait to try it out myself. Will you publish the tokenizer too as part of BEiT v2?

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/beit2
