### ISSUE TITLE
How to obtain the Pre-processed json dataset?

### ISSUE THREAD

**Issue by matt9704** [microsoft/unilm#83]
Hi! I wonder how to obtain the Pre-processed json dataset in the Example: XSum with minilm-l12-h384-uncased?

**Comment by addf400** [comment]
Thanks for your report, we will update the readme later. 
Before that, you can visit https://github.com/microsoft/unilm/tree/master/s2s-ft#example-xsum-with-minilm-l12-h384-uncased for getting urls for the pre-processed json.
