### ISSUE TITLE
Dose layoutlmv3 have RE task code?

### ISSUE THREAD

**Issue by tonylin52** [microsoft/unilm#830]
Hi, 

I am learning layoutlmv3 model for SER and RE task. But I don't find source code for RE task in the layoutlmv3 folder. Could you please release the layoutlmv3 RE task model head & dataloader code? Thanks!

**Comment by HYPJUDY** [comment]
Hi, which RE task are you referring to? I don't think we have experimented with the relation extraction task. Also, we have no plan to release other models or code.
