### ISSUE TITLE
Layout-XLM for Arabic

### ISSUE THREAD

**Issue by bely66** [microsoft/unilm#836]
Model I am using (LayoutXLM):
I wanna fine-tune the model for Arabic a Non-English Language that's not included in the pre-training that was done on (Chinese, Japanese, Spanish, French, Italian, German, Portuguese).
And I don't know if that's valid plan or I need to wait for another release.
Also is there a tutorial which can help test Layout-XLM on Arabic.
Regards,

**Comment by wolfshow** [comment]
The LayoutXLM model is pre-trained with more than 50 languages that including Arabic. The language you mentioned is the evaluation dataset XFUND.

**Comment by bely66** [comment]
@wolfshow 
Thanks for your timely response 
Okay that sounds good
is there any available notebooks or tutorials showing how to use it?

**Comment by wolfshow** [comment]
You may follow the LayoutLMv2 notebooks and replace with LayoutXLM: https://github.com/NielsRogge/Transformers-Tutorials/tree/master/LayoutLMv2
