### ISSUE TITLE
BEiT v2 and v3 code and checkpoints

### ISSUE THREAD

**Issue by eliahuhorwitz** [microsoft/unilm#837]
Hey,
When will the code and cheeckpoints for BEiT v2 v3 be published?
Thanks,
Eliahu

**Comment by donglixp** [comment]
https://github.com/microsoft/unilm/tree/master/beit2

**Comment by eliahuhorwitz** [comment]
Thanks!

**Comment by eliahuhorwitz** [comment]
@donglixp Thanks again, but the link to the pretrained checkpoints is not working, see my related issue here #850

**Comment by donglixp** [comment]
> @donglixp Thanks again, but the link to the pretrained checkpoints is not working, see my related issue here #850

Fixed by https://github.com/microsoft/unilm/pull/851
