### ISSUE TITLE
Code for pre-processing raw dataset?

### ISSUE THREAD

**Issue by matt9704** [microsoft/unilm#84]
Hi! I have a new dataset and wanna test your model on it, but I don't know how to pre-process the dataset into .json format like in Example: CNN / Daily Mail with unilm1-base-cased. Each story in my dataset is written in one file and all story files are included in one folder... Is there any code available for this pre-processing task? Thx

**Comment by donglixp** [comment]
pointer to https://github.com/microsoft/unilm/issues/11
