### ISSUE TITLE
LayoutLmv3 |  ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.4.0/metrics/seqeval/seqeval.py

### ISSUE THREAD

**Issue by 4daJKong** [microsoft/unilm#846]
I tried to fine-tune layoutLMv3 Chinese model on XFUND, and I input those in terminal
```
 python examples/run_xfund.py \
    --data_dir data --language zh \
    --do_train --do_eval \
    --model_name_or_path microsoft/layoutlmv3-base-chinese \
    --output_dir output 
```
At first, it returns error `AttributeError: module 'huggingface_hub' has no attribute 'hf_api'](https://github.com/huggingface/datasets/issues/4117#top)`
Then I update some packages including datasets, huggingface_hub, transformers, etc.
it returns a new error now:
`ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.4.0/metrics/seqeval/seqeval.py (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /huggingface/datasets/2.4.0/metrics/seqeval/seqeval.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbc58fd64d0>: Failed to establish a new connection: [Errno 111] Connection refused'))")))`
How to fix it?
P.S the cuda version in my linux server is 10.2 and here are some parts of my packages list:
| Name |                   Version  |                 Build  Channel |
_libgcc_mutex             0.1                        main    defaults
cudatoolkit               10.2.89             h713d32c_10    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
datasets                  2.3.2                    pypi_0    pypi
deepspeed                 0.5.7                    pypi_0    pypi
detectron2                0.6+cu102                pypi_0    pypi
evaluate                  0.1.2                    pypi_0    pypi
huggingface-hub           0.8.1                    pypi_0    pypi
layoutlmv3                0.1                       dev_0    <develop>
python                    3.7.13               h12debd9_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.10.0          py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
response                  0.5.0                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
torch                     1.9.0                    pypi_0    pypi
torchaudio                0.10.0               py37_cu102    pytorch
torchvision               0.11.0               py37_cu102    pytorch
transformers              4.12.5                   pypi_0    pypi

**Comment by HYPJUDY** [comment]
Have you solved the problem? It looks like a network issue. Can you reach the address on your server (e.g., through `wget https://raw.githubusercontent.com/huggingface/datasets/2.4.0/metrics/seqeval/seqeval.py`)?

**Comment by HYPJUDY** [comment]
I am closing this issue for now, since it is inactive.
