### ISSUE TITLE
Waiting for the code of BEIT-3

### ISSUE THREAD

**Issue by SZUHvern** [microsoft/unilm#848]
Hi,

The paper 'Image as a Foreign Language: BEIT Pretraining for All Vision and Vision-Language Tasks' is very interesting!
But I cannot find the code in this project yet.
Could you please release the code as soon as possible or just tell me what is the time?

Many thanks!

**Comment by donglixp** [comment]
The v2 code has been available at https://github.com/microsoft/unilm/tree/master/beit2 . We will work on v3 too.

**Comment by donglixp** [comment]
The code and pre-trained models of BEiT-3 can be found at [aka.ms/beit3](https://aka.ms/beit3).
