### ISSUE TITLE
Install instructions out-of-date for installing detectron2

### ISSUE THREAD

**Issue by nate-bush** [microsoft/unilm#849]
**Describe the bug**
Failure while installing detectron2 (following instructions for DiT).

The problem arises when using:
Following the install instructions for DiT

**To Reproduce**
1. Run "python -m pip install detectron2 -f  https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html"
2. See error:
```
Looking in links: https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html
ERROR: Could not find a version that satisfies the requirement detectron2 (from versions: none)
ERROR: No matching distribution found for detectron2
```

**Expected behavior**
detectron2 is successfully installed

- Platform: MacOS 
- Python version: 3.7.10
- PyTorch version (GPU?): torch==1.9.0 (CPU)

**Comment by nate-bush** [comment]
Error is with detectron2 https://github.com/facebookresearch/meshrcnn/issues/13

**Comment by CrasCris** [comment]
did you solve it ?@nate-bush
