### ISSUE TITLE
How do ·layoutLM· get the read order from a image

### ISSUE THREAD

**Issue by 578123043** [microsoft/unilm#85]
It seems layoutLM need a read order to get position_ids and position embedding.

Could you kindly tell the details that how do layoutLM· get the read order from a image.

Does it is made by tressact?

**Comment by ranpox** [comment]
Yes. For any document image, you can use [Tesseract](https://github.com/tesseract-ocr/tesseract) to obtain the hOCR result which is organized in reading order. Please check out the [Tesseract document ](https://github.com/tesseract-ocr/tesseract/wiki#running-tesseract) to get more info about how to output hOCR format.
