### ISSUE TITLE
BEiT v2 pretrained checkpoints links are not working 

### ISSUE THREAD

**Issue by eliahuhorwitz** [microsoft/unilm#850]
Hey,
Thanks for releasing the BEiT v2 code. However, the pretrained checkpoints are not working, I am getting an error that says "blob doesn't exist" when I try to download any of the four variants of the pretrained models. Below are the links that are not working:

- BEiT-base: [beitv2_base_patch16_224_pt1k_ft21k](https://conversationhub.blob.core.windows.net/beit-share-public/beitv2/pt_cls_pt_base_early_9_head_2_vqkd_encoder_base_decoder_3x768x12_clip_1600e-6d32a5f7.pth)
- BEiT-large: [beitv2_large_patch16_224_pt1k_ft21k](https://conversationhub.blob.core.windows.net/beit-share-public/beitv2/pt_cls_pt_large_early_21_head_2_vqkd_encoder_base_decoder_3x768x12_clip_1600e-726bb6d5.pth)
- BEiT-base: [beitv2_base_patch16_224_pt1k](https://conversationhub.blob.core.windows.net/beit-share-public/beitv2/pt_cls_pt_base_early_9_head_2_vqkd_encoder_base_decoder_3x768x12_clip_1600e-6d32a5f7.pth)
- BEiT-large: [beitv2_large_patch16_224_pt1k](https://conversationhub.blob.core.windows.net/beit-share-public/beitv2/pt_cls_pt_large_early_21_head_2_vqkd_encoder_base_decoder_3x768x12_clip_1600e-726bb6d5.pth)

Thanks,
Eliahu

**Comment by pengzhiliang** [comment]
Dear Eliahu:

I'm sorry that the mentioned links are invalid, and we will update them soon. But you can download those in [here](https://github.com/microsoft/unilm/tree/master/beit2#fine-tuning-on-imagenet-1k-image-classification).

**Comment by donglixp** [comment]
Solved by https://github.com/microsoft/unilm/pull/851
