### ISSUE TITLE
MiniLM-L12xH384 better than BERT-base on some dataset?

### ISSUE THREAD

**Issue by imohitmayank** [microsoft/unilm#852]
**Describe**
As per the [Finetuning section of MiniLM Readme](https://github.com/microsoft/unilm/tree/master/minilm#fine-tuning-on-nlu-tasks) the performance of `MiniLM-L12xH384` is even better than `BERT-base` for `SQuAD 2.0` and `MNLI-m` datasets. As distillation usually lead to usually lesser student performance (wrt teacher), how is the reported score higher than BERT? 
Thank you!

**Comment by donglixp** [comment]
MiniLM is better than BERT because the teacher of MiniLM is better than BERT.
