### ISSUE TITLE
How to evaluate the trained beit model on object detection

### ISSUE THREAD

**Issue by cnr0724** [microsoft/unilm#858]
Model I am using (UniLM, MiniLM, LayoutLM ...): BEiT v1

First of all, thanks for the great work.

I'm trying to apply beit v1 model on object detection field. Sadly, I realized that I cannot find a guide to run run_linear_eval.py. I know there's a kind and wonderful guide on image classification, but I don't think the guide covers the object detection. Can I get some advice on that?

Also, I trained the model on Pasval VOC format dataset. Do I have to rearrange the folder structure or the dataset format in order to evaluate the model? If so, which folder structure should I follow?

**Comment by donglixp** [comment]
The OD instruction is under preparation at https://github.com/microsoft/unilm/tree/master/beit2#fine-tuning-on-mscoco2017-object-detection .

**Comment by czczup** [comment]
Hi, any progress on BEiTv2 object detection?
