### ISSUE TITLE
Is there a plan for pre-trained models of LayoutLMv2, LayoutLMv3 made available for commercial use?

### ISSUE THREAD

**Issue by weicheng113** [microsoft/unilm#863]
Hi,

Thanks for sharing great performance models of LayoutLM series. The question was raised in #352 , but it has not got an answer. So may I ask if there is a plan for pre-trained models of LayoutLMv2, LayoutLMv3 to be made available for commercial use at some time in the future?

![Screenshot-8](https://user-images.githubusercontent.com/1066604/189557095-8a821af8-643c-4603-85e5-f4e0a20c69c5.png)

Thanks, Cheng

**Comment by devonkinghorn** [comment]
It's very confusing. Huggingface changed the license to MIT this morning.
https://huggingface.co/microsoft/layoutlmv3-base/discussions/4

**Comment by weicheng113** [comment]
That is great. Just check layoutlmv2 and layoutv3 are both under MIT.

**Comment by jack-gits** [comment]
![Uploading image.png…]()
seems not changed.

**Comment by DiddyC** [comment]
@jack-gits not sure what happened - seems like they've changed it back recently. 
https://huggingface.co/microsoft/layoutlmv3-base/commit/34ad996fcbb1e8172a2409d8d7f0f88a4602869e

**Comment by devonkinghorn** [comment]
It was MIT a few days ago. Now it's not?? I am very confused.  https://huggingface.co/microsoft/layoutlmv3-base/discussions/4/files

**Comment by DiddyC** [comment]
Seems like they have changed it back yesterday. 
https://github.com/microsoft/unilm/commit/2239a415aacfaff3af37c7d43995a4f0a9c41c04
vs.
https://github.com/microsoft/unilm/commit/8444c6b6c4bfcc1cea60d41b85b29d84c0cbec32

**Comment by writetoneeraj** [comment]
Any plans on changing license for layoutlmv2 and layoutxlm models from NC to MIT in future?

**Comment by mllife** [comment]
Can a fine-tuned model on custom dataset with different weights be used for commercial purpose?
