### ISSUE TITLE
Question about training VQKD

### ISSUE THREAD

**Issue by MiJordan23** [microsoft/unilm#865]
Hey,
Thank you for publishing the code for BEiT2.
I am trying to train VQKD, but I found that the total loss did not decrease and remained around 0.999.

Here is part of the training log:
> Epoch: [0]  [ 720/5004]  eta: 0:56:49  lr: 0.000003  bad_img: 0.0000 (0.0000)  loss: 0.9992 (0.9990)  quant_loss: 0.0038 (0.0043)  rec_loss: 0.9955 (0.9947)  total_loss: 0.9992 (0.9990)  weight_decay: 0.0001 (0.0001)  grad_norm: 4.0652 (4.0872)  time: 0.8124  data: 0.0011  max mem: 7845
Epoch: [0]  [ 730/5004]  eta: 0:56:40  lr: 0.000003  bad_img: 0.0000 (0.0000)  loss: 0.9984 (0.9990)  quant_loss: 0.0037 (0.0043)  rec_loss: 0.9948 (0.9947)  total_loss: 0.9984 (0.9990)  weight_decay: 0.0001 (0.0001)  grad_norm: 4.0666 (4.0869)  time: 0.8347  data: 0.0006  max mem: 7845
Epoch: [0]  [ 740/5004]  eta: 0:56:26  lr: 0.000003  bad_img: 0.0000 (0.0000)  loss: 0.9984 (0.9990)  quant_loss: 0.0039 (0.0043)  rec_loss: 0.9948 (0.9947)  total_loss: 0.9984 (0.9990)  weight_decay: 0.0001 (0.0001)  grad_norm: 4.0639 (4.0866)  time: 0.7400  data: 0.0007  max mem: 7845

Any help to this is much appreciated.
Thank you.

**Comment by pengzhiliang** [comment]
Thank you for your attention~

Could you provide more details?

**Comment by MiJordan23** [comment]
Thank you for your response.
I found an error in my code that the gradient is clipped to zero. After fixing the bug, the loss decreased normally.
