### ISSUE TITLE
[TrOCR, Huggingface] Inference predictions always upper case?

### ISSUE THREAD

**Issue by shensmobile** [microsoft/unilm#875]
Hi everyone,

I hope this is a reasonable place to ask this question.  I'm currently testing out TrOCR through HuggingFace and one thing I noticed is that the predictions from the generator are always in upper case.  Is this a result of me using HuggingFace or is this a model configuration setting I've missed somewhere?  I haven't re-trained, just using the pre-trained models available from the HF model hub.

**Comment by NielsRogge** [comment]
Hi,

This is a good question, to be honest I don't know either, it could be that the model was trained this way. Would be great if the authors could provide some insight here :) cc @donglixp @wolfshow

**Comment by wolfshow** [comment]
@shensmobile @NielsRogge Yes, the labeled benchmark data for scene text recognition is always in upper case. You may use the pre-trained models using document data for case-sensitive applications.

**Comment by shensmobile** [comment]
Hi!  I realized this too after looking at the dataset that they trained from.  Unfortunately the document/handwritten model isn't good enough for our use case.  That said, TrOCR is still insanely good, I just need something with case sensitivity for this specific project unfortunately.

**Comment by bit-scientist** [comment]
Hi, @shensmobile. What model did you end up using for case-sensitive dataset?
