### ISSUE TITLE
KeyError: 'S-QUESTION'

### ISSUE THREAD

**Issue by yts19871111** [microsoft/unilm#88]
When I use the prediction function, I will report this problem？

**Comment by donglixp** [comment]
@yts19871111  Could you provide the commands and more error information?

**Comment by yts19871111** [comment]
![Selection_102](https://user-images.githubusercontent.com/38058730/77305559-30562b00-6d31-11ea-946e-c0ddd12f3e5c.png)

**Comment by ranpox** [comment]
@yts19871111 Could you paste the exact command you used?

**Comment by elnazsn1988** [comment]
@yts19871111 I have the same problem, :

```
raceback (most recent call last):
  File "run_seq_labeling.py", line 856, in <module>
    main()
  File "run_seq_labeling.py", line 748, in main
    args, tokenizer, labels, pad_token_label_id, mode="train"
  File "run_seq_labeling.py", line 434, in load_and_cache_examples
    pad_token_label_id=pad_token_label_id,
  File "C:\projects\python-virtual-environments\unilm\layoutlm\utils_seq_labeling.py", line 152, in convert_examples_to_features
    [label_map[label]] + [pad_token_label_id] * (len(word_tokens) - 1)
KeyError: 'S-QUESTION'
```

```
command: 

C:\projects\python-virtual-environments\unilm\layoutlm>python run_seq_labeling.py  --data_dir data --model_type layoutlm  --model_name_or_path C:\projects\mcrs_dat\layoutlm-large-uncased-20200401T192902Z-001\layoutlm-large-uncased --do_lower_case --max_seq_length 512 --do_train --num_train_epochs 100.0 --logging_steps 10 --save_steps -1 --output_dir C:\projects\mcrs_dat\outp --labels data/labels.txt --per_gpu_train_batch_size 16 --fp16
```
complete log:

```
2020-04-02 20:02:15.707420: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-04-02 20:02:17.779501: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-02 20:02:18.896554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.29
pciBusID: 0000:01:00.0
2020-04-02 20:02:18.901372: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-02 20:02:18.904309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-02 20:02:18.907103: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-02 20:02:18.916393: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce RTX 2070 with Max-Q Design major: 7 minor: 5 memoryClockRate(GHz): 1.29
pciBusID: 0000:01:00.0
2020-04-02 20:02:18.926797: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2020-04-02 20:02:18.935223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-02 20:02:19.504991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-02 20:02:19.507746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-04-02 20:02:19.509326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2020-04-02 20:02:19.511329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6306 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "run_seq_labeling.py", line 856, in <module>
    main()
  File "run_seq_labeling.py", line 748, in main
    args, tokenizer, labels, pad_token_label_id, mode="train"
  File "run_seq_labeling.py", line 434, in load_and_cache_examples
    pad_token_label_id=pad_token_label_id,
  File "C:\projects\python-virtual-environments\unilm\layoutlm\utils_seq_labeling.py", line 152, in convert_examples_to_features
    [label_map[label]] + [pad_token_label_id] * (len(word_tokens) - 1)
KeyError: 'S-QUESTION'
```
Windows 10, Cuda 10.1

**Comment by elnazsn1988** [comment]
I also tried the https://github.com/microsoft/unilm/issues/61#issuecomment-593829931 edit to the Tokenization in pretained bert py file, no luck.

**Comment by ranpox** [comment]
Hi @elnazsn1988 ,
Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
The `data/labels.txt` should be like this:
~~~
B-ANSWER
B-HEADER
B-QUESTION
E-ANSWER
E-HEADER
E-QUESTION
I-ANSWER
I-HEADER
I-QUESTION
O
S-ANSWER
S-HEADER
S-QUESTION
~~~

**Comment by elnazsn1988** [comment]
> Hi @elnazsn1988 ,
> Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
> The `data/labels.txt` should be like this:
> 
> ```
> B-ANSWER
> B-HEADER
> B-QUESTION
> E-ANSWER
> E-HEADER
> E-QUESTION
> I-ANSWER
> I-HEADER
> I-QUESTION
> O
> S-ANSWER
> S-HEADER
> S-QUESTION
> ```

@ranpox thanks for the answer, checking my code realised as im using WSL on windows (Linux Wrapper) Im not able to access GPU correctly. Is there a way to transform the command : 

`cat data/train.txt | cut -d$'\t' -f 2 | grep -v "^$"| sort | uniq > data/labels.txt` into DOS (cmd terminal) so I can run the code?

**Comment by elnazsn1988** [comment]
> Hi @elnazsn1988 ,
> Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
> The `data/labels.txt` should be like this:
> 
> ```
> B-ANSWER
> B-HEADER
> B-QUESTION
> E-ANSWER
> E-HEADER
> E-QUESTION
> I-ANSWER
> I-HEADER
> I-QUESTION
> O
> S-ANSWER
> S-HEADER
> S-QUESTION
> ```

Hi @ranpox I was able to clear and create the solution to the problem with S-Question linked above, however when passing that I hit a Cuda error problem : 

`RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 6.02 GiB already allocated; 112.97 MiB free; 13.55 MiB cached)`

Have been trying to find where the batches are being defined so I can redefine Batch size and allow memory management, can you point to?

**Comment by ranpox** [comment]
@elnazsn1988 `--per_gpu_train_batch_size` is what you need.

**Comment by Thirunayan22** [comment]
> > Hi @elnazsn1988 ,
> > Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
> > The `data/labels.txt` should be like this:
> > ```
> > B-ANSWER
> > B-HEADER
> > B-QUESTION
> > E-ANSWER
> > E-HEADER
> > E-QUESTION
> > I-ANSWER
> > I-HEADER
> > I-QUESTION
> > O
> > S-ANSWER
> > S-HEADER
> > S-QUESTION
> > ```
> 
> Hi @ranpox I was able to clear and create the solution to the problem with S-Question linked above, however when passing that I hit a Cuda error problem :
> 
> `RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 6.02 GiB already allocated; 112.97 MiB free; 13.55 MiB cached)`
> 
> Have been trying to find where the batches are being defined so I can redefine Batch size and allow memory management, can you point to?



> > Hi @elnazsn1988 ,
> > Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
> > The `data/labels.txt` should be like this:
> > ```
> > B-ANSWER
> > B-HEADER
> > B-QUESTION
> > E-ANSWER
> > E-HEADER
> > E-QUESTION
> > I-ANSWER
> > I-HEADER
> > I-QUESTION
> > O
> > S-ANSWER
> > S-HEADER
> > S-QUESTION
> > ```
> 
> Hi @ranpox I was able to clear and create the solution to the problem with S-Question linked above, however when passing that I hit a Cuda error problem :
> 
> `RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 6.02 GiB already allocated; 112.97 MiB free; 13.55 MiB cached)`
> 
> Have been trying to find where the batches are being defined so I can redefine Batch size and allow memory management, can you point to?



> @elnazsn1988 `--per_gpu_train_batch_size` is what you need.



> > Hi @elnazsn1988 ,
> > Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
> > The `data/labels.txt` should be like this:
> > ```
> > B-ANSWER
> > B-HEADER
> > B-QUESTION
> > E-ANSWER
> > E-HEADER
> > E-QUESTION
> > I-ANSWER
> > I-HEADER
> > I-QUESTION
> > O
> > S-ANSWER
> > S-HEADER
> > S-QUESTION
> > ```
> 
> Hi @ranpox I was able to clear and create the solution to the problem with S-Question linked above, however when passing that I hit a Cuda error problem :
> 
> `RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 6.02 GiB already allocated; 112.97 MiB free; 13.55 MiB cached)`
> 
> Have been trying to find where the batches are being defined so I can redefine Batch size and allow memory management, can you point to?

Can you tell what your solution was?

**Comment by Thirunayan22** [comment]
> > Hi @elnazsn1988 ,
> > Please make sure you correctly follow the preprocessing steps in [Sequence Labeling Task](https://github.com/microsoft/unilm/tree/master/layoutlm#sequence-labeling-task)
> > The `data/labels.txt` should be like this:
> > ```
> > B-ANSWER
> > B-HEADER
> > B-QUESTION
> > E-ANSWER
> > E-HEADER
> > E-QUESTION
> > I-ANSWER
> > I-HEADER
> > I-QUESTION
> > O
> > S-ANSWER
> > S-HEADER
> > S-QUESTION
> > ```
> 
> Hi @ranpox I was able to clear and create the solution to the problem with S-Question linked above, however when passing that I hit a Cuda error problem :
> 
> `RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 6.02 GiB already allocated; 112.97 MiB free; 13.55 MiB cached)`
> 
> Have been trying to find where the batches are being defined so I can redefine Batch size and allow memory management, can you point to?

Can you tell what your solution was?
