### ISSUE TITLE
DeltaLm：What does 250002~250104th tokens of deltalm represent？ Are they all extra_ids?

### ISSUE THREAD

**Issue by yxzero** [microsoft/unilm#881]
Model I am using deltalm:  i want to continue pretrain deltalm，but i don't know 250002~250104th tokens represent

**Comment by shumingma** [comment]
0~3 are the default ids in the fairseq's dictionary, representing bos, pad, eos, and unk, respectively.
4~250003 represents the tokens from the sentencepiece model.
250004~250104 are the extra ids representing the span separators in the span corruption (pretraining) task.

**Comment by yxzero** [comment]
> 0-3 are the default ids in the fairseq's dictionary, representing bos, pad, eos, and unk, respectively. 4-250003 represents the tokens from the sentencepiece model. 250004-250104 are the extra ids representing the span separators in the span corruption (pretraining) task.


dict.txt only has 249997 tokens，250001-250003 is missing
