### ISSUE TITLE
The value of F in VLMo

### ISSUE THREAD

**Issue by chaochen99** [microsoft/unilm#883]
Dear Sir,

I recently read your  VLMO: Unified Vision-Language Pre-Training with Mixture-of-Modality-Experts paper and found it very intriguing.

I didn't find the description of the F layers in Figure 1. Could you clarify the value of F? thanks!

Looking forward to your reply!

**Comment by wenhui0924** [comment]
Thanks for the question. Please find the details in sec 4.1. We use 2 layers for the base-size model and 3 layers for the large-size model.

**Comment by chaochen99** [comment]
Thanks!
