### ISSUE TITLE
[BEiT] HuggingFace Spaces link in Readme is dead

### ISSUE THREAD

**Issue by ogencoglu** [microsoft/unilm#897]
HuggingFace Spaces link in Readme leads to 404 error.

**Comment by donglixp** [comment]
@ogencoglu Thanks for reporting the bad link issue. Could you provide more details about which the readme file is?

**Comment by ogencoglu** [comment]
`Try out the Web Demo:` part in beit readme. The link is this : https://huggingface.co/spaces/rowel/22k-image-classification

**Comment by donglixp** [comment]
The demo was not created by us. You could submit the issue at https://huggingface.co/spaces/rowel/22k-image-classification/discussions .

**Comment by ogencoglu** [comment]
This is like McDonald's advertising "free milkshake with Big Mac menu" but when you go there you get "Sorry, the milkshake machine is broken, contact the machine manufacturer". Why is it in the readme then?

**Comment by donglixp** [comment]
Oh, I see. The link was added to our readme by the huggingface's contributor. I will fix the issue then. Thank you for the reminder.
