### ISSUE TITLE
how to find pretrained model about layoutlm

### ISSUE THREAD

**Issue by hee0624** [microsoft/unilm#90]

**Comment by ranpox** [comment]
If you mean the pre-trained models for LayoutLM, you can find them in LayoutLM [README](https://github.com/microsoft/unilm/tree/master/layoutlm#pre-trained-model).

**Comment by hee0624** [comment]
![1](https://user-images.githubusercontent.com/18159275/77385526-50cec580-6dc3-11ea-8932-25cf0b2bbbe4.png)
Run this script need mdoel path

**Comment by hee0624** [comment]
get it ,Thx
