### ISSUE TITLE
Regarding DeepSpeed for pre-training BEiT and BEiT2

### ISSUE THREAD

**Issue by netw0rkf10w** [microsoft/unilm#907]
Hello,

I noticed that in BEiT and BEiT 2, you only used `enable_deepspeed` for fine-tuning. Could you share why you didn't use it for pre-training?

Thank you in advance for your response.

**Comment by addf400** [comment]
Hi, we use deepspeed with [apex O2](https://nvidia.github.io/apex/amp.html#opt-levels) to faster finetuning speed than 
apex O1 in torch.amp. 
It could also be used in the BEiT pre-training, but I didn't test it.

**Comment by addf400** [comment]
Apex O1 in torch.amp should be more stable than O2 but also with more computing resources and memory consumption. The more details can be found in this [URL](https://nvidia.github.io/apex/amp.html#opt-levels)

**Comment by tungdop2** [comment]
Hello @netw0rkf10w,
I try to use deepspeed for training, but I get error:
`
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasLtMatmul( ltHandle, computeDesc.descriptor(), &alpha_val, mat1_ptr, Adesc.descriptor(), mat2_ptr, Bdesc.descriptor(), &beta_val, result_ptr, Cdesc.descriptor(), result_ptr, Cdesc.descriptor(), &heuristicResult.algo, workspace.data_ptr(), workspaceSize, at::cuda::getCurrentCUDAStream())`
`
Did you used deepspeed for pretraining?

**Comment by donglixp** [comment]
> Hello @netw0rkf10w, I try to use deepspeed for training, but I get this error: `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling cublasLtMatmul( ltHandle, computeDesc.descriptor(), &alpha_val, mat1_ptr, Adesc.descriptor(), mat2_ptr, Bdesc.descriptor(), &beta_val, result_ptr, Cdesc.descriptor(), result_ptr, Cdesc.descriptor(), &heuristicResult.algo, workspace.data_ptr(), workspaceSize, at::cuda::getCurrentCUDAStream())` Did you try to use deepspeed for pretraining and?

We didn't use deepspeed in the pretraining process. Contributions are welcome.

**Comment by tungdop2** [comment]
Tks @donglixp, 
I just transfer your deepspeed code in finetuning to pretraing, but get above error. When I change fp16=False in ds config,it word, soI guess that error happen because vqdk model is not converted by deepspeed init. I dont know how to fix that. Can you help me?
Sorry for my bad English.
