### ISSUE TITLE
WavLM base pretrained-model weight is unavailable

### ISSUE THREAD

**Issue by XiaoyuBIE1994** [microsoft/unilm#916]
**Describe**
Model I am using (WavLM):

I can't download the pre-trained weight of WavLM Base, neither from Google Drive, nor from Azure. Is it still available? If yes, could someone re-open the sharing/downloading access? Thanks so much in advance.

**Comment by MarkWuNLP** [comment]
> **Describe** Model I am using (WavLM):
> 
> I can't download the pre-trained weight of WavLM Base, neither from Google Drive, nor from Azure. Is it still available? If yes, could someone re-open the sharing/downloading access? Thanks so much in advance.

Fixed. Please try again~

**Comment by JJ-Guo1996** [comment]
> > **Describe** Model I am using (WavLM):
> > I can't download the pre-trained weight of WavLM Base, neither from Google Drive, nor from Azure. Is it still available? If yes, could someone re-open the sharing/downloading access? Thanks so much in advance.
> 
> Fixed. Please try again~

HI~, can u show me how to fine-tune the WavLM. Where is the code?
