### ISSUE TITLE
Can Magneto train a 1000 layer network and how does it compare to Deepnet?

### ISSUE THREAD

**Issue by nbcc** [microsoft/unilm#922]
Looking forward to the reply. Thanks. ^^ @shumingma

**Comment by shumingma** [comment]
Magneto is based on the DeepNet's theory to derive its initialization, so it inherits the stability guarantee and the capability of scaling to 1,000 layers from DeepNet. Compared to DeepNet, Magneto is better at generality, supporting more modalities (including language, vision, speech, and multi-modal) and various tasks.

**Comment by nbcc** [comment]
> 

So it has been tested on a 1000-layer task? With proper initialization, can I assume that “deepnorm" and “subln" are equivalent?

**Comment by nbcc** [comment]
> Magneto is based on the DeepNet's theory to derive its initialization, so it inherits the stability guarantee and the capability of scaling to 1,000 layers from DeepNet. Compared to DeepNet, Magneto is better at generality, supporting more modalities (including language, vision, speech, and multi-modal) and various tasks.

A little difference in form:
<img width="612" alt="图片" src="https://user-images.githubusercontent.com/864331/202962236-aea07757-b52e-447d-aefc-076a9a133483.png">

<img width="620" alt="图片" src="https://user-images.githubusercontent.com/864331/202962250-982ed42a-e096-408d-845b-488f284ee1e3.png">

**Comment by donglixp** [comment]
@nbcc https://github.com/microsoft/torchscale
