### ISSUE TITLE
How to use Layoutlm in receipt understanding case?

### ISSUE THREAD

**Issue by hee0624** [microsoft/unilm#93]
Hi there,

Thanks for the repo and help! I was wondering how to use layoulm in receipt understanding? I don't find python script about it.

Thanks much in advance!

**Comment by donglixp** [comment]
@ranpox @wolfshow

**Comment by ranpox** [comment]
Hi @hee0624 ,
Currently, the preprocessing script only supports the FUNSD dataset. But you can convert your receipt dataset into BIO format in a similar way.
FYI: #81 
Thanks.
