### ISSUE TITLE
BEIT3 pretraining 

### ISSUE THREAD

**Issue by jinxixiang** [microsoft/unilm#930]
**Describe**
The model I am asking BEIT3

Dear authors,

Thank you for such seminal work!

I am wondering about the pretraining time and the required hardware resource. If I could be wrong, I didn't find related statements in the paper. Considering that the total training step is 1M, and the batch size is 2048 for each modal, it would take about 30 days on 8*8 A100 according to our initial estimation.

**Comment by donglixp** [comment]
The pretraining process takes about two weeks using 256 A100 40GB GPUs.

**Comment by jinxixiang** [comment]
Thank you for your reply.

**Comment by donglixp** [comment]
The code and pre-trained models of BEiT-3 can be found at [aka.ms/beit3](https://aka.ms/beit3).
