### ISSUE TITLE
Beit3 intermediate retrieval

### ISSUE THREAD

**Issue by amandaluof** [microsoft/unilm#938]
Thanks for your inspiring and effective work. You achieved really great performance on zero-shot and finetune retrieval.   But we are wondering how the batch size could be 16k in intermediate finetune. Supposed that there are 64 gpus, batch_size_per_gpu is 256, which may not be possible with the giant transformer. So do you use any skills to optimize?

**Comment by wenhui0924** [comment]
Hi @amandaluof, you can try to use [activation checkpoint](https://fairscale.readthedocs.io/en/stable/api/nn/checkpoint/checkpoint_activations.html).

**Comment by amandaluof** [comment]
Thanks for your reply :)

**Comment by donglixp** [comment]
The code and pre-trained models of BEiT-3 can be found at [aka.ms/beit3](https://aka.ms/beit3).
