### ISSUE TITLE
[TrOCR] Failed to execute the example of Evaluation of IAM

### ISSUE THREAD

**Issue by tairen99** [microsoft/unilm#946]
Thank you for your wonderful work on TrOCR.

I am trying to repeat the example of "[Evaluation of IAM](https://github.com/microsoft/unilm/tree/master/trocr#evaluation-on-iam)". Model I am using is TrOCR base: trocr-base-handwritten.pt

The problem arises when using the command line:

$(which fairseq-generate) \
        --data-type STR --user-dir ./ --task text_recognition --input-size 384 \
        --beam 10 --scoring cer2 --gen-subset test --batch-size ${BSZ} \
        --path ${MODEL} --results-path ${RESULT_PATH} --preprocess DA2 \
        --bpe gpt2 --dict-path-or-url https://layoutlm.blob.core.windows.net/trocr/dictionaries/gpt2_with_mask.dict.txt \ # --bpe sentencepiece --sentencepiece-model ./unilm3-cased.model --dict-path-or-url https://layoutlm.blob.core.windows.net/trocr/dictionaries/unilm3.dict.txt ## For small models
        --fp16 \
        ${DATA}

The bug is: **syntax error near unexpected token `--data-type'** as the image attached:
![image](https://user-images.githubusercontent.com/32938376/207506292-a6083c71-72a0-48c1-bd7b-ce50c6ff92b9.png)

I searched the fairseq command line information page ([link](https://fairseq.readthedocs.io/en/latest/command_line_tools.html)), I could not find the option for "--data-type".

Can you please let me know how you set up the IAM evaluation and which version of "fairseq" are you using.

Thank you in advance

- Platform: ubuntu20.04 with cuda:11.3.1
- Python version: python 3.7
- PyTorch version (GPU?): 1.11 with GPU

**Comment by Mohammed20201991** [comment]
cc @NielsRogge 
Dear @tairen99 : Did you manage to do the train part? because I have stuck with it

**Comment by Mohammed20201991** [comment]
I have same issue when running the following command line 👍 
```
export MODEL_NAME=ft_iam
export SAVE_PATH=/path/to/save/${MODEL_NAME}
export LOG_DIR=log_${MODEL_NAME}
export DATA=/path/to/data
mkdir ${LOG_DIR}
export BSZ=8
export valid_BSZ=16

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 \
    $(which fairseq-train) \
    --data-type STR --user-dir ./ --task text_recognition --input-size 384 \
    --arch trocr_large \   # or trocr_base
    --seed 1111 --optimizer adam --lr 2e-05 --lr-scheduler inverse_sqrt \
    --warmup-init-lr 1e-8 --warmup-updates 500 --weight-decay 0.0001 --log-format tqdm \
    --log-interval 10 --batch-size ${BSZ} --batch-size-valid ${valid_BSZ} --save-dir ${SAVE_PATH} \
    --tensorboard-logdir ${LOG_DIR} --max-epoch 300 --patience 20 --ddp-backend legacy_ddp \
    --num-workers 8 --preprocess DA2 --update-freq 1 \
    --bpe gpt2 --decoder-pretrained roberta2 \ # --bpe sentencepiece --sentencepiece-model ./unilm3-cased.model --decoder-pretrained unilm ## For small models
    --finetune-from-model /path/to/model --fp16 \
    ${DATA}
```
I had this issue :

```
warnings.warn(
usage: launch.py [-h] [--nnodes NNODES] [--nproc_per_node NPROC_PER_NODE] [--rdzv_backend RDZV_BACKEND] [--rdzv_endpoint RDZV_ENDPOINT]
                 [--rdzv_id RDZV_ID] [--rdzv_conf RDZV_CONF] [--standalone] [--max_restarts MAX_RESTARTS] [--monitor_interval MONITOR_INTERVAL]
                 [--start_method {spawn,fork,forkserver}] [--role ROLE] [-m] [--no_python] [--run_path] [--log_dir LOG_DIR] [-r REDIRECTS] [-t TEE]
                 [--node_rank NODE_RANK] [--master_addr MASTER_ADDR] [--master_port MASTER_PORT] [--use_env]
                 training_script ...
launch.py: error: unrecognized arguments: --data-type
user@m555:~user/troc_ft/unilm/trocr$     --seed 1111 --optimizer adam --lr 2e-05 --lr-scheduler inverse_sqrt \
>     --warmup-init-lr 1e-8 --warmup-updates 500 --weight-decay 0.0001 --log-format tqdm \
>     --log-interval 10 --batch-size ${BSZ} --batch-size-valid ${valid_BSZ} --save-dir ${SAVE_PATH} \
>     --tensorboard-logdir ${LOG_DIR} --max-epoch 300 --patience 20 --ddp-backend legacy_ddp \
>     --num-workers 8 --preprocess DA2 --update-freq 1 \
>     --bpe gpt2 --decoder-pretrained roberta2 \ # --bpe sentencepiece --sentencepiece-model ./unilm3-cased.model --decoder-pretrained unilm ## For small models
bash: --seed: command not found
```

**Comment by Mohammed20201991** [comment]
Related issue : 
`/home/user/troc_ft/bin/python: can't open file ' /home/user/troc_ft/bin/fairseq-train': [Errno 2] No such file or directory`

**Comment by liminghao1630** [comment]
@tairen99 From your screenshot, you may lack a "$" at the front of your command. 

@Mohammed20201991 When using the example command, please remove the comment in the middle.
