### ISSUE TITLE
BEiT initalization

### ISSUE THREAD

**Issue by vateye** [microsoft/unilm#949]
Hi, I am currently looking for the initialization of BEiT. The default setting for output projection and FFN weights are scaled by 1 / sqrt(2*N), where N is the current layer id. When I see the paper of DeepNet. I have noticed that the scaled factor only needs to fit the constraint 2N(v^2 + w^2) = O(1). Can we just simply set v = w = 1 / (2*sqrt(N)) to ensure 2N(v^2 + w^2) = 1？

**Comment by donglixp** [comment]
@vateye

If you would like to initialize ViT (preLN), the code at https://github.com/microsoft/unilm/blob/master/beit/modeling_finetune.py#L289-L317 can be used. The initialization was first proposed by our XLM-E paper https://arxiv.org/pdf/2106.16138.pdf (Sec 3.4).

![image](https://user-images.githubusercontent.com/1070872/208344741-4b0812f3-1a39-471d-87c1-0e5117122b00.png)

I also recommend the architecture and initialization of the Magneto architecture https://arxiv.org/pdf/2210.06423.pdf . It's more theoretically grounded and provides better performance compared with ViT (preLN). The implementation is open-source at https://github.com/microsoft/torchscale.

**Comment by vateye** [comment]
Thanks for your quick response. However, is there any theoretical derivation of this factor 1/sqrt{2l}? I am quite confused how it comes.
