### ISSUE TITLE
Image embeddings

### ISSUE THREAD

**Issue by lvaleriu** [microsoft/unilm#95]
Are you using image embeddings in the layoutlm project as stated in the paper? I didnt see where you open image files (except for getting size info).

```
class LayoutLMEmbeddings(nn.Module):
    """Construct the embeddings from word, position and token_type embeddings.
    """
```

Sorry if I've missed something obvious :).

Thank you.

**Comment by ranpox** [comment]
Hi @lvaleriu ,
Currently, the sequence labeling example doesn't include image embeddings. 
FYI #80 
Thanks.

**Comment by lvaleriu** [comment]
Thank you!
