### ISSUE TITLE
Can LayoutLM be used for max sequence length greater than 512?

### ISSUE THREAD

**Issue by nikgr95** [microsoft/unilm#96]
As the pretraining was done after rescaling the coordinates between [0, 1000] for the 2D position embeddings, I'm guessing that the max sequence length can be increased to something like 1024?

Or would a sliding window approach be better?

**Comment by ranpox** [comment]
Hi @nikgr95 ,
As we initialize the weight of LayoutLM with the pre-trained BERT, we need to follow some settings of BERT including the max sequence length.
I think a sliding window approach is better. You can easily implement it by modifying the example code.
