### ISSUE TITLE
WavLM: Projection matrix and label embeddings missing

### ISSUE THREAD

**Issue by yaya-sy** [microsoft/unilm#974]
Hi,

if i understand, the WavLM model uses the same loss as HuBERT. But i can't find anywhere in the code of the WavLM model, the parameters corresponding to the projection matrix and to the label embeddings (these two parameters are mentionned in the equation 1 in the paper). Do you planning to make these parameters open source ?

Thank you very much.

**Comment by MarkWuNLP** [comment]
Hi, 
    We release the WavLM for downstream task fine-tuning, and the two parameters you mentioned are not used for this purpose, so we don't release these two parameters.
