### ISSUE TITLE
Some layoutlm dataset questions

### ISSUE THREAD

**Issue by lvaleriu** [microsoft/unilm#98]
Here they are:

1. If I understood well you've used the image embeddings when trained the LayoutLM-Base and LayoutLM-Large. Do you think it is necessary to use image embeddings when fine-tunning these models on our datasets? I've obtained a pretty nice score with only "spatial" embeddings.

2. By "image embeddings" you mean embeddings extracted from each word associated crop in image (relative to the bbox)? Could we use some Imagenet backbone to extract features from the box instead of FasterRCnn?

Thank you!

**Comment by ranpox** [comment]
Hi @lvaleriu ,
Thanks for your feedback.
1. Actually, we didn't use the image embedding during the pretraining stage. FYI https://github.com/microsoft/unilm/issues/80#issuecomment-598531475
2. We didn't try other backbones except Fast(er) R-CNN with ResNet. The Fast(er) R-CNN is can directly extract fixed-length features from images with bounding boxes and that's exactly what we need.
