### ISSUE TITLE
E5 classification head

### ISSUE THREAD

**Issue by sh0416** [microsoft/unilm#982]
**Describe**
Model I am using E5:

I just want to know the training code for few shot text classification.
The code only contains evaluation code..
Where is the code for training classification head?
Thank you

**Comment by sh0416** [comment]
@intfloat ..?

**Comment by intfloat** [comment]
The training of classification head is done within the MTEB codebase to ensure fair comparison for different models.

You can find the relevant code here: https://github.com/embeddings-benchmark/mteb/blob/main/mteb/abstasks/AbsTaskClassification.py#L86-L89

Briefly speaking, it takes the embeddings from E5 models and trains a logistic regression classifier with few-shot labeled data.

**Comment by sh0416** [comment]
Great, Thanks!

**Comment by intfloat** [comment]
Hi @ibrahimsharaf ,

Yes, as mentioned in https://huggingface.co/intfloat/multilingual-e5-large#faq , you need to add `query: ` prefix for classification.

**Comment by gin-ee** [comment]
Are there any implications on using text documents prefixed with passage: for classification? These documents would have already been indexed in a vector database with passage: on ingestion.
