### ISSUE TITLE
Beats - Memory leak when making multiple prediction

### ISSUE THREAD

**Issue by Topper69** [microsoft/unilm#998]
I'm using the Beats model (fine tune iter3+ AS20K/AS2M same behavior) to make multiple prediction in a loop leading of a memory leak on each loop

Basic example:
```
import torch
from BEATs import BEATs, BEATsConfig

# load the fine-tuned checkpoints
checkpoint = torch.load('/home/pi/Documents/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt1.pt')

cfg = BEATsConfig(checkpoint['cfg'])
BEATs_model = BEATs(cfg)
BEATs_model.load_state_dict(checkpoint['model'])
BEATs_model.eval()

while True:
    # predict the classification probability of each class
    audio_input_16khz = torch.randn(3, 10000)
    padding_mask = torch.zeros(3, 10000).bool()

    probs = BEATs_model.extract_features(audio_input_16khz, padding_mask=padding_mask)[0]
    for i, (top5_label_prob, top5_label_idx) in enumerate(zip(*probs.topk(k=5))):
        top5_label = [checkpoint['label_dict'][label_idx.item()] for label_idx in top5_label_idx]
```

**Expected behavior**
No massive memory increase

- Platform: Raspberry pi 4 - Rapsbian 64b bulleseye
- Python version: 3.9.2
- PyTorch version (CPU): 1.13.1

**Comment by bytosaur** [comment]
hey there,
I am facing the same issue right here using Ubuntu 18.04 and torch 1.13.1+cu117. When using cuda i ran out of memory very quickly. So i tried without it, but the memory keeps increasing until it blows off.
I am processing large audio files with a sliding window. I carefully checked that i dont have any other resources that are growing in size. I used fil-profile to confirm that the high memory usage comes from extract_features in the backbone.py, but i am not very familiar with the process of profiling.

**Comment by Sanyuan-Chen** [comment]
Hi @Topper69 @bytosaur 

Please try to use `with torch.no_grad():` to reduce memory consumption during inferece:
```
with torch.no_grad():
    probs = BEATs_model.extract_features(audio_input_16khz, padding_mask=padding_mask)[0]
```

**Comment by Topper69** [comment]
Hi @Sanyuan-Chen,

Yes many thanks it's fixed the memory leak. It runs smoothly now.
